module-apps/application-messages/windows/NewMessage.cpp
SEND message button is now visible and active only
when the recipient field is not empty.
=> [EGD-7498] Disable message SEND button when recipient empty

CMakeLists.txt, Jenkinsfile, cmake/modules/AddPackage.cmake, cmake/modules/DiskImage.cmake, cmake/modules/DownloadAsset2.cmake, products/BellHybrid/CMakeLists.txt, products/BellHybrid/assets.json, products/PurePhone/CMakeLists.txt, products/PurePhone/assets.json, tools/download_asset2.py, tools/requirements.txt
EGD-7932
With this, all fonts and Luts bin are downloaded for other repo which
Is closed to others. With minimum changes to our cmake and flow
Fonts are cached in `~/.mudita/`
This is an quick enabler so that we can remove mpf and luts.bin from MuditaOS openourced
scripts with `2` will be merged into one with jira: EGD-7947
=> [EGD-7932] Added downloader for assets for Bell

image/assets/lang/Deutsch.json, image/assets/lang/English.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, image/assets/lang/Polski.json, image/assets/lang/Svenska.json, module-apps/application-music-player/data/MusicPlayerStyle.hpp, module-apps/application-music-player/widgets/SongItem.cpp, module-apps/application-music-player/widgets/SongItem.hpp, module-apps/application-music-player/windows/MusicPlayerMainWindow.cpp, module-apps/application-music-player/windows/MusicPlayerMainWindow.hpp
When playing tracks with long names they were incorrectly drawn in MP.
Now the beginning of string + elipsis is shown.
=> [EGD-7927] Long track attributes/names drawing

module-audio/Audio/StreamFactory.cpp, module-audio/Audio/StreamFactory.hpp, module-audio/Audio/test/unittest_transcode.cpp, module-audio/Audio/transcode/BasicInterpolator.hpp, module-audio/Audio/transcode/InputTranscodeProxy.cpp, module-bluetooth/Bluetooth/audio/BluetoothAudioDevice.cpp
[EGD-6857] Fix HSP audio quality
Fixed HSP sound quality issues:
- fixed HF caused by invalid output block size during interpolation of
the Bluetooth input,
- increased Bluetooth stack priority to greatly reduce deviation in
the interval between Bluetooth audio frames
- increased block size to increase time send interval to 8ms
Fixed issue with error handling when writing to the overflowed stream.
[EGD-6857]: https://appnroll.atlassian.net/browse/EGD-6857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EGD-6857] Fix HSP audio quality

module-services/service-desktop/endpoints/filesystem/FileContext.cpp, module-services/service-desktop/endpoints/filesystem/FileOperations.cpp, module-services/service-desktop/endpoints/include/endpoints/filesystem/FileContext.hpp, module-services/service-desktop/endpoints/include/endpoints/filesystem/FileOperations.hpp, module-utils/log/Logger.cpp
Using std::fstream for file I/O at every file access in FileContext. Additionally, reworked file opening/closing to happen on each file chunk read/write, so that a file isn’t left open in case of error or transfer cancelation.
=> [CP-825] Interrupted transfer to FS endpoint may corrupt the filesystem

board/rt1051/crashdump/crashcatcher_impl.cpp, board/rt1051/crashdump/crashdumpwriter_vfs.cpp, module-bsp/board/rt1051/bsp/eMMC/fsl_mmc.c, module-bsp/board/rt1051/bsp/eMMC/fsl_mmc.h, module-bsp/board/rt1051/bsp/eMMC/fsl_sdmmc_common.h, module-os/board/rt1051/_exit.c, module-os/board/rt1051/include/exit_backtrace.h, module-os/board/rt1051/port.c, module-platform/rt1051/src/disk_emmc.cpp, products/BellHybrid/CMakeLists.txt, third-party/CrashDebug/CrashCatcher/CrashCatcherPriv.h, third-party/CrashDebug/CrashCatcher/CrashCatcher_armv7m.S
Fix saving crash dump. 
Reduce crash dump size 
Add backtrace crashdump on exit abort or exceptions
=> [CP-670] crashdumps on exit

Target_RT1051.cmake, module-os/board/rt1051/_exit.cpp, module-os/board/rt1051/include/exit_backtrace.h
Umount all mounted filesystems in case of fault like
Hardfault, abort, uncautched exception.
=> [EGD-7976] Umount all filesystems on failure

module-apps/application-music-player/windows/MusicPlayerAllSongsWindow.cpp, module-apps/application-music-player/windows/MusicPlayerAllSongsWindow.hpp, module-gui/gui/widgets/ListViewEngine.cpp
When MP track list is open and volume changed, the list is loosing the
offset.
=> [EGD-7856] NP loosing track list offset

image/assets/lang/Polski.json, products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp, products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingInstructionPromptWindow.cpp
Fix onboarding guidelines:
- exiting info screen only on specific keypresses
- deep press up also activatess info screen
- deep press info screen also works on other info screens
=> [BH-1178] Fix onboarding guidelines

products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
Battery status screen is displayed by back long press
=> [BH-1172] Change a way of entering Battery status

products/BellHybrid/apps/application-bell-meditation-timer/windows/ReadyGoingWindow.cpp
"ReadyGoingWindow" is now displayed for 10s
=> [BH-1173] Change length of displaying screen

module-services/service-time/AlarmOperations.cpp, module-services/service-time/AlarmOperations.hpp, products/BellHybrid/apps/application-bell-background-sounds/presenter/BGSoundsProgressPresenter.cpp, products/BellHybrid/apps/application-bell-background-sounds/presenter/BGSoundsProgressPresenter.hpp, products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsProgressWindow.cpp, products/BellHybrid/services/time/AlarmOperations.cpp, products/BellHybrid/services/time/include/time/AlarmOperations.hpp, products/PurePhone/services/time/AlarmOperations.cpp, products/PurePhone/services/time/include/time/AlarmOperations.hpp
Implemented a very basic alarm operations priority.
[BH-1204] Fixed time format being incorrectly displayed
in background sounds app.
[BH-1204]: https://appnroll.atlassian.net/browse/BH-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BH-1191] Alarm operations priorities

products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/models/TimeUnitsModel.hpp
Default Time during Onboarding must be 12:00 AM (not PM)
=> [BH-1181] Change Onboarding Default Time

module-db/Interface/ContactRecord.cpp
There was an issue, when contact with a specific number was added,
then removed and added again via Mudita Center. Then
it was displayed without a name. This issue was caused by
another known issue with temporary contacts handling (EGD-79473).
This fix is a workaround to make adding contacts via MC work,
without the need to refactor temporary contacts handling.
=> [CP-813] Fix issues with adding contacts via Mudita Center

module-apps/application-calllog/ApplicationCallLog.cpp, module-apps/application-calllog/data/CallLogInternals.hpp, module-apps/application-calllog/windows/CallLogDetailsWindow.cpp, module-apps/application-calllog/windows/CallLogOptionsWindow.cpp, module-apps/application-calllog/windows/CallLogOptionsWindow.hpp, module-apps/application-messages/ApplicationMessages.cpp, module-apps/application-messages/data/SMSdata.hpp, module-apps/application-messages/include/application-messages/Constants.hpp, module-apps/application-messages/models/ThreadsModel.cpp, module-apps/application-messages/widgets/SMSOutputWidget.cpp, module-apps/application-messages/windows/MessagesMainWindow.cpp, module-apps/application-messages/windows/OptionsMessages.cpp, module-apps/application-messages/windows/OptionsMessages.hpp, module-apps/application-messages/windows/ThreadWindowOptions.cpp, module-apps/application-messages/windows/ThreadWindowOptions.hpp, module-apps/application-phonebook/data/PhonebookItemData.hpp, module-apps/application-phonebook/windows/PhonebookContactDetails.cpp, module-apps/application-phonebook/windows/PhonebookContactDetails.hpp, module-apps/application-phonebook/windows/PhonebookContactOptions.cpp, module-apps/application-phonebook/windows/PhonebookContactOptions.hpp, module-apps/apps-common/options/OptionStyle.hpp, module-apps/apps-common/options/type/OptionContact.cpp
After deleting/add a contact from the calllog, sms options,
and sms thread options, we return to the start screen
of the current application
=> [EGD-7920] GUI fixes after deleting/add contact

products/PurePhone/services/desktop/endpoints/contacts/ContactHelper.cpp
Removed redundant check for empty number, while adding
a new contact through service-desktop.
=> [CP-845] Allow saving contact without a phone number via MC

tools/check_commit_messages.py
Community commits were incorectly verified during checks on CI.
In details - commit list to check was incorrectly created thus
covered much more commits than it had to
=> [EGD-8000] Fix commit name check for community builds

module-os/memory/usermem.c
Fix userrealloc() function to the ANSI to comply
ANSI C standard
=> [EGD-7727] Fix userrealloc to ANSI standard capable

module-gui/gui/core/ImageManager.cpp
Find and fix unsafe usage of the file_size in the MuditaOS
filesystem.
=> [EGD-7658] Fix unsafe usage of std::filesystem::file_size

module-bluetooth/lib/btstack.cmake
I just noticed it while compiling the project, should have no functionality changes.
=> [EGD-7974] BTstack: fix typo in CMake

module-db/Interface/ContactRecord.cpp
number.isValid() always returns false if there is no national prefix.
=> [EGD-7993] Fixed contacts matching algorithm

module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp
Adding the necessary, short delay for synchronization
after configuration.
=> [EGD-7939] Fix wrong battery status after restarting the phone

module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.cpp, module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.hpp
Some devices were sending hangup message during connecting, which caused
call ended screen - now it's disabled unless a call has been picked up
=> [EGD-7873] Fix call ended screen during BT connecting

products/BellHybrid/config.cmake, products/PurePhone/config.cmake
Enabled USB device task to handle USB requests outside IRQ handler
=> [EGD-7877] Call errors while MTP file transfer

products/PurePhone/config.cmake
Disabling USB task to prevent BUSY errors during USB_DeviceCdcAcmSend().
=> [EGD-8027] Disable USB device task

module-audio/Audio/transcode/BasicInterpolator.hpp, products/PurePhone/config.cmake
Disabling USB task to prevent BUSY errors during USB_DeviceCdcAcmSend().
=> [EGD-8027] Disable USB device task - cherry-pick

module-audio/board/rt1051/puretx/PureTxAudioCodec.hpp
It is a quick fix for enable support for the 24-bit
audio flac files. It fix only flac but for
24 bit wav support 3rd party library should be added
Audio system will be fixed for support all format
in the another jira case
=> [EGD-8041] Quick fix for enable support 24-bit flac

module-apps/apps-common/windows/AppWindow.hpp, products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp, products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp, products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.hpp, products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp, products/BellHybrid/apps/application-bell-main/presenters/StateController.hpp, products/BellHybrid/apps/application-bell-main/widgets/BellBattery.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.hpp, products/BellHybrid/services/evtmgr/EventManager.cpp, products/BellHybrid/services/evtmgr/include/evtmgr/EventManager.hpp
[BH-1249][BH-1248] Added handling of battery charger async
events to the home screen.
[BH-1276] Enter battery status from snooze active window.
[BH-1278] Proper latch state handling when in battery critical state.
Fixed various minor bugs spotted along the way.
[BH-1249]: https://appnroll.atlassian.net/browse/BH-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1248]: https://appnroll.atlassian.net/browse/BH-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1276]: https://appnroll.atlassian.net/browse/BH-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1278]: https://appnroll.atlassian.net/browse/BH-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> [BH-1248] Battery charger events handling

module-bsp/board/linux/hal/battery_charger/BatteryCharger.cpp, module-services/service-appmgr/model/ApplicationManagerCommon.cpp, products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp, products/BellHybrid/apps/application-bell-main/include/application-bell-main/ApplicationBellMain.hpp
Removed handling of critical battery level from bell's
home screen. From now on, battery SOC can drop to 1%
(battery notification will change from showing 1 bar to
crossed battery symbol upon reaching <5% SOC). If it drops
any further system shutdown procedure is invoked which results
in the device being turned off.
=> [BH-1277] Fix critical battery flow

products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingFinalizeWindow.cpp, products/BellHybrid/apps/common/include/common/data/StyleCommon.hpp, products/BellHybrid/apps/common/src/windows/BellFactoryReset.cpp, products/BellHybrid/apps/common/src/windows/BellFinishedWindow.cpp
Summary screens icons are aligned vertically
=> [BH-1271] Icons on summary screens align vertical

products/BellHybrid/apps/application-bell-settings/models/advanced/FrontlightListItemProvider.cpp
Frontlight has to be on when entering frontlight settings
=> [BH-1227] Frontlight On When Entering Settings

module-apps/application-calllog/windows/CallLogDetailsWindow.cpp, module-apps/application-calllog/windows/CallLogDetailsWindow.hpp
After editing a contact from the calllog level,
the calllog details will be refreshed.
=> [EGD-7871] Fix refreshing calllog details after editing contact

board/rt1051/CMakeLists.txt, board/rt1051/ldscripts/libs.ld, board/rt1051/memcpy-armv7m.S
Newlib nano is an optimized for size version of newlib libc library.
While newlib nano is smaller in size, it is also noticeably slower than
the full version - https://interrupt.memfault.com/blog/memcpy-newlib-nano
Newlib full is more consistent w c11 stanard, including
* full newlib provides native possiblity to printf 64-variables,
including double and float.
* calling destructors of global objectes ate system exit
* probaly many more...
There was hard fault while trying to enable full newlib whithout
recompilling memcpy implementation with -mno-unaligned-access compile
option.
It was failing for missalinged memory access during memcpy.
Similar issue is described here -
https://bugs.launchpad.net/gcc-arm-embedded/+bug/1857469
=> [EGD-2489] Enable full newlib

module-bsp/board/rt1051/bellpx/bsp/switches/switches.cpp
light click should not be detected while deep press
=> [EGD-1295] Fix deep press with light click

module-os/board/rt1051/fsl_tickless_gpt.c, module-os/board/rt1051/port.c, module-os/board/rt1051/systemview/port.c, products/PurePhone/PurePhoneMain.cpp
Add support to the FreeRTOS to be able to back to main
functon when the scheduler is terminated.
=> [EGD-8127] Add FreeRTOS return to main when scheduler exits

module-services/service-cellular/ServiceCellular.cpp
Without a SIM card, the modem will be able to enter sleep mode,
which will significantly extend the battery life of the phone.
=> [EGD-8121] Fix cellular sleep mode enter without SIM

Target_RT1051.cmake, board/rt1051/ldscripts/sections.ld, module-bsp/board/rt1051/common/board.cpp, module-bsp/board/rt1051/common/startup_mimxrt1052.cpp, module-bsp/bsp/bsp.hpp, module-os/board/rt1051/__atexit.c, module-os/board/rt1051/__call_atexit.c, module-os/board/rt1051/_exit.cpp, module-os/board/rt1051/atexit.h, module-os/board/rt1051/include/exit_backtrace.h, module-platform/rt1051/CMakeLists.txt, module-platform/rt1051/src/RT1051Platform.cpp, module-sys/SystemManager/SystemManagerCommon.cpp, module-utils/log/Logger.cpp, module-utils/log/Logger.hpp, products/BellHybrid/CMakeLists.txt, products/PurePhone/CMakeLists.txt, products/PurePhone/PurePhoneMain.cpp
Added atexit functionality. All global destructors and functions
registered with atexit() should be called at program exit.
It was possbile to reuse original newlib implementation with 
MALLOC_PROVIDED flag set.
Made sure logger destructructor is called as last one.
Due to mudita OS legacy, it was not possible to simply fix dependencies
in global objectes and hence there are neither global objects destructors
nor functions registered with atexit() called when exit() is called.
Possibly it will be changed later.
=> [EGD-8129] Add atexit functionality

image/assets/lang/Deutsch.json, image/assets/lang/English.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, image/assets/lang/Polski.json
"Units" is removed from Time&Units app name
=> [BH-1328] Remove "Units" Literal

module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp, module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.hpp
When the voltage dropped below the brownout threshold,
the system did not detect the battery charging
and displayed a window with the low battery icon all the time.
=> [EGD-8141] Fix brownout handling while charging

products/PurePhone/CMakeLists.txt, products/PurePhone/assets_images.json
As well as mpi assets for the call: EGD-8158
1. the first one was bell only, now made common
2. the second one were mpi where docs asserted that we do not use mpi anymore
=> [EGD-8152] Added lacking colon asset

module-apps/apps-common/popups/presenter/AlarmPresenter.cpp
There was typo in check (missin **!** ) when copied the test in if :face_exhaling: 
for: 7127efa876eef0f593ba8358e911b606d06a14dc
=> [EGD-8108] Bugfix typo fix

module-apps/application-phonebook/widgets/ContactFlagsStyle.hpp
Swedish translation of the ICE contact was too long
to fit `ContactFlag` item.
=> [EGD-8114] Make ContactFlag item wider

module-services/service-cellular/service-cellular/Constans.hpp, module-sys/SystemManager/SystemManagerCommon.cpp
Service cellular is added to system close whitelists.
It prevents hard fault when cellular is blocked
on long command handler.
=> [EGD-8156] Fix cellular on system close whitelists

module-apps/application-meditation/widgets/TimerProperty.cpp
The user was able to set 0 meditation time and
start meditation. Now 0 is automatically changed
to minimal meditation time.
=> [EGD-7461] Disallow to set 0 meditation time

module-apps/application-settings/windows/system/DateAndTimeMainWindow.cpp
Elements in the date and time screen were in the wrong order.
Now they are aligned with design.
=> [EGD-8034] Switch elements order on date and time screen

module-utils/utility/Utils.hpp
Phone number validation in input field was too restrictive,
which caused error during attempt to save correctly
formatted phone numbers.
=> [EGD-8124] Allow to use dashes, parenthesis and dots in the phone numbers

module-apps/application-meditation/widgets/TimerProperty.cpp, module-apps/application-meditation/widgets/TimerProperty.hpp
Excepted behavior: Deleting characters should work in a
duration time input
Current Behavior: Pressing "#" to delete characters
doesn't work in the input
=> [EGD-8049] Fix deleting button in meditation app

module-vfs/drivers/src/purefs/fs/filesystem_vfat.cpp
Fix statvfs() function for report proper block size on
the vfat parition
=> [EGD-8198] Fix reporting block size on the fat patrtition

module-apps/apps-common/widgets/BellBaseLayout.hpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.hpp
Inform BottomBox that Battery Box has changed. BatteryBox does not take space for bottom text now and full message is displayed
=> [BH-1345] Fix Broken Text During Charging

module-apps/application-calendar/ApplicationCalendar.cpp, module-apps/application-meditation/ApplicationMeditation.cpp
Fixed empty Lock screen in applications Caledar and Meditation.
Error was caused by not handled messages response at all.
=> [EGD-8168] Fix Fixed lock screen in Calendar and Meditation

image/user/data/equalizer/earspeaker_routing.json, image/user/data/equalizer/headphones_playback.json, image/user/data/equalizer/headphones_routing.json, image/user/data/equalizer/loudspeaker_playback.json, image/user/data/equalizer/loudspeaker_routing.json, module-audio/Audio/Profiles/Profile.cpp, module-audio/Audio/Profiles/Profile.hpp, module-audio/Audio/Profiles/ProfileConfigUtils.cpp, module-audio/Audio/Profiles/ProfileConfigUtils.hpp, module-audio/Audio/Profiles/ProfilePlaybackHeadphones.hpp, module-audio/Audio/Profiles/ProfilePlaybackLoudspeaker.hpp, module-audio/Audio/Profiles/ProfileRoutingEarspeaker.hpp, module-audio/Audio/Profiles/ProfileRoutingHeadphones.hpp, module-audio/Audio/Profiles/ProfileRoutingLoudspeaker.hpp, module-audio/Audio/Profiles/README.md, module-audio/Audio/codec.hpp, module-audio/Audio/equalizer/Equalizer.cpp, module-audio/Audio/equalizer/Equalizer.hpp, module-audio/Audio/test/CMakeLists.txt, module-audio/Audio/test/testfiles/testProfile.json, module-audio/Audio/test/unittest_config_utils.cpp, module-audio/Audio/test/unittest_equalizer.cpp, module-audio/CMakeLists.txt, module-audio/README.md
This allows for imporing the audio profile setitngs, including
EQ settings from the json file, thus allowing modification of
those setitngs without the need of recompiling the source code.
=> [EGD-8162] Allow importing audio profile settings from json file

module-bsp/board/rt1051/bsp/lpm/RT1051LPM.cpp, module-bsp/board/rt1051/common/reboot_codes.hpp, module-bsp/bsp/lpm/bsp_lpm.hpp, module-services/service-appmgr/model/ApplicationManagerCommon.cpp, module-services/service-desktop/endpoints/developerMode/DeveloperModeHelper.cpp, module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp, module-services/service-desktop/endpoints/include/endpoints/developerMode/DeveloperModeHelper.hpp, module-services/service-desktop/endpoints/include/endpoints/update/UpdateHelper.hpp, module-services/service-desktop/endpoints/update/UpdateHelper.cpp, module-sys/SystemManager/PowerManager.cpp, module-sys/SystemManager/SystemManagerCommon.cpp, module-sys/SystemManager/include/SystemManager/PowerManager.hpp, module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp, module-sys/common/include/system/Common.hpp
It will allow to reboot the device to USB MSC mode
without need to interact with a physical keyboard.
=> [CP-1007] Add API for rebooting to USB MSC mode

module-sys/SystemManager/include/SystemManager/PowerManager.hpp
After a longer time (~ 14 hours), the Power Manager
Efficiency logs showed incorrect values.
=> [EGD-8225] Fix incorrect logs of Power Manager Efficiency

products/PurePhone/services/db/ServiceDB.cpp
Used proper instance of quotes DB to backup.
=> [CP-1048] Database instance mix-up in predefinedQuotesDB backup code

module-apps/application-meditation/widgets/IntervalBox.cpp
Fix meditation timer default interval is set to none
=> [EGD-8254] Fix Default interval is set to None

config/bootstrap.sh, config/run_runner_docker
For the `bootscript.sh` and `run_runner_docker` script to run, the directory name for "common_scripts_lib" must be spelled correctly.
=> [EGD-8258] Fix directory name in config scripts

module-apps/application-calllog/ApplicationCallLog.cpp, module-utils/phonenumber/NumberHolderMatcher.hpp, products/PurePhone/services/db/ServiceDB.cpp
Determined 3 reasons of lag
1. each calllog app opening is sending db::query::calllog::SetAllRead
which marks all calllog database entries as read and send CRUD
notification to application and hence the list view is rebuilt at least
twice for each app opening.
After deeper investigation it seems like dead feature (at least not
covered in GUI) and I am going to disable it.
2. DBServiceAPI::MatchContactByPhoneNumber requested for empty string
(private number) take really long time (above 1s).
3. DBServiceAPI::MatchContactByPhoneNumber took about time 150-200ms
This patch fixes only issues 1. and 2. Number 3. requires further
investigation and is consider as separate issue.
After mentioned fixes calllog is pretty responsive but requires ~2s
for each app start or page change.
=> [MOS-104] Fix calllog responsivness with large number of contacts

module-services/service-evtmgr/EventManager.cpp, module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp, module-sys/SystemManager/CpuSentinel.cpp, module-sys/SystemManager/include/SystemManager/CpuSentinel.hpp, module-sys/SystemManager/tests/unittest_CpuSentinelsGovernor.cpp
On the locked screen, while refreshing the screen,
the CPU woke up to the maximum frequency,
which resulted in an increased power consumption.
=> [MOS-144] Fix Increased CPU usage

module-apps/application-calllog/ApplicationCallLog.cpp, module-apps/application-calllog/windows/CallLogMainWindow.cpp, module-apps/apps-common/notifications/NotificationsListPresenter.cpp
There was no label on missed call notification from private number.
After fix it is diplaying "Missed calls" info.
Original fix from 60bdca524338025dc0117edcc5c5579376441b0b [MOS-104]
was also modifed as it previously introduced regression on menu window.
[MOS-104]: https://appnroll.atlassian.net/browse/MOS-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOS-97] Fix of wrong label for missed call notification

module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/service-cellular/ServiceCellular.hpp
UART baudrate changed from 460800 to 115200
* lower power consumption by modem
* CPU does not need to wake up to handle URC
=> [EGD-8128] Baudrate change for cellular transmission

products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
Due to improper ownership model, all data models
used by the main application were recreated each time
the language changed.
=> [BH-1259] Changing language resets snooze timer

module-apps/application-phonebook/windows/PhonebookIceContacts.cpp
The user was able to get to the regular contact list and manipulate it
on a locked phone after an emergency call. Now the user is switched back outside
the contacts app after going back from the ICE contact list.
=> [MOS-36] Disallow going to regular contact list after emergency call

module-sys/SystemManager/SystemManagerCommon.cpp, module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp, module-sys/common/include/system/Common.hpp
There are some issues with service eink and service desktop during update from mudita center and hence deinitializing both services during system update is temporarily disabled.
=> Egd 8193 proper system shutdown during update 2

module-apps/application-meditation/widgets/IntervalBox.cpp
[Meditation] There is no None interval chime
for meditation time < 31min
=> [MOS-233] Fix no chime interval in med timer

module-services/service-appmgr/include/service-appmgr/model/ApplicationManagerCommon.hpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, products/PurePhone/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp, test/pytest/service-desktop/test_device_info.py
Generating a device unique id during on-boarding
Returning device token generated from device unique id in DeviceInfo
Added test for device token in test_devic_info.py
=> [CP-1021] Add token field to Device Info API

module-apps/application-phonebook/windows/PhonebookSearch.cpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
Abc mode was not selected as a default,
because it was not added in this input field.
=> [MOS-234] Add Abc input mode to contact search

module-apps/application-alarm-clock/models/NewEditAlarmModel.cpp, module-apps/application-alarm-clock/presenter/AlarmRRulePresenter.cpp
Days of the week should be separated by
a comma and a space in the alarm repeat widget.
=> [MOS-76] add missing space in the separator

module-sys/SystemManager/SystemManagerCommon.cpp
After the restore process is complete, the system shuts down
properly without any unexpected events.
=> [MOS-135] Proper system shutdown during restore

doc/adding_unittests.md, doc/quickstart.md, doc/setup_ide.md
There are few broken links in the documentation that have been
corrected.  The cause is either errant whitespace in the link
or by confusing (link)[url] for [link](url).
Errors like this can be found with these regex grep statements:
```
grep -rnE "\([^\)]+\)\[[^]]+\]" doc/*
grep -rnE "[^\!]\[[^]]+\]\([^\)]*\s[^\)]*\)" doc/*
```
=> [MOS-218] Fix broken documentation links

products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
Delay homescreen display to avoid blinking on startup
=> [BH-1405] Delay homescreen display to avoid blinking

module-services/service-cellular/call/CallAudio.cpp
Audio service is deadlocked on sentinel because IsBussy() method returns
that it's all the time bussy. Even though there is no ongoing audio
requested from either GSM or apps.
=> [MOS-269] Fix lock audio subsystem during voice call

doc/setup_ide.md
These are initial instructions on how to configure the QtCreator IDE.
=> [MOS-219] Expand "Setup IDE" to include QtCreator

host-tools/littlefs-fuse/CMakeLists.txt
Fix compilation for the LFS fuse tools with GCC11
Please describe your pull request
=> [MOS-316] Fix compile lfs fuse with GCC11 host

module-services/service-bluetooth/ServiceBluetooth.cpp, module-services/service-bluetooth/service-bluetooth/ServiceBluetooth.hpp
Fix bluetooth not auto turning off.
Changes in logic (consulted with PO):
Changed logic to properly turn off on idle state (with no device connected).
Changed turnoff timeout to 10 minutes.
=> [MOS-291] Fix bluetooth auto turn off

image/CMakeLists.txt, products/BellHybrid/CMakeLists.txt, products/PurePhone/CMakeLists.txt
Fixing:
- json-rt1051-target name
- download Luts.bin from proprietary source, not public
=> [MOS-288] Fixing cmake - target names

module-bsp/board/rt1051/bsp/audio/CodecMAX98090.hpp
=> [MOS-303] GCC11 build fix

module-services/service-eink/ServiceEink.cpp, module-services/service-evtmgr/EventManager.cpp, products/PurePhone/EinkSentinelPure.cpp
eInk is turned on for 2 sec to redraw the screen 
- so far it was 3.8 sec
=> [MOS-117] Faster eInk sleep after screen redraw

module-sys/SystemManager/cpu/algorithm/FrequencyStepping.cpp, module-sys/SystemManager/cpu/algorithm/FrequencyStepping.hpp
Downscaling the CPU frequency from max to min
takes less than 1 second.
=> [MOS-338] Fix regression in the frequency stepping algorithm

products/BellHybrid/apps/application-bell-settings/presenter/BedtimeSettingsPresenter.cpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp, products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.cpp
Fix audio playback on return
Audio playback did not properly stop on return without save from Bedtime Tone Settings and Alarm Settings. Furthermore a crash due to segmentation fault was observed upon re-entering into those settings. This PR fixes those issues
=> [BH-1434] Fix Bedtime Tone Return

module-apps/application-call/ApplicationCall.cpp, module-apps/application-call/include/application-call/ApplicationCall.hpp, module-apps/application-call/windows/CallWindow.cpp, module-services/service-cellular/CellularRequestHandler.cpp, module-services/service-cellular/CellularServiceAPI.cpp, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/call/CallAudio.cpp, module-services/service-cellular/call/CallAudio.hpp, module-services/service-cellular/call/CellularCall.cpp, module-services/service-cellular/service-cellular/CellularMessage.hpp, module-services/service-cellular/service-cellular/CellularServiceAPI.hpp, module-services/service-cellular/service-cellular/call/CellularCall.hpp
AudioServiceAPI is now removed from Call app.
Call audio routing is handled in service cellular.
Please describe your pull request
=> [MOS-325] AudioServiceAPI removed from Call app

module-services/service-cellular/call/CallAudio.cpp
After the outgoing call was terminated,
the audio was terminated incorrectly,
therefore the next call did not ring.
=> [MOS-337] Fix no audio for incoming calls/messages

module-services/service-db/ServiceDBCommon.cpp, module-services/service-db/include/service-db/DBNotificationMessage.hpp, module-services/service-db/include/service-db/ServiceDBCommon.hpp, module-services/service-db/messages/DBNotificationMessage.cpp, module-services/service-desktop/CMakeLists.txt, module-services/service-desktop/OutboxNotifications.cpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/include/service-desktop/Outbox.hpp, module-services/service-desktop/include/service-desktop/OutboxNotifications.hpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, products/PurePhone/services/db/ServiceDB.cpp, products/PurePhone/services/desktop/endpoints/outbox/OutboxHelper.cpp
When contact record is created/updated/removed during 
connection with Mudita Center, notification of that             
action should be collected in outbox endpoint to
keep contacts data synchronized between MuditaOS
and Mudita Center. In upcoming PRs, SMS and SMSThread
records changes will be handled in a similar way.
=> [CP-1080] Collect contact notifications in outbox endpoint

module-gui/gui/widgets/NavBar.cpp, module-gui/gui/widgets/Style.hpp
RED - new look
BLACK - look before regression took place (community build)
So basically 100% overlap except time
Unfortunatelly the screen does not match MIRO perfectly (main time and date are shifted), but since im not fluent with Pure workflow I will only fix the refression I created and make a bug for the rest in JIRA
=> [MOS-361] Navbar fonts size fix

module-bsp/board/rt1051/bellpx/board.cpp
Going to SNVS requires usage of periph clock
That reuires further cpu configuration changes
Easiest way is to just change cpu freq to level 2
=> [BH-1443] Lower CPU freq before going to SNVS

test/CMakeLists.txt
This updates version number for the `MuditaOSPublicAssets` from version 0.0.4 to version 0.0.7 the CMake file for unit testing.
Without this update, the unit tests will fail because `image/assets/fonts/fontmap.json` is not in the asset tarball.
resolves #3719
=> [MOS-377] Update community assets version for unit tests

module-services/service-appmgr/include/service-appmgr/model/ApplicationManagerCommon.hpp, module-services/service-appmgr/model/ApplicationManagerCommon.cpp, products/BellHybrid/services/appmgr/ApplicationManager.cpp, products/BellHybrid/services/appmgr/include/appmgr/ApplicationManager.hpp, products/PurePhone/services/appmgr/ApplicationManager.cpp, products/PurePhone/services/appmgr/include/appmgr/ApplicationManager.hpp
Separate implementations of handleDisplayLanguageChanged()
This PR fixes BellHybrid application assertion during language change. HandleDisplayLanguageChanged() needs to have different behaviour now between Bell and Pure
=> [BH-1432] Split Language Display Handling

module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
When we start the system without the USB cable connected,
worker USB is initialized, which increases
the power consumption.
=> [MOS-371] Fix USB worker initialization

module-services/service-desktop/WorkerDesktop.cpp, module-services/service-desktop/WorkerDesktop.hpp, module-sys/SystemManager/SystemManagerCommon.cpp
After disconnecting the USB cable, the CPU consumption
increased to over 80% (for 4 MHz), which resulted
in a cyclical change in the CPU frequency and finally
a much shorter battery life.
=> [MOS-339] Fix rapid change of CPU frequency

module-bsp/board/rt1051/bsp/lpm/RT1051LPMCommon.cpp, module-bsp/board/rt1051/puretx/bsp/lpm/RT1051LPM.cpp
The buck regulators will run in PWM mode
when the load current exceeds a predefined threshold.
When the load current drops below the specified threshold,
the regulator will operate in energy saving mode (PSM)
improve performance under light loads.
=> [MOS-386] Enable auto mode for DCDC converter

evkbimxrt1050_sdram_init.jlinkscript, evkbimxrt1050_sdram_init_T6.jlinkscript
Fix jlink debug not working for Harmony by turning off hardware watchdog on jlink start.
Added same watchdog switch to T7(Pure) script as it could possibly become a problem in the future.
=> [BH-1455] Fix jlink debug not working

module-bluetooth/tests/tests-BluetoothDevicesModel.cpp, module-services/service-bluetooth/ServiceBluetooth.cpp, module-services/service-bluetooth/service-bluetooth/BluetoothDevicesModel.cpp, module-services/service-bluetooth/service-bluetooth/BluetoothDevicesModel.hpp
Fix of the bug that after pairing with one device
the entire list of devices that were visible at
the pairing time is transferred to paired devices
list.
=> [MOS-384] BT paired devices list fix

module-db/Common/Query.cpp, module-db/Common/Query.hpp, module-db/Interface/ContactRecord.cpp, module-db/Interface/SMSRecord.cpp, module-db/Interface/ThreadRecord.cpp, module-services/service-db/ServiceDBCommon.cpp, module-services/service-db/include/service-db/ServiceDBCommon.hpp
When sms thread record or sms record is modified during connection
with Mudita Center, notification of that action
should be collected in outbox endpoint to
keep contacts data synchronized between MuditaOS
and Mudita Center.
Documentation: 
[Outbox endpoint API](https://appnroll.atlassian.net/wiki/spaces/CP/pages/1599996137/Outbox+Endpoint+API+14)
[How to notify MC about updates to user data in almost real time](https://appnroll.atlassian.net/wiki/spaces/CP/pages/1598193852/How+to+notify+MC+about+updates+to+User+data+in+almost+real+time)
=> [CP-1085][CP-1082] Collect sms and sms thread notifications in outbox ep

products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp, products/BellHybrid/apps/application-bell-meditation-timer/models/ChimeVolume.cpp
Fixed saving of volume in Chime Model
This fixes the following issues of [BH-1433]
- Proper saving of volume value
- Activated subscription to Audio Notifications for volume change callback to properly work
[BH-1433]: https://appnroll.atlassian.net/browse/BH-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BH-1433] Chime Volume Model Fix

module-db/Common/Query.hpp
The `<optional>` header is required to use std::optional.  This fixes unit test building.
=> [MOS-400] Fix missing header

module-apps/application-call/ApplicationCall.cpp, module-apps/application-call/CMakeLists.txt, module-apps/application-call/data/CallSwitchData.hpp, module-apps/application-call/include/application-call/ApplicationCall.hpp, module-apps/application-call/model/CallModel.cpp, module-apps/application-call/model/CallModel.hpp, module-apps/application-call/presenter/CallPresenter.cpp, module-apps/application-call/presenter/CallPresenter.hpp, module-apps/application-call/test/CMakeLists.txt, module-apps/application-call/test/mock/CallPresenterMocks.hpp, module-apps/application-call/test/unittest_call_presenter.cpp, module-apps/application-call/windows/CallWindow.cpp, module-apps/application-call/windows/CallWindow.hpp, module-services/service-cellular/call/CallGUI.cpp, module-services/service-cellular/call/CallGUI.hpp, module-services/service-cellular/call/CellularCall.cpp, module-services/service-cellular/service-cellular/CellularMessage.hpp, module-utils/time/time/time_conversion.hpp
Call logic is now removed from call window and call app.
There was spaghetti logic mixed in window and app, now
call logic is based on notificatins from service cellular.
=> [MOS-326] Change call logic removed from call window

module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.hpp
Fix for the bug that after a few hours of inactivity 
time on lock screen was getting illegible.
=> [MOS-402] Illegible time bug fix

module-bsp/board/rt1051/os/CMakeLists.txt, module-os/CMakeLists.txt
Fixed issues with gdb pure due to the DEBUG_FREERTOS
flag not propagating correctly.
=> [MOS-422] Fix pure gdb tools

image/assets/lang/Deutsch.json, image/assets/lang/English.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, image/assets/lang/Polski.json, image/assets/lang/Svenska.json, module-apps/application-call/data/CallAppStyle.hpp, module-apps/application-call/model/CallModel.cpp, module-apps/application-call/model/CallModel.hpp, module-apps/application-call/presenter/CallPresenter.cpp, module-apps/application-call/presenter/CallPresenter.hpp, module-apps/application-call/test/mock/CallPresenterMocks.hpp, module-apps/application-call/windows/CallWindow.cpp, module-apps/application-call/windows/CallWindow.hpp, module-apps/application-messages/data/SMSdata.hpp, module-apps/application-messages/windows/SMSTemplatesWindow.cpp, module-services/service-cellular/ServiceCellular.cpp
Reworked ending with sms is now reworked. Sms is send by call app,
application messages is only providing template text.
Also call hangup and sms send order is changed due to delays caused by
sending sms.
=> [MOS-420] Fix Call ending with sms reworked

products/PurePhone/services/desktop/endpoints/include/endpoints/messages/MessageHelper.hpp, products/PurePhone/services/desktop/endpoints/messages/MessageHelper.cpp, test/pytest/service-desktop/test_message_threads.py
Add API for getting a single thread by its ID.
Documentation: https://appnroll.atlassian.net/wiki/spaces/CP/pages/990642315/Messages+Endpoint+API+8?focusedCommentId=1012794077#Get-a-thread-by-ID
=> [CP-1232] Extend messages EP API with getThreadByID method

module-services/service-audio/ServiceAudio.cpp
Fix of the issue that incoming call sound was played
both in Pure speaker and HFP device while HFP profile
connected.
=> [MOS-442] Incoming call sound both on HFP and Pure fix

module-apps/application-call/model/CallModel.cpp, module-apps/application-call/model/CallModel.hpp, module-apps/application-call/test/mock/CallPresenterMocks.hpp, module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp, module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.cpp, module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.hpp, module-services/service-cellular/CMakeLists.txt, module-services/service-cellular/CellularServiceAPI.cpp, module-services/service-cellular/DTMFCode.cpp, module-services/service-cellular/DTMFCode.hpp, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/service-cellular/CellularMessage.hpp, module-services/service-cellular/service-cellular/CellularServiceAPI.hpp, module-services/service-cellular/service-cellular/ServiceCellular.hpp, module-services/service-cellular/tests/CMakeLists.txt, module-services/service-cellular/tests/unittest_DTMFCode.cpp, module-utils/utility/Utils.hpp, module-utils/utility/tests/unittest_utils.cpp
By accident, I've broke DTMF handling via Pure's keyboard
This was because of non strict description of API method.
Now, it has been unified to use number, not its ASCII code
=> [MOS-263] Fix DTMF handling in Pure

products/PurePhone/sys/SystemManager.cpp
After exceeding the 10% threshold of the battery,
there was no reaction during charging and the phone freezes
on the screen with a low battery.
=> [MOS-444] Fix phone freezing on low battery screen

module-sys/SystemManager/SystemManagerCommon.cpp
The phone sometimes remained on the power off screen
during system shutdown.
=> [MOS-389] Fix phone stuck on shutdown screen

image/user/db/settings_v2_002-devel.sql, image/user/db/settings_v2_002.sql, module-apps/application-desktop/windows/DesktopMainWindow.cpp, module-apps/application-desktop/windows/DesktopMainWindow.hpp, module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommon.hpp, module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp, module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.hpp, module-apps/apps-common/windows/AppWindow.cpp, module-apps/apps-common/windows/AppWindow.hpp, module-gui/gui/Common.hpp, module-services/service-db/agents/settings/SystemSettings.hpp, products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsProgressWindow.cpp, products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsProgressWindow.hpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.hpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.hpp, products/PurePhone/apps/Application.cpp
Fix of the issue that time on the lock screen was
getting illegible after a few hours. This change
fixes the problem by performing deep refresh
instead of fast refresh every 30 minutes. The
refresh rate can be easily changed, as it is stored
in settings database.
=> [MOS-402] Time legibility on lock screen fix

module-services/service-evtmgr/api/EventManagerServiceAPI.cpp, module-services/service-evtmgr/service-evtmgr/EVMessages.hpp, module-services/service-evtmgr/service-evtmgr/EventManagerServiceAPI.hpp, products/PurePhone/services/evtmgr/EventManager.cpp, products/PurePhone/services/evtmgr/include/evtmgr/EventManager.hpp, products/PurePhone/sys/SystemManager.cpp
Torch is now disabled on critical low battery level.
It will protect from battery draining.
=> [MOS-450] Fix turn off torch on critical battery level

products/PurePhone/services/desktop/endpoints/messages/MessageHelper.cpp, test/pytest/service-desktop/test_message_threads.py
Allow deleting single message thread specified by id
using messages endpoint API.
Documentation: https://appnroll.atlassian.net/wiki/spaces/CP/pages/990642315/Messages+Endpoint+API+8#Delete-a-thread
=> [CP-1135] Extend messages API by deleteThread method

module-apps/application-alarm-clock/widgets/AlarmTimeItem.cpp, module-apps/application-alarm-clock/widgets/AlarmTimeItem.hpp
Added zero padding to alarm time fields when setting
alarm time.
=> [MOS-418] Add zero padding when setting alarm time

module-services/service-db/ServiceDBCommon.cpp, module-services/service-db/include/service-db/DBNotificationMessage.hpp, module-services/service-db/include/service-db/ServiceDBCommon.hpp, module-services/service-db/messages/DBNotificationMessage.cpp, module-services/service-desktop/OutboxNotifications.cpp
Fix of the issue that adding or deleting alarm in
alarms app didn't result in immediate updating
of the alarms list - app has to be closed and
opened for changes to be seen.
=> [MOS-457] Alarms list updating fix

module-cellular/at/Commands.hpp, module-cellular/at/src/ATFactory.cpp, module-cellular/at/src/Commands.cpp
Add new default QCFG settings:
- servicedomain,
- nwscanmode.
This may help the issue, however we don't know for sure as we have no clear reproduction.
The solution was sourced from Quectel forums for similair issue. 
=> [MOS-395] Add new def QCFG settings

products/BellHybrid/alarms/src/AlarmSoundPaths.cpp
Fixed missing relaxation entries by temporarily
replacing background sounds asset path.
1.6.0 update doesn't replace the old audio assets with the new ones.
As a result we have temporarily two identical copies placed under
different paths. This issue should be fixed with the proper migration
mechanism that we currently lack.
=> [BH-1482] Fixed missing relaxation entries

module-utils/utility/Utils.hpp, module-utils/utility/tests/unittest_utils.cpp
utils::getNumericValue returned improper result
for uint8_t and int8_t types, this change
fixes it.
=> [MOS-485] utils::getNumericValue fix

products/BellHybrid/apps/application-bell-settings/models/TimeUnitsModel.cpp
When setting the new time from the settings application,zero current seconds counter to have time set precisely.
=> [BH-1487] Seconds are not set to zero

module-apps/apps-common/ApplicationCommon.hpp, products/BellHybrid/apps/Application.cpp, products/BellHybrid/apps/include/Application.hpp
Prevent popups from clearing settings screen
Popups default switch reason is set to Popup instead of PhoneLock
=> [BH-1489] Prevent popups from clearing settings screen

products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
Reset timer on state machine reset (homescreen)
=> [BH-1480] Reset timer on state machine reset

products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingOnOffWindow.cpp
Remove refresh after backpress in transport mode
so that last refresh will be welcome screen
(race deletion)
=> [BH-1488] Remove refresh after back press on transport mode

module-apps/application-call/ApplicationCall.cpp, module-apps/application-call/include/application-call/ApplicationCall.hpp, module-services/service-appmgr/include/service-appmgr/Actions.hpp, module-services/service-appmgr/tests/test-ApplicationManifest.cpp, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/call/CallMachine.hpp, module-services/service-cellular/call/CellularCall.cpp, module-services/service-cellular/call/api/ModemCallApi.cpp, module-services/service-cellular/call/api/ModemCallApi.hpp, module-services/service-cellular/call/include/call/CallEvents.hpp, module-services/service-cellular/call/include/call/CellularCall.hpp, module-services/service-cellular/call/tests/test-CallMachine.cpp, module-services/service-cellular/service-cellular/CellularMessage.hpp, module-sys/PhoneModes/include/PhoneModes/Common.hpp, module-sys/PhoneModes/include/PhoneModes/Tethering.hpp
1. Removed AbortCall as popup and handled tethering in call machine.
Now: 
- there is no popup on dropped call from thethering mode
- there is incremented dropped call when in tethering mode ( and caller know it was dropped)
=> [MOS-419] Removed AbortCall as popup and handle tethering as part of call

module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommon.hpp, module-gui/gui/widgets/StatusBar.cpp, module-gui/gui/widgets/StatusBar.hpp, module-gui/gui/widgets/status-bar/BatteryBase.cpp, module-gui/gui/widgets/status-bar/BatteryBase.hpp, module-utils/EventStore/EventStore.cpp, module-utils/EventStore/EventStore.hpp
Fix of the issue that after the system has started
the network coverage wasn't updated for a long time
on the lock screen.
=> [MOS-473] Long time to refresh network coverage fix

products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
Correct alarm deactivation icon
=> [BH-1503] Correct alarm deactivation icon

module-services/service-appmgr/model/ApplicationManagerCommon.cpp
Sometimes the Mudita logo screen was still visible
even though the phone turned on and initialized properly.
=> [MOS-484] Fix freezes on the screen with the logo

module-apps/application-calendar/models/MonthModel.cpp, module-apps/application-calendar/models/MonthModel.hpp
By simplifying the logic, apparently the calendar got fixed.
Checked manually for the whole year 2022 and briefly for 2021, 2023.
Adding no unit tests because this was intended as a quick fix due to the plans to throw away and replace the whole logic.
=> [MOS-486] Fix the first day of month in the calendar

module-bsp/board/linux/hal/battery_charger/BatteryCharger.cpp, module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp, module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp, module-bsp/hal/include/hal/battery_charger/AbstractBatteryCharger.hpp, module-services/service-evtmgr/battery/BatteryController.cpp, module-services/service-evtmgr/battery/BatteryController.hpp
Invalid state of charge is now dropped. Invalid SoC was interpreted
as 0% battery.
=> [MOS-451] Drop invalid SoC

module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp, module-services/service-desktop/endpoints/security/SecurityEndpointHelper.cpp, test/pytest/service-desktop/test_security.py
The time of the next attempt to unlock the phone on
the MC side was bonded with the system time of
the MC host system. This could lead to issues when
the time on Pure was different than on MC host
operating system. Now everything relies on Pure
system time.
Documentation updated: https://appnroll.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=1299415622&selectedPageVersions=15&selectedPageVersions=13
=> [CP-1310] Add timeLeftToNextAttempt field to security EP

products/BellHybrid/apps/common/include/common/widgets/list_items/NumberWithSuffix.hpp
NumberWithSuffix list item contents
was shifted when going from view without
bottom text to the visible one.
=> [BH-1513] ListItems shift

products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
Homescreen alarm editing will remove the bottom text if exists
=> [BH-1510] Remove alarm notification text on alarm edit

products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsTimerSelectWindow.cpp
Relaxation app off value was not correctly translated due
to being defined as static const.
=> [BH-1508] Off string not translated correctly

module-apps/application-settings/ApplicationSettings.cpp, module-apps/application-settings/CMakeLists.txt, module-apps/application-settings/presenter/network/SimPINSettingsPresenter.cpp, module-apps/application-settings/presenter/network/SimPINSettingsPresenter.hpp, module-apps/application-settings/windows/network/SimPINSettingsWindow.cpp, module-apps/application-settings/windows/network/SimPINSettingsWindow.hpp
Fix of the bug that after selecting SIM slot
in which there's no card and trying to
enter PIN settings menu phone was getting
stuck in infinite looping between
PIN settings window and 'Cannot connect
to SIM card' popup.
=> [MOS-494] PIN settings infinite loop fix

module-apps/apps-common/locks/input/PhoneLockedKeysWhitelist.cpp
Fix of the issue that changing phone mode
using slider while the phone was locked
unnecessarily triggered the popup with
unlock instructions.
=> [MOS-37] Slider triggering unlock instructions popup fix

module-audio/Audio/decoder/DecoderWorker.hpp
There were occasional crashes due to too small a stack for the audio worker.
These were not caught via stack overflow catching logic most of the times
=> [MOS-53] Not enough stack for audio worker

module-apps/application-music-player/presenters/SongsPresenter.cpp, module-apps/application-music-player/windows/MusicPlayerMainWindow.cpp
Fix of the issue that after pausing playback
using Bluetooth device button, the progress
bar remained in progress and playback
time continued to count.
Correction of typo in variable name.
=> [MOS-532] Music player progress bar behaviour fix

products/BellHybrid/apps/application-bell-meditation-timer/windows/SettingsWindow.cpp
Deep press causes blank screen when in
meditation/settings.
=> [BH-1517] Blank screen after deep press

products/BellHybrid/apps/common/include/common/widgets/list_items/NumberWithSuffix.hpp, products/BellHybrid/apps/common/include/common/widgets/list_items/details.hpp
Controlling each list item's bottom
text by setVisibility does not give correct
results. It is required to explicitly resize
the bottom container.
From now on, resize call is
placed in ListItemBase so each new and existing
list items will be affected by this change resulting
in proper behavior without need for the programmer to
remember about it.
=> [BH-1520] Missing bottom texts

module-db/Interface/SMSTemplateRecord.cpp, module-db/Tables/SMSTemplateTable.cpp, module-db/Tables/SMSTemplateTable.hpp, module-db/queries/messages/templates/QuerySMSTemplateAdd.cpp, module-db/queries/messages/templates/QuerySMSTemplateAdd.hpp, module-db/tests/SMSTemplateTable_tests.cpp, products/PurePhone/services/desktop/endpoints/messages/MessageHelper.cpp, test/pytest/service-desktop/test_templates.py
No information about the newly added message template
was returned. Now temaplateID helps to identify
the newly added record.
Documentation:  https://appnroll.atlassian.net/wiki/spaces/CP/pages/990642315/Messages+Endpoint+API+8#Add-a-message-template
=> [CP-1334] Return templateID after adding new message template

module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/WorkerDesktop.cpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, module-services/service-evtmgr/battery/BatteryController.cpp, module-services/service-evtmgr/battery/BatteryController.hpp, module-services/service-evtmgr/service-evtmgr/BatteryMessages.hpp
Tethering popup loop is fixed. Also there was unneded USB
configuration on each battery SoC change event.
=> [MOS-509] Fixed tethering popup loop

image/assets/lang/Deutsch.json, image/assets/lang/Espanol.json
Change characters that do not exist in exported font to existing ones
It seems that ö is not the same as ö
ä is not the same as ä
and ó is not the same as ó
=> [BH-1523] Fix diacritic characters

module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp, module-bluetooth/lib/btstack.cmake
There was an error when user tried to connect using TRY AGAIN.
The bug was in the bluetooth stack, so we updated it as it has
a fix for it. Now it works and BT overall should work better now.
=> [MOS-527] Fix bluetooth reconnection error

module-apps/application-desktop/models/ActiveNotificationsListPresenter.cpp
Fix of the issue that RF button clears
snoozed alarms notifications from desktop.
=> [MOS-32] RF clears snoozed alarms fix

cmake/modules/ConfigureVersionJson.cmake
Misspelled variable could cause missing checksum for updater
=> [MOS-555] Fix misspelled cmake variable

module-apps/apps-common/popups/BluetoothAuthenticatePopup.cpp, module-bluetooth/Bluetooth/BluetoothStateMachine.hpp
Fix of the issue that forgotten BT device
reappeared on 'All devices' list after
reentering the list from home screen.
Additionally fixed pairing confirmation
popup that wouldn't hide after pressing
"Confirm".
=> [MOS-529] Forgotten BT device remains on the list

module-services/service-cellular/call/CallMachine.hpp, module-services/service-cellular/call/tests/test-CallMachine.cpp
Calls from a favorite contact for enabled notifications
were rejected.
=> [MOS-556] Fix call rejection in DND

module-apps/apps-common/popups/lock-popups/PhoneLockedInfoWindow.cpp, module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp, module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.hpp, module-apps/apps-common/popups/presenter/WallpaperPresenter.cpp, module-apps/apps-common/popups/presenter/WallpaperPresenter.hpp, module-gui/gui/widgets/StatusBar.cpp, module-gui/gui/widgets/StatusBar.hpp
Refresh lock screen only when clock wallpaper 
or status bar time is set.
Remove unused items from status bar to avoid refresh
every minute. Add status in debug log to make
sure which module performed the refresh.
=> [MOS-499] Turn off the one-minute screen refresh for quotes

module-bluetooth/Bluetooth/BluetoothStateMachine.hpp, module-services/service-bluetooth/ServiceBluetooth.cpp, module-services/service-bluetooth/service-bluetooth/ServiceBluetooth.hpp
The call answer event was incorrectly routed to BT, thus
the device was not aware of answering the call
=> [MOS-570] Fix HFP answering bug

board/linux/libiosyscalls/CMakeLists.txt, board/linux/libiosyscalls/src/syscalls_common.hpp, board/linux/libiosyscalls/src/syscalls_posix.cpp, board/linux/libiosyscalls/src/syscalls_wrapper.cpp
Add wrapper for posix stat function
in order to invoke our implementation.
=> [MOS-549] Linux simulator crashes on GCC12

module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommon.hpp, module-apps/apps-common/WindowsStack.cpp, module-apps/apps-common/WindowsStack.hpp, module-services/service-cellular/call/CellularCall.cpp
Fix of the issue that when phone was started in
mode different than Connected, next mode changed
resulted in bypassing of the lock.
=> [MOS-559] Fix unlock when phone started not in Connected mode

module-apps/application-notes/ApplicationNotes.cpp, module-apps/application-notes/presenter/NoteEditWindowPresenter.cpp, module-apps/application-notes/presenter/NoteEditWindowPresenter.hpp, module-apps/application-notes/windows/NoteEditWindow.cpp, module-apps/application-notes/windows/NoteEditWindow.hpp
Removed the auto-save facility from Notes as it was lacking any configuration and worked in unwanted moment(s).
=> [MOS-23] Back button works as save button in Notes

products/BellHybrid/apps/Application.cpp, products/BellHybrid/apps/CMakeLists.txt, products/BellHybrid/apps/application-bell-alarm/ApplicationBellAlarm.cpp, products/BellHybrid/apps/application-bell-alarm/include/application-bell-alarm/ApplicationBellAlarm.hpp, products/BellHybrid/apps/application-bell-alarm/presenter/BellAlarmSetPresenter.cpp, products/BellHybrid/apps/application-bell-alarm/presenter/BellAlarmSetPresenter.hpp, products/BellHybrid/apps/application-bell-alarm/presenter/BellAlarmWindowPresenter.cpp, products/BellHybrid/apps/application-bell-alarm/presenter/BellAlarmWindowPresenter.hpp, products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp, products/BellHybrid/apps/common/include/common/popups/presenter/AlarmActivatedPresenter.hpp, products/BellHybrid/apps/common/src/popups/presenter/AlarmActivatedPresenter.cpp, products/BellHybrid/apps/include/Application.hpp
Alarm model was moved to the bell-specific
application class. By doing this, each application will
have access to its unique and private instance of the model.
Later, it can be propagated to the specific presenters etc.
The next step should be to use only the one instance
of the alarm model and propagate it to the each application.
=> [BH-1519] Shared alarm model instance

module-bsp/CMakeLists.txt, module-bsp/board/rt1051/CMakeLists.txt, module-bsp/board/rt1051/bellpx/bsp/audio/AW8898driver.cpp, module-bsp/board/rt1051/bellpx/bsp/switches/switches.cpp, module-bsp/board/rt1051/bsp/rtc/rtc.cpp, module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp, module-bsp/devices/power/CW2015.cpp
Removed `-Wno-unused-variable` from
module-bsp.
Fixed issues that were reported after
removing it.
Removed unneeded compile flags from
rt1051 cmake file.
=> [BH-1536] Remove unneeded compilation flags

products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
Remove redundant arrows when alarm is ringing
=> [BH-1531] Remove redundant arrows when alarm is ringing

module-apps/application-settings/windows/phone-modes/PhoneModesWindow.cpp
Pure in simulator crashes with ASAN error when phone mode is uninitialized and user navigates into Settings -> Phone Modes.
Fix out of bounds memory access when selected phone mode is Uninitialized.
=> MOS-586-crash-of-pure-simulator-while-navigating-into-settings-phone-modes

module-services/service-evtmgr/WorkerEventCommon.cpp, module-services/service-evtmgr/service-evtmgr/WorkerEventCommon.hpp
In rare cases when corresponding Press and Release key events were not generated the logic prevented other keys from being handled. Handling of other keys is no longer blocked.
In addition to the above Release event is artificially generated. This ensures that key presses are not ignored if there were no real Release event. Typically this may occur when keys are pressed fast one after another. A side effect is that when a key was pressed while other one was already pressed then both of them are handled by the UI which prevents e.g. letters from being ignored while writing.
=> [MOS-210] Avoid blocking of key handling, artificially generate Release

module-apps/application-onboarding/windows/OnBoardingDateAndTimeWindow.cpp
The label 'SWITCH' remains visible instead of the original 'SELECT' whenever
exiting Change time zone' or 'Change date and time' sub-menus. The state returns
to normal when highlighting other options for the  'Date and time' screen.
=> [MOS-569] Fix incorrect navtext in onboarding for time zone and date time

.gitignore, .vscode/c_cpp_properties.json, .vscode/cmake-variants.yaml, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json
Make cmake build paths for the cmake extension the same as the ones used when building from command line and consistent with added tasks.
Add configure (cmake) and build (ninja) tasks.
Add/fix/improve launch configurations (for rt1051 [cortex-debug](https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug) extension is required).
Fix cpp properties to allow vscode finding headers and symbols.
Side note. There is a bug in `arm-none-eabi-gdb` 10 and 11 preventing comfortable debugging of muditaos with and without vscode (internal error in `bt` or `info stack`). Switching to `arm-none-eabi-gdb` 12.1 solves this issue. `gdb-multiarch` 12.0.9 works as well.
=> [MOS-591] Improve and unify vscode ide support

module-services/service-cellular/src/SimCard.cpp
Fix of the issue that entering 'PIN settings'
window before SIM card was ready caused
the crash of the system.
=> [MOS-514] Fix crash on entering PIN settings

module-apps/apps-common/popups/AlarmPopup.cpp
Fix of the issue that long press
of right function button causes
alarm popup window to close,
but alarm is still ringing.
The only way to turn it off was
to power off the phone.
=> [MOS-600] Fix RF button hold leaves alarm ringing

module-db/Interface/SMSRecord.cpp, test/pytest/service-desktop/test_messages.py
After adding a new message via Messages EP API,
threadID field was always 0, which was incorrect.
=> [CP-563] Return correct threadID after adding new message

image/user/db/meditation_stats_001.sql, module-db/Database/sqlite3vfs.cpp, module-services/service-db/DatabaseAgent.cpp, module-services/service-db/agents/settings/SettingsAgent.cpp, module-services/service-db/agents/settings/SettingsAgent.hpp, module-services/service-db/include/service-db/DatabaseAgent.hpp, products/BellHybrid/apps/application-bell-meditation-timer/CMakeLists.txt, products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp, products/BellHybrid/apps/application-bell-meditation-timer/models/Statistics.cpp, products/BellHybrid/apps/application-bell-meditation-timer/models/Statistics.hpp, products/BellHybrid/apps/application-bell-meditation-timer/presenter/StatisticsPresenter.cpp, products/BellHybrid/apps/application-bell-meditation-timer/presenter/StatisticsPresenter.hpp, products/BellHybrid/apps/application-bell-meditation-timer/widgets/SummaryListItem.cpp, products/BellHybrid/apps/application-bell-meditation-timer/widgets/SummaryListItem.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/StatisticsWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/StatisticsWindow.hpp, products/BellHybrid/services/db/CMakeLists.txt, products/BellHybrid/services/db/ServiceDB.cpp, products/BellHybrid/services/db/agents/MeditationStatsAgent.cpp, products/BellHybrid/services/db/agents/MeditationStatsAgent.hpp, products/BellHybrid/services/db/databases/CMakeLists.txt, products/BellHybrid/services/db/databases/MeditationStatisticsDB.cpp, products/BellHybrid/services/db/databases/MeditationStatisticsDB.hpp, products/BellHybrid/services/db/databases/MeditationStatisticsTable.cpp, products/BellHybrid/services/db/databases/MeditationStatisticsTable.hpp, products/BellHybrid/services/db/include/db/MeditationStatsMessages.hpp, products/BellHybrid/services/db/tests/CMakeLists.txt, products/BellHybrid/services/db/tests/MeditationStatisticsTable_tests.cpp, products/PurePhone/services/db/ServiceDB.cpp
Meditation stats backend. 
As part of this task minor update of the database agent interface was done in order to use it
instead of adding another record interface/database and manage them manually.
The `SummaryListItem` and body of the `StatisticsPresenter` was added only for test purposes. They will be reworked in the next task(BH-1357 and BH-1538).
=> [BH-1356] Meditation stats backend

module-apps/application-settings/ApplicationSettings.cpp, module-apps/application-settings/windows/bluetooth/BluetoothWindow.cpp, module-apps/application-settings/windows/bluetooth/BluetoothWindow.hpp
Fix of the issue that after entering
bluetooth settings power state is shown
as off at first, even though bluetooth
is turned on.
=> [MOS-421] Fix BT state first rendering off

module-apps/application-settings/windows/display-keypad/DisplayLightWindow.cpp, module-apps/application-settings/windows/display-keypad/DisplayLightWindow.hpp
The timer is responsible for refreshing debug options which interferes
with navigation strings of other windows until it is stopped when window
is destroyed.
=> [MOS-601] Disable debug timer in DisplayLightWindow

products/PurePhone/BinaryAssetsVersions.cmake
Changed downloaded version of updater,
1.5.2 allows to downgrade MuditaOS.
=> [MOS-635] Bump updater version for Pure

module-apps/application-desktop/windows/DesktopMainWindow.cpp, module-apps/application-desktop/windows/DesktopMainWindow.hpp, module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/popups/presenter/WallpaperPresenter.cpp, module-bsp/board/rt1051/bsp/eink/EinkDisplay.cpp, module-services/service-evtmgr/battery/BatteryController.cpp
Power on the e-ink only when it is needed e.g. fast or deep
refresh. This change should extend the battery life for a few hours.
Update battery percentage only when discharging.
=> [MOS-499] Improve lock screen power consumption

module-apps/application-settings/ApplicationSettings.cpp, module-apps/application-settings/models/bluetooth/BluetoothSettingsModel.cpp, module-apps/application-settings/models/bluetooth/BluetoothSettingsModel.hpp, module-apps/application-settings/windows/bluetooth/BluetoothWindow.cpp, module-services/service-bluetooth/ServiceBluetooth.cpp, module-services/service-bluetooth/service-bluetooth/ServiceBluetooth.hpp
Added code to update BT power state
when it automatically turns off due
to inactivity.
=> [MOS-421] Add state refresh when BT automatically turns off

module-services/service-eink/ServiceEink.cpp
Sometimes it took a long time to redraw
the screen with the USB cable unplugged.
=> [MOS-638] Fix poor phone responsiveness

module-bsp/board/rt1051/drivers/RT1051DriverI2C.cpp, module-bsp/board/rt1051/drivers/RT1051DriverI2C.hpp, module-bsp/board/rt1051/puretx/bsp/keyboard/keyboard.cpp, module-bsp/drivers/i2c/DriverI2C.hpp
Now the keyboard driver is checking the result of i2c
transmission and we get an error code if something fails.
=> [MOS-613] Fix keyboard doesn't respond

module-services/service-desktop/endpoints/deviceInfo/DeviceInfoEndpointCommon.cpp, module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp, module-services/service-desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpointCommon.hpp, products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, test/pytest/service-desktop/test_device_info.py
DeviceInfo endpoint now contains information such as:
`deviceSpaceTotal` - total storage space on the device
`systemReservedSpace` - storage space on the device
reserved for the OS
`usedUserSpace` - storage space on the device used
for user files on the user partition
Documentation: https://appnroll.atlassian.net/wiki/spaces/CP/pages/957055183/Device+Info+endpoint+1#Get-Device-Information
=> [CP-1448] Add storage info to device info endpoint

image/assets/lang/Deutsch.json, pure_changelog.md
Improved translation of PLAY label
in German.
https://github.com/mudita/MuditaOS/issues/4022
=> [MOS-664] PLAY label translation fix

module-bsp/board/linux/hal/battery_charger/BatteryCharger.cpp, module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp, module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp, module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.hpp, module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp, module-bsp/hal/include/hal/battery_charger/AbstractBatteryCharger.hpp, module-services/service-evtmgr/battery/BatteryController.cpp, module-services/service-evtmgr/battery/BatteryController.hpp, pure_changelog.md
If there were errors while charging the battery,
e.g. too high temperature, the detection of USB
connection/disconnection failed.
=> [MOS-648] Fix USB connection/disconnection detection

module-services/service-cellular/call/CallMachine.hpp, module-services/service-cellular/call/tests/test-CallMachine.cpp, pure_changelog.md
Added missing state transition in call 
state machine, required to switch 
call sound to loudspeaker before 
the call has been answered or 
rejected.
=> [MOS-667] Fix loudspeaker switching

module-services/service-cellular/call/api/CallTimer.cpp, module-services/service-cellular/call/api/CallTimer.hpp, pure_changelog.md
Fix of the issue that cancelled or rejected
outgoing call had improper duration in
calllog.
=> [MOS-665] Fix incorrect outgoing call duration

module-services/service-desktop/WorkerDesktop.cpp, pure_changelog.md
Modified USB notifications logging so no logs are being created
when USB data is received, thus logs are not overloaded and are
smaller
=> [MOS-668] Modify USB notifications logging

module-services/service-cellular/CMakeLists.txt, module-services/service-cellular/Pdu.cpp, module-services/service-cellular/Pdu.hpp, module-services/service-cellular/QMBNManager.cpp, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/tests/CMakeLists.txt, module-services/service-cellular/tests/unittest_Pdu.cpp, module-utils/utility/Utils.cpp, module-utils/utility/Utils.hpp, module-utils/utility/tests/unittest_utils.cpp, pure_changelog.md
The `[MMS]` notification is shown in message thread of the correct number
- Add PDU WAP Push MMS Notification parser
- Use it in ServiceCellular to parse the raw message
- Refactor hexToBytes and bytesToHex utils
- Add endsWith util
- Add unit tests
=> MOS-101 Parse MMS notification and show [MMS] in message thread

module-services/service-desktop/ServiceDesktop.cpp, pure_changelog.md
After connecting to PC with locked phone there were pop-ups
of tethering and unlocking the screen in the wrong order.
=> [MOS-74] Fix wrong tethering popup order

module-cellular/at/Commands.hpp, module-cellular/at/src/ATFactory.cpp, module-services/service-cellular/call/CallMachine.hpp, module-services/service-cellular/call/CellularCall.cpp, module-services/service-cellular/call/api/ModemCallApi.cpp, products/PurePhone/services/db/ServiceDB.cpp, pure_changelog.md
Fixed no calllog entries in DND mode, which were caused
by not starting the call in the DB interface, so no entry was created.
Moreover, small optimization of the DND handling.
=> [MOS-259][MOS-602] Fix no calllog entries in DND mode

module-apps/application-music-player/include/application-music-player/ApplicationMusicPlayer.hpp, module-audio/Audio/AudioCommon.cpp, module-audio/Audio/AudioDevice.hpp, module-audio/Audio/Operation/PlaybackOperation.cpp, module-audio/Audio/Operation/PlaybackOperation.hpp, module-audio/Audio/Operation/RecorderOperation.cpp, module-audio/Audio/Operation/RecorderOperation.hpp, module-audio/Audio/decoder/DecoderWorker.cpp, module-bluetooth/Bluetooth/audio/BluetoothAudioDevice.cpp, module-bluetooth/Bluetooth/audio/BluetoothAudioDevice.hpp, module-bluetooth/Bluetooth/interface/profiles/A2DP/A2DP.cpp, module-bluetooth/Bluetooth/interface/profiles/A2DP/AVRCP.cpp, module-bluetooth/Bluetooth/interface/profiles/A2DP/AVRCP.hpp, module-services/service-audio/ServiceAudio.cpp, module-services/service-audio/include/service-audio/ServiceAudio.hpp, module-services/service-db/include/service-db/Settings.hpp, pure_changelog.md
Fix of the issue that after disconnecting
BT A2DP device during music playback
and reconnecting it without leaving
music player app the sound was not
audible anywhere.
Additionally unified behaviour of music
playback on connection/disconnection
of audio devices.
=> [MOS-92] Fix continuing music playback after BT disconnection

module-sys/SystemManager/GovernorSentinelOperations.cpp, module-sys/SystemManager/tests/unittest_CpuSentinelsGovernor.cpp, pure_changelog.md
If the service is closed the governor removes connected
sentinel. The base iterator refers to the element that is next
in the reversed list. Adding std::next the iterator points to
the correct element.
=> [MOS-676] Fix destroying wrong sentinels

module-services/service-eink/ServiceEink.cpp, module-sys/SystemManager/SystemManagerCommon.cpp, module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp, pure_changelog.md
While restoring data the timer can turn off power of eink to
save the power. To avoid this situation we need to power on
the eink before wiping out the display. The restore procedure
also performs reversing servises list to close. In this case
we do it twice so the order is wrong.
=> [MOS-662][MOS-301] Fix Eink shutdown while restoring data

module-bsp/board/rt1051/bsp/cellular/rt1051_cellular.cpp, pure_changelog.md
Fix "DMA is busy" errors when booting the GSM modem
at the stage of finding the appropriate baudrate.
=> [MOS-91] Fix cellular DMA errors

module-apps/apps-common/locks/handlers/PhoneLockHandler.cpp, module-apps/apps-common/locks/handlers/PhoneLockHandler.hpp, module-apps/apps-common/locks/widgets/Lock.cpp, pure_changelog.md
Fix of the issue that passcode lock time
wasn't updating on 'Wrong passcode' popup,
what led to discrepancy of the time
between lock screen and the popup.
=> [MOS-714] Fix passcode lock time discrepancy

module-bsp/board/rt1051/os/_exit.cpp, module-services/service-evtmgr/EventManager.cpp, module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp, module-sys/SystemManager/SystemManagerCommon.cpp, module-utils/log/CMakeLists.txt, module-utils/log/Logger.cpp, module-utils/log/Logger.hpp, module-utils/log/LoggerBuffer.hpp, module-utils/log/LoggerBufferContainer.hpp, module-utils/log/LoggerWorker.cpp, module-utils/log/LoggerWorker.hpp, module-utils/log/StringCircularBuffer.hpp, module-utils/log/board/rt1051/log_rt1051.cpp, module-utils/log/doc/logging_engine.md, module-utils/log/logdump/include/logdump/logdump.h, module-utils/log/logdump/logdump.cpp, module-utils/log/tests/test_logDumps.cpp, products/BellHybrid/BellHybridMain.cpp, products/PurePhone/PurePhoneMain.cpp, pure_changelog.md
Due to losing bytes the logger has a worker
which is responsible for dumping logs to
the file. The logger also has its own timer
to dump logs every 15 minutes. EventManager
is not responsible for interval dumping logs
now.
=> [MOS-424] Improvement of logger module

module-services/service-db/DBServiceAPI.cpp, module-services/service-db/include/service-db/DBServiceAPI.hpp, module-services/service-db/include/service-db/DBServiceMessage.hpp, module-services/service-db/messages/DBServiceMessage.cpp, module-services/service-desktop/BackupRestore.cpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/endpoints/backup/BackupHelper.cpp, module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp, module-services/service-desktop/endpoints/include/endpoints/backup/BackupHelper.hpp, module-services/service-desktop/endpoints/restore/RestoreHelper.cpp, module-services/service-desktop/include/service-desktop/BackupRestore.hpp, module-services/service-desktop/include/service-desktop/DesktopMessages.hpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, module-vfs/paths/filesystem_paths.cpp, module-vfs/paths/include/purefs/filesystem_paths.hpp, products/PurePhone/services/db/ServiceDB.cpp, products/PurePhone/services/db/include/db/ServiceDB.hpp, products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, source/MessageType.hpp
This mechanism is similar to the current backup implementation but is stripped of irrelevant data that is not required by the MC to perform data synchronization.
Documentation: https://appnroll.atlassian.net/wiki/spaces/CP/pages/1727627287/Backup+Endpoint+API+4#Synchronization
=> [CP-1484] Add new mechanism for data synchronization between MOS and MC

image/assets/lang/Deutsch.json, image/assets/lang/English.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, image/assets/lang/Polski.json, module-apps/application-settings/widgets/SpinBoxOptionSettings.cpp, module-apps/application-settings/widgets/SpinBoxOptionSettings.hpp, module-apps/application-settings/windows/apps/AlarmClockWindow.cpp, module-apps/application-settings/windows/apps/PhoneWindow.cpp, module-apps/application-settings/windows/display-keypad/DisplayLightWindow.cpp, module-apps/apps-common/widgets/SpinBox.cpp, module-apps/apps-common/widgets/SpinBox.hpp, pure_changelog.md
Fix of the issue that with German language
selected manual volume setting bar and
vibration volume setting bar would
disappear when focused.
=> [MOS-666] Fix disappearing setting bars in German

module-services/service-cellular/src/ServiceCellularPriv.cpp, module-utils/phonenumber/PhoneNumber.cpp, module-utils/phonenumber/PhoneNumber.hpp, pure_changelog.md
Get rid of unnecessary separators which can be
problematic for cellular modem. Add modem soft
reset if send SMS message will fail.
=> [MOS-395] Fix issue with inability to send SMS

image/user/data/equalizer/loudspeaker_routing.json, module-audio/Audio/Profiles/ProfilePlaybackHeadphones.hpp, module-audio/Audio/Profiles/ProfilePlaybackLoudspeaker.hpp, module-audio/Audio/Profiles/ProfileRoutingEarspeaker.hpp, module-audio/Audio/Profiles/ProfileRoutingHeadphones.hpp, module-audio/Audio/Profiles/ProfileRoutingLoudspeaker.hpp
Workaround for the issue that updater
places audio config JSON files in
wrong location. This should be
removed after the updater is fixed.
Additionally update of loudspeaker
routing config.
=> [MOS-743] Workaround for audio config paths

module-services/service-cellular/ServiceCellular.cpp, pure_changelog.md
Checking how many parts the modem sent
and then catching an exception in case of an error.
=> [MOS-738] Fix receiving an empty SMS message

module-apps/application-settings/ApplicationSettings.cpp, module-apps/application-settings/include/application-settings/ApplicationSettings.hpp, module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommon.hpp, module-apps/apps-common/popups/lock-popups/SimInfoWindow.cpp, module-apps/apps-common/popups/lock-popups/SimInfoWindow.hpp, module-apps/apps-common/popups/lock-popups/SimLockInputWindow.cpp, pure_changelog.md
Made SIM cards settings windows switching more robust. Is as a prerequisite for MOS-641.
=> [MOS-640] Change windows flow in SIM settings

module-apps/application-settings/ApplicationSettings.cpp
Handling the case when the user during PIN changing or turning the PIN on/off puts the SIM tray out and shortly after back in. In such a case, the Settings application now goes to the 'SIM cards' window
instead of 'PIN settings'.
=> [MOS-753] SIM reinsertion case in SIM Settings

harmony_changelog.md, products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.cpp
Set all settings values each time a value is changed instead of doing it after pressing enter and moving to the next settings page.
=> BH-1581 Prevent meditation settings reset with deep press

harmony_changelog.md, image/assets/lang/Deutsch.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.cpp, tools/generate_update_image.sh
This PR makes possible to update to 1.7.0 from 1.6.0 but not from any of the previous versions. For it to work we have to change MC to force users to first update to 1.6.0 and only after that to update to 1.7.0.
It also includes the following fixes:
https://github.com/mudita/MuditaOS/pull/4104
https://github.com/mudita/MuditaOS/pull/4107
=> [BH-1588] Allow update from 1.6.0 to 1.7.0 and add two fixes

module-apps/apps-common/WindowsPopupFilter.hpp
Make Make gui::popup::Filter's destructor
virtual because it has a virtual method.
Additionally, added a documenting comment.
=> [MOS-769] Make a destructor virtual

module-apps/ModuleApps.md, module-apps/application-settings/ApplicationSettings.cpp, module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/locks/handlers/SimLockHandler.cpp, module-apps/apps-common/locks/handlers/SimLockHandler.hpp, module-apps/apps-common/popups/data/PopupRequestParams.hpp, module-apps/apps-common/popups/lock-popups/SimInfoWindow.cpp, module-apps/apps-common/popups/lock-popups/SimInfoWindow.hpp, module-apps/apps-common/popups/lock-popups/SimLockInputWindow.cpp, products/PurePhone/services/appmgr/ApplicationManager.cpp
Made SimInfo pop-ups completely omitted when
going back to windows.
Fixed the SimUnlockInputRequestParams's
constructor.
Done a bit of refactor in the places of
interest, e.g. naming clarification.
=> [MOS-350] Restored notifications about PIN changes

products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
The deep press doesn't have any effect on the power nap application. 
At the end of the power nap, the deep press change only alarm mode.
=> [BH-1590] Light press ends the Power Nap

.vscode/tasks.json, module-services/service-eink/ServiceEink.cpp, products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp, products/BellHybrid/apps/application-bell-meditation-timer/data/Contract.hpp, products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.cpp, products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/SettingsWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/SettingsWindow.hpp
Main changes:
- When options are changed do not save the data right away.
- Move loading data from onBeforeShow to keep options after popup.
- Fix the back/close logic to avoid saving volume when back is long
pressed.
Additional changes:
- added vscode tasks
- disabled refresh cancel log
=> [BH-1592] Prevent saving meditation settings when going back

harmony_changelog.md, products/BellHybrid/services/evtmgr/CMakeLists.txt, products/BellHybrid/services/evtmgr/EventManager.cpp, products/BellHybrid/services/evtmgr/backlight-handler/BacklightHandler.cpp, products/BellHybrid/services/evtmgr/include/evtmgr/backlight-handler/BacklightHandler.hpp, products/BellHybrid/services/evtmgr/internal/key_sequences/BedsideLampSequence.hpp, products/BellHybrid/services/evtmgr/internal/key_sequences/FrontlightSequence.hpp
To activate the bedside lamp the user needs to hold the frontlight button for approximately 3 seconds. 
The bedside lamp turns off after 10 minutes or after pressing frontlight button.
=> [BH-1574] Add bedside lamp feature

harmony_changelog.md, module-apps/apps-common/widgets/BellBaseLayout.cpp, module-apps/apps-common/widgets/BellBaseLayout.hpp, module-apps/apps-common/widgets/TimeSetFmtSpinner.hpp, module-apps/apps-common/widgets/TimeSetSpinner.hpp, module-gui/gui/core/FontInfo.cpp, module-gui/gui/core/FontInfo.hpp, module-gui/gui/widgets/Style.hpp, products/BellHybrid/CMakeLists.txt, products/BellHybrid/apps/common/include/common/data/BellMainStyle.hpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithAmPm.cpp, products/BellHybrid/assets/assets_proprietary.json
Changes:
- Increase home screen font size to 220 regular (with altered char spacing, line spacing and baseline).
- Decrease the size of colon.
- Increase the size of AM/PM to normal on the home screen with AM/PM.
=> [BH-1557] Change Harmony home screen font to bigger one

image/user/db/settings_v2_002.sql, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/service-cellular/CellularMessage.hpp, module-services/service-cellular/service-cellular/VolteState.hpp, module-services/service-cellular/src/VolteHandler.hpp, module-services/service-db/agents/settings/SystemSettings.hpp, pure_changelog.md
VoLTE enabled/disabled state is now stored in settings database. VoLTE is enabled or disabled to mach setting during modem initialisation.
=> [MOS-792] Added VoLTE setting in db

products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, products/BellHybrid/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
Add reading serial number from emmc partition
Add serial number to body response for deviceInfo endpoint for Harmony
=> [CP-1666] DeviceInfo request should return "SerialNumber" for Harmony

pure_changelog.md
Added a possibility to use a custom GDB for crash analysis.
=> [MOS-823] Update 'misc' submodule reference

module-apps/apps-common/locks/widgets/SimLockBox.cpp, module-apps/apps-common/popups/lock-popups/SimLockInputWindow.cpp, pure_changelog.md
When we returned from the SOS screen to the PIN entry screen, the "confirm" button disappeared.
=> [MOS-660] Fix disappearing button in PIN entering screen

image/assets/lang/Deutsch.json, image/assets/lang/English.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, image/assets/lang/Polski.json, image/assets/lang/Svenska.json, module-apps/application-settings/include/application-settings/ApplicationSettings.hpp, module-apps/application-settings/windows/network/NetworkWindow.cpp, module-services/service-cellular/service-cellular/VolteState.hpp, module-services/service-cellular/src/VolteHandler.hpp
When VoLTE isn't permitted for the current SIM
card's operator, display information only.
Otherwise, display a switch.
After this change, the code still works as previously - VoLTE availability isn't restricted yet and the whole thing, including translations, will be ready when connected together to form the whole MOS-815.
=> [MOS-821] Adjust VoLTE GUI basing on operator

module-services/service-cellular/CMakeLists.txt, module-services/service-cellular/src/ServiceCellularPriv.cpp, module-services/service-cellular/src/ServiceCellularPriv.hpp, module-services/service-cellular/src/volte/ImsiParserInterface.hpp, module-services/service-cellular/src/volte/ImsiParserUS.cpp, module-services/service-cellular/src/volte/ImsiParserUS.hpp, module-services/service-cellular/src/volte/OperatorInfo.hpp, module-services/service-cellular/src/volte/VolteAllowedListInterface.hpp, module-services/service-cellular/src/volte/VolteAllowedUSList.cpp, module-services/service-cellular/src/volte/VolteAllowedUSList.hpp, module-services/service-cellular/src/volte/VolteCapabilityHandler.cpp, module-services/service-cellular/src/volte/VolteCapabilityHandler.hpp, module-services/service-cellular/src/volte/VolteCapabilityHandlerCellular.cpp, module-services/service-cellular/src/volte/VolteCapabilityHandlerCellular.hpp, module-services/service-cellular/src/volte/VolteCapabiltyHandlerCellularInterface.hpp, module-services/service-cellular/tests/CMakeLists.txt, module-services/service-cellular/tests/unittest_volteCapabilityHandler.cpp
Added reading IMSI and parsing US MCC and MNC.
MCC and MNC are filterd if they aret TMobile US.
=> [MOS-816] Add IMSI parsing & filtering

module-apps/application-settings/ApplicationSettings.cpp, module-apps/application-settings/presenter/system/SARInfoWindowPresenter.cpp
Fix of the issue that entering SAR option
in menu resulted in crash of the phone
due to uncaught exception caused by
invalid path provided.
=> [MOS-783] Fix crash on entering SAR menu

module-apps/application-onboarding/ApplicationOnBoarding.cpp, module-apps/apps-common/locks/handlers/SimLockSubject.cpp, pure_changelog.md
It was not possible to finish onboarding properly
when we selected a SIM card without an active PIN
=> [MOS-827] Fix looping on the SIM card selection screen

image/assets/lang/Deutsch.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, image/assets/lang/Svenska.json, module-apps/application-settings/windows/network/NetworkWindow.cpp, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/service-cellular/VolteState.hpp, module-services/service-cellular/src/ServiceCellularPriv.cpp, module-services/service-cellular/src/VolteHandler.hpp, module-services/service-cellular/src/volte/ImsiParserUS.cpp, module-services/service-cellular/src/volte/VolteAllowedUSList.cpp, module-services/service-cellular/src/volte/VolteCapabilityHandler.cpp, module-services/service-cellular/src/volte/VolteCapabilityHandler.hpp, module-services/service-cellular/src/volte/VolteCapabilityHandlerCellular.cpp, module-services/service-cellular/src/volte/VolteCapabilityHandlerCellular.hpp, module-services/service-cellular/src/volte/VolteCapabiltyHandlerCellularInterface.hpp, module-services/service-cellular/tests/unittest_volteCapabilityHandler.cpp, module-services/service-cellular/tests/unittest_volteHandler.cpp, pure_changelog.md
Steering the GUI and the modem according to
whether VoLTE is permitted for the active
SIM card's operator. This is done based on
the SIM card's IMSI string.
Additionally, made logging more consistent.
Co-authored by Kuba Kleczkowski.
=> [MOS-825] VoLTE steering according to IMSI

module-bsp/board/linux/usb_cdc/usb_cdc.cpp
Fix for the linux simulator crashes caused by connecting/disconnecting charger.
The deleting of the USBLinuxReceive task has been added in the USB stack de-initialization process to avoid creating multiple instances during next initializations.
=> [MOS-820] Fix crashes caused by plugging the charger.

doc/os_api/usb_device_descriptor/device_colour.md, doc/os_api/usb_device_descriptor/usb_device_descriptor.md, module-bsp/bsp/usb/usb.hpp, module-services/service-desktop/CMakeLists.txt, module-services/service-desktop/DeviceColour.cpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/WorkerDesktop.cpp, module-services/service-desktop/WorkerDesktop.hpp, module-services/service-desktop/include/service-desktop/DeviceColour.hpp
Getting information about device colour and changing it to number. 
Pass information about device colour to usb_stack. 
Set a bcdDevice with the corresponding value.
=> [CP-1665] Adding an information about device colour to USB descriptor

module-services/service-cellular/call/CellularCall.cpp, module-services/service-cellular/call/api/ModemCallApi.cpp, module-services/service-cellular/call/api/ModemCallApi.hpp
Those were occuring after calls which were preceded by a few VoLTE on/off toggles.
=> MOS-839 Fix crashes occuring after a few VoLTE toggles

module-services/service-eink/ServiceEink.cpp
Always refresh the whole screen if deep refresh is required.
=> [MOS-550] Disable deep partial refresh

module-db/Interface/ContactRecord.cpp, module-db/Interface/ContactRecord.hpp, module-db/tests/ContactsRecord_tests.cpp, pure_changelog.md
Adding or removing code country from contact's number creates a new number record. Old number, which was connected witch contact previously, is removed from the numbers table to avoid miss match numbers. Changing country code only creates new number records, without removing old ones. Old ones are temporary number from now.
=> [MOS-737] Fix for adding a country code prefix to existing contact

module-cellular/modem/mux/CellularMuxFrame.h
Added an additional condition that checks the size of the hacked frame to avoid processing an incorrect sized frame.
=> [MOS-741] Fix crashes during the cellular frame processing

module-apps/apps-common/widgets/TimeSetSpinner.hpp, products/BellHybrid/CMakeLists.txt, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.cpp, products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVerticalWithDate.hpp, products/BellHybrid/apps/common/include/common/widgets/BellBattery.hpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVerticalWithDate.cpp, products/BellHybrid/apps/common/src/widgets/BellBattery.cpp, products/BellHybrid/apps/common/src/widgets/LayoutVertical.cpp
Decrease space between colon and digits in TimeSetSpinner for smaller fonts.
Decrease main vertical time width.
Use battery icon with smaller width.
Decrease space between battery icon and percentage.
=> [BH-1612] Show battery 100% on 24h vert. face with date

harmony_changelog.md, module-services/service-evtmgr/screen-light-control/ScreenLightControlParameters.hpp, module-services/service-evtmgr/service-evtmgr/ScreenLightControlMessage.hpp, products/BellHybrid/alarms/src/actions/FrontlightAction.cpp, products/BellHybrid/apps/application-bell-settings/models/FrontlightModel.cpp, products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsModel.cpp, products/BellHybrid/services/evtmgr/EventManager.cpp, products/BellHybrid/services/evtmgr/backlight-handler/BacklightHandler.cpp, products/BellHybrid/services/evtmgr/include/evtmgr/backlight-handler/BacklightHandler.hpp
Now the bedside lamp has lower priority
than the pre-wake up and main alarm. It means
that the front light will be changed according
to alarm settings.
Fix front light brightness calculation for
pre-wake up and main alarm.
=> [BH-1574][BH-1614] Fix the bedside lamp and brightness in the alarm 

module-apps/application-alarm-clock/widgets/AlarmRRuleOptionsItem.cpp
The additional navigation bar restore has been added to have proper state after exit from custom repeat window. No object did it before.
=> [MOS-558] Fix wrong navigation bar state after exit from custom repeat window.

module-apps/application-onboarding/ApplicationOnBoarding.cpp, pure_changelog.md
When the user locked the screen during onboarding, the lock screen appeared but without the current time and date.
=> [MOS-831] Fix screen lock during onboarding

products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
If there is no record in the database using
the default brightness.
=> [BH-1619] Use default brightness

harmony_changelog.md, pure_changelog.md
=> [CP-1413] Windows displays wrong name of connected device

module-services/service-cellular/CellularServiceAPI.cpp, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/call/CellularCall.cpp, module-services/service-cellular/call/api/CallTimer.hpp, module-services/service-cellular/service-cellular/CellularServiceAPI.hpp, module-services/service-cellular/service-cellular/ServiceCellular.hpp, module-services/service-cellular/src/ModemResetHandler.cpp, module-services/service-cellular/src/ModemResetHandler.hpp, module-services/service-cellular/src/ServiceCellularPriv.cpp, module-services/service-cellular/src/volte/VolteCapabilityHandler.cpp, pure_changelog.md
Fixed the problem that the call state polling
timer wasn't terminated in some cases, so the
modem command AT+CLCC had still been issued
until e.g. another call was made. In such cases,
this lead to inability for the modem to go to
a power-down state due to constant activity and
thus lead to battery power waste.
Additionally, fixed a hidden bug that TimerRing
hadn't got a virtual destructor.
Also thrown out some dead code.
=> [MOS-810] Fixed call state timer termination

module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, module-vfs/paths/filesystem_paths.cpp, products/BellHybrid/BellHybridMain.cpp, products/BellHybrid/paths/Paths.cpp, products/PurePhone/PurePhoneMain.cpp
Fixed MTP root paths for both Harmony and
Pure due to the MTP implementation
not supporting hierarchical directories.
=> [MOS-807] Fix MTP root path

image/assets/lang/English.json, products/BellHybrid/alarms/src/actions/FrontlightAction.cpp, products/BellHybrid/alarms/src/actions/FrontlightAction.hpp, products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpListItemProvider.cpp
Due to changed UI the user couldn't turn off
chime and turn on the front light. Now the user
is able to do it.
=> [BH-1621] Fix UI design regression in pre-wake up

products/PurePhone/services/appmgr/ApplicationManager.cpp
Auto-lock was not disabled properly when preventing was on
Changelog entry not added on purpose - user won't see this change (at least shouldn't ;) )
=> [MOS-847] Fix auto-lock preventing

cmake/modules/AddPackage.cmake, products/BellHybrid/BinaryAssetsVersions.cmake, products/BellHybrid/CMakeLists.txt, products/PurePhone/BinaryAssetsVersions.cmake
Change binary assets versions for both
products, fixed missing dependencies
in Bell's CMake, added 'Bell' target
that automatically builds the
image.
=> [MOS-000] Bump binaries and add Bell target

image/assets/lang/Deutsch.json, image/assets/lang/Francais.json, pure_changelog.md
During onboarding, the text displayed in French and German was truncated.
=> [MOS-160] Fix broken text on SIM selection screen

image/assets/lang/Espanol.json, pure_changelog.md
On the PIN entry screen,
the text displayed in Spanish was truncated.
=> [MOS-159] Fix broken text on the PIN input screen

module-services/service-appmgr/model/ApplicationManagerCommon.cpp, module-sys/SystemManager/SystemManagerCommon.cpp, module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
Fix of the issue that factory reset screen
informing user of need to manually turn
on the phone to continue the process
was appearing also when restarting to
backup or restore.
=> [MOS-851] Remove factory reset screen from backup and restore

module-apps/application-onboarding/ApplicationOnBoarding.cpp
After inserting the SIM tray at the onboarding stage before selecting the slot - it is not possible to select the slot and activate the desired SIM card if it does not have a PIN enabled.
=> [MOS-836] Fix for selecting SIM during onboarding

products/PurePhone/services/appmgr/ApplicationManager.cpp
Fix of the issue that in some cases phone
wouldn't lock automatically after given
timeout. This is not a proper fix,
rather a workaround, the whole autolock
mechanism should get refactored to
support testing via harness.
=> [MOS-852] Fix autolock not working in UDM version

module-cellular/modem/mux/CellularMux.cpp, module-cellular/modem/mux/CellularMux.h, module-services/service-cellular/RequestFactory.cpp, module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/tests/unittest_request_factory.cpp
User is now able to make emergency call with no sim card inserted. RF functionality in modem is still disabled until sim card is selected by user.
=> [MOS-813] Emergency calling fixed

module-apps/application-notes/windows/NotesOptions.cpp, pure_changelog.md
Check clipboard content before showing
paste option.
=> [MOS-201] Fix notes paste option

module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp, module-vfs/paths/filesystem_paths.cpp, module-vfs/paths/include/purefs/filesystem_paths.hpp, products/BellHybrid/BellHybridMain.cpp, products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, products/PurePhone/PurePhoneMain.cpp, products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
Added MTP path for products to enable MC to use it instead of hardcoded paths
=> [MOS-856] Add MTP path to DeviceInfo endpoint

module-apps/application-settings/windows/system/DateAndTimeMainWindow.cpp
Fixed missing timezone window, which should be displayed after Automatic date and time setting is set to disabled. MOS-181 is also fixed by this commit.
=> [MOS-373] Fixed missing timezone window

harmony_changelog.md, products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsListItemProvider.cpp, products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpListItemProvider.cpp
If the user changes the front light intensity in
pre-wake up or main alarm and then going back
the front light value and intensity are the same.
=> [BH-1618] Fix the wrong front light on the back action

harmony_changelog.md, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
The deep press doesn't deactivate the pause
in a timer or loop mode.
=> [BH-1620] Fix pause deactivation by a deep press

module-db/tests/ContactsRecord_tests.cpp, scripts/lua/restore.lua, scripts/lua/share/consts.lua
Added checking if requested to restore backup
from pre-UDM version and setting db versions
to zero in such case, as version info file
(called backup.json in legacy backups) doesn't
contain info about versions.
=> [MOS-855] Fix restore from legacy backup

module-services/service-fileindexer/CMakeLists.txt, module-services/service-fileindexer/StartupIndexer.cpp
When startup indexer for FileIndexer starts, it checks for lock file. If it's not present, it starts the indexing.
Due to changes in DB initialization we have to purge the DB before starting the init scan because of potential restore content
=> [MOS-853] Purge multimedia database when initializing indexer

module-audio/tags_fetcher/CMakeLists.txt, module-audio/tags_fetcher/TagsFetcher.cpp, module-audio/tags_fetcher/TagsFetcher.hpp, pure_changelog.md
Bumped taglib version to latest master
Added sanity check for version field in tag parser in taglib so in case of damaged/invalid tag it returns no tag at all
It was caused by zipped mp3 files and renamed to mp3 again
Changes in taglib:
https://github.com/mudita/taglib/commit/f700e74025f56de2d35ef0c2a460f0ee2abaa034
=> [MOS-765] Fixed crash on invalid ID3 tag

module-gui/gui/widgets/text/Text.cpp, module-gui/gui/widgets/text/Text.hpp, pure_changelog.md
Now backspace (held # button) removes everything from the beginning up to the cursor
Coauthored with @Lefucjusz
=> [MOS-757] Fixed backspace behavior

module-gui/gui/core/DrawCommand.cpp, pure_changelog.md
Fix of the issue that email, first name and last
name fields were not able to display strings that
started with 'j'. Nothing was shown in such case.
=> [MOS-828] Fix 'j' glyph issue in Contacts app

module-gui/gui/widgets/text/Text.cpp
Fix of the issue that after partially deleting
the text, the cursor sometimes was positioned
somewhere in the middle of the remaining text,
not at the beginning where it should.
=> [MOS-757] Fix wrong cursor final position after deleting

products/BellHybrid/services/audio/ServiceAudio.cpp
Increase stack size because internally drflac_open() uses cache which by default has 4kB.
=> [BH-1566] Fix flac playback

module-services/service-cellular/src/ServiceCellularPriv.cpp, products/PurePhone/services/appmgr/ApplicationManager.cpp, pure_changelog.md
Also, done a minor code cleanup.
=> [MOS-840] Make VoLTE switch unavailable after SIM card is taken out

module-apps/application-call/ApplicationCall.cpp, module-services/service-db/DBServiceAPI.cpp, module-services/service-db/include/service-db/DBServiceAPI.hpp
Emergency contact is now recognized when typed mannualy.
=> [MOS-390] Fixed emergency number recognition

image/assets/lang/Deutsch.json, image/assets/lang/English.json, image/assets/lang/Espanol.json, image/assets/lang/Francais.json, image/assets/lang/Polski.json, image/assets/lang/Svenska.json, module-apps/application-messages/widgets/SMSInputWidget.cpp, pure_changelog.md
Fix of the issue that pasting previously copied
text in new message field on thread screen
resulted in text shown in gray and invisibility
of each subsequently entered character.
Further analysis of this issue shown two
additional bugs in this place in code,
as a result a decision to completely
remove 'Reply' prompt text has been
made. Extended description of these
issues can be found in comment under
MOS-27 Jira ticket.
[MOS-27]: https://appnroll.atlassian.net/browse/MOS-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOS-27] Fix invisible message text after pasting

module-apps/application-alarm-clock/widgets/AlarmRRuleOptionsItem.cpp, pure_changelog.md
The additional navigation bar restore has been added to have proper state after exit from custom repeat window. The restoration of the repeat option spinner labels has been added after uncheck of all options.
=> [MOS-558] Fix wrong nav. bar state after exit from custom repeat window

module-apps/application-messages/windows/NewMessage.cpp, module-apps/apps-common/ApplicationCommonPopupBlueprints.cpp, module-apps/apps-common/locks/input/PhoneLockedKeysWhitelist.cpp, pure_changelog.md
Fix of the issue that moving mode slider on new message window caused the content of the message to be deleted.
=> [MOS-495] Fix deleting message content when changing phone mode

module-apps/application-phonebook/include/application-phonebook/ApplicationPhonebook.hpp, module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.cpp, module-apps/application-phonebook/windows/PhonebookNewContact.cpp, pure_changelog.md
Fix of the issue that editing existing contact's
number by adding country prefix resulted in
PureOS crash due to application stack overflow.
Additionally moved misplaced changelog entry.
=> [MOS-863] Fix phonebook crash when adding country prefix

module-apps/application-call/windows/CallWindow.cpp, module-apps/application-call/windows/NumberWindow.cpp, module-apps/apps-common/windows/AppWindow.cpp, module-apps/apps-common/windows/AppWindow.hpp, pure_changelog.md
Fixed unwanted Mudita Center passcode prompt after long press '#' while dialing
=> [CP-1575] Fix unwanted Center passcode prompt

board/linux/CMakeLists.txt, board/linux/crashdump-serial-number/CMakeLists.txt, board/linux/crashdump-serial-number/crashdump_serial_number.cpp, board/linux/crashdump-serial-number/include/crashdump-serial-number/crashdump_serial_number.hpp, board/rt1051/CMakeLists.txt, board/rt1051/crashdump-serial-number/CMakeLists.txt, board/rt1051/crashdump-serial-number/crashdump_serial_number.cpp, board/rt1051/crashdump-serial-number/include/crashdump-serial-number/crashdump_serial_number.hpp, board/rt1051/crashdump/crashcatcher_impl.cpp, board/rt1051/crashdump/crashdumpwriter_vfs.cpp, board/rt1051/crashdump/crashdumpwriter_vfs.hpp, harmony_changelog.md, module-services/service-db/agents/settings/FactorySettings.cpp, module-services/service-desktop/WorkerDesktop.cpp, products/BellHybrid/CMakeLists.txt, products/BellHybrid/serial-number-reader/CMakeLists.txt, products/BellHybrid/serial-number-reader/SerialNumberReader.cpp, products/BellHybrid/serial-number-reader/include/serial-number-reader/SerialNumberReader.hpp, products/BellHybrid/services/db/CMakeLists.txt, products/BellHybrid/services/db/ServiceDB.cpp, products/BellHybrid/services/desktop/endpoints/CMakeLists.txt, products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, products/PurePhone/services/db/CMakeLists.txt, products/PurePhone/services/db/ServiceDB.cpp, pure_changelog.md
Add the serial number and generation timestamp to crashdump filename.
=> [CP-1512] Add information allowing indetification to crashdump file

module-apps/apps-common/locks/handlers/SimLockHandler.cpp, pure_changelog.md
Fixed with adding a missing internal state reset on SIM connection failure.
=> [MOS-838] Unable to unlock SIM card (corner case)

module-services/service-time/AlarmMessageHandler.cpp, pure_changelog.md
Fixed by adding additional alarm's event cache update after assigning the callback.
=> [MOS-606] Fix inactive alarms after the timezone change and reboot.

module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, products/PurePhone/PurePhoneMain.cpp, pure_changelog.md
Fix the issue when the USB cable connected to the device during boot up and Center requested a passcode before the device was fully up. What caused a 'Wrong passcode' message after typing a passcode via Center.
=> [CP-1579] Fix correct password inserted during Pure boot is not accepted

module-apps/application-call/windows/CallWindow.cpp, module-audio/Audio/Operation/Operation.cpp, module-audio/Audio/Operation/Operation.hpp, module-audio/Audio/Operation/RouterOperation.cpp, module-audio/Audio/Operation/RouterOperation.hpp, module-bluetooth/Bluetooth/audio/BluetoothAudioDevice.cpp, module-bluetooth/Bluetooth/interface/profiles/A2DP/A2DP.cpp, module-bluetooth/Bluetooth/interface/profiles/A2DP/AVRCP.cpp, module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp, pure_changelog.md
Fix of the issue that connecting or
disconnecting BT device while call
was in progress resulted in no sound
being heard anywhere due to audio
routing being stopped when HFP device
disconnected.
Additionally minor code cleanup and fixed 
misplaced changelog entry.
=> [MOS-814] Fix no sound after BT device connection during call

module-apps/apps-common/popups/presenter/AlarmPresenter.cpp
According to the requirements the alarm after.
30 minutes of playing will be stopped
instead of snoozed.
=> [MOS-606] Fix the Pure's alarm plays indefinitely

module-audio/tags_fetcher/TagsFetcher.cpp, module-audio/tags_fetcher/TagsFetcher.hpp, pure_changelog.md
Fix of the issue that whole file path was
displayed instead of just filename in music 
player for invalid audio file for which Taglib 
failed to obtain tags.
=> [MOS-767] Fix full path displayed for invalid audio file

board/rt1051/crashdump/crashcatcher_impl.cpp, board/rt1051/crashdump/crashdumpwriter_vfs.cpp, board/rt1051/crashdump/crashdumpwriter_vfs.hpp, module-utils/rotator/include/rotator/Rotator.hpp, module-utils/rotator/tests/test_Rotator.cpp
Adding indexing to crashdumps to ensure resistance to the device date retraction.
When the max crashdump count reaches the file with the highest index number will be removed.
=> [CP-1512] Add crashdumps indexing

module-services/service-evtmgr/EventManager.cpp, module-services/service-evtmgr/WorkerEventCommon.cpp, module-services/service-evtmgr/battery/BatteryController.cpp, module-services/service-evtmgr/battery/BatteryController.hpp, module-services/service-evtmgr/battery/BatteryState.cpp, module-services/service-evtmgr/battery/BatteryState.hpp, module-services/service-evtmgr/service-evtmgr/BatteryMessages.hpp, module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp, module-services/service-evtmgr/service-evtmgr/WorkerEventCommon.hpp, module-services/service-evtmgr/service-evtmgr/include/EventManagerParams.hpp, module-services/service-time/AlarmMessageHandler.cpp, module-services/service-time/AlarmMessageHandler.hpp, module-services/service-time/AlarmOperations.cpp, module-services/service-time/AlarmOperations.hpp, module-services/service-time/AlarmServiceAPI.cpp, module-services/service-time/ServiceTime.cpp, module-services/service-time/include/service-time/AlarmMessage.hpp, module-services/service-time/include/service-time/AlarmServiceAPI.hpp, module-sys/SystemManager/SystemManagerCommon.cpp, module-utils/utility/Units.hpp, products/BellHybrid/services/evtmgr/CMakeLists.txt, products/BellHybrid/services/evtmgr/EventManager.cpp, products/BellHybrid/services/evtmgr/include/evtmgr/battery/Thresholds.hpp, products/PurePhone/services/evtmgr/CMakeLists.txt, products/PurePhone/services/evtmgr/include/evtmgr/EventManager.hpp, products/PurePhone/services/evtmgr/include/evtmgr/battery/Thresholds.hpp, products/PurePhone/services/time/AlarmOperations.cpp, products/PurePhone/services/time/include/time/AlarmOperations.hpp, products/PurePhone/sys/SystemManager.cpp, pure_changelog.md
When we had a critical battery level and the alarm clock rang, it was impossible to turn it off.
=> [MOS-275] Fix alarm rings on the low battery screen

module-audio/Audio/StreamFactory.cpp, module-audio/Audio/decoder/Decoder.cpp, module-audio/Audio/decoder/Decoder.hpp, module-audio/Audio/decoder/DecoderWorker.cpp, module-audio/board/rt1051/puretx/PureTxAudioCodec.cpp, module-bsp/board/rt1051/os/include/FreeRTOSConfig.h, module-services/service-audio/ServiceAudio.cpp, module-sys/Service/Worker.cpp, pure_changelog.md
Fix of the issue that caused system crash when
trying to play 96kHz FLAC file with USB cable
connected. The reason of the issue was the lack
of FreeRTOS heap space left, what caused
pvPortMalloc() to fail when allocating
memory for stream buffer.
Additionally minor code cleanup.
=> [MOS-882] Fix FLAC file playback with USB cable connected

module-apps/application-messages/ApplicationMessages.cpp, pure_changelog.md
In order to delete notification of unread messages from the thread, which was deleted.
After successful deletion of the thread
the unread messages counter is updated
as when the thread is opened.
=> [MOS-651] Update the unread message counter after a thread deletion

pure_changelog.md
* It's now possible to rename files using MTP
* Fixed issue with fs notification being sent from MTP before file transfer is complete. This resulted in audio tracks appearing on the MusicPlayer list while still being transferred.
=> [MOS-544] MTP integration issues

module-apps/application-messages/ApplicationMessages.cpp, module-apps/application-messages/include/application-messages/ApplicationMessages.hpp, module-apps/application-messages/windows/SMSThreadViewWindow.cpp, module-apps/application-messages/windows/ThreadWindowOptions.cpp, pure_changelog.md
Conversation marked in OPTIONS as read did not disappear from notifications about SMS threads on the main screen.
=> [MOS-340] Fix notifications of unread SMS threads on the home screen

module-services/service-cellular/ServiceCellular.cpp
Added checking if a SIM card is present in the active slot during ApplicationSettings initialization so that in case there's no SIM, the VoLTE switch is made anavailable to toggle.
=> [MOS-840] VoLTE switch unavailability fix

module-apps/application-messages/models/SMSThreadModel.cpp, module-apps/application-messages/models/SMSThreadModel.hpp, pure_changelog.md
Now thread will be marked as read when new message arrives when the thread is opened
=> [MOS-33] Mark thread as read when new message arrives

module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
Fix of the issue that previous commit
didn't resolve - for some Bluetooth
devices voice still wasn't heard
after disconnection and reconnection
during a call.
=> [MOS-814] Fix no sound after BT reconnection

module-audio/Audio/Stream.hpp, module-audio/Audio/StreamFactory.cpp, module-audio/Audio/StreamFactory.hpp, module-audio/Audio/test/unittest_stream.cpp
Fix of the heap fragmentation issue that caused
phone crash when trying to play music files
while connecting USB cable in a certain order.
Audio stream buffering length was slightly
reduced, so that smaller contiguous block of
heap is required to store audio buffer.
=> [MOS-882] Fix heap fragmentation issue during playback

module-apps/application-alarm-clock/widgets/AlarmRRuleOptionsItem.cpp
Fixed disappearing edit label in alarm add window
when custom interval has been selected
=> [MOS-558] Fix disappearing edit label in alarms

module-services/service-cellular/call/CallMachine.hpp, pure_changelog.md
Fixed the case when a dot appeared around the Calls app tile notifying about an answered call.
=> [MOS-870] Fix undesirable notification on call

module-os/memory/usermem.c
"pure heapstats" command was returning incorrect
system heap data
=> [MOS-75] Fix incorrect data in pure heapstats tool

module-apps/apps-common/popups/HomeModesWindow.cpp, pure_changelog.md
=> [MOS-48] Shorten phone modes pop-up duration

module-apps/application-messages/widgets/SMSOutputWidget.cpp, pure_changelog.md
When the width of the box with the currently read SMS changed, the label with the time of receiving the message disappeared.
=> [MOS-722] Fix time disappearing in SMS thread

module-apps/application-desktop/windows/DesktopMainWindow.cpp, module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/locks/windows/LockInputWindow.cpp, module-apps/apps-common/popups/lock-popups/PhoneLockedInfoWindow.cpp, module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp, module-apps/apps-common/popups/lock-popups/SimLockInputWindow.cpp, module-apps/apps-common/popups/lock-popups/SimNotReadyWindow.cpp, pure_changelog.md
Now those parameters are always on the statusbar
=> [MOS-59] Always display network technology and signal strength

module-apps/application-calllog/CalllogModel.cpp, module-apps/application-calllog/widgets/CalllogItem.cpp, module-apps/application-calllog/widgets/CalllogItem.hpp, module-gui/gui/widgets/ListView.cpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, pure_changelog.md
Fix of the issue that scrollbar in
call log didn't represent the actual
page being shown correctly.
=> [MOS-18] Fix calllog scrollbar

module-apps/application-settings/models/network/SimContactsRepository.cpp, module-apps/application-settings/models/network/SimContactsRepository.hpp, module-apps/apps-common/AsyncTask.cpp, module-db/Interface/ContactRecord.cpp, module-db/Interface/ContactRecord.hpp, module-db/queries/phonebook/QueryMergeContactsList.cpp, module-db/queries/phonebook/QueryMergeContactsList.hpp, module-db/tests/ContactsRecord_tests.cpp, pure_changelog.md
Fix for imported contacts from SIM don't show up in Mudita Center. Added functionality to send notifications after all imported contacts are added to the database.
=> [CP-1210] Contacts imported from SIM don't show up in Mudita Center

products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp, pure_changelog.md
Fix for incorrect signal strength displayed in Center when network status is NotRegistered.
=> [CP-1419] Signal range in Pure status without SIM card inserted

harmony_changelog.md, products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
Add missing timer start in entry event handler
=> [BH-1582] Fix alarm edit inactivity handling

module-apps/application-phonebook/windows/PhonebookContactOptions.cpp, pure_changelog.md
Fix for displaying wrong screen after contact removal
=> [MOS-68] Deleting a contact flow finishes with a wrong screen

module-gui/gui/widgets/NavBar.cpp, pure_changelog.md
Fix of the issue that navbar fonts for the
left and right function buttons were bold,
what was inconsistent with the design.
=> [MOS-361] Fix improper fonts in navbar

module-db/Interface/ContactRecord.cpp, module-db/Interface/ContactRecord.hpp, module-db/Tables/ContactsTable.cpp, module-db/tests/ContactsRecord_tests.cpp, module-services/service-db/DBServiceAPI.cpp, pure_changelog.md
Fix for scenario when contact with some number with/without country code was deleted, and new contact with same number but without/with country code is added and then new contact have same prefix as deleted one. Now new contact will have number exacly like provided.
=> [MOS-864] Fix for country code in new contact based on deleted one

module-apps/apps-common/popups/AlarmPopup.cpp, module-apps/apps-common/popups/AlarmPopup.hpp, module-apps/apps-common/popups/presenter/AlarmPresenter.hpp, pure_changelog.md
When we were currently in the snoozed alarms screen and a new alarm rang, the data was displayed incorrectly.
=> [MOS-52] Fix the data displayed on snoozed alarms screen

module-apps/application-call/windows/CallWindow.cpp, pure_changelog.md
After quick dobule "END CALL" selection, the window for adding a contact is displayed for a while.
=> [MOS-60] Fix displaying an incorrect window after ending a call

module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.cpp, module-apps/apps-common/windows/AppWindow.cpp, module-gui/gui/widgets/text/Text.cpp, module-gui/gui/widgets/text/modes/InputMode.cpp, module-gui/gui/widgets/text/modes/InputMode.hpp, pure_changelog.md
Fix of the improper asterisk button behavior
in new contact window - pressing the button
to change an input mode resulted in
'OPTIONS' label being displayed for the
left function button in navbar when the
asterisk button was held.
Additionally, as usual, minor code cleanup.
=> [MOS-172] Fix asterisk button behavior in contacts

module-db/Interface/ContactRecord.cpp, module-db/Interface/ContactRecord.hpp, pure_changelog.md
Fix for importing and removing contacts from SIM card causes issue that imported contacts didn't have a name and could by multiplied.
=> [MOS-884] Importing contacts from SIM card more than once

module-utils/time/test/unittest_time.cpp, module-utils/time/time/time_conversion.cpp, pure_changelog.md
Fix for displaying an additional 0 at the begging of the clock. It affects the clock in the status bar and messages and calls time.
=> [MOS-192] Time should not include 0 at the beginning

module-apps/application-desktop/windows/MmiPullWindow.cpp, pure_changelog.md
Previously only the mode restricted to digits was available.
=> [MOS-35] Add more input modes for USSD reply

module-apps/application-special-input/widgets/SpecialInputTableWidget.cpp, module-apps/application-special-input/widgets/SpecialInputTableWidget.hpp, module-apps/apps-common/ApplicationCommon.cpp, module-services/service-appmgr/Controller.cpp, pure_changelog.md
Fix of the issue of screen ghosting after
emoji selection, visible particularly well
in messages app - changed fast refresh
to deep one on returning from emoji selection
screen to the previous application.
Additionally minor code cleanup.
=> [MOS-204] Fix screen ghosting after emoji selection

module-apps/apps-common/widgets/TimeSetFmtSpinner.cpp, module-apps/apps-common/widgets/TimeSetFmtSpinner.hpp, module-gui/gui/widgets/Item.cpp, products/BellHybrid/apps/common/include/common/widgets/BellStatusClock.hpp, products/BellHybrid/apps/common/src/widgets/BellStatusClock.cpp, products/BellHybrid/apps/common/src/widgets/ListItems.cpp
Change the resizing logic of the children of TimeSetFmtSpinner.
Remove arguments of TimeSetFmtSpinner and BellStatusClock ctors.
=> [BH-1609] Fix resizing of format in TimeSetFmtSpinner

module-apps/application-call/ApplicationCall.cpp, module-apps/application-call/model/CallModel.hpp, module-apps/application-call/presenter/CallPresenter.cpp, module-services/service-cellular/call/CallMachine.hpp, module-services/service-cellular/call/api/CallMulticast.cpp, module-services/service-cellular/call/api/CallMulticast.hpp, module-services/service-cellular/call/tests/test-CallMachine.cpp, module-services/service-cellular/service-cellular/CellularMessage.hpp, pure_changelog.md
Fix of the issue that missed call triggered
view that shown 'call ended' text.
=> [MOS-29] Fix invalid screen after missed call

module-apps/application-messages/widgets/SMSOutputWidget.cpp
Fix of the issue that entering messages
and trying to send SMS without SIM card
inserted (and in a few another cases
when sending resulted in failure)
phone would crash.
=> [MOS-902] Fix crash when entering message thread

image/system_a/data/lang/Deutsch.json, image/system_a/data/lang/English.json, image/system_a/data/lang/Espanol.json, image/system_a/data/lang/Francais.json, image/system_a/data/lang/Polski.json, image/system_a/data/lang/Svenska.json, module-apps/application-messages/models/SMSTemplateModel.cpp, module-apps/application-messages/windows/SMSTemplatesWindow.cpp, module-apps/application-messages/windows/SMSTemplatesWindow.hpp, pure_changelog.md
Now there's information displayed that there are no templates and in order to add some, the user needs to use Mudita Center. Also, given no templates, the screen doesn't show the 'USE' button.
=> [MOS-663] SMS templates: no empty state can be allowed

module-audio/tags_fetcher/TagsFetcher.cpp
Fixed problem with fs notification events
being sent one time too many.
=> [MOS-205] Unneeded fs notify events

module-apps/application-phonebook/windows/PhonebookNewContact.cpp, pure_changelog.md
From now on, after cancelling or confirming a new contact creation initiated from the call log, the phone goes back to correct windows.
=> [MOS-357] Broken navigation around contact adding

module-services/service-cellular/ServiceCellular.cpp, module-services/service-cellular/src/SMSSendHandler.cpp, module-services/service-cellular/src/SMSSendHandler.hpp, module-services/service-cellular/src/ServiceCellularPriv.cpp, module-services/service-cellular/tests/unittest_smssendhandler.cpp, pure_changelog.md
Fixed misleading SMS flow after sending error.
When modem was rebooting attempt to send SMS was causing Rejected by no sim popup, which was misleading for user.
=> [MOS-879] Fixed misleding SMS flow

module-apps/application-messages/ApplicationMessages.cpp, module-apps/application-messages/include/application-messages/ApplicationMessages.hpp, pure_changelog.md
After clicking the message icon on the "contact details" screen,
the user will be redirected to either the message thread with that person
or to the new message screen (only if thread does not exist yet
or has been deleted in the past)
=> [MOS-38] Fix window redirection when clicking on the SMS icon

module-apps/application-alarm-clock/widgets/AlarmMusicOptionsItem.cpp, module-apps/application-settings/models/apps/SoundsModel.cpp, module-apps/application-settings/windows/apps/SoundSelectWindow.cpp, pure_changelog.md
Change of the behavior of alarm sounds
and ringtones preview, so that it matches
the design.
Additionally fixed lack of ringtones list
looping.
=> [MOS-28] Change alarm sounds and ringtones preview behavior

module-apps/application-settings/models/apps/SoundsModel.cpp, module-apps/application-settings/windows/apps/SoundSelectWindow.cpp
Fix of the missing tick mark that should appear
on the currently selected ringtone, but didn't.
=> [MOS-906] Fix missing tick mark in ringtones list

module-services/service-evtmgr/EventManager.cpp, module-services/service-evtmgr/backlight-handler/BacklightHandlerCommon.hpp, products/PurePhone/services/evtmgr/EventManager.cpp, products/PurePhone/services/evtmgr/backlight-handler/BacklightHandler.cpp, products/PurePhone/services/evtmgr/include/evtmgr/BacklightHandler.hpp, products/PurePhone/services/evtmgr/screen-light-control/ScreenLightControl.cpp, pure_changelog.md
Fix of the issue that turning off the phone and
clicking any keyboard button resulted in
crash and reboot.
=> [MOS-905] Fix crash on power off with USB cable connected

module-bsp/board/rt1051/puretx/board.cpp, pure_changelog.md
Fix of the issue that resulted in long
turn off time of the phone, which was
caused by unfortunate coincidence
of functions names - as a result the
one from the included header file was
called instead of the one from the
anonymous namespace inside the file,
what resulted in not cutting off
board power until the watchdog
triggered.
=> [MOS-176] Fix long turn off time

module-apps/application-messages/models/SMSTemplateModel.cpp, module-apps/application-messages/windows/SMSTemplatesWindow.cpp
Fixed a regression that the SMS template list showed always the state representing no templates defined, regardless if there were any in the database.
There's a minor side effect that querying the database and refreshing the window is doubled which can be seen in debugging, but it's unnoticeable in usage.
- Has changelog entry added <--- _done previously alongside the original change which wasn't released publicly yet, so not needed for this regression fix_
=> [MOS-663] Regression fix

module-apps/application-phonebook/windows/PhonebookNewContact.cpp, pure_changelog.md
Reverted due to a regression spotted that is de facto worse than the original problem. Needs reworking
=> Revert "[MOS-357] Broken navigation around contact adding"

module-apps/application-call/ApplicationCall.cpp, module-apps/application-call/include/application-call/ApplicationCall.hpp, module-apps/application-call/model/CallModel.cpp, module-apps/application-call/presenter/CallPresenter.cpp, module-apps/application-call/presenter/CallPresenter.hpp, module-apps/application-call/test/mock/CallPresenterMocks.hpp, module-apps/application-call/windows/CallWindow.cpp, module-apps/application-call/windows/CallWindow.hpp, module-audio/Audio/Audio.hpp, module-audio/Audio/AudioCommon.hpp, module-audio/Audio/Operation/PlaybackOperation.cpp, module-audio/Audio/Operation/RecorderOperation.cpp, module-audio/Audio/Operation/RouterOperation.cpp, module-audio/Audio/test/unittest_audio.cpp, module-bluetooth/Bluetooth/interface/profiles/A2DP/A2DP.cpp, module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp, module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.cpp, module-services/service-audio/AudioServiceAPI.cpp, module-services/service-audio/ServiceAudio.cpp, module-services/service-audio/include/service-audio/AudioMessage.hpp, module-services/service-audio/include/service-audio/AudioServiceAPI.hpp, module-services/service-audio/include/service-audio/ServiceAudio.hpp, module-services/service-evtmgr/AppSettingsNotify.cpp, pure_changelog.md
Fix for the loudspeaker becomes active again when a headset is unplugged if it was on while the headset was connected to the phone.
=> [MOS-871] Loudspeaker icon is not updated when audio routing has changed

module-audio/Audio/decoder/decoderCommon.hpp, module-audio/Audio/decoder/decoderFLAC.cpp, module-audio/Audio/decoder/decoderMP3.cpp, pure_changelog.md
Since a currently played file is deleted, the player goes to the next file from the list. A special case: if the deleted file is the last one, the playback stops (and can be resumed by the user).
=> [MOS-878] Don't break audio playback on file deletion

module-apps/application-phonebook/windows/PhonebookNewContact.cpp, pure_changelog.md
Reverts only the direct cause of a regression spotted and the changelog item.
=> [MOS-357] Reverting regression

module-apps/application-call/model/CallModel.cpp, module-apps/application-messages/windows/SMSTemplatesWindow.cpp, pure_changelog.md
Fix of the issue that rejecting call with template 
resulted in displaying 'Call ended' screen, while
'Call rejected' screen should be displayed.
Fixed missing 'USE' label in templates
window.
=> [MOS-29] Fix invalid screen after rejecting with template

harmony_changelog.md, products/BellHybrid/apps/application-bell-settings/widgets/DialogYesNo.cpp, products/BellHybrid/apps/application-bell-settings/windows/AboutYourBellWindow.cpp, products/BellHybrid/apps/application-bell-settings/windows/AboutYourBellWindow.hpp
In the french language, the software version was missing. 
Now the About window is able to display even longer software versions.
Yes/No behavior in the Factory Reset window is
fixed. Earlier it worked in carousel mode.
=> [BH-1640][BH-1645] Fix About and Factory Reset windows

module-bsp/board/rt1051/bsp/lpm/Oscillator.cpp, module-bsp/board/rt1051/common/fsl_drivers/CMakeLists.txt, module-bsp/board/rt1051/common/fsl_drivers/fsl_common.h, module-bsp/board/rt1051/common/fsl_drivers/fsl_common_arm.c
Some Harmony devices are struggling to switch between internal to external oscillators. According to the newest version of the library (lpm.c - Low Power Mode) the NXP is recommending adding at least a 200us delay after
enabling the external oscillator.
Their implementation is not full because the CPU speed used in the delay function is hardcoded.
So if the CPU has a frequency 4MHz the delay takes ~26ms.
To avoid that situation we use the proper speed of the CPU in the delay function.
=> [BH-1554] Add delay after init external oscillator

module-db/Database/Field.cpp, module-db/Database/Field.hpp, module-db/Database/sqlite3vfs.cpp, module-services/service-db/agents/settings/FactorySettings.cpp
Change of the algorithm used to initialize
settings database with values read from EEPROM,
previously first insertion failure resulted
in stopping the whole process, now next values
are inserted even if previous has failed.
Additionally minor cleanup.
=> [MOS-766] Change factory entries initialization routine

module-services/service-gui/DrawCommandsQueue.cpp, module-services/service-gui/DrawCommandsQueue.hpp, module-services/service-gui/WorkerGUI.cpp, module-services/service-gui/tests/test-DrawCommandsQueue.cpp, module-sys/Service/Worker.cpp, module-sys/Service/include/Service/Worker.hpp, module-utils/log/Logger.cpp, module-utils/log/Logger.hpp
In some cases, the system wasn't able to turn off
because the GUI service got stuck. The device
was still working in the background. The cause
was an empty queue in DrawCommandQueue which
hang the GUI worker.
The interface was modified and synchronization
the mechanism was removed.
The thread no longer waits in dequeue().
Also changed the worker to close in the right
the way the logger worker.
=> [BH-1624] Fix shutdown procedure

module-apps/application-phonebook/windows/PhonebookInputOptions.cpp, module-apps/application-phonebook/windows/PhonebookMainWindow.cpp, pure_changelog.md
Fix of the issue that pasting text into fields
in new contact view when there was already some
text present there resulted in improper
ellipsis placement and cursor misalignment.
=> [MOS-928] Fix pasting in new contact view fields

module-apps/application-onboarding/windows/EULALicenseWindow.cpp, module-gui/gui/widgets/text/Text.cpp, module-gui/gui/widgets/text/Text.hpp, pure_changelog.md
Optional feature: the _Text_ control can be setup to do this; the default is line-by-line (as it had been before). Now this has been used to scroll the EULA window as it contains plenty of text.
=> [MOS-938] Allow Text control to scroll several lines at once

module-gui/gui/widgets/ListViewEngine.cpp, module-gui/gui/widgets/ListViewEngine.hpp, pure_changelog.md
Fix of the issue that pressing up arrow in
empty list (e.g. notes, messages, alarms)
resulted in unnecessary deep refresh of
the screen, as the content didn't change.
Additionally minor code cleanup in separate
commit.
=> [MOS-932] Fix unneeded deep refresh in empty list

module-apps/application-call/windows/CallWindow.cpp, module-apps/application-messages/ApplicationMessages.cpp, module-apps/application-messages/data/SMSdata.hpp, module-apps/application-messages/windows/NewMessage.cpp, module-apps/application-messages/windows/NewMessage.hpp, module-apps/application-messages/windows/SMSTemplatesWindow.cpp, module-apps/application-messages/windows/SMSTemplatesWindow.hpp, module-apps/application-messages/windows/SMSThreadViewWindow.cpp, module-apps/application-messages/windows/SMSThreadViewWindow.hpp, module-apps/application-phonebook/models/ContactDetailsModel.cpp, module-apps/application-phonebook/widgets/InformationWidget.cpp, module-apps/apps-common/widgets/ActiveIconFactory.cpp, module-gui/gui/SwitchData.hpp, pure_changelog.md
Fix for inconsistent redirection to message threads list when pressing BACK from sending message from Contact view. Also proveded mechanizm to help switching back to previous App, when some App call window from another App.
=> [MOS-925] Fix redirection on BACK from sending message from Contact view

harmony_changelog.md, products/BellHybrid/assets/assets_proprietary.json
Added missing characters to font 'gt_pressura_light_46' used in Relaxation
=> [CP-1848] Problems with displaying file names

module-bluetooth/Bluetooth/btstack_config.h, pure_changelog.md
Fixes an issue when another device is connected via HFP and a new device wants to connect
Updated BT stack to 1.5.5 version
=> [MOS-525] Fix BT autoconnect when another device is already connected

module-bsp/board/rt1051/bellpx/clock_config.cpp, module-bsp/board/rt1051/puretx/clock_config.cpp
=> [MOS-000] Remove redundant newlines when printing clocks

module-bsp/board/linux/hal/battery_charger/BatteryCharger.cpp, module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp, module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp, module-bsp/devices/power/CW2015.cpp, module-bsp/hal/include/hal/battery_charger/AbstractBatteryCharger.hpp, module-services/service-evtmgr/battery/BatteryController.cpp, module-services/service-evtmgr/battery/BatteryController.hpp
The CW2015 driver should avoid any logic.
Thus I2C communication attempts were moved
to the BatteryCharger which is product specific.
=> [BH-1649] Reimplement I2C communication attempts

module-apps/application-meditation/data/Constants.hpp, module-apps/application-meditation/widgets/TimerProperty.cpp, module-apps/application-meditation/widgets/TimerProperty.hpp
The meditation time entered from the keyboard will be remembered.
=> [MOS-202] Add meditation parameters to non-volatile memory

module-bsp/board/linux/hal/battery_charger/BatteryCharger.cpp, module-services/service-eink/board/linux/renderer/src/RWindow.cpp, module-services/service-evtmgr/EventManager.cpp, module-services/service-evtmgr/WorkerEventCommon.cpp, module-services/service-evtmgr/battery/BatteryBrownoutDetector.cpp, module-services/service-evtmgr/battery/BatteryBrownoutDetector.hpp, module-services/service-evtmgr/battery/BatteryController.cpp, module-services/service-evtmgr/battery/BatteryController.hpp, module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp, module-services/service-evtmgr/service-evtmgr/WorkerEventCommon.hpp, module-services/service-evtmgr/service-evtmgr/include/EventManagerParams.hpp, module-utils/EventStore/EventStore.hpp, products/BellHybrid/services/evtmgr/EventManager.cpp, products/BellHybrid/services/evtmgr/WorkerEvent.cpp, products/BellHybrid/services/evtmgr/WorkerEvent.hpp, products/BellHybrid/services/evtmgr/include/evtmgr/battery/Thresholds.hpp, products/PurePhone/services/evtmgr/WorkerEvent.cpp, products/PurePhone/services/evtmgr/WorkerEvent.hpp, products/PurePhone/services/evtmgr/include/evtmgr/EventManager.hpp, products/PurePhone/services/evtmgr/include/evtmgr/battery/Thresholds.hpp
The system closes only if the SoC is 0%, but
it doesn't react if the voltage has a low level.
The new implementation invokes the close
procedure if the voltage is less than 3.4V.
This solution should avoid the possibility to
hang the MCU.
=> [BH-1630] Turn off the device for low voltage

module-services/service-cellular/src/SMSSendHandler.cpp
SMS handling is now fixed after attempt to send SMS in offline mode. After SMS was rejected by Offline mode, Pure was not able to send any message until device reboot.
=> [MOS-960] Fixed SMS flow after failed try in Offline

module-services/service-cellular/service-cellular/requests/UssdRequest.hpp
Now call request begins with # character is dicoverd and handled as a USSD code.
=> [MOS-944] Fixed handling USSD started by #

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, module-apps/apps-common/widgets/spinners/ItemSpinner.hpp, module-apps/apps-common/widgets/spinners/Model.hpp, module-bsp/board/rt1051/bsp/rtc/rtc.cpp, module-os/memory/UserMemStatsLogger.hpp, module-os/memory/usermem.c, module-os/memory/usermem.h, module-services/service-evtmgr/WorkerEventCommon.cpp, module-utils/log/api/log/debug.hpp, products/BellHybrid/BellHybridMain.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVerticalSimple.cpp
Disable libphonenumber initialization since it is not used in Harmony but takes around 1.4MB of memory
=> [BH-1655] Fix memory leaks in clock faces and shortcuts

module-services/service-cellular/src/CSQHandler.cpp, module-services/service-cellular/src/ServiceCellularPriv.cpp, pure_changelog.md
When the modem was turned off (e.g. due to a discharged battery), 
CSQ reporting mode logs caused logger buffer overflow.
=> [MOS-924] Fix redundant logs about CSQ reporting mode

module-apps/application-call/ApplicationCall.cpp, pure_changelog.md
During onboarding, the user could add new contacts by entering the emergency call screen.
=> [MOS-942] Fix access to contacts when onboarding in progress

module-apps/application-phonebook/windows/PhonebookNewContact.cpp, pure_changelog.md
Fix of the issue that after adding new contact
a window with contact details was shown, whereas
after adding new contact with the same number
as the one already present in another contact,
a list of all contacts was shown.
Minor cleanup.
=> [MOS-969] Unify GUI action after contact adding

module-db/Interface/SMSTemplateRecord.cpp, module-db/Interface/SMSTemplateRecord.hpp, module-db/Tables/SMSTemplateTable.cpp, module-db/Tables/SMSTemplateTable.hpp, module-db/tests/Helpers.cpp, module-db/tests/SMSTemplateRecord_tests.cpp, module-db/tests/SMSTemplateTable_tests.cpp, module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp, products/PurePhone/services/db/databases/migration/sms/0/devel.sql, products/PurePhone/services/db/databases/migration/sms/0/up.sql, products/PurePhone/services/db/databases/migration/sms/current/111a2d1b_Adding_new_column_to_templates_table_to_manage_templates_order/.meta, products/PurePhone/services/db/databases/migration/sms/current/111a2d1b_Adding_new_column_to_templates_table_to_manage_templates_order/down.sql, products/PurePhone/services/db/databases/migration/sms/current/111a2d1b_Adding_new_column_to_templates_table_to_manage_templates_order/up.sql, products/PurePhone/services/desktop/endpoints/messages/MessageHelper.cpp, test/pytest/service-desktop/test_templates.py
This API allows for managing message templates order.
Documentation: https://appnroll.atlassian.net/wiki/spaces/CP/pages/990642315/Messages+Endpoint+API+8#Change-a-message-template-order
=> [CP-702] Add API for managing templates order

module-services/service-cellular/tests/unittest_request_factory.cpp
Cellular call request factory unit test was commented out due to failing cases. After MOS-944 failng cases are updated and all tests are passing.
=> [MOS-177] Fix request factory UT are uncommented

harmony_changelog.md, products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp, products/BellHybrid/apps/application-bell-settings/models/FrontlightListItemProvider.cpp, products/BellHybrid/apps/application-bell-settings/models/FrontlightModel.cpp, products/BellHybrid/apps/application-bell-settings/presenter/FrontlightPresenter.cpp, products/BellHybrid/apps/application-bell-settings/presenter/FrontlightPresenter.hpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/PrewakeUpPresenter.cpp, products/BellHybrid/apps/application-bell-settings/windows/BellSettingsFrontlightWindow.cpp, products/BellHybrid/apps/common/include/common/models/FrontlightModel.hpp
Run the frontlight settings in "on demand" mode now turn on the backlight with the proper intensity.
If the device is idle in the frontlight settings the backlight isn't turned on after backing to the main window.
=> [BH-1650][BH-1651] Fix the frontlight settings

module-audio/tags_fetcher/TagsFetcher.cpp, products/BellHybrid/CMakeLists.txt, products/PurePhone/CMakeLists.txt
Use ConstMemoryConstrainedFileRef newly added to taglib
=> [CP-1837] Random crashes while copying files

module-bsp/board/rt1051/bsp/eMMC/fsl_mmc.c, module-platform/rt1051/src/disk_emmc.cpp, module-platform/rt1051/src/disk_emmc.hpp
Added logging of eMMC storage card
parameters so that it's easy to
determine what chip is installed
in the device the logs are from.
=> [BH-1672] Add logging of eMMC parameters

module-bsp/board/rt1051/bsp/magnetometer/magnetometer.cpp, module-bsp/bsp/magnetometer/magnetometer.hpp, pure_changelog.md
Fix of the magnetometer-related
issue causing the phone to crash
on shutdown on some rare 
occasions.
Cleanup of the magnetometer driver.
Added checks of all I2C operations
return codes and error messages
in case of failures.
=> [MOS-981] Fix crash on phone turn off

module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp
Due to high current consumption the device
will be charging only for DCP mode and if the timeout will occur.
=> [BH-1689] Turn off USB charging for CDP and SPD modes

module-apps/application-messages/windows/SMSTemplatesWindow.cpp, pure_changelog.md
Fixed Template window clearing after all templates are removed.
=> [CP-1974] Deleting all templates leaves some text on pure screen

image/system_a/data/lang/Deutsch.json, image/system_a/data/lang/English.json, image/system_a/data/lang/Espanol.json, image/system_a/data/lang/Francais.json, image/system_a/data/lang/Polski.json, image/system_a/data/lang/Svenska.json, module-apps/apps-common/notifications/NotificationsListPresenter.cpp, pure_changelog.md
Display "New message", translated accordingly - in singular - in case there had been multiple unread
SMS messages and now only one remains unread.
=> [MOS-578] Fix misleading SMS notification text

harmony_changelog.md, products/BellHybrid/apps/common/include/common/widgets/BellBattery.hpp, products/BellHybrid/apps/common/src/widgets/BellBattery.cpp
The new layout of battery status has the battery
SOC on the left side and battery image on the right.
=> [BH-1691] Change the layout of the battery status

harmony_changelog.md, module-bsp/drivers/pwm/DriverPWM.cpp, module-bsp/drivers/pwm/DriverPWM.hpp
Fix of the bug in PWM driver that
resulted in accessing array out of
bounds, what caused occasional
system crash on startup.
=> [BH-1695] Fix Harmony crash on startup

module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommonPopupBlueprints.cpp, module-apps/apps-common/WindowsPopupFilter.cpp, module-apps/apps-common/locks/data/LockData.hpp, module-apps/apps-common/locks/data/PhoneLockMessages.hpp, module-apps/apps-common/locks/handlers/PhoneLockHandler.cpp, module-apps/apps-common/locks/handlers/PhoneLockHandler.hpp, module-apps/apps-common/popups/data/PopupRequestParams.hpp, module-apps/apps-common/popups/data/PopupRequestParamsBase.hpp, module-apps/apps-common/popups/lock-popups/PhoneLockInputWindow.cpp, module-bsp/board/linux/usb_cdc/usb_cdc.cpp, module-bsp/bsp/usb/usb.hpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/WorkerDesktop.cpp, module-services/service-desktop/WorkerDesktop.hpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, products/PurePhone/services/appmgr/ApplicationManager.cpp, pure_changelog.md
Fixed file access via MTP even when phone is not unlocked. Now access is granted when the phone is unlocked by the user entering a passcode. If the phone is not passcode protected (passcode is nor set) then access to the files is always possible via MTP.
=> [MOS-686] Fixed MTP availability only after phone unlocked

module-bsp/board/rt1051/bellpx/clock_config.cpp, module-bsp/board/rt1051/bsp/lpm/CpuFreqLPM.cpp, module-bsp/board/rt1051/bsp/lpm/CpuFreqLPM.hpp, module-bsp/board/rt1051/bsp/lpm/RT1051LPMCommon.cpp, module-bsp/board/rt1051/drivers/RT1051DriverPLL2.cpp, module-bsp/board/rt1051/drivers/RT1051DriverSEMC.cpp, module-bsp/board/rt1051/os/_exit.cpp, module-bsp/board/rt1051/puretx/clock_config.cpp, products/BellHybrid/services/evtmgr/EventManager.cpp
* Switching VDD_SOC_IN only after PLL2 is turned off.
* Weak LDO stabilization delay.
* Removed switching to 1.275V before frequency change.
* Cleanups in LDO switching.
* Removed switching PeriphClk2Div for fCPU <= 24MHz, using AhbDiv instead.
* Removed log from _exit that caused logger mutex deadlock.
Coauthored with @dawidwojtas-mudita and @Maciej-Mudita.
=> [BH-1673] Harmony random resets fixes

module-apps/application-call/ApplicationCall.cpp, module-apps/application-call/include/application-call/ApplicationCall.hpp, module-apps/apps-common/ApplicationCommon.cpp, module-gui/gui/input/Translator.cpp, pure_changelog.md
Fixed a scenario where the user click to make a call to some contact and then quickly click BACK (right function button) to end the call and despite that Pure was still calling without showing any information. This fix prevent to handle key press event as a key longpress even after application lose a focus, or change a state.
=> [MOS-973] Fix for a ghost call after quick click back key to end a call

module-cellular/modem/mux/CellularMux.cpp, module-cellular/modem/mux/CellularMux.h, module-utils/log/Logger.cpp, module-utils/log/Logger.hpp, module-utils/log/LoggerBuffer.cpp, module-utils/log/LoggerBuffer.hpp, module-utils/log/LoggerWorker.cpp, module-utils/log/LoggerWorker.hpp, module-utils/log/StringCircularBuffer.cpp, module-utils/log/StringCircularBuffer.hpp, module-utils/log/api/log/log.hpp, module-utils/log/board/linux/log_linux.cpp, module-utils/log/board/rt1051/log_rt1051.cpp, module-utils/log/log.cpp, module-utils/log/tests/test_LoggerBuffer.cpp, module-utils/log/tests/test_log.cpp, test/mock-logs.cpp
Fixes and optimizations in logger:
* fixed possible buffer overflow when logging logs over line buffer size;
* reduced max log line length to 2048;
* moved pubsetbuf before file opening;
* log file stream buffer created once in logger ctor;
* additional minor cleanup.
=> [MOS-993] Logger bug fixes and optimizations

module-bsp/board/linux/rtc/rtc.cpp, module-bsp/board/rt1051/bsp/rtc/rtc.cpp, module-bsp/bsp/rtc/rtc.hpp
Save date and time at the startup of the system for analysis purposes.
=> [BH-1700] Add date and time to logs at the startup

module-bsp/board/linux/lpm/LinuxLPM.cpp, module-bsp/board/linux/lpm/LinuxLPM.h, module-bsp/board/rt1051/bsp/lpm/CpuFreqLPM.cpp, module-bsp/board/rt1051/bsp/lpm/CpuFreqLPM.hpp, module-bsp/board/rt1051/bsp/lpm/Oscillator.cpp, module-bsp/board/rt1051/bsp/lpm/RT1051LPMCommon.cpp, module-bsp/board/rt1051/bsp/lpm/RT1051LPMCommon.hpp, module-bsp/board/rt1051/common/board.cpp, module-bsp/board/rt1051/drivers/RT1051DriverPLL2.cpp, module-bsp/bsp/lpm/bsp_lpm.hpp
Next part of Harmony random resets fixes:
* added RC OSC startup delay as in newest lpm.c;
* changed order of clock source, oscillator and
LDO switching;
* removed connecting internal DCDC load resistor,
as it is only required to speed up converter
startup after it was turned off completely;
* changed DCDC operation mode to continuous
conduction;
* set low VDD_SOC_IN voltage back to 950mV as
suggested in RM;
* added switching DCDC converter to discontinuous
conduction mode for two lowest CPU clock
frequencies. 
=> [BH-1673] Fixes for Harmony random resets

module-bsp/board/rt1051/bellpx/irq_gpio.cpp, module-bsp/board/rt1051/bsp/watchdog/watchdog.cpp, module-bsp/bsp/watchdog/watchdog.hpp
Fix of the issue that RTWDOG performed
only CPU reset in case of timeout due
to IRQ misconfiguration resulting in
RTWDOG handler not being called.
=> [BH-1702] Fix RTWDOG main DCDC reset

module-bsp/bsp/usb/usb.hpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/WorkerDesktop.cpp, module-services/service-desktop/WorkerDesktop.hpp
Fix of the issue that Harmony's MTP
was constantly locked after MOS-686
fix, as the mechanics of unlocking
was not handled for Harmony at all.
=> [BH-1706] Fix inaccessible MTP on Harmony

module-bsp/board/rt1051/bellpx/irq_gpio.cpp, module-bsp/board/rt1051/common/board.cpp, module-bsp/board/rt1051/puretx/irq_gpio.cpp
Added mechanism that stores address of last
executed instruction before RTWDOG timeout
to enable some basic debugging in such cases,
as such resets do not create crashdumps and
leave no information in logs.
=> [MOS-230] Print last instruction address before RTWDOG reset

harmony_changelog.md, products/BellHybrid/services/evtmgr/internal/key_sequences/PowerOffSequence.hpp
When holding the back button the device would promt to power off after 5s. This was not inline with the manual. Now the prompt will come up after 10s which is correct by the manual. In the code the actual time is set to 9s because an additional 1s delay is caused by the OS and screen refreash rate.
=> [BH-1705] Fixed back button power off timer 10s

harmony_changelog.md, module-services/service-gui/ServiceGUI.cpp
Fixed the problem with the not appearing system closing window in some cases
=> [BH-1625] The shutdown window doesn't appear while closing the system

module-bsp/board/linux/CMakeLists.txt, module-bsp/board/linux/trng/trng.cpp, module-bsp/board/rt1051/CMakeLists.txt, module-bsp/board/rt1051/bsp/trng/RT1051Trng.cpp, module-bsp/board/rt1051/bsp/trng/RT1051Trng.hpp, module-bsp/board/rt1051/bsp/trng/trng.cpp, module-bsp/board/rt1051/common/fsl_drivers/CMakeLists.txt, module-bsp/board/rt1051/common/fsl_drivers/fsl_trng.c, module-bsp/board/rt1051/common/fsl_drivers/fsl_trng.h, module-bsp/bsp/trng/trng.hpp, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp, module-utils/time/time/dateCommon.hpp, module-utils/utility/Utils.cpp, products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
Use hardware TRNG integrated into RT1051 MCU
as an entropy source for builds complied
for RT1051.
=> [MOS-238] Use on-chip hardware TRNG as an entropy source

module-bsp/board/rt1051/bsp/rtc/rtc.cpp
Add extra logs when the RTC timeout error occurs.
In that, we can find reason in registers of what happened.
=> [BH-1718] Add extra logs to the RTC module

harmony_changelog.md, module-bsp/board/rt1051/bellpx/bsp/switches/switches.cpp
When the button is pressed/released we get an interrupt which falls or rises edge. We read the gpio state a bit later so in case of debouncing we can register the wrong pin state. After the debounce interval the state is stable.
=> [BH-1708] Fix buttons behavior

module-bsp/board/linux/usb_cdc/usb_cdc.cpp, module-bsp/bsp/usb/usb.hpp
Fix of the issue that sync with Mudita Center
would fail often after changes introduced in
CP-1968.
=> [MOS-997] Fix failing sync with Mudita Center

module-services/service-db/agents/quotes/QuotesAgent.cpp, module-services/service-db/agents/quotes/QuotesSettingsSerializer.cpp, module-services/service-db/agents/quotes/RandomizedQuoteModel.cpp, module-services/service-db/agents/quotes/RandomizedQuoteModel.hpp
* Changed RNG used when randomizing quotes list 
that was accidentally omitted in the previous PR.
* Small cleanup around RandomizedQuoteModel.
=> [MOS-238] Change RNG used in quotes randomization

harmony_changelog.md, module-bsp/board/linux/rtc/rtc.cpp, module-bsp/board/rt1051/bsp/rtc/rtc.cpp, module-bsp/bsp/rtc/rtc.hpp
The secure RTC can lock and the clock is not updated. To prevent this situation we reset LP registers (except for timestamps and alarms) and clear the LVD flag. Then we enable again LP SRTC.
=> [BH-1717] Fix no clock update

products/BellHybrid/services/evtmgr/internal/key_sequences/PowerOffSequence.hpp
When holding the back button, the device would prompt to power off after ~9-10s. This was not inline with the manual. Now the prompt will come up just after 10s. Previously the timer was set to 9s to account for delays caused be the OS and display, however it is now decided that the only thing that should matter is the time you actually have to hold the button for the prompt to show. This time is more or less exactly the same as the time set in the code.
=>  [BH-1705] Adjusted power off timer to >=10s

harmony_changelog.md, module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp, module-utils/CrashdumpMetadataStore/CrashdumpMetadataStore.hpp, module-utils/log/CMakeLists.txt, module-utils/log/Logger.cpp, module-utils/log/Logger.hpp, module-utils/log/LoggerWorker.cpp, module-utils/log/api/log/log.hpp, module-utils/log/log.cpp, module-utils/log/tests/CMakeLists.txt, module-utils/log/tests/test_LoggerBufferContainer.cpp, module-utils/log/tests/test_log.cpp, module-utils/log/tests/test_logDumps.cpp, pure_changelog.md
Added info about product, OS version, commit hash
and serial number to log filename to simplify
triage and quick sanity check of the logs in
cases many log files have to be analyzed.
=> [MOS-999] Provide additional info in log filename

harmony_changelog.md, module-sys/common/include/system/Common.hpp, products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp, products/BellHybrid/sys/SystemManager.cpp
Disabling the alarm by clicking "deep press" on the system shutdown screen only visually deactivated the alarm
but the alarm sound continued to ring.
=> [BH-1722] Fix unswitchable alarm audio

.vscode/settings.json
This fix is due to a bug in Ubuntu. The GTK path
must be changed in order to run the simulator window.
=> [BH-000] Fix simulator in vsc

.gitmodules, doc/build_targets.md, module-platform/linux/tests/unittest_filesystem_core.cpp, module-platform/linux/tests/unittest_filesystem_ext4.cpp, module-platform/linux/tests/unittest_filesystem_littlefs.cpp, module-platform/linux/tests/unittest_filesystem_reedgefs.cpp, third-party/json/test/json11-test.cpp
Fix of the issue that unit tests build would not
fail when unit test contained 2 test cases with
identical name.
Changed Catch2 submodule to local fork.
Minor unit tests and build target docs cleanup.
=> [MOS-184] Fix unit tests not failing on duplicate test case

run.sh
If the debug session was started using the run.sh script, the python version is now python 3.
=> [BH-1720] Changed GDB python to python 3

module-apps/application-onboarding/windows/EULALicenseWindow.cpp, module-gui/gui/widgets/text/Text.cpp, module-gui/gui/widgets/text/Text.hpp
Fix of the issue that EULA would not refresh
during scrolling at the end of document.
=> [MOS-938] Fix EULA multiline scrolling

module-bsp/board/rt1051/bellpx/board.cpp, module-bsp/board/rt1051/bsp/lpm/RT1051LPMCommon.cpp
If the CPU fails during changing the frequency
the device can stuck in SNVS mode.
So the CPU frequency is checked and if
the frequency is wrong the CPU doesn’t enter SNVS mode. The watchdog should restart the CPU.
=> [BH-1730] Fix enter into SNVS mode

module-apps/application-messages/models/SMSThreadModel.cpp, module-apps/application-messages/models/SMSThreadModel.hpp, module-apps/application-messages/windows/SMSThreadViewWindow.cpp, module-apps/application-messages/windows/SMSThreadViewWindow.hpp, module-db/Interface/ThreadRecord.hpp
Fix of the issue that after entering messages
app, opening one of the threads and returning
to main messages app window, new messages in
this thread were automatically marked as read.
=> [MOS-1003] Fix automatically marking new message as read

module-apps/application-call/windows/CallWindow.cpp, module-apps/application-messages/ApplicationMessages.cpp, module-apps/application-messages/data/SMSdata.hpp, module-apps/application-messages/windows/SMSTemplatesWindow.cpp, pure_changelog.md
Fix of the issue that unlocked phone would
automatically lock after user tried to reject
incoming call via SMS and stayed on the
templates window.
=> [MOS-1004] Fix autolock on SMS template call rejection

harmony_changelog.md, products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
During the alarm occurrence and the system turn-off screen
- selecting "No" option causes the "Next alarm will ring in 24h" prompt to be displayed
=> [BH-1726] Fix unwanted popup on shutdown screen

harmony_changelog.md, module-gui/gui/input/Translator.cpp, products/BellHybrid/apps/application-bell-main/windows/BellBatteryStatusWindow.cpp, products/BellHybrid/apps/application-bell-main/windows/BellBatteryStatusWindow.hpp, products/BellHybrid/services/evtmgr/EventManager.cpp
When the user holds the back button for 10 seconds to display the "turning off" prompt, we  show a redundant clock face display.
=> [BH-1728] Fix redundant clock face display while shutting down Harmony

module-sys/Service/Worker.cpp, module-sys/Service/include/Service/Worker.hpp
Changed default Worker join timeout to a more realistic value
in case of system shutdown procedure.
=> [BH-1412] Improve system shutdown procedure

image/system_a/data/lang/Deutsch.json, image/system_a/data/lang/English.json, image/system_a/data/lang/Espanol.json, image/system_a/data/lang/Francais.json, image/system_a/data/lang/Polski.json, image/system_a/data/lang/Svenska.json, module-apps/application-messages/data/MessagesStyle.hpp, module-apps/application-messages/windows/SMSThreadViewWindow.cpp, module-apps/application-messages/windows/SMSThreadViewWindow.hpp, module-gui/gui/widgets/ListViewEngine.cpp, module-gui/gui/widgets/ListViewEngine.hpp, products/PurePhone/CMakeLists.txt, products/PurePhone/assets/assets_common.json, pure_changelog.md
Not all messages can fit on the current screen in sms conversation windows, so there may be some holes that might suggest that  there are no more messages to display. Now, when there are more SMS to see by scrolling up, the Old Messages label will indicate this fact.
=> [MOS-930] Fix for for misunderstanding holes in sms conversations

module-db/Interface/ContactRecord.cpp, module-db/Interface/ContactRecord.hpp, module-db/tests/ContactsRecord_tests.cpp, pure_changelog.md
There was possibility to add contact, or edit some contact, with have 2 same phone numbers (exactly the same or witch/without country code). Now this has been fixed and is not possible to create, even by editing, contact with 2 exactly the same numbers or 2 same numbers and one of them with a country code
=> [MOS-1007] Fix for add/update contact with 2 same phone numbers

CMakeLists.txt, products/BellHybrid/CMakeLists.txt, products/PurePhone/CMakeLists.txt
Fix of the issue that rebuilding simulator
image after multimedia files have been
indexed resulted in no files visible in
Music Player app.
=> [MOS-1013] Fix missing audio files in simulator after rebuilding image

module-services/service-desktop/include/service-desktop/ServiceDesktopDependencies.hpp, module-services/service-gui/ServiceGUI.cpp, module-services/service-gui/service-gui/ServiceGUI.hpp, module-services/service-gui/service-gui/ServiceGUIDependencies.hpp, module-sys/SystemManager/SystemManagerCommon.cpp, products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
Changed startup services order.
Prevent handling multiple "close ready" messages from one service while closing system.
Introduced a new state in ServiceGUI.
Fixed a problem with turning on Harmony with a connected USB cable.
=> [BH-1412] Fix system shutdown procedure

doc/running_on_phone.md
This add a warning to remember about switching off `Automatic date and time` function before stat debugging
=> [MOS-603] Add warning to README in Upload to SDRAM via J-Link section

harmony_changelog.md, products/BellHybrid/services/time/AlarmOperations.cpp, products/BellHybrid/services/time/include/time/AlarmOperations.hpp
The deep press can disable alarms which cause
disable sounds. That behavior interrupts sounds in
applications.
=> [BH-1748] Fix problem with sounds in applications

module-bsp/board/rt1051/CMakeLists.txt, module-bsp/board/rt1051/bsp/lpm/Bandgap.cpp, module-bsp/board/rt1051/bsp/lpm/Bandgap.hpp, module-bsp/board/rt1051/drivers/RT1051DriverPLL.cpp, module-bsp/board/rt1051/drivers/RT1051DriverPLL.hpp, module-bsp/board/rt1051/drivers/RT1051DriverPLL2.cpp, module-services/service-audio/ServiceAudio.cpp, module-services/service-audio/include/service-audio/ServiceAudio.hpp, pure_changelog.md
Optimized power management strategy used by
ServiceAudio:
* changed minimum CPU frequency from 528MHz to 264MHz;
* added switching to 24MHz when operation active, but paused;
* minor cleanup in several places.
=> [MOS-1018] ServiceAudio power management optimizations

module-apps/apps-common/popups/TetheringConfirmationPopup.cpp, module-apps/apps-common/popups/TetheringOffPopup.cpp, pure_changelog.md
Fixed data loss when creating or editing a note/contact after connecting the USB cable and selecting the option to enable tetering in the popup window that appears. Now when tethering is enabled via the popup, the user will return to Application without data loss.
=> [MOS-948] Fix for tethering popup was losing app context

module-apps/application-call/windows/CallWindow.cpp, module-apps/application-call/windows/NumberWindow.cpp, pure_changelog.md
Fix of the issue that when trying to call empty
number when entering number via keypad
on main screen, popup 'Something went wrong'
would appear, while no action should
happen in such case.
=> [MOS-929] Block executing call when phone number empty

harmony_changelog.md, products/BellHybrid/apps/application-bell-meditation-timer/CMakeLists.txt, products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationCountdownPresenter.cpp, products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationCountdownPresenter.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.hpp
When the meditation countdown timer is enabled
and the deep press is performed before this window expired then it displays 0:00 timer.
=> [BH-1750] Fix meditation countdown timer

harmony_changelog.md, products/BellHybrid/apps/Application.cpp, products/BellHybrid/apps/common/include/common/popups/BellTurnOffOptionWindow.hpp, products/BellHybrid/apps/common/src/popups/BellTurnOffOptionWindow.cpp
"Turn off" window should be displayed for 10 seconds triggered by pressing the buttons "light" and "back" or 180 seconds triggered from the menu->settings
=> [BH-1756] Fix "turn off" window display time

module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommon.hpp, module-apps/apps-common/popups/TetheringConfirmationPopup.cpp, module-services/service-appmgr/model/ApplicationManagerCommon.cpp, products/PurePhone/sys/SystemManager.cpp, pure_changelog.md
Fix of the issue that after phone has locked
on tethering confirmation popup, unplugging
USB cable would result in bypassing phone
lock screen without providing password.
Minor ApplicationCommon cleanup.
=> [MOS-1024] Fix unlocking phone after locked with tethering popup

image/system_a/data/lang/Deutsch.json, image/system_a/data/lang/English.json, image/system_a/data/lang/Espanol.json, image/system_a/data/lang/Francais.json, image/system_a/data/lang/Polski.json, image/system_a/data/lang/Svenska.json
Change translations for Old Messages text to Previous Messages text.
=> [MOS-930] Change translations for Old Messages text

module-apps/application-call/ApplicationCall.cpp, module-services/service-cellular/CellularServiceAPI.cpp, module-services/service-cellular/service-cellular/CellularServiceAPI.hpp, module-services/service-time/ServiceTime.cpp, pure_changelog.md
It was possible to display an Alarm with the appropriate Alarm window exactly when end of call window with call summary are displayed and automatically closed after 3 seconds. This commit will fix this scenario. Now Alarm is snooze in the same way as if there is a phone call going on.
=> [MOS-1010] Fix for Alarm disappearance during end of call window

module-apps/apps-common/locks/data/PhoneLockMessages.hpp, module-apps/apps-common/locks/handlers/PhoneLockHandler.cpp, module-apps/apps-common/locks/handlers/PhoneLockHandler.hpp, module-apps/apps-common/locks/handlers/PhoneLockSubject.cpp, module-apps/apps-common/locks/widgets/Lock.cpp, module-apps/apps-common/locks/widgets/Lock.hpp, module-apps/apps-common/locks/widgets/PhoneLockBox.cpp, module-apps/apps-common/notifications/NotificationsModel.cpp, module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp, module-services/service-desktop/endpoints/security/SecurityEndpointHelper.cpp, products/PurePhone/services/appmgr/ApplicationManager.cpp, pure_changelog.md
Fix of the issue that after blocking
passcode from Center, Pure would still
display passcode input popup; providing
valid passcode there would result in
phone entering invalid state, where it
behaved as if it was unlocked, but
with blocked passcode.
=> [MOS-1021] Fix blocked passcode behavior

module-apps/apps-common/popups/TetheringConfirmationPopup.cpp, module-apps/apps-common/popups/TetheringOffPopup.cpp, pure_changelog.md
**Reverting** previous fix because when tethering is switched on the user are not able to use phone features, and we this fix make the user to pass this block and it would make their confuse.
=> [MOS-948] Revert: Fix for tethering popup was losing app context

module-apps/application-messages/windows/OptionsMessages.cpp, module-apps/application-notes/ApplicationNotes.cpp, module-apps/application-notes/windows/NoteCreateWindow.cpp, module-apps/application-notes/windows/NoteEditWindow.cpp, module-apps/application-notes/windows/NoteEditWindow.hpp, module-apps/application-notes/windows/NotesOptions.cpp, module-apps/application-notes/windows/NotesOptions.hpp, module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.cpp, module-apps/application-phonebook/windows/PhonebookInputOptions.cpp, module-utils/Clipboard/Clipboard.cpp, module-utils/Clipboard/Clipboard.hpp, module-utils/Clipboard/test/unittest_clipboard.cpp, pure_changelog.md
Fix of the issue that in Notes app 'Copy text'
option was shown in 'Options' menu even if
the note didn't contain any text.
=> [MOS-1028] Fix possibility to copy text from empty note

harmony_changelog.md, module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp, products/BellHybrid/services/evtmgr/EventManager.cpp, products/BellHybrid/services/evtmgr/internal/key_sequences/ResetSequence.hpp
If the user performs a manual reset there is no information in the logs. It can be treated as software resets.
So the best solution is to add a log about incoming manual reset and dump all logs to the file.
=> [BH-1761] Add a log when manual reset is performed

module-apps/application-notes/windows/NoteEditWindow.cpp, module-apps/application-notes/windows/NoteEditWindow.hpp
Fix of minor corner case bug in previous
implementation - pressing left functional
button when selecting input mode would
display empty options menu even if note
and clipboard were empty.
Additionally fixed the same bug for
'Save' button.
=> [MOS-1028] Fix corner case with input mode in Notes app

module-apps/application-meditation/ApplicationMeditation.cpp, module-apps/application-meditation/include/application-meditation/ApplicationMeditation.hpp, module-apps/application-meditation/windows/MeditationTimerWindow.cpp, module-apps/application-meditation/windows/MeditationWindow.cpp, module-apps/application-meditation/windows/MeditationWindow.hpp, module-apps/apps-common/locks/handlers/LockPolicyHandler.cpp, module-gui/gui/core/FontManager.cpp, pure_changelog.md
Fix of the issue that Meditation app
would prevent phone from locking on
every screen, though it should do
so only on timer screen.
=> [MOS-1031] Fix Meditation app screen lock

module-apps/application-alarm-clock/widgets/AlarmTimeItem.cpp, module-apps/application-alarm-clock/widgets/AlarmTimeItem.hpp, module-apps/apps-common/widgets/DateAndTimeStyle.hpp, module-audio/tags_fetcher/TagsFetcher.cpp, module-utils/utility/Utils.hpp, pure_changelog.md
Fix of multiple issues that manifested in
input fields of alarm clock, i.e. value
not erasing automatically, redundant
double-zero filling of hours field,
lack of zero-filling of minutes field
when navigating to AM/PM field in
12h mode.
=> [MOS-552] Fix alarm clock input behavior

module-apps/application-settings/windows/system/ChangeDateAndTimeWindow.cpp, module-apps/application-settings/windows/system/SystemMainWindow.cpp, pure_changelog.md
Fix of the issue that pressing 'Save' when setting 
time would set the time indeed, but the UI would
not return to previous window, what might look
as if saving failed.
=> [MOS-1032] Fix misleading 'Save' button behavior when setting time

module-apps/application-notes/windows/NoteEditWindow.cpp, module-apps/application-notes/windows/NoteEditWindow.hpp, module-apps/application-phonebook/windows/PhonebookNewContact.cpp, module-apps/application-phonebook/windows/PhonebookNewContact.hpp, module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommon.hpp, module-apps/apps-common/WindowsStack.cpp, module-apps/apps-common/WindowsStack.hpp, module-apps/apps-common/popups/TetheringConfirmationPopup.cpp, module-apps/apps-common/popups/TetheringConfirmationPopup.hpp, module-gui/gui/widgets/Window.hpp, pure_changelog.md
Fixed data loss when creating or editing a note/contact after connecting the USB cable and selecting the option to enable tetering in the popup window that appears. Now, when the user wants to enable tethering, they will be asked if they want to exit without saving.
=> [MOS-948] Fix for tethering popup was losing user unsaved data

module-apps/application-music-player/ApplicationMusicPlayer.cpp, module-apps/application-music-player/presenters/SongsPresenter.cpp, module-apps/application-music-player/presenters/SongsPresenter.hpp, module-apps/application-music-player/windows/MusicPlayerAllSongsWindow.cpp, module-apps/application-music-player/windows/MusicPlayerAllSongsWindow.hpp, module-apps/application-music-player/windows/MusicPlayerMainWindow.cpp, module-apps/application-music-player/windows/MusicPlayerMainWindow.hpp, pure_changelog.md
* Fix of the issue that switching from songs list to main view after playing and stopping
some track resulted in elapsed time counter
not being updated until the song is unpaused;
* cleanups.
=> [MOS-1036] Fix song time not updated when returning from list

module-services/service-desktop/WorkerDesktop.cpp, module-services/service-desktop/WorkerDesktop.hpp
Fix of the issue that after disconnecting tethering 
Pure would not connect back to Center, only 
USB cable reconnection would resolve the issue.
=> [CP-2184] Fix Pure not connecting to MC after leaving tethering

test/requirements.txt
while setting up MuditaOS toolchain in a virtual environment I noticed a requirement was missing. Probably it comes preinstalled on Ubuntu so no one noticed until now.
=> [BH-1765] Added missing python requirement

module-apps/application-onboarding/windows/OnBoardingChangeDateAndTimeWindow.cpp
Fix of the regression created by previous
commit - saving manually set time resulted
in switching two windows back instead of
just one.
=> [MOS-1032] Fix double return to previous window in onboarding

module-apps/application-phonebook/windows/PhonebookMainWindow.cpp, module-apps/application-phonebook/windows/PhonebookMainWindow.hpp, module-apps/application-phonebook/windows/PhonebookNewContact.cpp, module-apps/application-phonebook/windows/PhonebookNewContact.hpp, pure_changelog.md
Fix of the issue that 'Call' label would
disappear or show as 'Options' label
when switching through the windows in
particular scenarios.
Additionally fixed possibility to
call to contact when selecting it
via messages app by pressing
unlabeled left functional.
=> [MOS-1037] Fix disappearing 'Call' label in phonebook

module-gui/gui/widgets/Item.cpp, module-gui/test/test-google/test-gui-gridlayout.cpp
Fix not seting focus to false when all items where removed from parent
=> [BH-1764] Fix GridLayoutTesting Border Callback Test

harmony_changelog.md, module-services/service-evtmgr/EventManager.cpp, module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp, module-sys/SystemManager/CpuGovernor.cpp, module-sys/SystemManager/CpuSentinel.cpp, module-sys/SystemManager/PowerManager.cpp, module-sys/SystemManager/SystemManagerCommon.cpp, module-sys/SystemManager/include/SystemManager/CpuGovernor.hpp, module-sys/SystemManager/include/SystemManager/CpuSentinel.hpp, module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp, products/BellHybrid/services/evtmgr/EventManager.cpp, products/BellHybrid/services/evtmgr/include/evtmgr/user-activity-handler/UserActivityHandler.hpp, products/BellHybrid/services/evtmgr/user-activity-handler/UserActivityHandler.cpp, products/PurePhone/services/evtmgr/include/evtmgr/EventManager.hpp, products/PurePhone/services/evtmgr/include/evtmgr/UserActivityHandler.hpp, products/PurePhone/services/evtmgr/user-activity-handler/UserActivityHandler.cpp, pure_changelog.md
- Sentinel locks the frequency when pressing buttons and the encoder.
- The "user activity" sentinel will be properly managed by the system (CpuGovernor) just like other sentinels.
- Adding information about active sentinels in the power management statistics logs
=> [BH-1774] Fix frequency lock during user activity

harmony_changelog.md, module-services/service-desktop/endpoints/update/UpdateHelper.cpp, pure_changelog.md
Fix of the issue that exceptions thrown
by file_size method were not caught
at all, what resulted in system crashing.
=> [BH-1780] Fix uncaught std::filesystem::file_size exception

module-apps/application-messages/windows/NewMessage.cpp
* Fix of the issue that locking phone on new message 
window would cause phone number field contents 
to duplicate.
* Minor cleanups.
=> [MOS-1044] Fix duplicating phone number in messages app

module-apps/application-call/ApplicationCall.cpp, module-apps/application-call/data/CallSwitchData.hpp, module-apps/application-call/include/application-call/ApplicationCall.hpp, module-apps/application-call/windows/CallWindow.cpp, module-apps/application-call/windows/CallWindow.hpp, module-apps/application-call/windows/EmergencyCallWindow.cpp, module-apps/application-call/windows/EmergencyCallWindow.hpp, module-apps/application-call/windows/EnterNumberWindow.cpp, module-apps/application-call/windows/EnterNumberWindow.hpp, module-apps/application-call/windows/NumberWindow.hpp, module-apps/application-call/windows/WindowNames.hpp, module-apps/application-calllog/include/application-calllog/ApplicationCallLog.hpp, module-apps/application-desktop/windows/DesktopMainWindow.cpp, module-apps/application-messages/windows/SMSTemplatesWindow.cpp, module-apps/application-special-input/include/application-special-input/ApplicationSpecialInput.hpp, module-services/service-cellular/CellularServiceAPI.cpp, products/PurePhone/PurePhoneMain.cpp, products/PurePhone/services/appmgr/RunAppsInBackground.cpp, pure_changelog.md
* Removed call to abort() method in case 
EnterNumberWindow's SwitchData handler
receives message that can't be handled,
what caused the phone to crash.
* Unify ApplicationCall window names definitions.
* Code cleanup.
=> [MOS-1047] Fix calling abort() in EnterNumberWindow

module-services/service-cellular/call/doc/README.md
Typo in documentation module-services/service-cellular/call/doc/README.md
The state machine library is called `sml`, not `stm`.
The link is correct.
When searching on Github, it was difficult to find that **MuditaOS** uses this library.
=> [MOS-1046] Update module-services/service-cellular/call/doc/README.md

module-apps/apps-common/widgets/ButtonTriState.cpp, module-apps/apps-common/widgets/ButtonTriState.hpp, module-gui/gui/widgets/text/Text.cpp, module-gui/gui/widgets/text/Text.hpp, pure_changelog.md
Fix of the issue that VoLTE checking
state label was cut off due to
improper setMinimumWidthToFitText()
method behavior when text is placed
in box with rounded corners.
=> [MOS-1048] Fix not fitting VoLTE button label

harmony_changelog.md, module-sys/SystemManager/CMakeLists.txt, module-sys/SystemManager/LogSentinel.cpp, module-sys/SystemManager/PowerManager.cpp, module-sys/SystemManager/include/SystemManager/LogSentinel.hpp, module-sys/SystemManager/include/SystemManager/PowerManager.hpp, module-utils/log/CMakeLists.txt, module-utils/log/Logger.cpp, module-utils/log/Logger.hpp, pure_changelog.md
This will improve security and peripheral stabilization when downloading logs to a file.
=> [BH-1791] Add CPU frequency lock during log dump

image/system_a/data/lang/Deutsch.json, image/system_a/data/lang/English.json, image/system_a/data/lang/Espanol.json, image/system_a/data/lang/Francais.json, image/system_a/data/lang/Polski.json, image/system_a/data/lang/Svenska.json, module-apps/application-settings/windows/network/NetworkWindow.cpp, module-apps/application-settings/windows/network/NetworkWindow.hpp, module-apps/apps-common/options/OptionStyle.hpp, module-apps/apps-common/options/type/OptionSetting.cpp, module-apps/apps-common/options/type/OptionSetting.hpp, module-apps/apps-common/widgets/ButtonTriState.cpp, products/PurePhone/PurePhoneMain.cpp, pure_changelog.md
Changed VoLTE label from 'beta' to
'experimental'.
Fixed transition state label font
size to match the design.
=> [MOS-1052] Change VoLTE label from 'beta' to 'experimental'

harmony_changelog.md, module-bsp/board/rt1051/bsp/eink/ED028TC1.cpp, module-bsp/board/rt1051/bsp/eink/bsp_eink.cpp, module-bsp/board/rt1051/common/fsl_drivers/fsl_lpspi.c
According to the newest fsl library, the LPSPI_Reset function shouldn't be invoked in the LPSPI_MasterInit function.
As a result, the LPSPI module can't work after calling this API.
Fix the system crash when an EInk error occurs. If the display returns the error the driver could invoke the EinkPowerDown function recursively which causes a crash.
=> [BH-1814] Fix EInk errors in logs

harmony_changelog.md, products/BellHybrid/apps/application-bell-onboarding/include/application-bell-onboarding/ApplicationBellOnBoarding.hpp, products/BellHybrid/services/time/AlarmOperations.cpp, products/BellHybrid/services/time/include/time/AlarmOperations.hpp, products/BellHybrid/services/time/tests/test-BellAlarmOperations.cpp
The alarm shouldn't activate itself when the onboarding is in progress. So now we check the onboarding status before checking alarms.
Increased size of the onboarding application stack. This should resolve the issue when somehow, the alarm is set but there is no stack that causes the application to crash.
=> [BH-1817] Fix alarm when the onboarding is active

.vscode/tasks.json, Target_Linux.cmake, doc/quickstart.md, harmony_changelog.md
Due to using wrappers for the glibc syscalls, the ASAN doesn't work well. We also had trouble integrating this tool with GCC12.
The ASAN is still available but is turned off by default. Use -DLINUX_ENABLE_SANITIZER=ON to turn on.
Our recommendation is to use Valgrind as the runtime profiling tool. It's added for visual studio code.
=> [BH-1822] Disable Address Sanitizer

harmony_changelog.md, module-services/service-eink/ServiceEink.cpp
If the previous refresh failed the driver tried to add a new frame in the front of the vector. In some cases, the updateFrames could be empty, and adding a frame caused a system crash.
=> [BH-1830] Fix eink crash while refreshing

harmony_changelog.md, module-apps/apps-common/widgets/TimeFixedWidget.cpp, products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp, products/BellHybrid/apps/application-bell-powernap/data/PowerNapStyle.hpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/data/RelaxationStyle.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
Removed minus sign shown next to the remaining
time value for timers showing progress in
Meditation, Relaxation and Power Nap apps.
Style constants cleanup.
=> [BH-1825] Remove minus sign in countdown timers of progress

products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp
Removed minus sign in countdown timer in Meditation
=> [BH-1824] Removal of the minus sign in countdown time in Meditation

module-apps/apps-common/widgets/TimeSetFmtSpinner.cpp, module-apps/apps-common/widgets/TimeSetFmtSpinner.hpp, module-apps/apps-common/widgets/TimeSetSpinner.cpp, module-apps/apps-common/widgets/TimeSetSpinner.hpp, products/BellHybrid/apps/application-bell-relaxation/data/RelaxationStyle.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationVolumeWindow.cpp, products/BellHybrid/apps/common/include/common/data/StyleCommon.hpp, products/BellHybrid/apps/common/include/common/widgets/BellStatusClock.hpp, products/BellHybrid/apps/common/src/widgets/BellStatusClock.cpp
* Fix of the issue that after changing font size of the 
clock presented in Relaxation, Meditation and 
Power Nap apps, AM/PM label was not shown
in 12h mode.
* Added logs informing about missing margins map 
entry so that such issue is easier to debug if it 
should happen in the future.
=> [BH-1807] Fix missing AM/PM label in apps clock

harmony_changelog.md, module-gui/gui/core/renderers/ArcRenderer.cpp, module-utils/math/Math.hpp
Replacing double with float in rendering a circular progressbar results in a significant reduction in the demand for computing power, which in turn translates into reduced power consumption in all applications using a circular progressbar.
=> [BH-1846] Reducing power consumption while the application is running

harmony_changelog.md, module-bsp/board/rt1051/bellpx/bsp/lpm/WfiController.cpp, module-bsp/board/rt1051/bsp/watchdog/watchdog.cpp, module-bsp/board/rt1051/common/system_MIMXRT1051.c, module-sys/SystemWatchdog/SystemWatchdog.cpp, module-sys/SystemWatchdog/include/SystemWatchdog/SystemWatchdog.hpp
* Fixed initial RTWDOG config procedure, which 
put watchdog module in some non-deterministic
state due to not waiting after unlock request
and config change, what prevented the watchdog
to be reconfigured later in the OS.
* Configured RTWDOG to continue running in WFI 
to prevent potential freezes caused by
CPU not being woken up by periodic RTC
interrupt.
=> [BH-1833] Enable RTWDOG in WFI mode

config/requirements.txt, docker/assets/requirements.txt, tools/requirements.txt
GitHub's dependabot suggests we might be using outdated and vulnerable python libraries. This commit updates our requirements to use more recent verions of some of the libraries.
=> [BH-1842] Fix dependabot alerts

products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
Fix for the issue that after BH-1636
hour value in alarm edit mode was
displayed with a cursor below it,
which was inconsistent with the
design.
=> [BH-1865] Remove redundant cursor in alarm edit mode

harmony_changelog.md, products/BellHybrid/apps/common/src/AlarmModel.cpp
Fix the function that it's responsible for disabling the snooze alarm. After snoozing the alarm
and deactivating the alarm device shouldn't ring.
Collaborated with: @Maciej-Mudita @Lefucjusz @rrandomsky @patrycja-paczkowska
=> [BH-1867][BH-1868] Fix alarm rings after deactivation

products/BellHybrid/apps/Application.cpp, products/BellHybrid/apps/application-bell-powernap/ApplicationBellPowerNap.cpp, products/BellHybrid/apps/application-bell-powernap/CMakeLists.txt, products/BellHybrid/apps/application-bell-powernap/include/application-bell-powernap/ApplicationBellPowerNap.hpp, products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapMainWindowPresenter.cpp, products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapMainWindowPresenter.hpp, products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapWarningPresenter.cpp, products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapWarningPresenter.hpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapWarningWindow.cpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapWarningWindow.hpp, products/BellHybrid/apps/common/include/common/popups/AlarmActivatedWindow.hpp, products/BellHybrid/apps/common/include/common/popups/presenter/AlarmActivatedPresenter.hpp, products/BellHybrid/apps/common/src/popups/AlarmActivatedWindow.cpp, products/BellHybrid/apps/common/src/popups/presenter/AlarmActivatedPresenter.cpp
Below the 10% battery level threshold, we remind the user to recharge the battery to be sure that the alarm will ring.
=> [BH-1636] Add low battery info when the power nap is activated

harmony_changelog.md, module-bsp/board/rt1051/bellpx/bsp/switches/switches.cpp
Add double checking debouncing timer with reference GPT timer to eliminate incorrect behavior on deep press after exiting WFI
=> [BH-1870] Fix displaying the menu after deep press on main screen

products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
Graphics in pop-ups for vertical layout were shifted to the left
=> [BH-1871] Fix popup formatting for vertical home screen layout

module-apps/apps-common/widgets/AlarmSetSpinner.cpp, module-gui/gui/widgets/Item.cpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
Fix of the issue that underline appeared under
hours value when setting alarm time with knob
down (alarm disabled) after previous
confirmation of the alarm time.
=> [BH-1874] Fix underline appearing when setting alarm time

module-bsp/board/rt1051/puretx/board.cpp, pure_changelog.md
Fix of the issue that screen backlight
would sometimes flash lightly when the
phone is turning off.
=> [MOS-1061] Fix screen backlight flash when turning off

module-apps/application-onboarding/windows/UpdateDialogWindow.cpp, module-gui/gui/core/RawFont.cpp, module-gui/gui/core/RawFont.hpp, module-gui/gui/widgets/text/core/lines/MultiTextLine.cpp, pure_changelog.md
Fix of the issue that Pure would freeze
before displaying the last onboarding
screen if the language set during
onboarding was Spanish.
=> [MOS-1063] Fix device freeze after onboarding in Spanish

harmony_changelog.md, module-apps/apps-common/ApplicationCommon.cpp, module-apps/apps-common/ApplicationCommon.hpp, products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp, products/BellHybrid/apps/application-bell-main/CMakeLists.txt, products/BellHybrid/apps/application-bell-main/include/application-bell-main/ApplicationBellMain.hpp, products/BellHybrid/apps/application-bell-main/include/application-bell-main/presenters/HomeScreenPresenter.hpp, products/BellHybrid/apps/application-bell-main/models/UsbStatusModel.cpp, products/BellHybrid/apps/application-bell-main/models/UsbStatusModel.hpp, products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp, products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.hpp, products/BellHybrid/apps/common/include/common/layouts/BaseHomeScreenLayoutProvider.hpp, products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassic.hpp, products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVertical.hpp, products/BellHybrid/apps/common/include/common/widgets/BellConnectionStatus.hpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp, products/BellHybrid/apps/common/src/widgets/BellConnectionStatus.cpp
The "connected" label did not appear on the home screen if the USB was connected on another screen.
=> [BH-1882] Fix display of "Connected" label on home screen

products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithQuotes.cpp
Add again infoBox widget to avoid memory leaks on the home screen.
=> [BH-1860] Fix memory leak

harmony_changelog.md, module-platform/rt1051/src/disk_emmc.cpp, products/BellHybrid/BinaryAssetsVersions.cmake
The BIWIN eMMC memory
doesn't work stable when enablePreDefinedBlockCount flag is enabled.
=> [BH-1884] Fix biwin memory errors

harmony_changelog.md, module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp, module-bsp/bsp/battery_charger/battery_charger.hpp
The battery charger worker had only ~10% free
stack size so it was a possibility to stack overflow. 
After increasing the stack by 512 bytes the worker has ~40% free stack space.
=> [BH-1885] Increase stack size for battery charger task

harmony_changelog.md, products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithQuotes.hpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp, products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithQuotes.cpp
Below 20%, instead of quotes, the battery with percentage information about the charge level will appear on the main screen.
=> [BH-1883] Add a low battery notification on home screen with quotes

harmony_changelog.md, module-services/service-desktop/endpoints/update/UpdateHelper.cpp, module-utils/tar/include/tar/tar.hpp, module-utils/tar/tar.cpp, module-vfs/drivers/src/purefs/fs/filesystem_ext4.cpp, pure_changelog.md
* Added stream buffering for reading data 
from tar archive with update.
* Increased size of the buffer used for 
unpacking files from tar archive.
* Changed buffers data type from vectors 
to raw heap-allocated arrays.
=> [BH-1887] Speed up update process

module-apps/application-phonebook/windows/PhonebookMainWindow.cpp, module-db/Tables/ContactsTable.cpp, module-db/Tables/ContactsTable.hpp, pure_changelog.md
Fix of the issue that Pure would crash
when trying to delete all contacts from
Mudita Center when main window of
phonebook was opened and focus was
set on different contact than the
first one in the list.
=> [MOS-1067] Fix Pure crash when deleting all contacts

module-bsp/board/rt1051/bellpx/board/pin_mux.h, module-bsp/board/rt1051/bellpx/pin_mux.c, module-bsp/board/rt1051/puretx/board/pin_mux.h, module-bsp/board/rt1051/puretx/pin_mux.c, products/BellHybrid/BinaryAssetsVersions.cmake
Add init eMMC pins to make sure that the pins are configured in debug mode.
If we run a debug mode the 1st bootloader is not run so the pins may have incorrect config. 
Added config also for Pure.
=> [BH-1913] Fix debug mode

module-db/Tables/MultimediaFilesTable.cpp
Fix displaying vertical list before fileindexer ends
=> [BH-1896] Add opening the vertical lists on the currently set sound

module-bsp/board/rt1051/bellpx/bsp/lpm/WfiController.cpp
Fix of the issue that debug session would sometimes 
disconnect when the CPU entered WFI mode due to
core clock being stopped.
=> [BH-1921] Fix debug session disconnects on entering WFI

module-apps/apps-common/popups/WindowWithTimer.cpp, module-apps/apps-common/popups/WindowWithTimer.hpp, module-apps/apps-common/widgets/BellBaseLayout.hpp, module-apps/apps-common/windows/AppWindow.hpp, module-gui/gui/widgets/Item.hpp, module-gui/gui/widgets/Window.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationVolumeWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationVolumeWindow.hpp
Fix of the issue that autoclose of volume
window in Relaxation would result in not
updating current volume value in database.
=> [BH-1930] Fix no volume update in DB in Relaxation

products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp, products/BellHybrid/apps/application-bell-settings/presenter/BedtimeSettingsPresenter.cpp, products/BellHybrid/apps/application-bell-settings/presenter/BedtimeSettingsPresenter.hpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.hpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/PrewakeUpPresenter.cpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/PrewakeUpPresenter.hpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/SnoozePresenter.cpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/SnoozePresenter.hpp, products/BellHybrid/apps/application-bell-settings/windows/BellSettingsBedtimeToneWindow.cpp, products/BellHybrid/apps/application-bell-settings/windows/BellSettingsBedtimeToneWindow.hpp, products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsSnoozeWindow.cpp, products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsSnoozeWindow.hpp, products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.cpp, products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.hpp, products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsPrewakeUpWindow.cpp, products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsPrewakeUpWindow.hpp
After passing to the next menu from the list with labels the deep refresh must be performed to avoid ghosting on the screen.
=> [BH-1933] Perform a deep refresh in settings

harmony_changelog.md, module-services/service-evtmgr/screen-light-control/ScreenLightControlParameters.hpp, products/BellHybrid/alarms/BellAlarmHandler.cpp, products/BellHybrid/alarms/CMakeLists.txt, products/BellHybrid/alarms/src/actions/FrontlightAction.cpp, products/BellHybrid/alarms/src/actions/IgnoreKeysAction.cpp, products/BellHybrid/alarms/src/actions/IgnoreKeysAction.hpp
If the chime is before the backlight we need to ignore keys. Otherwise, the back button will run the backlight.
=> [BH-1935] Fix the backlight in pre-wake up

harmony_changelog.md, module-sys/SystemManager/PowerManager.cpp, module-sys/SystemManager/include/SystemManager/PowerManager.hpp
When the CPU is in WFI mode, the CPU usage statistics should only reflect the WFI range and not the other frequency ranges.
=> [BH-1950] Fix incorrect Power Management statistics in the logs

image/system_a/data/lang/Polski.json, products/BellHybrid/apps/application-bell-focus-timer/presenter/FocusTimerPresenter.cpp, products/BellHybrid/apps/common/include/common/widgets/list_items/MinutesWithOff.hpp
Fixed incorrect conjugation of word
"minuta" on Focus Timer summary
screen.
=> [BH-1955] Fix incorrect Polish conjugation in Focus Timer

module-apps/apps-common/widgets/TimeMinuteSecondWidget.cpp, module-apps/apps-common/widgets/TimeMinuteSecondWidget.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
Only at startup, when the number of seconds is less than 30, the minutes are rounded down, otherwise they are rounded up
=> [BH-1944] Changing the rounding method for minutes in relaxation

harmony_changelog.md, module-apps/application-meditation/widgets/MeditationTimer.cpp, module-apps/apps-common/widgets/AbstractProgressTime.hpp, module-apps/apps-common/widgets/ProgressTimer.cpp, module-apps/apps-common/widgets/ProgressTimer.hpp, module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.cpp, module-apps/apps-common/widgets/TimeMinuteSecondWidget.cpp, module-apps/apps-common/widgets/TimeMinuteSecondWidget.hpp, products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationVolumeWindow.cpp, products/BellHybrid/apps/common/include/common/widgets/list_items/details.hpp
The longer the time countdown on the progress bar, the less frequently the screen is refreshed, which results in less power consumption when running the Meditation, Relaxation, Power Nap and Focus Timer applications.
=> [BH-1971] Changing the refresh rate of the progress bar screen

module-apps/apps-common/widgets/AbstractProgressTime.hpp, module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.cpp, module-apps/apps-common/widgets/TimeMinuteSecondWidget.cpp, module-apps/apps-common/widgets/TimeMinuteSecondWidget.hpp
Fix of the issue that Meditation and
Power Nap apps would crash during
active sessions due to bad optional
access introduced in previous time
displaying fix.
=> [BH-1992] Fix crash in Meditation and Power Nap

module-bluetooth/Bluetooth/audio/BluetoothAudioDevice.cpp, module-bluetooth/Bluetooth/audio/BluetoothAudioDevice.hpp, module-utils/utility/Utils.hpp, pure_changelog.md
Fix of the issue that A2DP stream volume
was controlled using naive approach
with linear scaling instead of
exponential one, what resulted in
highly non-linear volume control
experience.
=> [MOS-1069] Change A2DP stream volume scale to exponential

harmony_changelog.md, products/BellHybrid/apps/application-bell-settings/windows/BellSettingsWindow.cpp
Changed order of entries in Settings menu, so
that they're grouped in logical categories.
=> [BH-2000] Change order of entries in Settings

cmake/modules/Assets.cmake
Workaround for an issue that arised after
Jenkins has been migrated to new machine.
Because of some reason build would fail
on rsync'ing non-existent '.db-journal'
files - locally the same rsync works
perfectly fine.
These files are not needed anyway,
so temporary exclude them from
rsync.
This should be reverted after CI/CD
is fixed.
=> [BH-000] Workaround for CI/CD issue

harmony_changelog.md, module-services/service-desktop/ServiceDesktop.cpp, module-services/service-desktop/WorkerDesktop.cpp, module-services/service-desktop/WorkerDesktop.hpp, module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
Fixes of the issues that would cause device crash 
when connected with broken USB cable:
* fixed memory leaks in VCOM init and deinit 
functions;
* guarded accessing desktopWorker object in 
message handlers, as messages are 
asynchronous and might arrive after worker has
already been destroyed. Not the cleanest solution, 
but does the trick.
=> [BH-2002] Fix crash when connected with broken USB cable

module-audio/Audio/decoder/DecoderMP3.cpp
Fix of the issue that improper check
of dr_mp3 library initialization
success could result in double-free
of library internals in case
initialization was unsuccessful.
=> [BH-2020] Fix double-free in DecoderMP3

products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp, products/BellHybrid/apps/application-bell-settings/widgets/SongsListViewItem.cpp, products/BellHybrid/apps/common/include/common/models/SongsModel.hpp, products/BellHybrid/apps/common/src/AudioModel.cpp, products/BellHybrid/apps/common/src/models/SongsModel.cpp
Fix of the issue that removing custom
alarm file while the alarm was ringing
would result in "Unsupported media file"
popup being shown for any file on
alarm sound selection list.
=> [BH-2019] Fix alarm sounds list after selected file deletion

module-audio/Audio/decoder/DecoderWAV.cpp
Fix of the issue that the device would crash
when entering alarm sound selection list
after deleting selected file during alarm
ringing, but only when file's format was
WAV.
=> [BH-2019] Fix crash after deleting WAV alarm sound

scripts/lua/products/BellHybrid/scripts/update.lua
The alarm directory is created while updating the software.
=> [BH-2024] Fix lack of alarm directory after updating software

products/BellHybrid/apps/application-bell-whats-new/ApplicationWhatsNew.cpp, products/BellHybrid/apps/application-bell-whats-new/include/application-bell-whats-new/ApplicationWhatsNew.hpp
When the alarm rings during the What`s new application, the system handles the alarm and closes the current application. After the alarm ends, we go to the main application without showing any more new features.
=> [BH-2025] Add alarm handling in What`s new application

module-utils/utility/CMakeLists.txt, module-utils/utility/Version.cpp, module-utils/utility/Version.hpp, products/BellHybrid/apps/application-bell-whats-new/models/WhatsNewFeaturesModel.cpp, products/BellHybrid/services/appmgr/ApplicationManager.cpp, scripts/lua/products/BellHybrid/scripts/entry.lua
This task relates to the What’s new feature that needs to know which version of MuditaOS was installed before the update. Normally What’s new uses a database to get the previous  version, but after the first run this field will be empty. To bypass this issue the PureRecovery needs to save the previous version in recovery_status.json that is generated after the update process.
=> [BH-2026] Add mechanism for getting previously OS version

module-bsp/board/linux/hal/battery_charger/BatteryCharger.cpp, products/BellHybrid/apps/application-bell-relaxation/data/RelaxationStyle.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationEndedWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationPausedWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationPausedWindow.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.hpp
Updated looped relaxation windows to match
new design.
Fixed issue with misaligned pause button
on timed relaxation windows.
=> [BH-2035] Update relaxation paused window

products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.hpp
The meditation start countdown screen will be consistent with the meditation screen.
=> [BH-2036] Fix missing label in the countdown to the start of meditation

products/BellHybrid/apps/common/src/options/BellOptionWithDescriptionWindow.cpp
Fix of a regression introduced by c6192fd9,
resulting in BellOptionWithDescriptionWindow
not parsing rich text in case no token map
is provided.
=> [BH-2037] Fix text parsing on factory reset screen

products/BellHybrid/apps/application-bell-focus-timer/windows/FocusMainWindow.cpp, products/BellHybrid/apps/application-bell-focus-timer/windows/FocusSettingsWindow.cpp, products/BellHybrid/apps/application-bell-focus-timer/windows/FocusSettingsWindow.hpp, products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.cpp, products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationMainWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationMainWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationTimerWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationTimerWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/SettingsWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/SettingsWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/StatisticsWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/StatisticsWindow.hpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapMainWindow.cpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapSessionEndedWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationPausedWindow.cpp, products/BellHybrid/apps/common/include/common/windows/ShortcutsWindow.hpp, products/BellHybrid/apps/common/src/layouts/ShortcutsLayoutClassic.cpp, products/BellHybrid/apps/common/src/windows/ShortcutsWindow.cpp
* Removed frames that were drawn around 
the entire screen, as they're not present in
the design and are not even visible,
as the very edge of the display is
covered by the casing.
* Cleanups.
=> [BH-2038] Remove redundant frames around screen

products/BellHybrid/apps/application-bell-focus-timer/data/FocusTimerStyle.hpp, products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.cpp, products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.hpp, products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp, products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.hpp, products/BellHybrid/apps/application-bell-powernap/data/PowerNapStyle.hpp, products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.hpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp, products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.hpp
Fix of the issue that pause and bell
icons were misaligned in Power Nap,
Meditation and Focus Timer after
introduction of BH-2013.
=> [BH-2042] Fix misaligned pause and bell icons

products/BellHybrid/services/audio/ServiceAudio.cpp, products/BellHybrid/services/audio/VolumeFade.cpp, products/BellHybrid/services/audio/include/audio/VolumeFade.hpp
During the fade in or fade out phase, when the user turns the encoder to set the volume, the fade in or fade out phase continues and the target volume is set to the one requested by the user
=> [BH-2029] Add volume control during fade in and fade out

products/BellHybrid/services/audio/VolumeFade.cpp
If the song is shorter than the fade in and out durations, we reduce the target volume value so that both phases have time to complete.
=> [BH-2032] Add fade in and fade out support for very short songs

products/PurePhone/services/desktop/endpoints/EndpointFactoryPure.cpp
Fix of the naming issue that caused build
with developer options enabled to fail.
=> [BH-2061] Fix developer build

module-audio/Audio/AudioCommon.hpp, products/BellHybrid/alarms/src/actions/PlayAudioActions.cpp, products/BellHybrid/services/audio/VolumeFade.cpp, products/BellHybrid/services/audio/include/audio/VolumeFade.hpp
The alarm volume should gradually increase by 0.1 every 300 ms, which gives a time of 45 seconds for a full 15-point scale
=> [BH-2062] Fix alarm volume fade in duration

CMakeLists.txt, cmake/modules/Assets.cmake, cmake/modules/DownloadAsset.cmake, cmake/modules/Utils.cmake, image/CMakeLists.txt, module-db/tests/Helpers.cpp, products/BellHybrid/CMakeLists.txt, products/PurePhone/CMakeLists.txt, test/CMakeLists.txt
* Fix for the issue that resulted in race
condition between target creating and
populating databases and the one copying
created databases to required directories.
The issue was caused by lack of dependency
between those targets, what allowed CMake
engine to parallelize them. As a result,
databases were copied before their creation
has been finished, what resulted in weird
discrepancies in databases content and
occasional rsync errors.
* Removed unused multicomp_install
function.
* Refactored DB tests readContent
helper.
=> [BH-2065] Fix race condition between CMake targets

harmony_changelog.md, module-audio/Audio/AudioCommon.hpp, module-audio/Audio/Operation/PlaybackOperation.cpp, module-audio/Audio/Operation/PlaybackOperation.hpp, products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationMainWindowPresenter.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.hpp, products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp
* Changed the message that is shown 
when entering alarm sound selection list
after file selected as an alarm has been 
deleted via Center.
* Fixed bug with audio exception error code 
not being set at all.
* Removed unused logic handling file limit 
error message, as there is no longer fixed 
tracks limit.
=> [BH-2064] Change message shown after removing alarm file

products/BellHybrid/services/audio/ServiceAudio.cpp, products/BellHybrid/services/audio/VolumeFade.cpp, products/BellHybrid/services/audio/include/audio/VolumeFade.hpp
When we stopped the song at the beginning of the relaxation, it had no effect to fade in that was still running in the background, meaning that when we resumed playback, we had a sudden increase in volume.
Additionally, after pausing and resuming relaxation, the fade out appeared too quickly.
=> [BH-2067] Fix fade in for relaxation after pausing a song

tools/db_migration.py
Update outdated license URL in migration tool,
which was accidentally missed in commit
https://github.com/mudita/MuditaOS/commit/773f2c7eb156fadb62983d670c1a8a876b2fe8b7.
=> [BH-2071] Update license URL in migration tool

products/BellHybrid/services/audio/ServiceAudio.cpp, products/BellHybrid/services/audio/VolumeFade.cpp
When the user changed the volume during pause, the fade out started at the wrong level.
=> [BH-2067] Fix volume change during relaxation pause

module-audio/Audio/AudioCommon.hpp, products/BellHybrid/alarms/src/actions/PlayAudioActions.cpp, products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
Power nap volume should gradually increase by 0.1 every 300 ms, which gives a time of 45 seconds for a full 15-point scale
=> [BH-2072] Fix power nap volume fade in duration

harmony_changelog.md, products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp, products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.hpp
Fix of the issue that abandoning meditation
by clicking back will result in displaying
meditation session summary with invalid
accusative form in Polish.
=> [BH-2073] Fix invalid accusative form in Meditation

products/BellHybrid/services/db/agents/ShuffleQuoteModel.cpp
Fix of the issue that the device would
crash and never be able to boot up
again after receiving invalid timestamp
(e.g. -1).
=> [BH-2078] Fix crash upon receiving invalid timestamp

image/system_a/data/lang/Deutsch.json, image/system_a/data/lang/English.json, image/system_a/data/lang/Espanol.json, image/system_a/data/lang/Francais.json, image/system_a/data/lang/Polski.json
Fix of the issue that link to
Mudita Forum displayed at the
end of What's New would lead
to 404 page.
=> [BH-2079] Fix outdated forum link

module-audio/Audio/decoder/DecoderMP3.cpp
Fix of the issue that playing large MP3
files with missing Xing frame would
result in crash due to minimp3
trying to compute metadata by analyzing
the entire file and running out of
heap memory.
=> [BH-2081] Fix crash for MP3s with missing Xing frame

products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
Fix of the issue that frontlight would
blink for a second after light clicking
to stop ringing Power Nap.
=> [BH-2090] Fix blink when disabling Power Nap

harmony_changelog.md, products/BellHybrid/apps/application-bell-relaxation/data/RelaxationCommon.hpp, products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningLoopPresenter.cpp, products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningLoopPresenter.hpp, products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningProgressPresenter.hpp, products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationTimerSelectPresenter.cpp, products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationPlayer.cpp, products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationPlayer.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.hpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp, products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationTimerSelectWindow.cpp, products/BellHybrid/apps/application-bell-whats-new/presenter/WhatsNewMainPresenter.cpp, products/BellHybrid/apps/application-bell-whats-new/presenter/WhatsNewMainPresenter.hpp, products/BellHybrid/serial-number-parser/SerialNumberParser.cpp, products/BellHybrid/serial-number-parser/include/serial-number-parser/SerialNumberParser.hpp
* Removed timer logic that would refresh the 
entire loop mode screen in Relaxation.
The contents of the screen doesn't change
unless there's a user activity or time
update, so the timer is not needed.
This should improve battery life in
Relaxation loop mode.
* Minor cleanups.
=> [BH-2091] Remove timer from loop mode in Relaxation

harmony_changelog.md, module-audio/Audio/Operation/PlaybackOperation.cpp, module-audio/Audio/Operation/PlaybackOperation.hpp, module-audio/Audio/decoder/Decoder.cpp, module-audio/Audio/decoder/Decoder.hpp, module-audio/Audio/decoder/DecoderFLAC.cpp, module-audio/Audio/decoder/DecoderFLAC.hpp, module-audio/Audio/decoder/DecoderMP3.cpp, module-audio/Audio/decoder/DecoderMP3.hpp, module-audio/Audio/decoder/DecoderWAV.cpp, module-audio/Audio/decoder/DecoderWAV.hpp
* Fix of the issue that seeking in large MP3 file would 
cause OOM error when creating MP3 indexes. This 
caused OS crash when looping large MP3 file in 
Relaxation.
* Minor cleanups.
=> [BH-2100] Fix crash when seeking in large MP3 file

harmony_changelog.md, module-gui/gui/widgets/Rect.cpp, products/BellHybrid/apps/common/include/common/data/BatteryUtils.hpp, products/BellHybrid/apps/common/include/common/windows/BellBatteryStatusWindow.hpp, products/BellHybrid/apps/common/src/windows/BellBatteryStatusWindow.cpp
* Fixed misaligned charging symbol on battery popup, shown after holding back button.
* Fixed improper handling of string_view storing battery image name.
=> [BH-2108] Fix misaligned charging symbol
