mudita/MuditaOS

- README.md
- doc/quickstart.md
Updated readme to contain product-specific buiild options
> [EGD-7826] Update quickstart readme

- module-vfs/README.md
Update VFS documentation after change user
partition from the LittleFS to the EXT4 fs
> [EGD-7945] Update documentation about the VFS

- config/bin_blob_check.sh
- config/pre-commit.hook
Git hook check to avoid committing forbidden files
> bin check hook

- module-bsp/board/linux/usb_cdc/usb_cdc.cpp
- module-bsp/bsp/usb/usb.hpp
- module-services/service-desktop/WorkerDesktop.cpp
Polling routine replaced with event driven implementation for USB receive
> [BH-1167] USB async receive

- module-vfs/drivers/include/purefs/fs/drivers/file_handle_ext4.hpp
- module-vfs/drivers/include/purefs/fs/drivers/file_handle_littlefs.hpp
- module-vfs/drivers/include/purefs/fs/drivers/file_handle_vfat.hpp
- module-vfs/drivers/src/purefs/fs/filesystem_ext4.cpp
- module-vfs/include/user/purefs/fs/file_handle.hpp
- module-vfs/include/user/purefs/fs/filesystem.hpp
- module-vfs/include/user/purefs/fs/handle_mapper.hpp
- module-vfs/src/purefs/fs/filesystem.cpp
Force closing all opened files when unmount
filesystem is called.
> [EGD-7883] Close all opened files when umount

- CMakeLists.txt
- Jenkinsfile
- cmake/modules/AddPackage.cmake
- cmake/modules/DiskImage.cmake
- cmake/modules/DownloadAsset2.cmake
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/assets.json
- products/PurePhone/CMakeLists.txt
- products/PurePhone/assets.json
- tools/download_asset2.py
- tools/requirements.txt
Cherry-pick of https://github.com/mudita/MuditaOS/pull/3210
> [EGD-7932] Added downloader for assets for Bell - cherry pick

- module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-main/include/application-bell-main/ApplicationBellMain.hpp
- products/BellHybrid/apps/application-bell-main/widgets/BellBattery.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellBatteryStatusWindow.cpp
- products/BellHybrid/services/appmgr/ApplicationManager.cpp
- products/BellHybrid/services/appmgr/include/appmgr/ApplicationManager.hpp
- products/BellHybrid/sys/SystemManager.cpp
- products/BellHybrid/sys/include/sys/SystemManager.hpp
Fix few battery related issues:
[BH-1136]
[BH-1137]
[BH-1156]
[BH-1136]: https://appnroll.atlassian.net/browse/BH-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1137]: https://appnroll.atlassian.net/browse/BH-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1156]: https://appnroll.atlassian.net/browse/BH-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BH-1136] Fix battery low level issues

- products/BellHybrid/apps/common/include/common/data/StyleCommon.hpp
- products/BellHybrid/apps/common/src/popups/AlarmActivatedWindow.cpp
- products/BellHybrid/apps/common/src/popups/AlarmDeactivatedWindow.cpp
Make popup layout according to the design
> [BH-1149] Fix popup layout

- cmake/modules/Assets.cmake
- cmake/modules/DiskImage.cmake
- products/BellHybrid/assets.json
- products/PurePhone/assets.json
- test/CMakeLists.txt
Luts were downloaded to the wrong directory
> [EGD-7969] Fix assets script

- products/BellHybrid/apps/application-bell-bedtime/ApplicationBellBedtime.cpp
- products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
- products/BellHybrid/apps/common/include/common/models/BedtimeModel.hpp
- products/BellHybrid/services/time/AlarmOperations.cpp
Fix HF on shutdown caused by wrong BedtimeModel deinitialization.
> [BH-1170] Fix hf on shutdown

- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
- products/BellHybrid/apps/application-bell-settings/models/TimeUnitsModel.cpp
- products/BellHybrid/config/ProductConfig.in.hpp
Added possibility to enable/disable
displaying of temperature and corresponding
settings/onboarding views.
> [BH-1166] Disable temperature feature

- module-gui/gui/widgets/ListView.cpp
- module-gui/gui/widgets/ListView.hpp
- module-gui/gui/widgets/ListViewWithArrows.cpp
- module-gui/gui/widgets/ListViewWithArrows.hpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/options/BellOptionsNavigation.hpp
- products/BellHybrid/apps/common/src/options/BellOptionWindow.cpp
- products/BellHybrid/apps/common/src/options/BellOptionsNavigation.cpp
- products/BellHybrid/apps/common/src/options/BellShortOptionWindow.cpp
Invert of list navigation keys in relation to knob movements
> [BH-977] Fix inversed list navigation

- module-services/service-desktop/parser/ParserFSM.cpp
- module-services/service-desktop/parser/ParserFSM.hpp
Added a timer to reset a Parser when transfer times out
> [EGD-7400] Device won't reconnect to MC when unplugged during communication

- products/BellHybrid/assets.json
- products/PurePhone/assets.json
- tools/download_asset2.py
Luts file was to big to download via api which limit is 1MB
> [EGD-7973] Fixed luts file problem

- Jenkinsfile
more cores in use - one jenkins at once with all might we can get
ccache one 100gb catalog
> [EGD-7975] Added more cores and general ccache

- products/BellHybrid/assets.json
- products/PurePhone/assets.json
- tools/download_asset2.py
> EGD-7973 release bell

- module-bsp/board/rt1051/bellpx/bsp/lpm/PowerProfile.cpp
- products/BellHybrid/EinkSentinelBell.cpp
tweaks in power profile for bell to stay low with fcpu as much as possible
> [BH-1189] Fix battery usage optimization

- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
Don't set default alarm time after soonze
> [BH-1155] Fix alarm time after snooze

- module-db/Interface/ThreadRecord.cpp
- module-os/board/rt1051/_exit.cpp
- module-services/service-evtmgr/EventManager.cpp
- module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp
- module-sys/SystemManager/SystemManagerCommon.cpp
- module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
- module-utils/log/CMakeLists.txt
- module-utils/log/logdump/CMakeLists.txt
- module-utils/log/logdump/include/logdump/logdump.h
- module-utils/log/logdump/logdump.cpp
- products/BellHybrid/BellHybridMain.cpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/services/evtmgr/EventManager.cpp
- products/BellHybrid/services/evtmgr/include/evtmgr/EventManager.hpp
- products/PurePhone/CMakeLists.txt
- products/PurePhone/PurePhoneMain.cpp
- products/PurePhone/services/evtmgr/include/evtmgr/EventManager.hpp
- products/PurePhone/test/test-settings/test-service-db-settings-api.cpp
Log are now dumped:
* on system shutdown including hard faults and aborts
* every 5 minutes
Fixed some logs
> Egd 7948 extend log dumping

- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
This PR fixes two issues:
BH-1157
BH-1186
Those were caused by wrong check of initial latch state.
> [BH-1157] Fix deactivate state stuck

- module-apps/apps-common/widgets/TimeSetFmtSpinner.cpp
- products/BellHybrid/apps/application-bell-settings/models/TimeUnitsModel.cpp
Fix clock setup for 12H and 24H time formats
> [BH-1108] Fix main clock time setup

- products/BellHybrid/apps/application-bell-settings/data/BellSettingsStyle.hpp
- products/BellHybrid/services/appmgr/include/appmgr/IdleHandler.hpp
Fixed wrong font size
[BH-1183] Auto back timer update
[BH-1183]: https://appnroll.atlassian.net/browse/BH-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BH-1182] Onboarding updates

- products/BellHybrid/apps/application-bell-meditation-timer/presenter/IntervalChimePresenter.cpp
Display last setting of Meditation Timer - Chime Interval
> [BH-1164[ Remember value for Chime Interval

- products/BellHybrid/apps/Application.cpp
- products/BellHybrid/apps/CMakeLists.txt
- products/BellHybrid/apps/include/Application.hpp
Stop all audio playback on long back click
> [BH-1142] Fix stop audio on long back click

- Jenkinsfile
For ccache to work with abspaths
> [EGD-7982] Added one build catalog

- Jenkinsfile
CI timing improvement workaround/fix pick
> EGD-7982 pick to stable

- module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp
- module-services/service-evtmgr/battery-level-check/BatteryLevelCheck.cpp
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/services/appmgr/ApplicationManager.cpp
- products/BellHybrid/services/appmgr/include/appmgr/ApplicationManager.hpp
- products/BellHybrid/sys/SystemManager.cpp
- products/BellHybrid/sys/include/sys/SystemManager.hpp
Fix of critcal battery behavior for Bell
> [BH-1198] Fix critical battery level behavior

- module-apps/application-alarm-clock/models/NewEditAlarmModel.cpp
- module-apps/application-alarm-clock/models/NewEditAlarmModel.hpp
- module-apps/application-alarm-clock/presenter/AlarmClockEditWindowPresenter.cpp
- module-apps/application-alarm-clock/presenter/AlarmClockEditWindowPresenter.hpp
- module-apps/application-alarm-clock/windows/CustomRepeatWindow.cpp
- module-apps/application-alarm-clock/windows/NewEditAlarmWindow.cpp
Fixed data removal on alarm when setting custom repeat.
> [EGD-7957] Fixed data removal on alarm when setting custom repeat

- products/BellHybrid/BinaryAssetsVersions.cmake
Update Bell updater and ecoboot bin versions to newest.
> [BH-1208] Update bin versions

- products/BellHybrid/apps/application-bell-main/include/application-bell-main/ApplicationBellMain.hpp
> [BH-1209] Fix Bell crash on shutdown

- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
Fix alarm ringing even though the back was pressed on progress window.
> [BH-1202] Fix nap alarm after back

- products/BellHybrid/services/audio/ServiceAudio.cpp
hold of CPU freq when audio is active
> [BH-1211] Fix bell audio use cpu sentinel

- module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp
- module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.hpp
Added temporary fix for SOC calculation
during discharging.
> [BH-1162] Battery SOC filtering

- module-apps/application-settings/windows/bluetooth/AddDeviceWindow.cpp
- module-apps/application-settings/windows/bluetooth/AllDevicesWindow.cpp
- module-bluetooth/Bluetooth/Device.hpp
- module-bluetooth/Bluetooth/interface/BluetoothDriverImpl.cpp
- module-bluetooth/Bluetooth/interface/profiles/GAP/GAP.cpp
- module-bluetooth/Bluetooth/interface/profiles/GAP/GAP.hpp
- module-bluetooth/tests/tests-BluetoothDevicesModel.cpp
- module-services/service-bluetooth/service-bluetooth/BluetoothDevicesModel.cpp
- module-services/service-bluetooth/service-bluetooth/SettingsSerializer.cpp
- module-services/service-desktop/endpoints/bluetooth/BluetoothMessagesHandler.cpp
Fixed bluetooth pairing for devices with long names.
> [EGD-7931] Fixed bt pairing

- module-apps/application-settings/models/bluetooth/BluetoothSettingsModel.cpp
- module-apps/application-settings/models/bluetooth/BluetoothSettingsModel.hpp
- module-apps/application-settings/windows/bluetooth/AllDevicesWindow.cpp
Fixes HF when forgetting more than available devices
> [EGD-7988] Fix 'forget' HF in BT devices window

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- products/BellHybrid/apps/Application.cpp
- products/BellHybrid/apps/include/Application.hpp
- products/PurePhone/apps/Application.cpp
- products/PurePhone/apps/include/Application.hpp
Changed time update interval to 1 minute
> [BH-1140] Changed time update interval

- products/BellHybrid/alarms/src/actions/PlayAudioActions.cpp
- products/BellHybrid/alarms/src/actions/PlayAudioActions.hpp
Remove prewakeup chime audio playback timeout,
it was interacting and disabling alarm chime
> [BH-1176] Fix prewakeup-alarm interaction

- module-apps/apps-common/locks/data/SimLockMessages.hpp
- module-apps/apps-common/locks/handlers/SimLockHandler.cpp
- module-apps/apps-common/locks/handlers/SimLockHandler.hpp
- module-apps/apps-common/locks/handlers/SimLockSubject.cpp
- module-apps/apps-common/locks/handlers/SimLockSubject.hpp
- module-apps/apps-common/popups/lock-popups/SimLockInputWindow.cpp
- products/PurePhone/services/appmgr/ApplicationManager.cpp
Sim input popup interactions on back fix.
> [EGD-7919] Sim input popup interactions on back fix.

- image/assets/lang/Deutsch.json
- image/assets/lang/English.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/application-bell-onboarding/CMakeLists.txt
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingWelcomeWindow.cpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingWelcomeWindow.hpp
Additional "Welcome" screen is added to the Onboarding application
> [BH-1123] Welcome Screen Update

- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.hpp
Added cyclic deep refresh on main screen every 30 minutes.
> [BH-1028] Cyclic Deep Refresh

- module-services/service-evtmgr/backlight-handler/BacklightHandlerCommon.cpp
- module-services/service-evtmgr/backlight-handler/BacklightHandlerCommon.hpp
- module-services/service-evtmgr/screen-light-control/ControlFunctions.cpp
- module-services/service-evtmgr/screen-light-control/ScreenLightControlParameters.cpp
- module-services/service-evtmgr/screen-light-control/ScreenLightControlParameters.hpp
- module-services/service-evtmgr/service-evtmgr/ScreenLightControlMessage.hpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
- products/BellHybrid/apps/application-bell-settings/models/advanced/FrontlightListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/advanced/FrontlightModel.cpp
- products/BellHybrid/services/evtmgr/CMakeLists.txt
- products/BellHybrid/services/evtmgr/EventManager.cpp
- products/BellHybrid/services/evtmgr/backlight-handler/BacklightHandler.cpp
- products/BellHybrid/services/evtmgr/include/evtmgr/backlight-handler/BacklightHandler.hpp
- products/BellHybrid/services/evtmgr/screen-light-control/ScreenLightControl.cpp
- products/BellHybrid/services/evtmgr/screen-light-control/ScreenLightControl.hpp
- products/PurePhone/services/evtmgr/backlight-handler/BacklightHandler.cpp
- products/PurePhone/services/evtmgr/include/evtmgr/BacklightHandler.hpp
> [BH-1030] Frontlight ramp

- products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsProgressWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
Fix top clock not being updated on progress window start
Fix AM/PM not showing in PowerNap top clock
> [BH-1215] Fix top clock

- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
- products/BellHybrid/apps/common/include/common/widgets/ListItems.hpp
Set Snooze Chime Interval to be coherent with length
Note: This PR also applies changes in [BH-1159]
[BH-1159]: https://appnroll.atlassian.net/browse/BH-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BH-1154] Snooze Chime Interval / Length Coherent

- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
Pressing back button starts snooze
> [BH-1206] Enter Snooze from Back Button

- module-cellular/at/cmd/src/CFUN.cpp
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/connection-manager/ConnectionManager.cpp
- module-services/service-cellular/connection-manager/ConnectionManagerCellularCommands.cpp
- module-services/service-cellular/service-cellular/ServiceCellular.hpp
- module-services/service-cellular/service-cellular/connection-manager/ConnectionManagerCellularCommands.hpp
- module-services/service-cellular/service-cellular/connection-manager/ConnectionManagerCellularCommandsInterface.hpp
- module-services/service-cellular/tests/unittest_connection-manager.cpp
- module-sys/SystemManager/CpuSentinel.cpp
- module-sys/SystemManager/include/SystemManager/CpuSentinel.hpp
Service cellular is holding minimum cpu frequency during
phone mode switch.
> [EGD-7909] Fixed phone mode switching

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- module-gui/gui/widgets/Window.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsBedtimeToneWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/advanced/BellSettingsFrontlightWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsSnoozeWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsPrewakeUpWindow.cpp
no action on onClose when switched to popup window
> [BH-955] Fix onClose when popup displayed

- products/BellHybrid/apps/application-bell-background-sounds/data/BGSoundsStyle.hpp
Make bottom description font light (not bold)
> [BH-1217] Fix library app font

- products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.hpp
Display frontlight only when enabled in settings
> [BH-1174] Fix frontlight during alarm

- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
- products/BellHybrid/apps/application-bell-main/widgets/SnoozeTimer.cpp
- products/BellHybrid/apps/application-bell-main/widgets/SnoozeTimer.hpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.hpp
- products/BellHybrid/apps/common/include/common/models/AbstractAlarmModel.hpp
- products/BellHybrid/apps/common/include/common/models/AlarmModel.hpp
- products/BellHybrid/apps/common/src/AlarmModel.cpp
Fixed bug causing snooze on/off settings not being
handled properly.
> [BH-1185] Proper handling of snooze on/off

- module-apps/apps-common/popups/WindowWithTimer.cpp
- module-apps/apps-common/popups/WindowWithTimer.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.hpp
- products/BellHybrid/apps/common/include/common/data/BellFinishedWindowSwitchData.hpp
- products/BellHybrid/apps/common/src/windows/BellFinishedWindow.cpp
Set meditation end window timeout to 5s
5s captures entire length of gong audio
> [BH-1213] Fix meditation end window timeout

- module-bluetooth/Bluetooth/BluetoothWorker.cpp
- module-bluetooth/Bluetooth/BluetoothWorker.hpp
- module-bluetooth/Bluetooth/CommandHandler.cpp
- module-bluetooth/Bluetooth/interface/profiles/ProfileManager.cpp
- module-bluetooth/Bluetooth/interface/profiles/ProfileManager.hpp
- module-services/service-bluetooth/ServiceBluetooth.cpp
When user tried to unpair connected device, the device was not
disconnecting. Now it's fixed
> [EGD-7874] Fix no disconnect after unpair

- module-apps/apps-common/popups/presenter/AlarmPresenter.cpp
- module-services/service-time/AlarmOperations.cpp
- module-services/service-time/AlarmOperations.hpp
- module-services/service-time/tests/tests-AlarmOperations.cpp
fixed the processing of alarms set to the same time also taking into account concurrent snoozes
> [EGD-7960] Fix of concurrent alarms handling

- module-services/service-evtmgr/screen-light-control/ControlFunctions.cpp
- module-services/service-evtmgr/screen-light-control/ControlFunctions.hpp
- module-services/service-evtmgr/screen-light-control/ScreenLightControl.hpp
- module-services/service-evtmgr/screen-light-control/ScreenLightControlParameters.hpp
- products/BellHybrid/services/evtmgr/screen-light-control/ScreenLightControl.cpp
- products/BellHybrid/services/evtmgr/screen-light-control/ScreenLightControl.hpp
- products/PurePhone/services/evtmgr/backlight-handler/BacklightHandler.cpp
- products/PurePhone/services/evtmgr/include/evtmgr/BacklightHandler.hpp
- products/PurePhone/services/evtmgr/screen-light-control/ScreenLightControl.cpp
- products/PurePhone/services/evtmgr/screen-light-control/ScreenLightControl.hpp
Cumulated fixes for both screen and keypad light:
https://appnroll.atlassian.net/browse/EGD-7900
https://appnroll.atlassian.net/browse/EGD-7898
https://appnroll.atlassian.net/browse/EGD-7897
> [EGD-7900] Fix backlight behavior

- module-platform/linux/tests/unittest_filesystem_core.cpp
- module-platform/linux/tests/unittest_filesystem_ext4.cpp
- module-vfs/drivers/src/purefs/fs/filesystem_vfat.cpp
Fix and unifying the stat() syscall in the VFS
Fix the ftruncate() syscalls in the FAT and VFS
> [EGD-7881] Fix stat syscalls in the VFS

- products/PurePhone/services/evtmgr/EventManager.cpp
- products/PurePhone/services/evtmgr/backlight-handler/BacklightHandler.cpp
- products/PurePhone/services/evtmgr/include/evtmgr/BacklightHandler.hpp
only torch short press refreshes backlight handler
> [EGD-7478] Fix torch backlight action

- module-os/board/rt1051/_exit.cpp
Calling abort() or exit() from the interrupt context
causes that the phone enters into bootloop, because
in the exception mode ISR cannot be used.
We are add guards for prevent clean system shudown
when abort is called from the ISR context.
> [EGD-7996] Prevent crashdump recursion from ISR

- module-apps/application-calculator/tests/CalculatorInput_tests.cpp
- module-audio/Audio/test/unittest_audio.cpp
- module-db/tests/CalllogRecord_tests.cpp
- module-db/tests/CalllogTable_tests.cpp
- module-db/tests/ContactGroups_tests.cpp
- module-db/tests/ContactsAddressTable_tests.cpp
- module-db/tests/ContactsNameTable_tests.cpp
- module-db/tests/ContactsNumberTable_tests.cpp
- module-db/tests/ContactsRecord_tests.cpp
- module-db/tests/ContactsRingtonesTable_tests.cpp
- module-db/tests/ContactsTable_tests.cpp
- module-db/tests/MultimediaFilesTable_tests.cpp
- module-db/tests/NotesRecord_tests.cpp
- module-db/tests/NotesTable_tests.cpp
- module-db/tests/NotificationsRecord_tests.cpp
- module-db/tests/NotificationsTable_tests.cpp
- module-db/tests/QueryInterface.cpp
- module-db/tests/SMSRecord_tests.cpp
- module-db/tests/SMSTable_tests.cpp
- module-db/tests/SMSTemplateRecord_tests.cpp
- module-db/tests/SMSTemplateTable_tests.cpp
- module-db/tests/ThreadRecord_tests.cpp
- module-db/tests/ThreadsTable_tests.cpp
- module-gui/test/test-catch-text/test-gui-Text.cpp
- module-gui/test/test-catch-text/test-gui-TextFixedSize.cpp
- module-gui/test/test-catch-text/test-gui-TextLineCursor.cpp
- module-gui/test/test-catch/test-language-input-parser.cpp
- module-services/service-db/test/test-factory-settings.cpp
- module-services/service-db/test/test-service-db-quotes.cpp
This is temporary workaround that shouldn't be merged outside of release branch.
It allows selected Pure related tests to fail. 
Other solution would include adding Pure specific assets to project as well as some Pure specific fonts, which I presume is more invasive. 
Test use per product should be addressed globally.
> [BH-1187] Temp workaround for tests not working in Bell release

- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingLanguageWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingLanguageWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/models/advanced/AboutYourBellModel.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/advanced/LanguageWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/advanced/LanguageWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/widgets/advanced/AboutYourBellListItem.cpp
- products/BellHybrid/apps/application-bell-settings/windows/advanced/AboutYourBellWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/advanced/AboutYourBellWindow.hpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/Languages.hpp
- products/BellHybrid/apps/common/include/common/widgets/ListItems.hpp
- products/BellHybrid/apps/common/src/widgets/ListItems.cpp
- products/BellHybrid/apps/common/src/windows/BellWelcomeWindow.cpp
- products/BellHybrid/config/ProductConfig.in.hpp
BH-1220 - Hide memory info from About screen
BH-1224 - Removed Svenska language
BH-1226 - Onboarding trigger set to light click
BH-1243 - Implemented proper snooze settings flow
> [BH-1220] Various critical bug fixes

- products/BellHybrid/BinaryAssetsVersions.cmake
> [BH-1238] Update bootloader version

- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.hpp
- products/BellHybrid/services/appmgr/include/appmgr/IdleHandler.hpp
Home Screen alarm time set return updated to 10s
> [BH-1223] Global idle return timer 180s

- module-utils/log/Logger.cpp
It will be possible to debug cellular now.
> [EGD-8001] Fix enable cellular logs

- products/BellHybrid/apps/application-bell-main/widgets/BellBattery.hpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
Charging battery UI fix:
- bigger font
- center widget
> [BH-1254] Charging battery UI fix

- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.cpp
Fixed bluetooth not ringing after bt call hang up.
> [EGD-7875] Fixed bt not ringing

- .idea/modules.xml
- module-bluetooth/Bluetooth/BluetoothWorker.cpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFPImpl.hpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSPImpl.hpp
Some fallback names were incorrect
> [EGD-7697] Fix BT names in all files

- module-apps/application-call/data/CallAppStyle.hpp
- module-apps/application-call/widgets/StateIcon.hpp
- module-apps/application-call/widgets/StateIcons.cpp
- module-apps/application-call/widgets/StateIcons.hpp
- module-apps/application-call/windows/CallWindow.cpp
- module-apps/application-call/windows/CallWindow.hpp
- module-apps/application-call/windows/EnterNumberWindow.cpp
- module-gui/gui/widgets/ImageBoxWithText.cpp
- module-gui/gui/widgets/ImageBoxWithText.hpp
fixed state icons to use box layout plus string and allignement fixes
> [EGD-5374] fix call gui issues

- module-apps/application-messages/windows/SMSThreadViewWindow.cpp
After editing a contact from the message level,
the contact details will be refreshed in the message view.
> [EGD-7728] Fix refreshing contact details after editing

- image/assets/lang/Polski.json
- products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp
- products/BellHybrid/apps/application-bell-powernap/data/PowerNapListItem.cpp
- products/BellHybrid/apps/application-bell-powernap/data/PowerNapStyle.hpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/LanguageUtils.hpp
- products/BellHybrid/apps/common/src/LanguageUtils.cpp
Add support for genitive form for Polish language "minute" word
> [BH-1219] Fix language numeral form

- image/assets/lang/Deutsch.json
- image/assets/lang/English.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
- products/BellHybrid/apps/common/src/TimeUtils.cpp
Alarm Activation Message: "&" is replaced with "i" for polish translation
> [BH-1121] Alarm Activation Message

- config/bootstrap_config
- config/build_runner_docker
- config/common_scripts_lib
- config/download_assets
- config/license_header_check.sh
- config/requirements.txt
- docker/Dockerfile.runner.in
- docker/jenkins-docker/Dockerfile
- test/requirements.txt
Cleanup of docker scripts and small fixups
> [EGD-8019] Clean docker build scripts

- config/bootstrap_config
- config/build_runner_docker
- config/common_scripts_lib
- config/download_assets
- config/license_header_check.sh
- config/requirements.txt
- docker/Dockerfile.runner.in
- docker/jenkins-docker/Dockerfile
- test/requirements.txt
Cleanup of docker scripts and small fixups
Cherry-pick of https://github.com/mudita/MuditaOS/pull/3342
> [EGD-8019] Clean docker build scripts - cherry-pick

- module-cellular/modem/mux/CellularMux.cpp
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/src/ServiceCellularPriv.cpp
- module-services/service-cellular/src/SimCard.cpp
- module-services/service-cellular/src/SimCard.hpp
Modem is now disconected from network until active sim card
is selected.
> [EGD-7864] Fix Modem rf in enabled after sim selected

- module-apps/apps-common/widgets/ProgressTimer.cpp
Quick and dirty fix for release for no Gong on Pure
> [EGD-8024] Dirty release fix for no meditation gong

- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
Fix state transitions in state controller
> [BH-1267] Fix state controller

- products/PurePhone/BinaryAssetsVersions.cmake
Use the lastest bootloader version.
> [EGD-8033] Bump binaries versions

- module-services/service-time/AlarmOperations.cpp
- module-services/service-time/AlarmOperations.hpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
- products/BellHybrid/services/time/AlarmOperations.cpp
- products/BellHybrid/services/time/include/time/AlarmOperations.hpp
- products/PurePhone/services/time/AlarmOperations.cpp
- products/PurePhone/services/time/include/time/AlarmOperations.hpp
Enhanced alarm priorities handling
[BH-1259] Snooze time displayed incorrectly
while returning to the home screen
[BH-1263] Bottom message displayed when
editing alarm
Fixed ambiguous iterator use.
[BH-1259]: https://appnroll.atlassian.net/browse/BH-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1263]: https://appnroll.atlassian.net/browse/BH-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BH-1191] Alarm priorities

- products/BellHybrid/apps/Application.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/ApplicationBellMeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/include/application-bell-meditation-timer/ApplicationBellMeditationTimer.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/IntervalChimePresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-powernap/ApplicationBellPowerNap.cpp
- products/BellHybrid/apps/application-bell-powernap/include/application-bell-powernap/ApplicationBellPowerNap.hpp
- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapMainWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
- products/BellHybrid/apps/include/Application.hpp
Implement correct idle timeout handling in applications
> [BH-1270] Fix idle timeout in applications

- image/assets/lang/Deutsch.json
- image/assets/lang/English.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingFinalizeWindow.cpp
Finalize Screen ipdated icon, removed literals
> [BH-1272] Update Onboarding Finalize Screen

- products/BellHybrid/apps/application-bell-alarm/data/BellAlarmStyle.hpp
- products/BellHybrid/apps/application-bell-alarm/windows/BellAlarmSetWindow.cpp
Proper formatting applied to Alarm Set icon
> [BH-1244] Align Alarm Set Window

- module-apps/application-meditation/widgets/MeditationTimer.cpp
- module-apps/application-meditation/widgets/MeditationTimer.hpp
- module-apps/application-meditation/windows/MeditationTimerWindow.cpp
Fix the gong timer application after timer compoment
fixes
> [EGD-8024] Fix no gong after preparation time

- module-bsp/board/rt1051/bellpx/board/pin_mux.h
- module-bsp/board/rt1051/bellpx/bsp/lpm/RT1051LPM.cpp
- module-bsp/board/rt1051/bellpx/bsp/lpm/RT1051LPM.hpp
- module-bsp/board/rt1051/bellpx/irq_gpio.cpp
- module-bsp/board/rt1051/bellpx/pin_mux.c
- module-bsp/board/rt1051/bsp/watchdog/watchdog.cpp
addig the power reset of the system if RTWDOG triggers
> [BH-1269] Add watchdog power reset

- module-services/service-evtmgr/EventManager.cpp
- products/BellHybrid/services/evtmgr/EventManager.cpp
- products/PurePhone/services/evtmgr/EventManager.cpp
attached dome switch as power (reboot) key when usb connected
> [BH-1282] Fix bell power on when usb connected

- Jenkinsfile
- docker/Dockerfile.runner.in
Shared library allows us to centralize jenkins workflow between jobs
> [EGD-7879] Change Jenkinsfile to use shared library

- products/BellHybrid/apps/Application.cpp
- products/BellHybrid/apps/application-bell-background-sounds/ApplicationBellBackgroundSounds.cpp
- products/BellHybrid/apps/application-bell-background-sounds/include/application-bell-background-sounds/ApplicationBellBackgroundSounds.hpp
- products/BellHybrid/apps/application-bell-background-sounds/widgets/BGSoundsPlayer.cpp
- products/BellHybrid/apps/application-bell-powernap/ApplicationBellPowerNap.cpp
- products/BellHybrid/apps/application-bell-powernap/include/application-bell-powernap/ApplicationBellPowerNap.hpp
- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
- products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/ApplicationBellSettings.hpp
- products/BellHybrid/apps/application-bell-settings/presenter/BedtimeSettingsPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/PrewakeUpPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/SnoozePresenter.cpp
- products/BellHybrid/apps/common/include/common/models/AbstractAudioModel.hpp
- products/BellHybrid/apps/common/include/common/models/AudioModel.hpp
- products/BellHybrid/apps/common/src/AudioModel.cpp
- products/BellHybrid/apps/include/Application.hpp
- products/BellHybrid/services/audio/ServiceAudio.cpp
Make sure apps are only stopping their own audio playbacks
> [BH-1273] Fix audio asset playback stop

- module-apps/application-onboarding/ApplicationOnBoarding.cpp
- module-sys/PhoneModes/Subject.cpp
- module-sys/PhoneModes/include/PhoneModes/Subject.hpp
- products/PurePhone/sys/SystemManager.cpp
Fix tethering mode popup show when no simcard
is selected. It'll works in the onBoarding and
normal mode.
> [EGD-8013] Fix tethering popup show when no SIMCARD

- image/assets/lang/Polski.json
Changed 'Nieprzeczytane' to 'Nowe'.
> [EGD-8056] Fix new messages string

- Jenkinsfile
Added fail cause to the GH status from CI
> [EGD-8059] Add verbosity to GH checks

- tools/check_commit_messages.py
Fixed for commits fixing more than one issue
> [EGD-7817][EGD-0000] Allow multiple Jira tickets in commit message

- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/connection-manager/ConnectionManager.cpp
- module-services/service-cellular/connection-manager/ConnectionManagerCellularCommands.cpp
- module-services/service-cellular/service-cellular/CellularMessage.hpp
- module-services/service-cellular/service-cellular/connection-manager/ConnectionManager.hpp
- module-services/service-cellular/service-cellular/connection-manager/ConnectionManagerCellularCommands.hpp
- module-services/service-cellular/service-cellular/connection-manager/ConnectionManagerCellularCommandsInterface.hpp
- module-services/service-cellular/src/SimCard.hpp
- module-services/service-cellular/tests/unittest_connection-manager.cpp
Service cellular will retry phone mode change on
failed attempt.
> [EGD-7909] Fix Retry mode change on fail

- module-apps/apps-common/ApplicationCommon.cpp
- module-services/service-evtmgr/EventManager.cpp
- module-utils/log/api/log/debug.hpp
Added Permanent Frequency setting in Advanced Developer
Mode with simple set window.
> [EGD-7922] Input events debuging

- test/pytest/test_device_diagnostics.py
Moved test script out of pytest/service-desktop
Cleaned up and fixed test code for multiple log/crash dump files
> [CP-831] Move and repair test_device_diagnostics.py

- test/pytest/service-desktop/test_device_diagnostics.py
Reverts mudita/MuditaOS#3373 - merged accidentally using auto-merge.
> Revert "[CP-831] Move and repair test_device_diagnostics.py"

- module-apps/apps-common/widgets/BellSideListItem.cpp
- module-apps/apps-common/widgets/BellSideListItem.hpp
Set BellSideListItem font sizez according to the design
> [BH-1218] fix ui font size

- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
Prevent meditation app from spawning multiple instances
> [BH-1251] Fix meditation app respawning

- products/BellHybrid/apps/application-bell-main/widgets/BellBattery.cpp
- products/BellHybrid/apps/application-bell-main/widgets/BellBattery.hpp
Battery icon aligned to the middle of screen
> [BH-1283] Battery icon alignment

- products/BellHybrid/apps/common/src/popups/AlarmActivatedWindow.cpp
Alarm Activated should not return to Alarm Set
> [BH-1252] Alarm Activated Behaviour Change

- module-apps/application-settings/windows/advanced/CPUModeTestWindow.cpp
- module-bsp/board/rt1051/bsp/eink_frontlight/eink_frontlight.cpp
- module-bsp/board/rt1051/bsp/vibrator/vibrator.cpp
- module-bsp/board/rt1051/drivers/RT1051DriverPWM.cpp
- module-bsp/board/rt1051/drivers/RT1051DriverPWM.hpp
- module-bsp/bsp/common.hpp
- module-bsp/drivers/pwm/DriverPWM.hpp
Fixed CPU frequency conversion.
> [EGD-8079] CPU frequency conversion PWM fix

- image/user/db/settings_v2_002-devel.sql
- image/user/db/settings_v2_002.sql
- module-apps/application-settings/ApplicationSettings.cpp
- module-apps/application-settings/CMakeLists.txt
- module-apps/application-settings/data/WallpaperOption.hpp
- module-apps/application-settings/include/application-settings/ApplicationSettings.hpp
- module-apps/application-settings/models/display-keypad/WallpaperOptionModel.cpp
- module-apps/application-settings/models/display-keypad/WallpaperOptionModel.hpp
- module-apps/application-settings/windows/display-keypad/DisplayAndKeypadWindow.cpp
- module-apps/application-settings/windows/display-keypad/WallpaperWindow.cpp
- module-apps/application-settings/windows/display-keypad/WallpaperWindow.hpp
- module-services/service-db/agents/settings/SystemSettings.hpp
Added connection of wallpaper window to settings
> [EGD-8083] Add wallpaper option

- module-audio/Audio/AudioDevice.hpp
- module-audio/board/linux/LinuxAudioDevice.cpp
- module-audio/board/rt1051/SAIAudioDevice.cpp
- module-audio/board/rt1051/SAIAudioDevice.hpp
- module-audio/board/rt1051/bellpx/BellPxAudioCodec.cpp
- module-audio/board/rt1051/bellpx/BellPxAudioCodec.hpp
- module-audio/board/rt1051/puretx/PureTxAudioCodec.cpp
- module-bsp/board/rt1051/bellpx/audio.cpp
- module-bsp/board/rt1051/bellpx/board/clock_config.h
- module-bsp/board/rt1051/bellpx/bsp/audio/CodecAW8898.cpp
- module-bsp/board/rt1051/bellpx/clock_config.cpp
- module-bsp/board/rt1051/common/audio.hpp
- module-bsp/board/rt1051/drivers/RT1051DriverPLL.cpp
- module-bsp/board/rt1051/puretx/audio.cpp
- module-bsp/board/rt1051/puretx/board/clock_config.h
- module-bsp/board/rt1051/puretx/clock_config.cpp
- module-bsp/drivers/pll/DriverPLL.cpp
- module-bsp/drivers/pll/DriverPLL.hpp
Added 44.1/48kHz sample rate support.
[BH-1281] Software volume scaling.
[BH-1287] Update audio sample tag.
[BH-1286] Copy typo fix.
[BH-1281]: https://appnroll.atlassian.net/browse/BH-1281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1287]: https://appnroll.atlassian.net/browse/BH-1287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BH-1286]: https://appnroll.atlassian.net/browse/BH-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BH-1175] Various sample rates support

- image/assets/lang/English.json
Implemented minor requests from design team.
> [BH-1286] Turn off question

- image/user/db/settings_bell_002.sql
Alarm Tone Morning Dew, updated mp3 file
> [BH-1290] Main Alarm Tone Update

- .gitmodules
- third-party/CMakeLists.txt
- third-party/dr_libs/CMakeLists.txt
It adds dr_libs as third party subrepo.
> [EGD-8075] Add dr_libs as subrepo

- module-audio/Audio/decoder/DecoderWorker.hpp
- module-audio/Audio/decoder/decoderWAV.cpp
- module-audio/Audio/decoder/decoderWAV.hpp
- module-audio/CMakeLists.txt
- third-party/CMakeLists.txt
Replace plain straigh waw decoder by the dr_wav library
> [EGD-8076] Replace wav decoder by dr_wav

- products/BellHybrid/apps/application-bell-meditation-timer/ApplicationBellMeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/CMakeLists.txt
- products/BellHybrid/apps/application-bell-meditation-timer/include/application-bell-meditation-timer/ApplicationBellMeditationTimer.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-powernap/ApplicationBellPowerNap.cpp
- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.hpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/data/StyleCommon.hpp
- products/BellHybrid/apps/common/include/common/windows/SessionPausedWindow.hpp
- products/BellHybrid/apps/common/src/windows/SessionPausedWindow.cpp
Pause functionality in PowerNap app
> [BH-1177] PowerNap Pause

- image/user/db/multimedia_001.sql
> [BH-1294] Missing multimedia db

- module-apps/application-messages/widgets/SMSInputWidget.cpp
- module-gui/gui/widgets/text/Text.cpp
- module-gui/gui/widgets/text/Text.hpp
> [EGD-3363] Added color setter to Text

- image/assets/lang/Deutsch.json
- image/assets/lang/English.json
- image/assets/lang/Español.json
- image/assets/lang/Français.json
- image/assets/lang/Polski.json
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapSessionEndedWindow.cpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapSessionEndedWindow.hpp
> [BH-1293] Update PowerNap screen

- products/BellHybrid/CMakeLists.txt
Temperature is displayed on Home Screen
> [BH-1289] Restore Temperature Reading

- module-apps/application-phonebook/models/NewContactModel.cpp
- module-apps/application-phonebook/models/NewContactModel.hpp
- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
Adding and immediate removal of a contact made it possible
to edit a contact that no longer existed.
> [EGD-7920] Fix GUI in adding / removing contacts

- module-gui/gui/widgets/text/CMakeLists.txt
- module-gui/gui/widgets/text/Text.cpp
- module-gui/gui/widgets/text/Text.hpp
- module-gui/gui/widgets/text/TextFixedSize.cpp
- module-gui/gui/widgets/text/core/cursors/TextCursor.cpp
- module-gui/gui/widgets/text/core/cursors/TextCursor.hpp
- module-gui/gui/widgets/text/core/cursors/TextLineCursor.cpp
- module-gui/gui/widgets/text/core/cursors/TextLineCursor.hpp
- module-gui/gui/widgets/text/core/lines/Lines.cpp
- module-gui/gui/widgets/text/core/lines/Lines.hpp
- module-gui/gui/widgets/text/core/lines/MultiTextLine.cpp
- module-gui/gui/widgets/text/core/lines/MultiTextLine.hpp
- module-gui/gui/widgets/text/core/lines/ScopedParentDisown.hpp
- module-gui/gui/widgets/text/core/lines/TextLine.cpp
- module-gui/gui/widgets/text/core/lines/TextLine.hpp
- module-gui/test/test-catch-text/CMakeLists.txt
- module-gui/test/test-catch-text/test-gui-MultiTextLine.cpp
- module-gui/test/test-catch-text/test-gui-TextLineCursor.cpp
TextLine split and cleanup to support SingleLine text.
> [EGD-7979] TextLine split and cleanup to support SingleLine text

- image/assets/lang/Deutsch.json
- image/assets/lang/English.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
- products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/IntervalChimePresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationTimerPresenter.cpp
Removed duplicate text, fixed counting conjugations
> [BH-1305] Meditation Screens Language Fixes

- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingLanguageWindow.cpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingLanguageWindow.hpp
Tips are displayed in selected (focused) language
> [BH-1285] Onboarding tips language

- module-apps/application-alarm-clock/models/NewEditAlarmModel.cpp
- module-apps/application-alarm-clock/models/NewEditAlarmModel.hpp
- module-apps/application-alarm-clock/presenter/AlarmClockEditWindowPresenter.cpp
- module-apps/application-alarm-clock/presenter/AlarmClockEditWindowPresenter.hpp
- module-apps/application-alarm-clock/windows/NewEditAlarmWindow.cpp
- module-apps/application-alarm-clock/windows/NewEditAlarmWindow.hpp
- module-apps/application-phonebook/models/NewContactModel.cpp
- module-apps/application-phonebook/models/NewContactModel.hpp
- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
- module-apps/application-phonebook/windows/PhonebookNewContact.hpp
- module-apps/application-settings/models/apps/SoundsModel.cpp
- module-apps/application-settings/windows/apps/SoundSelectWindow.cpp
- module-apps/application-settings/windows/apps/SoundSelectWindow.hpp
Fixed return to home actions on phonebook, ringtone and alarm.
> [EGD-8104] Fixed return to home actions on phonebook, ringtone and alarm

- module-audio/Audio/decoder/DecoderWorker.cpp
- module-audio/Audio/decoder/decoderMP3.cpp
- module-audio/Audio/decoder/decoderMP3.hpp
Mp3 decoder replaced with dr_mp3.
> [EGD-8094] Change mp3 decoder replaced with dr_mp3

- module-audio/board/rt1051/bellpx/BellPxAudioCodec.cpp
> [BH-1331] Volume control fix

- module-services/service-time/AlarmOperations.hpp
- products/BellHybrid/alarms/BellAlarmHandler.cpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.hpp
- products/BellHybrid/services/time/AlarmOperations.cpp
- products/BellHybrid/services/time/include/time/AlarmOperations.hpp
Prewakeup frontlight when alarm light off
> [BH-1240] Prewakeup frontlight when alarm light off

- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
> [BH-1342] Snooze timer copy fix

- module-bsp/board/linux/board.cpp
- module-bsp/board/rt1051/bsp/lpm/RT1051LPM.cpp
- module-bsp/board/rt1051/common/board.cpp
- module-bsp/board/rt1051/common/startup_mimxrt1052.cpp
- module-bsp/bsp/bsp.hpp
- module-os/board/rt1051/_exit.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
Add support for Reboot and Power off for the
_platform_exit code.
Add _platform_exit mode handle
> [EGD-8131] Add Reboot/Poweroff for _platform_exit()

- module-audio/board/rt1051/bellpx/BellPxAudioCodec.cpp
- module-services/service-time/AlarmOperations.hpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/alarms/BellAlarmHandler.cpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.hpp
- products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsTimerSelectWindow.cpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
- products/BellHybrid/apps/application-bell-main/widgets/SnoozeTimer.cpp
- products/BellHybrid/apps/application-bell-main/widgets/SnoozeTimer.hpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.hpp
- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/application-bell-onboarding/include/application-bell-onboarding/ApplicationBellOnBoarding.hpp
- products/BellHybrid/services/time/AlarmOperations.cpp
- products/BellHybrid/services/time/include/time/AlarmOperations.hpp
Bell release : 1.4.0-rc5
Including all the bug fixes added to the stable since the last release. It does not contain new features from the stable branch.
* BH-1331
* BH-1339
* BH-1240
* BH-1342
* BH-1336
* Reverted BH-1289 -> Sadly we are not yet ready to deploy the temperature compensation feature.
> Bh 1344 rc5

- config/style_check_hook.sh
- products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/ApplicationBellSettings.hpp
Fix flat settings - rename main window
> [BH-1303] Fix flat settings

- module-apps/application-settings/windows/system/LanguagesWindow.cpp
- module-apps/application-settings/windows/system/LanguagesWindow.hpp
- module-utils/i18n/CMakeLists.txt
- module-utils/i18n/JSONLoader.hpp
- module-utils/i18n/Metadata.hpp
- module-utils/i18n/i18n.cpp
- module-utils/i18n/i18nImpl.hpp
- module-utils/i18n/include/i18n/i18n.hpp
- products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingLanguageWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingLanguageWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/presenter/LanguageWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/LanguageWindowPresenter.hpp
i18n correctly loads languages
with special characters.
> [BH-1332] i18n update

- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.hpp
Fixed settings being saved upon idle exit.
> BH-1234 Fix settings save upon idle exit

- test/pytest/service-desktop/test_security.py
Add security EP API to QAMuditaHarness repo.
Refactor security EP test to make it work.
> [CP-858] Fix test security

- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
- products/BellHybrid/apps/common/include/common/models/AbstractAlarmModel.hpp
- products/BellHybrid/apps/common/include/common/models/AlarmModel.hpp
- products/BellHybrid/apps/common/src/AlarmModel.cpp
> [BH-1353] Invalid snooze msg

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
Text duplications removed for rest of languages
> [BH-1354] Fix Text Duplications

- module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
- products/BellHybrid/apps/common/src/AlarmModel.cpp
- products/BellHybrid/services/evtmgr/EventManager.cpp
- products/BellHybrid/services/evtmgr/include/evtmgr/EventManager.hpp
Correct alarm-knob state on turnon
> [BH-1335] Correct alarm-knob state on turnon

- image/assets/lang/Espanol.json
Fix minute singular copy in Spanish
> [BH-1346] Fix minute singular copy in Spanish

- module-apps/application-desktop/ApplicationDesktop.cpp
> [EGD-8101] Removed not sent action requestf for battery charging

- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
Fixed answering the call via Pure when connecting to the BT device
> [EGD-8005] Fixed constant ringing in HFP after call answer

- cmake/modules/AddPackage.cmake
As in description - changed tar compression to multithreaded one
> [EGD-8032] Changed image compression to multithreaded one

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp
- module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.hpp
Added 4 hour deep refresh on locked screen.
> [EGD-8080] Added 4 hour deep refresh on locked screen

- module-audio/Audio/Profiles/ProfileRoutingEarspeaker.hpp
Changed the earspeaker EQ according to the poll
> [EGD-8159] Change earspeaker EQ

- module-apps/apps-common/popups/AlarmPopup.cpp
- module-apps/apps-common/popups/presenter/AlarmPresenter.cpp
- module-apps/apps-common/popups/presenter/AlarmPresenter.hpp
Now user cant close alarm window with LF
> [EGD-8108] Alarm window bugfix

- module-os/FreeRTOS/include/FreeRTOSConfig.h
- module-os/board/rt1051/systemview/FreeRTOSConfig.h
- module-sys/SystemWatchdog/SystemWatchdog.cpp
- module-sys/SystemWatchdog/include/SystemWatchdog/SystemWatchdog.hpp
- products/BellHybrid/BellHybridMain.cpp
- products/PurePhone/PurePhoneMain.cpp
Made sure that watchdog thread is properly closed while exiting OS.
> [EGD-8154] Added watchdog thread closure on system exit

- test/pytest/service-desktop/test_messages.py
- test/pytest/service-desktop/test_send_sms.py
Refactored sms part of messages endpoint tests.
Rewritten with use of messages EP API from harness.
> [CP-857] Refactor test_messages.py and test_send_sms.py

- module-bsp/board/rt1051/bellpx/bsp/fuel_gauge/fuel_gauge.cpp
Apply fuel gauge configuration instead of poweroff at the end
> [BH-1376] Fuel gauge configuration apply

- module-services/service-evtmgr/screen-light-control/ControlFunctions.cpp
- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/models/FrontlightModel.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/FrontlightPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/FrontlightPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsFrontlightWindow.cpp
- products/BellHybrid/apps/common/include/common/models/FrontlightModel.hpp
Fix frontlight idle exit
The frontlight value will be reverted
> [BH-1343] Fix frontlight idle exit

- module-apps/application-desktop/CMakeLists.txt
- module-apps/application-desktop/models/ActiveNotificationsListPresenter.cpp
- module-apps/application-desktop/models/ActiveNotificationsListPresenter.hpp
- module-apps/application-desktop/windows/DesktopMainWindow.cpp
- module-apps/application-desktop/windows/DesktopMainWindow.hpp
- module-apps/apps-common/CMakeLists.txt
- module-apps/apps-common/notifications/NotificationTilesBox.cpp
- module-apps/apps-common/notifications/NotificationTilesBox.hpp
- module-apps/apps-common/notifications/NotificationTilesPresenter.cpp
- module-apps/apps-common/notifications/NotificationTilesPresenter.hpp
- module-apps/apps-common/notifications/NotificationsListPresenter.cpp
- module-apps/apps-common/notifications/NotificationsListPresenter.hpp
- module-apps/apps-common/notifications/NotificationsModel.cpp
- module-apps/apps-common/notifications/NotificationsModel.hpp
- module-apps/apps-common/notifications/NotificationsPresenter.hpp
- module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp
- module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.hpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperBase.hpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperClock.cpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperClock.hpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperLogo.cpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperLogo.hpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperQuote.cpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperQuote.hpp
- module-apps/apps-common/popups/presenter/WallpaperPresenter.cpp
- module-apps/apps-common/popups/presenter/WallpaperPresenter.hpp
- module-gui/gui/widgets/Style.hpp
simplified home screen notifications as tiles on phone locked wallpaper
> [EGD-6824] Simplified notifications on quote wallpaper

- module-apps/application-alarm-clock/windows/AlarmClockMainWindow.cpp
- module-apps/application-calllog/windows/CallLogMainWindow.cpp
- module-apps/application-messages/windows/MessagesMainWindow.cpp
- module-apps/application-music-player/windows/MusicPlayerAllSongsWindow.cpp
- module-apps/application-notes/windows/NoteMainWindow.cpp
- module-apps/application-notes/windows/SearchResultsWindow.cpp
- module-apps/application-phonebook/windows/PhonebookContactDetails.cpp
- module-apps/application-phonebook/windows/PhonebookMainWindow.cpp
- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
- module-apps/application-phonebook/windows/PhonebookSearchResults.cpp
- module-apps/apps-common/InternalModel.hpp
- module-apps/apps-common/windows/OptionWindow.cpp
- module-gui/gui/widgets/ListView.cpp
- module-gui/gui/widgets/ListView.hpp
- module-gui/gui/widgets/ListViewEngine.cpp
- module-gui/gui/widgets/ListViewEngine.hpp
Fixed looped lists bugs and applied to all Pure lists.
> [EGD-8035] Fixed looped lists and applied to all Pure lists

- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
Fix extreme values arrows on snooze interval
> [BH-1243] Fix extreme values arrows on snooze interval

- module-apps/apps-common/popups/presenter/QuotesPresenter.cpp
- module-apps/apps-common/popups/presenter/QuotesPresenter.hpp
- module-services/service-db/CMakeLists.txt
- module-services/service-db/agents/quotes/QuotesAgent.cpp
- module-services/service-db/agents/quotes/QuotesAgent.hpp
- module-services/service-db/agents/quotes/QuotesSettingsSerializer.cpp
- module-services/service-db/agents/quotes/QuotesSettingsSerializer.hpp
- module-services/service-db/agents/quotes/RandomizedQuoteModel.cpp
- module-services/service-db/agents/quotes/RandomizedQuoteModel.hpp
- module-services/service-db/agents/settings/SystemSettings.hpp
- module-services/service-db/include/service-db/QuotesMessages.hpp
- module-services/service-db/include/service-db/Settings.hpp
- module-services/service-db/test/test-service-db-quotes.cpp
- module-services/service-db/test/test-service-db-quotes.hpp
- products/PurePhone/services/db/ServiceDB.cpp
Added randomization of the quotes when quote wallpaper is selected
> [EGD-6823] Add quote randomization

- test/pytest/service-desktop/test_device_info.py
Previously test was expecting to get any answer.
Now it is enhanced to check if returned values make any sense.
Additionally added test for checking log files location.
> [CP-850] Improve and update test device info

- module-apps/application-messages/widgets/SMSInputWidget.cpp
- module-gui/gui/widgets/text/Text.cpp
Fixed sms input cursor starting position to document end.
> [EGD-7056] Fixed sms input cursor starting position to document end

- .gdbinit-1051
- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/WindowsPopupQueue.cpp
- module-apps/apps-common/WindowsPopupQueue.hpp
- module-apps/tests/windows/test-WindowsPopupQueue.cpp
- module-gui/gui/SwitchData.hpp
On initial code there was option to store only one popup of set
priority, now we can store multiple ones
> [EGD-8164] Multiple same popups can be stored

- module-apps/application-call/ApplicationCall.cpp
There was bad translation name.
> [EGD-8161] Fix proper info on call with no sim

- products/BellHybrid/services/time/AlarmOperations.cpp
- products/BellHybrid/services/time/include/time/AlarmOperations.hpp
Restore snooze chime processing to alarm operations
> [BH-1365] Restore snooze chime processing to alarm operations

- module-bluetooth/Bluetooth/BluetoothWorker.cpp
- module-bluetooth/Bluetooth/BluetoothWorker.hpp
- module-services/service-bluetooth/ServiceBluetooth.cpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- module-services/service-time/ServiceTime.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
Release of resources and closing of all unfinished
services and workers.
> [EGD-8138] Software closing procedure improved

- test/pytest/service-desktop/test_calllog.py
- test/pytest/service-desktop/test_contacts.py
Refactor contacts EP test to make it work again.
Rewritten with use of contacts EP API moved to harness submodule.
> [CP-856] Refactor test contacts

- module-apps/application-call/ApplicationCall.cpp
Race condition workaround
[EGD-8166]
[EGD-8166]: https://appnroll.atlassian.net/browse/EGD-8166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EGD-8166] Private Number instead proper number shown on screen

- products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- products/BellHybrid/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
- products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- products/PurePhone/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
- Fixed size truncation to 32-bit value
- Calculating storage info from all partitions
- Code cleanup
> [CP-988] Fix reporting of storage size

- products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.hpp
> [BH-1381] Fix alarm settings regression

- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
- products/BellHybrid/apps/application-bell-main/widgets/SnoozeTimer.cpp
- products/BellHybrid/apps/application-bell-main/widgets/SnoozeTimer.hpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
- products/BellHybrid/apps/common/include/common/models/AbstractAlarmModel.hpp
- products/BellHybrid/apps/common/include/common/models/AlarmModel.hpp
- products/BellHybrid/apps/common/src/AlarmModel.cpp
Snooze length UI sync
Rounding up the snooze length
> [BH-1193] Snooze length UI sync

- module-apps/apps-common/notifications/NotificationsModel.cpp
- module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp
Paramter pointer was used without checking if it is nullptr
> [EGD-8167] Fix for crash on SOS screen

- module-cellular/at/Commands.hpp
- module-services/service-cellular/ServiceCellular.cpp
Added handling of errors in retrieving a message from the modem
> [EGD-6991] Message from the operator is not fully shown

- module-apps/application-alarm-clock/models/NewEditAlarmModel.cpp
- module-apps/application-alarm-clock/widgets/AlarmClockStyle.hpp
- module-apps/application-alarm-clock/widgets/AlarmOptionsItem.cpp
- module-apps/application-alarm-clock/widgets/AlarmOptionsItem.hpp
- module-apps/application-call/data/CallAppStyle.hpp
- module-apps/application-call/windows/NumberWindow.cpp
- module-apps/application-meditation/data/Style.hpp
- module-apps/application-meditation/widgets/IntervalBox.cpp
- module-apps/application-meditation/widgets/IntervalBox.hpp
- module-apps/application-meditation/windows/MeditationWindow.cpp
- module-apps/apps-common/CMakeLists.txt
- module-apps/apps-common/widgets/TextSpinnerBox.cpp
- module-apps/apps-common/widgets/TextSpinnerBoxWithLabel.cpp
- module-apps/apps-common/widgets/TextSpinnerBoxWithLabel.hpp
- module-apps/apps-common/widgets/spinners/GenericSpinner.hpp
- module-apps/apps-common/widgets/spinners/SpinnerPolicies.hpp
Meditation timer interval widget replacement.
> [EGD-7792] Meditation timer interval widget replacement

- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
- module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
- module-sys/common/include/system/Common.hpp
Made sure all services are deinitialized properly
> [EGD-8193] Proper system shutdown durign update

- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
- module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
- module-sys/common/include/system/Common.hpp
Revert commit for system close
> Revert "[EGD-8193] Proper system shutdown durign update"

- module-bsp/board/linux/magnetometer/magnetometer.cpp
- module-bsp/board/rt1051/bsp/magnetometer/magnetometer.cpp
- module-bsp/bsp/magnetometer/magnetometer.hpp
- products/PurePhone/services/evtmgr/WorkerEvent.cpp
We stop reading from the magnetometer
during the system shutdown procedure
> [EGD-8191] Magnetometer deinitialisation

- module-bsp/board/rt1051/bsp/cellular/rt1051_cellular.cpp
- module-cellular/modem/ATParser.cpp
- module-cellular/modem/ATParser.hpp
- module-cellular/modem/BaseChannel.hpp
- module-cellular/modem/mux/CellularMux.cpp
- module-cellular/modem/mux/DLCChannel.cpp
- module-cellular/modem/mux/DLCChannel.h
- module-cellular/test/mock/AtCommon_channel.hpp
Fix DMA issue on tx modem data.
> [EGD-7956] Fix DMA issue on tx modem data

- module-bsp/board/rt1051/bellpx/bsp/switches/switches.cpp
Lightclick suppression on deepress
> [BH-1386] Lightclick suppression on deepress

- module-bsp/board/rt1051/bsp/cellular/rt1051_cellular.cpp
- module-cellular/modem/ATParser.cpp
- module-cellular/modem/ATParser.hpp
- module-cellular/modem/BaseChannel.hpp
- module-cellular/modem/mux/CellularMux.cpp
- module-cellular/modem/mux/DLCChannel.cpp
- module-cellular/modem/mux/DLCChannel.h
- module-cellular/test/mock/AtCommon_channel.hpp
This reverts commit 7d8fbec207a517755fbd8193e2584a6233697d27.
> [EGD-7956] Revert Fix DMA issue on tx modem data

- image/assets/lang/Deutsch.json
- image/assets/lang/English.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
- image/assets/lang/Svenska.json
- module-apps/application-messages/windows/NewMessage.cpp
- module-apps/application-messages/windows/NewMessage.hpp
- module-apps/application-phonebook/ApplicationPhonebook.cpp
- module-apps/application-phonebook/CMakeLists.txt
- module-apps/application-phonebook/data/PhonebookItemData.hpp
- module-apps/application-phonebook/data/PhonebookStyle.hpp
- module-apps/application-phonebook/include/application-phonebook/ApplicationPhonebook.hpp
- module-apps/application-phonebook/models/MultipleNumbersModel.cpp
- module-apps/application-phonebook/models/MultipleNumbersModel.hpp
- module-apps/application-phonebook/models/PhonebookModel.cpp
- module-apps/application-phonebook/models/PhonebookModel.hpp
- module-apps/application-phonebook/widgets/MultipleNumbersWidget.cpp
- module-apps/application-phonebook/widgets/MultipleNumbersWidget.hpp
- module-apps/application-phonebook/windows/PhonebookMainWindow.cpp
- module-apps/application-phonebook/windows/PhonebookMultipleNumbersSelect.cpp
- module-apps/application-phonebook/windows/PhonebookMultipleNumbersSelect.hpp
- module-apps/application-phonebook/windows/PhonebookSearchResults.cpp
Added Phonebook multiple number selector.
> [EGD-7420] Phonebook multiple numbers selector

- products/BellHybrid/BinaryAssetsVersions.cmake
Updates bootloader version to one with fixes for BH-1398 & BH-1312.
> [BH-1398] Fix boot welcome screen

- module-cellular/CMakeLists.txt
- module-cellular/at/cmd/CSQ.hpp
- module-cellular/at/cmd/src/CSQ.cpp
- module-cellular/test/mock/AtCommon_channel.hpp
- module-cellular/test/unittest_parse_result.cpp
- module-services/service-cellular/CMakeLists.txt
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/service-cellular/CellularMessage.hpp
- module-services/service-cellular/service-cellular/ServiceCellular.hpp
- module-services/service-cellular/src/CSQHandler.cpp
- module-services/service-cellular/src/CSQHandler.hpp
- module-services/service-cellular/src/ServiceCellularPriv.cpp
- module-services/service-cellular/src/ServiceCellularPriv.hpp
- module-services/service-cellular/src/URCCounter.cpp
- module-services/service-cellular/src/URCCounter.hpp
Added CSQ notifications counter and CSQ poll mode.
It will help to reduce current cosnuption in case of
variable signal.
> [EGD-8203] Add URC counter and csq poll mode

- module-services/service-db/test/test-service-db-quotes.cpp
simple fix for randomly failing unittests
> [EGD-8246] Fix of quotes unit tests

- module-apps/application-settings/models/display-keypad/QuotesModel.cpp
- module-apps/application-settings/windows/display-keypad/QuotesAddWindow.cpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperQuote.cpp
- module-apps/apps-common/popups/lock-popups/phone-lock-wallpapers/WallpaperQuote.hpp
fix for invalid window transitions, list update and quote display on wallpaper
> [EGD-8247][EGD-8249][EGD-8250] Fix of Quotes UI minor bugs

- products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/windows/BellSettingsTimeUnitsWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/AboutYourBellWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/AboutYourBellWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsBedtimeToneWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsBedtimeToneWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsFrontlightWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsFrontlightWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsLanguageWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsLanguageWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsTimeUnitsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsSnoozeWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsSnoozeWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsPrewakeUpWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsPrewakeUpWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/bedtime_settings/BellSettingsBedtimeToneSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/bedtime_settings/BellSettingsBedtimeToneSettingsWindow.hpp
Language change will not play alarm sound anymore
> [BH-1391] Language change sound

- module-apps/application-phonebook/windows/PhonebookMultipleNumbersSelect.cpp
- module-apps/apps-common/popups/lock-popups/PhoneLockedWindow.cpp
PhoneLock timer fix on return from emergency.
> [EGD-8218] PhoneLock timer fix on return from emergency

- module-services/service-db/agents/quotes/RandomizedQuoteModel.cpp
- module-services/service-db/test/test-service-db-quotes.cpp
fixed crash when quotes set is empty at first quotes selection
> [EGD-8256] Fix crash on quotes with empty database

- tools/macflash.sh
- tools/macflash_setup.sh
Added macflash.sh and macflash_setup.sh scripts
> [CP-1005] Macflash tool to flash Pure on macOS

- tools/check_commit_messages.py
Added new project to the check
> [MOS-154] Update commit message check

- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
Updates main clock time when alarm is ringing from another application
> [BH-1403] Alarm ringing clock fix

- module-gui/gui/widgets/SideListView.cpp
- module-gui/gui/widgets/SideListView.hpp
- module-gui/gui/widgets/Style.hpp
Remove dead code from SideListView
> [BH-655] SideListView - Remove dead code

- module-utils/utility/Utils.cpp
- module-utils/utility/Utils.hpp
- module-utils/utility/tests/unittest_utils.cpp
Allocating large objects on heap
Moved out generateRandomId() to utils namespace
> [CP-1073] Stack overflow in utils::filesystem::generateRandomId

- test/pytest/service-desktop/test_device_info.py
Fixed regexp’s for gitVersion, serialNumer.
Fixed invalid escape sequence in regexp.
> [CP-1072] Fix issues in harness test for DeviceInfo

- module-bsp/board/rt1051/puretx/bsp/lpm/PowerProfile.cpp
- module-sys/SystemManager/PowerManager.cpp
Add minimal frequency ~4Mhz, more aggressive CPU freq
optimizations
> [MOS-114] CPU frequency scalling improvements

- module-sys/SystemManager/PowerManager.cpp
Skip 12MHz freq level in the scaller
> [MOS-114] Frequency scalling skip 12MHz Level

- cmake/modules/ProjectConfig.cmake
- module-bsp/board/rt1051/puretx/CMakeLists.txt
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.hpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/CurrentMeasurementScope.cpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/CurrentMeasurementScope.hpp
- tools/plot_current_measurement.py
- tools/requirements.txt
added current measurement transfer over logs to plot it on PC side
> [MOS-109] Add current measurement scope

- module-apps/application-desktop/ApplicationDesktop.cpp
- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- module-apps/apps-common/messages/AppMessage.hpp
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
Rework last render before shutdown to avoid races
Display low battery screen on exit
> [BH-1385] Low battery screen on exit

- module-apps/apps-common/popups/lock-popups/PhoneLockedInfoWindow.cpp
extened timeout for better readbility
> [MOS-224] Fix phone lock window timeout

- module-services/service-db/DBServiceAPI.cpp
fixed call when making first call from unknown number when Pure is in DnD mode
> [MOS-227] Fix DnD first call crash

- test/pytest/service-desktop/test_outbox.py
Needed to verify if the Outbox endpoint API works correctly
> [CP-1037] Add test for Outbox EP API

- module-services/service-desktop/CMakeLists.txt
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
- module-services/service-desktop/endpoints/include/endpoints/EndpointType.hpp
- module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
- module-services/service-desktop/include/service-desktop/Outbox.hpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- module-services/service-desktop/parser/MessageHandler.cpp
- module-services/service-desktop/parser/MessageHandler.hpp
- products/PurePhone/services/desktop/endpoints/CMakeLists.txt
- products/PurePhone/services/desktop/endpoints/EndpointFactoryPure.cpp
- products/PurePhone/services/desktop/endpoints/include/endpoints/outbox/OutboxEndpoint.hpp
- products/PurePhone/services/desktop/endpoints/include/endpoints/outbox/OutboxHelper.hpp
- products/PurePhone/services/desktop/endpoints/outbox/OutboxEndpoint.cpp
- products/PurePhone/services/desktop/endpoints/outbox/OutboxHelper.cpp
Outbox endpoint will be used to provide notifications
about changes in messages/threads/calls during connection
with Mudita Center. This mechanism will ensure an efficient
data synchronization between Mudita Pure and Mudita Center.
> [CP-1033] Add Outbox endpoint to service-desktop

- image/assets/lang/English.json
- image/user/db/settings_bell_002.sql
- module-apps/apps-common/CMakeLists.txt
- module-apps/apps-common/widgets/spinners/ItemSpinner.hpp
- module-apps/apps-common/widgets/spinners/SpinnerPolicies.hpp
- module-apps/apps-common/widgets/spinners/Spinners.hpp
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
- products/BellHybrid/apps/application-bell-settings/CMakeLists.txt
- products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/ApplicationBellSettings.hpp
- products/BellHybrid/apps/application-bell-settings/models/LayoutModel.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/LayoutWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/LayoutWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsLayoutWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsLayoutWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsWindow.cpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/models/LayoutModel.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayouts.cpp
- products/BellHybrid/services/db/include/db/SystemSettings.hpp
Functionality for switching the selected layout from Application Settings.
Solves [BH-1318] and all sub-tasks associated 
[BH-1318]: https://appnroll.atlassian.net/browse/BH-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BH-1314] Switch Layout from Settings

- module-gui/gui/input/Translator.cpp
- module-gui/gui/input/Translator.hpp
- module-gui/gui/widgets/text/Text.cpp
Text Abc mode keypress rotation fix.
> [MOS-152] Text Abc mode keypress rotation fix

- module-apps/application-phonebook/widgets/PhonebookItem.cpp
- module-db/Tables/ContactsTable.cpp
If a contact contains only first name I would expect it to appear on the
list sorted alphabetically according to the letters.
> [MOS-85] Fix contact that has no Last name

- module-apps/application-messages/windows/MessagesMainWindow.cpp
- module-apps/application-messages/windows/SMSThreadViewWindow.cpp
- module-apps/apps-common/notifications/NotificationProvider.cpp
- module-db/CMakeLists.txt
- module-db/Interface/NotificationsRecord.cpp
- module-db/Interface/NotificationsRecord.hpp
- module-db/queries/notifications/QueryNotificationsDecrement.cpp
- module-db/queries/notifications/QueryNotificationsDecrement.hpp
- module-db/tests/NotificationsRecord_tests.cpp
Refactored handling of notifications on home/lock creen
> [MOS-143] Fix notifications for unread message/missed calls

- products/BellHybrid/apps/common/include/common/widgets/BellBattery.hpp
- products/BellHybrid/apps/common/src/widgets/BellBattery.cpp
Two elements in statusbox are properly aligned
> [BH-1404] Aligment of two elements

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-sys/common/include/system/Common.hpp
Added missing refresh conditions.
> [MOS-111] Added missing refresh conditions

- products/BellHybrid/services/audio/ServiceAudio.cpp
Change default alarm volume to 7.
> [BH-1413] Change default alarm volume

- module-gui/gui/widgets/text/core/cursors/TextBlockCursor.cpp
- module-gui/gui/widgets/text/core/cursors/TextBlockCursor.hpp
- module-gui/test/test-catch-text/test-gui-TextBlockCursor.cpp
Added "!?" into sentence detection signs.
> [MOS-152] Added "!?" into sentence detection signs

- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsLayoutWindow.cpp
- products/BellHybrid/apps/common/include/common/widgets/BellBattery.hpp
Layout selection widget now has arrows shifted for better visibility
> [BH-1411] Shift arrows on layout selection

- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
This is a fix for changes made in PR#3451 which disabled turning on of Frontlight after Powernap finished
> [BH-1246] PowerNap Frontlight fix

- module-apps/apps-common/widgets/TimeSetFmtSpinner.cpp
- module-gui/gui/widgets/text/Label.cpp
- module-gui/gui/widgets/text/Text.cpp
- module-gui/gui/widgets/text/TextConstants.hpp
Added print text edit type for label purposes.
> [MOS-250] Added print text edit type for label purposes

- products/PurePhone/BinaryAssetsVersions.cmake
> [CP-1100] Fix update not working

- image/user/db/settings_bell_002.sql
- products/BellHybrid/alarms/src/actions/PlayAudioActions.cpp
- products/BellHybrid/alarms/src/actions/PlayAudioActions.hpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
Fixed issues with managing main alarm duration
> [BH-1408] Main alarm stops

- module-apps/application-phonebook/widgets/PhonebookItem.cpp
- module-apps/application-phonebook/widgets/PhonebookItem.hpp
The font was bold, which was inconsistent with the designs.
https://projects.invisionapp.com/d/main?origin=v7#/console/18241335/381446305/preview?scrollOffset=8749
Before:
After:
> [MOS-16] Change favourite contacts font to regular

- module-apps/application-music-player/presenters/SongsPresenter.cpp
Unsupported files prevent switching to the
next / last track
> [MOS-24] Fix music player switch to the next track

- test/get_os_log.py
- test/pytest/conftest.py
Added detection of Mudita Harmony
> [MOS-273] Update Harness to detect Mudita Bell devices

- module-bsp/board/linux/torch/torch.cpp
- module-bsp/board/rt1051/bsp/torch/torch.cpp
- module-bsp/bsp/torch/torch.hpp
- module-services/service-evtmgr/api/torch.cpp
- products/PurePhone/services/evtmgr/EventManager.cpp
We save on power consumption ~0.7 mA.
> [MOS-256] Turn off torch driver when not in use

- module-apps/application-phonebook/models/NewContactModel.cpp
- module-apps/application-phonebook/models/NewContactModel.hpp
- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
Fixed edit contact window erasing data on special character select.
> [MOS-89] Fixed edit contact window erasing data on special character select

- module-bluetooth/Bluetooth/interface/profiles/A2DP/AVRCP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.cpp
Bluetooth stack updated from 1.4.1 to 1.5.1.
> [MOS-231] Updated bt stack

- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/application-bell-onboarding/include/application-bell-onboarding/BellOnBoardingNames.hpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingOnOffWindow.cpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingOnOffWindow.hpp
Delete unused window name and simplify flows
> [BH-1407] Onboarding windows cleanup

- module-bluetooth/Bluetooth/interface/profiles/A2DP/A2DP.cpp
- module-services/service-audio/AudioServiceAPI.cpp
- module-services/service-cellular/NetworkSettings.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsModel.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpSettingsModel.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeSettingsModel.cpp
- products/BellHybrid/apps/common/src/models/BedtimeModel.cpp
Remove unused variables from PVS Studio analysis
> [MOS-300] Remove unused variables

- .github/pull_request_template.md
- README.md
- doc/README.md
- doc/build_targets.md
- doc/development_workflow.md
- doc/download_assets.md
- doc/generate_doxygen.md
- doc/quickstart.md
- doc/running_on_phone.md
- products/PurePhone/ProductKeyFeatures.md
- test/README.md
Now our basic documentation should be clearer and more self-explanatory
closes: https://github.com/mudita/MuditaOS/issues/3570
> [MOS-281] Base documentation update

- module-sys/SystemManager/SystemManagerCommon.cpp
Restored Eink service to Restore whitelist
> [CP-1119] Fix Restore failure

- module-apps/apps-common/popups/BluetoothAuthenticatePopup.cpp
There should be select instead of confirm
- [ x] Complies with our guidelines for contributions
- [x ] Has unit tests if possible.
> [MOS-124] Fix navbar text

- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- module-services/service-evtmgr/EventManager.cpp
Turn off USB device drivers when the usb cable
is disconnected.
> [MOS-257] Turn off USB drivers when usb is disconnected

- module-apps/application-messages/windows/NewMessage.cpp
- module-apps/application-messages/windows/SMSThreadViewWindow.cpp
Fix edit message regression functionality in the drafts
> [MOS-98] Fix message regression functionality in drafts

- module-services/service-bluetooth/ServiceBluetooth.cpp
Fix bluetooth auto turn off disconnecting connected device after audio being played.
> [MOS-291] Fix bluetooth auto turnoff

- image/user/db/predefined_quotes_002.sql
Fixes too long copies in quotes categories.
> [MOS-153] Fix quotes too long copies

- module-services/service-cellular/call/CellularCall.cpp
- module-services/service-cellular/service-cellular/call/CellularCall.hpp
Partial fix of the reported problem. 
Fixes tempalate window being closed during call. 
Other part (user staying on template window after caller hang up, will be fixed in another PR.
> [MOS-276] Fix exiting from template

- cmake/modules/AddPackage.cmake
- doc/build_targets.md
Rename json-target to match recent changes
> [MOS-288] Fix upgrade packages build

- module-audio/Audio/Profiles/README.md
Fix of the gain parameter range
> [MOS-303] Documentation fix

- module-utils/unicode/utf8/test/unittest_utf8.cpp
- module-utils/unicode/utf8/utf8/UTF8.cpp
- module-utils/unicode/utf8/utf8/UTF8.hpp
Added UT case for failing phone number
Fixed decimal semi-octet decoding (AKA ascii combination)
> [MOS-45] Invalid number decoding

- tools/generate_image.sh
Added PART3_SIZE parameter to generation of user partition
Please describe your pull request
> [MOS-342] Fix warning in disk image build

- module-apps/CMakeLists.txt
- module-apps/ModuleApps.md
- module-apps/application-test/ApplicationTest.cpp
- module-apps/application-test/ApplicationTest.md
- module-apps/application-test/CMakeLists.txt
- module-apps/application-test/include/application-test/ApplicationTest.hpp
- module-apps/application-test/presenters/TestPresenter.cpp
- module-apps/application-test/presenters/TestPresenter.hpp
- module-apps/application-test/windows/LocalStyle.hpp
- module-apps/application-test/windows/TestPopup.cpp
- module-apps/application-test/windows/TestPopup.hpp
- module-apps/application-test/windows/TestWindow.cpp
- module-apps/application-test/windows/TestWindow.hpp
- module-apps/apps-common/popups/Popups.cpp
- module-apps/apps-common/popups/Popups.hpp
- module-services/ModuleServices.md
- module-services/service-test/ServiceTest.cpp
- module-services/service-test/include/service-test/ServiceTest.hpp
- module-sys/README.md
- module-sys/SystemManager/doc/ServicesSynchronization.md
- module-utils/log/api/log/debug.hpp
- products/PurePhone/CMakeLists.txt
- products/PurePhone/PurePhoneMain.cpp
A working example of application and service ready to copy from
with minimum documentation
> [MOS-307] Application and Service example and docs

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Svenska.json
Added missing translations for edit quotes label.
> [MOS-336] Add missing translation

- module-apps/application-calendar/include/application-calendar/data/CalendarData.hpp
- module-apps/application-calllog/windows/CallLogDetailsWindow.cpp
- module-apps/application-settings/windows/OptionsWidgetMaker.cpp
- module-apps/application-settings/windows/OptionsWidgetMaker.hpp
- module-apps/application-settings/windows/advanced/ColorTestWindow.cpp
- module-apps/application-settings/windows/bluetooth/PhoneNameWindow.cpp
- module-apps/apps-common/notifications/NotificationProvider.cpp
- module-apps/apps-common/popups/presenter/AlarmPresenter.cpp
- module-apps/apps-common/widgets/ButtonOnOff.cpp
- module-audio/Audio/equalizer/Equalizer.cpp
- module-audio/Audio/test/unittest_equalizer.cpp
- module-bluetooth/Bluetooth/Device.cpp
- module-bluetooth/Bluetooth/Device.hpp
- module-cellular/modem/ATStream.cpp
- module-gui/gui/widgets/BoxLayoutSizeStore.cpp
- module-gui/gui/widgets/text/core/TextDocument.cpp
- module-gui/gui/widgets/text/core/cursors/TextBlockCursor.cpp
- module-gui/gui/widgets/text/parsers/RichTextParser.cpp
- module-vfs/drivers/src/purefs/fs/filesystem_vfat.cpp
- products/BellHybrid/BellHybridMain.cpp
- products/BellHybrid/apps/common/include/common/options/OptionBellMenu.hpp
- products/BellHybrid/apps/common/src/AudioModel.cpp
- products/BellHybrid/services/audio/ServiceAudio.cpp
Fixes to major part of issues found
by PVS Studio static analysis
mainly micro-optimisations.
> [MOS-240] PVS Studio analysis bugs fix

- module-audio/Audio/Operation/PlaybackOperation.cpp
Fix of the audio playback bug, which
prevented playback resuming after
unplugging the headset when playback
was paused.
> [MOS-331] Fix audio resuming after headset unplugging

- module-db/Database/Database.cpp
This is a workaround for issue with loading databases after update through updater app (Mudita Center).
Currently, updater moves .sql files into wrong directory (1/current/user/db rather than 3/user/db).
To support such case, unfortunately we have to check both directory. To properly fix this issue,
a patch for updater is needed, however it cannot be released with package consisting db changes. 
It will need to be released after coming 1.2.0 version. A followup task will be created immediately.  
> [MOS-351] Fix DB load after update

- doc/fonts.md
- module-gui/gui/core/Font.cpp
- module-gui/gui/core/FontManager.cpp
- module-gui/gui/core/FontManager.hpp
- products/BellHybrid/CMakeLists.txt
- products/PurePhone/CMakeLists.txt
> [MOS-288] Split default and fallback fonts to separate entries

- module-sys/Service/include/Service/ServiceCreator.hpp
- products/BellHybrid/BellHybridMain.cpp
> [BH-1438] Bell crash during start

- products/BellHybrid/assets/assets_common.json
> [BH-1440] ServiceDesktop crash during startup

- module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
Increasing the stack for battery charger worker
> [MOS-360] Fix battery charger stack overflow

- module-services/service-desktop/BackupRestore.cpp
- module-services/service-desktop/include/service-desktop/BackupRestore.hpp
Fix restore not working after adding predefined_quotes database.
> [CP-1147] Fix restore not working

- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/data/Contract.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationCommon.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/include/application-bell-meditation-timer/MeditationTimer.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/models/ChimeVolume.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/models/ChimeVolume.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/StatisticsPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/StatisticsPresenter.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/SettingsWindow.cpp
- products/BellHybrid/apps/common/include/common/models/AbstractAudioModel.hpp
- products/BellHybrid/apps/common/src/AudioModel.cpp
Chime Volume Model implementation
Implementation of [BH-1433] functionality 
[BH-1433]: https://appnroll.atlassian.net/browse/BH-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BH-1433] Meditation Timer Gong Volume

- module-gui/gui/widgets/Style.hpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsLayoutWindow.cpp
- products/BellHybrid/apps/common/include/common/widgets/LayoutVertical.hpp
- products/BellHybrid/apps/common/include/common/widgets/TimeSetSpinnerVertical.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVerticalWithAmPm.cpp
- products/BellHybrid/apps/common/src/widgets/LayoutVertical.cpp
- products/BellHybrid/assets/assets_community.json
- products/BellHybrid/assets/assets_proprietary.json
Layouts settings arrows adjustment
> [BH-1411] Layouts settings arrows adjustment

- module-bsp/board/rt1051/bellpx/CMakeLists.txt
- module-bsp/board/rt1051/bellpx/bsp/rtc/rtc_configuration.cpp
- module-bsp/board/rt1051/bsp/rtc/rtc.cpp
- module-bsp/board/rt1051/bsp/rtc/rtc_configuration.hpp
- module-bsp/board/rt1051/puretx/CMakeLists.txt
- module-bsp/board/rt1051/puretx/bsp/rtc/rtc_configuration.cpp
> [BH-1446] RTC Calibration per product

- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/call/CallGUI.cpp
- module-services/service-cellular/call/CallGUI.hpp
- module-services/service-cellular/call/CellularCall.cpp
- module-services/service-cellular/service-cellular/CellularMessage.hpp
- module-services/service-cellular/service-cellular/ServiceCellular.hpp
- module-services/service-cellular/service-cellular/call/CellularCall.hpp
Call state notifications are now send on state change.
Please describe your pull request
> [MOS-376] Add Call state notifications

- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVertical.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
Vertical layout fix for 24H format
> [BH-1450] Vertical layout fix for 24H format

- module-apps/application-settings/windows/advanced/CPUModeTestWindow.cpp
- module-bsp/CMakeLists.txt
- module-bsp/board/linux/CMakeLists.txt
- module-bsp/board/linux/sink/RTTSink.cpp
- module-bsp/board/rt1051/CMakeLists.txt
- module-bsp/board/rt1051/sink/RTTSink.cpp
- module-bsp/bsp/key_to_cstr.cpp
- module-bsp/sink/CMakeLists.txt
- module-bsp/sink/FileSink.cpp
- module-bsp/sink/README.md
- module-bsp/sink/sink/FileSink.hpp
- module-bsp/sink/sink/RTTSink.hpp
- module-bsp/sink/sink/Sink.hpp
- module-cellular/at/ErrorCode.hpp
- module-os/FreeRTOS/prof.c
- module-sys/SystemManager/CMakeLists.txt
- module-sys/SystemManager/CpuPackPrinter.cpp
- module-sys/SystemManager/PowerManager.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
- module-sys/SystemManager/include/SystemManager/CpuPrinter.hpp
- third-party/msgpack11/CMakeLists.txt
Requires:
https://github.com/mudita/MuditaOSTop/pull/1
It enables us to use RTT channel 1 to gather system usage.
> MOS-258 Ui tooling to see the system usage

- .github/pull_request_template.md
- .github/workflows/github-actions-pr-checklist-check.yml
- doc/development_workflow.md
Added requirement for a completed checklist
> [MOS-375] Add GitHub PR Tasks Completed Check

- .github/workflows/github-actions-pr-checklist-check.yml
- module-bluetooth/Bluetooth/CommandHandler.cpp
- module-bluetooth/Bluetooth/command/BatteryLevel.hpp
- module-bluetooth/Bluetooth/command/BatteryLevelData.cpp
- module-bluetooth/Bluetooth/command/BatteryLevelData.hpp
- module-bluetooth/Bluetooth/command/Command.hpp
- module-bluetooth/Bluetooth/command/CommandData.hpp
- module-bluetooth/Bluetooth/interface/profiles/A2DP/A2DP.cpp
- module-bluetooth/Bluetooth/interface/profiles/A2DP/A2DP.hpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.hpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFPImpl.hpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.hpp
- module-bluetooth/Bluetooth/interface/profiles/Profile.hpp
- module-bluetooth/Bluetooth/interface/profiles/ProfileManager.cpp
- module-bluetooth/Bluetooth/interface/profiles/ProfileManager.hpp
- module-bluetooth/CMakeLists.txt
- module-bluetooth/tests/tests-command.cpp
- module-services/service-bluetooth/ServiceBluetooth.cpp
- module-services/service-bluetooth/service-bluetooth/ServiceBluetooth.hpp
- module-services/service-evtmgr/EventManager.cpp
Added handling of the battery state in the HFP profile
> [MOS-365] Add BT battery handling

- module-services/service-appmgr/include/service-appmgr/model/ApplicationManagerCommon.hpp
- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
- module-services/service-eink/ServiceEink.cpp
- module-services/service-eink/ServiceEink.hpp
- module-services/service-eink/messages/ImageMessage.hpp
- module-services/service-gui/ServiceGUI.cpp
- module-services/service-gui/service-gui/ServiceGUI.hpp
There is another race still possible, but far less likely
> [BH-1442] Eliminate race on shutdown screen

- config/bootstrap_config
- module-audio/Audio/test/CMakeLists.txt
- module-audio/Audio/test/DummyAudioDevice.cpp
- module-audio/Audio/test/DummyAudioDevice.hpp
- module-audio/Audio/test/unittest_audio.cpp
- module-audio/board/linux/CMakeLists.txt
- module-audio/board/linux/LinuxAudioDevice.cpp
- module-audio/board/linux/LinuxAudioDevice.hpp
- module-audio/board/linux/PulseAudioWrapper.cpp
- module-audio/board/linux/PulseAudioWrapper.hpp
- module-bsp/WorkerQueue.hpp
- module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
Replaced PortAudio library with PulseAudio.
Fixed minor issues with the WorkerQueue module.
> [BH-1453] Fix audio on the simulator

- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFPImpl.hpp
- module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.cpp
- module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.hpp
- module-bluetooth/Bluetooth/interface/profiles/SCO/ScoUtils.cpp
Fixes for the HFP-related problems - lack of the
sound from caller's phone in HF speakers and
not working BT device's hardware hangup button.
> [MOS-353][MOS-387] HFP profile fixes

- module-sys/SystemManager/CMakeLists.txt
- module-sys/SystemManager/CpuGovernor.cpp
- module-sys/SystemManager/GovernorSentinelOperations.cpp
- module-sys/SystemManager/GovernorSentinelOperations.hpp
- module-sys/SystemManager/include/SystemManager/CpuGovernor.hpp
- module-sys/SystemManager/tests/unittest_CpuSentinelsGovernor.cpp
> [MOS-380]  Sentinels for each that removes unused data added

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
> [BH-1460] Add clock face translations

- .github/workflows/github-actions-pr-checklist-check.yml
Community PRs should be able to pass checks now
> [MOS-413] Fix task-check action for community PRs

- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsLayoutWindow.cpp
- products/BellHybrid/apps/common/include/common/widgets/LayoutVertical.hpp
- products/BellHybrid/apps/common/include/common/widgets/TimeSetSpinnerVertical.hpp
- products/BellHybrid/apps/common/src/widgets/TimeSetSpinnerVertical.cpp
Increase distance between numbers on vert. layout
This PR is a proposition of a solution to BH-1444
Adjust the distances between numbers on the vertical layout
> [BH-1444] Vertical layouts font distance

- module-bluetooth/Bluetooth/interface/profiles/GAP/GAP.cpp
Fixed pairing with devices without IO capabilities -
now pairing does not require confirming any passcode
> [MOS-383] Fix pairing with NoInputNoOutput devices

- products/BellHybrid/apps/application-bell-main/include/application-bell-main/ApplicationBellMain.hpp
Add confirmation screen at layout settings
> [BH-1471] Add confirmation screen at layouts settings

- module-bsp/board/rt1051/bsp/cellular/rt1051_cellular.cpp
- module-cellular/modem/ATCommon.cpp
- module-cellular/modem/ATCommon.hpp
- module-cellular/modem/mux/DLCChannel.cpp
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/doc/README.md
- module-services/service-cellular/service-cellular/ServiceCellular.hpp
After finishing communication with cellular,
we switch to sleep mode faster, saving the battery
at the same time.
> [MOS-228] GSM sleep mode dependend on communication with modem

- module-bluetooth/Bluetooth/CommandHandler.cpp
- module-bluetooth/Bluetooth/command/Command.hpp
- module-bluetooth/Bluetooth/command/CommandData.hpp
- module-bluetooth/Bluetooth/command/NetworkStatusData.cpp
- module-bluetooth/Bluetooth/command/NetworkStatusData.hpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.hpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFPImpl.hpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HSP/HSP.hpp
- module-bluetooth/Bluetooth/interface/profiles/Profile.hpp
- module-bluetooth/Bluetooth/interface/profiles/ProfileManager.cpp
- module-bluetooth/Bluetooth/interface/profiles/ProfileManager.hpp
- module-bluetooth/CMakeLists.txt
- module-services/service-bluetooth/ServiceBluetooth.cpp
- module-services/service-bluetooth/service-bluetooth/ServiceBluetooth.hpp
Connected HFP with cellular statuses
> [MOS-264] Added network registration and roaming status to HFP

- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
- module-bluetooth/Bluetooth/interface/profiles/HFP/HFPImpl.hpp
- module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.cpp
- module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.hpp
Added implementation enabling user to place call
with the phone number supplied from HFP device
Some minor HFP state machine handling fixes
> [MOS-368] Add possibility to place call from HFP

- module-bluetooth/Bluetooth/interface/profiles/HFP/HFP.cpp
- module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.cpp
- module-bluetooth/Bluetooth/interface/profiles/PhoneInterface.hpp
- module-services/service-cellular/ServiceCellular.cpp
- module-utils/utility/Utils.hpp
- module-utils/utility/tests/unittest_utils.cpp
Added handling of HFP DTMF code sending,
fixed DTMF sending in cellular's code
> [MOS-263] Add HFP DTMF handling

- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
Refactored handlers of sys::messages and
some cleanups in the service desktop.
> [CP-1231] Refactor handlers in service desktop

- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
Bedtime reminder will popup on homescreen again
> [BH-1463] Bedtime reminder regression fix

- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationTimerPresenter.cpp
Add correct form of minutes copy in meditation app
> [BH-1472] Add correct form of minutes copy in meditation app

- cmake/modules/AddVersionJson.cmake
- cmake/modules/ConfigureVersionJson.cmake
- config/version_linux.json.cmake_template
- config/version_rt1051.json.cmake_template
- products/BellHybrid/CMakeLists.txt
- products/PurePhone/CMakeLists.txt
Remove binary dependencies from linux build
> [BH-1454] Remove binary dependencies from linux build

- module-services/service-db/ServiceDBCommon.cpp
> [MOS-425] Crash fix on unchecked nullptr

- module-apps/application-special-input/ApplicationSpecialInput.cpp
- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
- module-services/service-fileindexer/ServiceFileIndexer.cpp
Increased stack for:
ApplicationSpecialInput, FileIndexer and ApplicationManager
> [MOS-392] Increase the stack size for tasks

- products/BellHybrid/apps/common/src/layouts/HomeScreenLayouts.cpp
> Bh 1461 remove temperature layouts

- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/src/LanguageUtils.cpp
- products/BellHybrid/apps/common/tests/CMakeLists.txt
- products/BellHybrid/apps/common/tests/test-LanguageUtils.cpp
Fix minutes form above hundred
> [BH-1472] Fix minutes form above hundred

- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
Disable double notification on alarm toggle
> [BH-1479] Disable double notification on alarm toggle

- module-services/service-appmgr/include/service-appmgr/model/ActionsRegistry.hpp
- module-services/service-appmgr/model/ActionsRegistry.cpp
- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
Fix in action handling in ApplicationManager
> [MOS-453] Fix HF on Low Battery Notification

- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
> [BH-1483] Revert unsaved alarm changes

- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
> [BH-1484] Incorrect alarm activate icon

- image/user/data/equalizer/headphones_routing.json
- module-audio/Audio/AudioCommon.hpp
- module-audio/Audio/Operation/Operation.cpp
- module-audio/Audio/Operation/RouterOperation.cpp
- module-audio/Audio/Operation/RouterOperation.hpp
- module-bsp/board/linux/headset/headset.cpp
- module-bsp/board/rt1051/bsp/headset/headset.cpp
- module-bsp/bsp/headset/headset.hpp
- module-services/service-audio/ServiceAudio.cpp
- products/PurePhone/services/evtmgr/WorkerEvent.cpp
Fixes non-working wired headset audio
during call.
> [MOS-411] Wired headset audio fix

- products/BellHybrid/apps/application-bell-main/include/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
> [BH-1474] Randomize quotes

- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationTimerPresenter.cpp
> [BH-1486] Stop meditation time setting from increasing itself

- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/models/StartDelay.cpp
Hide meditation settings
Hide meditation submenu, go straitght to "meditate now"
> [BH-1485] Hide meditation settings

- module-bsp/board/rt1051/os/fsl_tickless_gpt.c
- module-bsp/board/rt1051/os/include/FreeRTOSConfig.h
- module-os/application.c
Made required changes to be able to compile
freeRTOS using tickless idle.
> [BH-1423] Enable tickless option

- module-apps/apps-common/widgets/spinners/StringOutputSpinner.hpp
Fix frontlight settings arrows
> [BH-1494] Fix frontlight settings arrows

- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
Restore complete chime intervals list
> [BH-1492] Restore complete chime intervals list

- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationTimerWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationTimerWindow.hpp
> [BH-1499] Crash on meditation enter

- module-apps/apps-common/widgets/spinners/StringOutputSpinner.hpp
- products/BellHybrid/apps/common/include/common/widgets/list_items/details.hpp
Previous solution caused some regressions along the system
This approach solves the bug differently, avoiding those regressions
> [BH-1494] Frontlight arrows show fix - remove regressions

- products/BellHybrid/apps/common/src/options/BellShortOptionWindow.cpp
Add close reason check on onClose to disable destruction on popup
> [BH-1501] Prevent blanking factory reset window on deepress

- products/BellHybrid/apps/common/src/popups/AlarmActivatedWindow.cpp
- products/BellHybrid/apps/common/src/popups/AlarmDeactivatedWindow.cpp
Stop timer on alarm activation/deactivation popup skip
> [BH-1506] Stop timer on alarm act/deact popup skip

- module-services/service-cellular/ServiceCellular.cpp
[MOS-419] Without RING URC CLIP comes delayed
[MOS-419]: https://appnroll.atlassian.net/browse/MOS-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOS-419] Without RING URC CLIP comes delayed

- products/BellHybrid/apps/common/include/common/widgets/list_items/NumberWithSuffix.hpp
> [BH-1505] Missing texts on settings

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Svenska.json
- module-apps/application-calllog/windows/CallLogMainWindow.cpp
- module-apps/application-calllog/windows/CallLogMainWindow.hpp
- module-gui/gui/widgets/header/DeleteAction.cpp
1. Added the missing language translations.
2. Incorporated changes requested by the QA.
3. Factored out the ugly global pointer in favour of a class member.
> [MOS-447] call log erasing

- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
- image/assets/lang/Svenska.json
> [MOS-447] Clear all call log option

- products/BellHybrid/apps/common/include/common/popups/BedtimeNotificationWindow.hpp
- products/BellHybrid/apps/common/src/popups/BedtimeNotificationWindow.cpp
Bedtime deeppress wont stop relaxation music
> [BH-1507] Bedtime deeppress wont stop relaxation music

- module-cellular/at/UrcFactory.hpp
- module-db/Database/DatabaseInitializer.cpp
- module-db/Tables/NotesTable.cpp
- module-services/service-cellular/service-cellular/requests/CallRequest.hpp
- module-services/service-fileindexer/Common.hpp
- module-utils/unicode/ucs2/ucs2/UCS2.cpp
- test/CMakeLists.txt
> [MOS-512] fix build with gcc12

- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/service-cellular/CellularMessage.hpp
- module-sys/PhoneModes/Subject.cpp
- module-sys/PhoneModes/include/PhoneModes/Subject.hpp
- products/PurePhone/sys/SystemManager.cpp
We discard tethering while the ongoing call now
> [MOS-516] FIX: tethering while call disabled

- module-sys/PhoneModes/Subject.cpp
- module-sys/PhoneModes/include/PhoneModes/Subject.hpp
- products/PurePhone/sys/SystemManager.cpp
Fix of the issue that tethering popup showed
after the USB cable has been connected even
if selected SIM card was not present, so
there was no connection to network.
> [MOS-42] Tethering popup with SIM not present fix

- module-services/service-appmgr/include/service-appmgr/model/ApplicationManagerCommon.hpp
- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
- products/PurePhone/services/appmgr/ApplicationManager.cpp
The synchronization of the application startup
has been improved.
> [MOS-515] Fix freezing on the on-boarding screen

- module-bluetooth/Bluetooth/AbstractController.hpp
- module-bluetooth/Bluetooth/BluetoothStateMachine.hpp
- module-bluetooth/Bluetooth/CommandHandler.cpp
- module-bluetooth/Bluetooth/CommandHandler.hpp
- module-bluetooth/Bluetooth/WorkerController.cpp
- module-bluetooth/Bluetooth/WorkerController.hpp
- module-bluetooth/Bluetooth/command/event/Events.hpp
- module-bluetooth/tests/tests-StatefulController.cpp
- module-services/service-bluetooth/ServiceBluetooth.cpp
Fix of the issue that after connecting
to Bluetooth device it was impossible
to disconnect using Disconnect button.
> [MOS-528] Fixed BT disconnect option

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
Added missing translations for
meditation application.
> [BH-1478] Add missing translations

- module-apps/application-calculator/ApplicationCalculator.cpp
Lock screen after auto lock in Calculator was broken.
Now it's fixed.
> [MOS-293] Fixed lock screen from Calculator.

- products/BellHybrid/CMakeLists.txt
Updated "Woodland Ambiance" asset tags.
> [BH-1495] Relaxation app assets update

- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
Updated Polish and French translations.
> [BH-1478] Translations update

- module-apps/application-meditation/windows/MeditationTimerWindow.cpp
Fix of the issue that end of the meditation
unlocks phone.
> [MOS-54] End of meditation unlocks phone fix

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
> Bell 1.6.0 rc8 cherrypicks

- module-services/service-desktop/endpoints/developerMode/DeveloperModeHelper.cpp
- module-services/service-desktop/endpoints/include/endpoints/developerMode/DeveloperModeHelper.hpp
- test/eq_setup.py
Profile modification is possible via the python script
> [MOS-492] Enable overriding audio profiles via harness

- module-apps/application-call/ApplicationCall.cpp
- module-apps/application-call/presenter/CallPresenter.cpp
- module-apps/application-call/presenter/CallPresenter.hpp
- module-apps/application-call/windows/CallWindow.cpp
- module-apps/application-phonebook/models/PhonebookModel.cpp
> [MOS-519] Fixed ICE conntact calls.

- module-audio/Audio/Profiles/ProfilePlaybackHeadphones.hpp
- module-audio/Audio/Profiles/ProfilePlaybackLoudspeaker.hpp
- module-audio/Audio/Profiles/ProfileRoutingEarspeaker.hpp
- module-audio/Audio/Profiles/ProfileRoutingHeadphones.hpp
- module-audio/Audio/Profiles/ProfileRoutingLoudspeaker.hpp
Updated fallback audio configs with parameters
obtained from R&D in Wrocław.
> [MOS-506] Update fallback audio configs

- module-audio/board/linux/LinuxAudioDevice.cpp
- module-audio/board/linux/LinuxAudioDevice.hpp
- module-audio/board/linux/PulseAudioWrapper.cpp
- module-audio/board/linux/PulseAudioWrapper.hpp
Switched to the more efficient way of
spawning pulse audio context/stream.
This change fixed rare issues reported by
address sanitizer and accidental freezes.
> [BH-1457] Simulator audio

- products/BellHybrid/CMakeLists.txt
Short period of silence cut off at the end
New version MuditaOSPublicAssets set to 0.0.10-bell for Harmony product
> [BH-1458] Relaxation - Woodland Ambiance music has a break at the end

- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/src/ServiceCellularPriv.cpp
In reporting mode, if we receive more than 4 URCs in the last 15
minutes, we will switch to the pooling mode immediately
> [MOS-560] Parameter calibration for URC pooling mode

- board/linux/libiosyscalls/src/syscalls_common.hpp
Add missing include file with GLIBC version.
> [MOS-574] Fix GCC12 port

- image/assets/lang/English.json
- module-apps/apps-common/widgets/ProgressTimer.cpp
- module-apps/apps-common/widgets/ProgressTimer.hpp
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.cpp
- module-apps/apps-common/widgets/TimerWithCallbacks.hpp
- module-gui/gui/widgets/Arc.cpp
- module-gui/gui/widgets/Arc.hpp
- module-gui/gui/widgets/ProgressBar.cpp
- module-gui/gui/widgets/ProgressBar.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.hpp
Rework meditation progress layout
> [BH-1522] Meditation - new circular progress layout

- config/bootstrap_config
- docker/Dockerfile.runner.in
Needed for package build via docker image
> [MOS-572] Add sfdisk do docker image

- doc/README.md
- doc/boot_and_update.md
Added minimal documentation on upate:
- how it works
- what is the arhitecture behind
Please see: https://github.com/mudita/MuditaOS/blob/be19691e5cff9a753bf62920277706b7b5c43081/doc/boot_and_update.md
> [MOS-561] Minimal documentation on how update works

- image/assets/lang/English.json
- module-apps/apps-common/widgets/ProgressTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.hpp
- products/BellHybrid/apps/common/include/common/data/StyleCommon.hpp
Pause icon on the same window as progress
Prevent progress from stepping during pause
Adjust meditation finished window to design
> [BH-1522] Meditation pause and finish design adjustments

- products/PurePhone/BinaryAssetsVersions.cmake
Needed to apply fix from updater
> [MOS-571] Bump updater version for Pure

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- module-apps/apps-common/notifications/policies/CallNotificationPolicy.cpp
- module-apps/apps-common/notifications/policies/NotificationsListPolicy.cpp
- module-apps/apps-common/notifications/policies/SMSNotificationPolicy.cpp
- module-bsp/board/rt1051/bsp/magnetometer/magnetometer.cpp
- module-gui/gui/widgets/StatusBar.hpp
- module-gui/gui/widgets/status-bar/PhoneMode.cpp
- module-services/service-cellular/call/include/call/CellularCall.hpp
- module-sys/PhoneModes/include/PhoneModes/Observer.hpp
- module-sys/PhoneModes/include/PhoneModes/PhoneMode.hpp
- module-sys/PhoneModes/include/PhoneModes/Subject.hpp
- products/PurePhone/services/appmgr/ApplicationManager.cpp
Correction of the previous fix addressing this issue.
Previous idea didn't work when popup tried to
display in application other than ApplicationDesktop.
> [MOS-559] Fix phone unlock after mode change

- products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.cpp
Meditation application's start delay range
was changed according to the new requirements.
> [BH-1518] Change start delay range

- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/models/StartDelay.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationCountdownPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationCountdownPresenter.hpp
Introduced minor changes to the meditation countdown presenter. Among others, replaced settings pointer with already existing alarm model. Fixed incorrect delay time when set to None.
> [BH-1537] Countdown presenter mods

- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-main/include/application-bell-main/ApplicationBellMain.hpp
- products/BellHybrid/apps/application-bell-main/include/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
Fixed harmony crash after deep
pressing while in main menu.
> [BH-1541] Harmony restarts

- module-services/service-evtmgr/screen-light-control/ScreenLightControlParameters.hpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.hpp
- products/BellHybrid/services/evtmgr/backlight-handler/BacklightHandler.cpp
- products/BellHybrid/services/evtmgr/include/evtmgr/backlight-handler/BacklightHandler.hpp
- products/PurePhone/services/evtmgr/screen-light-control/ScreenLightControl.cpp
Frontlight wont flash on snooze when alarm light is off
and automatic frontlight mode is on
> [BH-1509] Frontlight wont flash on snooze

- image/assets/lang/English.json
Fix 2 typos in greetings messages
> [BH-1527] Typos in greetings messages

- products/BellHybrid/apps/application-bell-bedtime/windows/BellBedtimeWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/common/include/common/data/BellFinishedWindowSwitchData.hpp
- products/BellHybrid/apps/common/include/common/windows/BellFinishedWindow.hpp
- products/BellHybrid/apps/common/src/windows/BellFinishedWindow.cpp
Meditation finish will dedirect to homescreen
> [BH-1539] Meditation finish will redirect to homescreen

- image/assets/lang/Francais.json
> [BH-1540] Meditation translation typo

- module-bsp/board/rt1051/CMakeLists.txt
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.hpp
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger_utils.hpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
add nullopt in case when we don't get valid value
add the checksum of the configuration file
add file size validation
add file write validation
add SoC discrepancy check
> [MOS-510] Fix wrong charger configuration

- module-bsp/board/rt1051/bsp/torch/AL3644TT.hpp
- module-bsp/board/rt1051/bsp/torch/torch.cpp
- products/PurePhone/services/evtmgr/EventManager.cpp
Perform turn-off torch in only one place.
Before writing i2c make sure the torch is power supplied.
Minor code refactor.
> [MOS-589] Fix torch driver

- module-apps/apps-common/CMakeLists.txt
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.cpp
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.hpp
- module-apps/apps-common/widgets/TimeFixedWidget.cpp
- module-apps/apps-common/widgets/TimeFixedWidget.hpp
- products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsProgressWindow.cpp
- products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsProgressWindow.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.hpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.hpp
> [BH-1542] Fixed colon width

- module-services/service-cellular/call/CallMachine.hpp
- module-services/service-cellular/call/api/CallMulticast.cpp
- module-services/service-cellular/call/api/CallMulticast.hpp
- module-services/service-cellular/call/api/ModemCallApi.cpp
- module-services/service-cellular/call/api/ModemCallApi.hpp
- module-services/service-cellular/call/doc/README.md
- module-services/service-cellular/call/tests/test-CallMachine.cpp
> MOS-612-fix-typo-in-code-and-docs

- board/README.md
- board/linux/README.md
- board/rt1051/README.md
Created readme about files in board directory. Also added
documentation on how to add or update syscalls wrappers.
It was necessary because we need to know how to maintain
wrappers in case of updating libraries.
> [MOS-573] RT1051 and linux documentation

- module-sys/SystemManager/CpuGovernor.cpp
- products/PurePhone/services/evtmgr/CMakeLists.txt
- products/PurePhone/services/evtmgr/EventManager.cpp
- products/PurePhone/services/evtmgr/include/evtmgr/EventManager.hpp
- products/PurePhone/services/evtmgr/include/evtmgr/UserActivityHandler.hpp
- products/PurePhone/services/evtmgr/user-activity-handler/UserActivityHandler.cpp
Add sentinel that increases and hold the CPU frequency
after a button press event
> [MOS-598] Improved keyboard responsiveness

- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
Sometimes the user was unable to connect
to the Mudita Center due to sync errors
> Fix Mudita Center synchronization fail

- image/assets/lang/English.json
- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/data/Contract.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/include/application-bell-meditation-timer/MeditationTimer.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/models/Statistics.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/models/Statistics.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/StatisticsPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/StatisticsPresenter.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/widgets/SummaryListItem.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/widgets/SummaryListItem.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/StatisticsWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/StatisticsWindow.hpp
Meditation statistics GUI including:
- new list item widget
- integration with the back-end 
> Bh 1538 Meditation stats

- module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp
Next to each of the files listed in the file list in the path
specified in the request is now displayed its size.
> [CP-1454] Add file size to the list of files in specified path

- test/pytest/service-desktop/test_filesystem_ops.py
Add test for listing files and their size in a specified path.
> [CP-1453] Update test script for file system endpoint

- pure_changelog.md
> [MOS-000] Update changelog

- module-apps/application-settings/presenter/network/SimPINSettingsPresenter.cpp
- module-apps/application-settings/presenter/network/SimPINSettingsPresenter.hpp
- module-apps/application-settings/windows/network/SimPINSettingsWindow.cpp
> [MOS-649] Rename confusing method

- module-bluetooth/Bluetooth/interface/profiles/A2DP/AVRCP.cpp
- module-bluetooth/Bluetooth/interface/profiles/A2DP/AVRCP.hpp
Fix of the AVRCP volume control.
Minor code cleanup.
> [MOS-647] Fix AVRCP volume control

- module-apps/application-phonebook/widgets/PhonebookListView.cpp
Fix of the issue that contact group
letter appeared below the
corresponding contacts when
navigating up.
> [MOS-657] Fix contacts list order

- .github/pull_request_template.md
Updated PR template to have reminder about changelog entry
> [MOS-000] Update PR template

- products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsProgressWindow.cpp
- products/BellHybrid/apps/application-bell-main/include/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
Fixed GUI refreshing while
on the home screen, power nap progress
and relaxation progress window.
> [BH-1551] Fix GUI refreshing

- module-apps/application-meditation/widgets/MeditationTimer.hpp
- module-apps/apps-common/CMakeLists.txt
- module-apps/apps-common/widgets/DigitsContainer.cpp
- module-apps/apps-common/widgets/DigitsContainer.hpp
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.cpp
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.hpp
- module-apps/apps-common/widgets/TimeFixedWidget.cpp
- module-apps/apps-common/widgets/TimeFixedWidget.hpp
- module-apps/tests/widgets/test-DigitsContainer.cpp
- module-utils/time/test/unittest_time.cpp
- module-utils/time/time/time_conversion.cpp
- module-utils/time/time/time_conversion.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
*DigitsContainer definicions moved to cpp file(for proper linkage)
*DigitsContainer changed container to std::vector
*Fixed a bug in ProgressTimerWithBarGraphAndCounter where timerText was
treated as timeWidget
*MeditationCountdownWindow timer is now custom size
*Minus removed form MeditationRunningWindow timer
> [BH-1542] Pure meditation fix and cetner TimeFixedWidget

- module-bsp/board/rt1051/bsp/magnetometer/magnetometer.cpp
Readings from magnetometer are noisy. In some cases, the noise can
change slider mode. So we did a few measurements to calculate
the level of noise and then checking the slider position.
> [MOS-349] Improvement of slider reaction

- image/user/db/settings_bell_002.sql
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayouts.cpp
Default layout changed to the `ClassicWithBattery`.
> [BH-1556] Change default layout

- products/BellHybrid/apps/common/src/layouts/HomeScreenLayouts.cpp
Enable/disable temperature layouts based on
the global configuration.
> [BH-1558] Temperature layouts conf

- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingFinalizeWindow.cpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingFinalizeWindow.hpp
- products/BellHybrid/apps/common/include/common/data/StyleCommon.hpp
- products/BellHybrid/apps/common/src/windows/BellFactoryReset.cpp
- products/BellHybrid/apps/common/src/windows/BellFinishedWindow.cpp
Fixed issue with the icon/text not centered properly.
> [BH-1561] Confirmation window's icon alignment

- README.md
Just fixing two spelling mistakes in the README file.
> [MOS-650] Fix spelling mistakes in README

- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
Fix for tethering popup when charger is connected
> [MOS-74] Fix wrong tethering popup order

- module-bsp/board/rt1051/bsp/magnetometer/magnetometer.cpp
When tethering is on we can change the slider position,
however, we can't change the slider mode. If we change
the slider position after tethering is off we need to update
the slider mode. Fix typo in the Y register.
> [MOS-692] Update slider after tethering is off

- module-apps/application-alarm-clock/models/AlarmsRepository.cpp
- module-apps/application-alarm-clock/models/AlarmsRepository.hpp
- module-apps/apps-common/widgets/spinners/StringOutputSpinner.hpp
- module-db/Database/DatabaseInitializer.cpp
- module-db/Database/DatabaseInitializer.hpp
- module-db/tests/DbInitializer.cpp
- module-gui/gui/Common.hpp
- module-gui/gui/widgets/BoxLayout.cpp
- module-gui/gui/widgets/BoxLayout.hpp
- module-gui/gui/widgets/Item.cpp
- module-gui/gui/widgets/Item.hpp
- module-services/service-time/AlarmServiceAPI.cpp
- module-utils/utility/Utils.hpp
- module-utils/utility/tests/unittest_utils.cpp
- products/BellHybrid/keymap/include/keymap/KeyMap.hpp
- products/BellHybrid/services/evtmgr/internal/key_sequences/GenericLongPressSequence.hpp
- Forward arguments
- Remove unused code
- Remove auto return type when it's not needed
- Add const to member functions
- Use startsWith and endsWith from utils
- Allow instantiation of operators only for specific types
- Caluclate key mask in compile time
> MOS-685 make small improvements in various places of the code

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
Updated meditation statistics translations.
> [BH-1550] Medstats translations

- image/assets/lang/Polski.json
- pure_changelog.md
Added Polish translation to a calendar title.
> [MOS-709] Added Polish translation to a calendar title

- module-apps/apps-common/widgets/DateSetSpinner.cpp
- module-apps/apps-common/widgets/DateSetSpinner.hpp
Switched to YYYY/MM/DD format.
> [BH-1563] Date UX improvements

- module-bluetooth/Bluetooth/interface/profiles/A2DP/A2DP.cpp
- module-db/Interface/CalllogRecord.hpp
- module-db/Interface/ContactRecord.cpp
- module-db/Interface/ContactRecord.hpp
- module-db/Interface/SMSRecord.hpp
- module-services/service-db/DBServiceAPI_GetByQuery.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-utils/phonenumber/PhoneNumber.cpp
- module-utils/phonenumber/PhoneNumber.hpp
- products/PurePhone/services/desktop/endpoints/calllog/CalllogHelper.cpp
- products/PurePhone/services/desktop/endpoints/contacts/ContactHelper.cpp
- products/PurePhone/services/desktop/endpoints/include/endpoints/contacts/ContactHelper.hpp
Fix of the issue that phone crashed when trying
to import contact with phone number that couldn't
be parsed.
Additionally minor code cleanup.
> [MOS-677] Fix crash on importing unprocessable contact

- module-apps/application-settings/windows/network/ApnOptionsWindow.cpp
- module-apps/application-settings/windows/network/ApnOptionsWindow.hpp
- module-apps/application-settings/windows/network/NewApnWindow.cpp
- module-apps/application-settings/windows/network/NewApnWindow.hpp
- pure_changelog.md
> [MOS-691] Fix memory leaks in APN settings

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- module-apps/apps-common/locks/handlers/SimLockHandler.cpp
- module-apps/apps-common/locks/handlers/SimLockHandler.hpp
- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/PurePhone/services/appmgr/ApplicationManager.cpp
In the course of working on MOS-640, fixed a potential bug in message handling and refactored unclear naming and logic there and in some other places.
> [MOS-718] Fix part of SIM unlocking

- module-bsp/board/linux/usb_cdc/usb_cdc.cpp
- module-bsp/bsp/usb/usb.hpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
Make MTP root path configurable.
> [CP-1560] MTP root path

- products/PurePhone/BinaryAssetsVersions.cmake
Changed version of updater in downloaded
assets, version 1.5.4 has improved
logging functionality.
> [MOS-646] Bump updater version for Pure

- module-bsp/board/linux/usb_cdc/usb_cdc.cpp
- module-bsp/bsp/usb/usb.hpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- pure_changelog.md
User files accessible via MTP only if phone is unlocked
> [MOS-686] Fix the accessibility of user files by MTP

- test/pytest/service-desktop/test_sync.py
The purpose of this test script is to test
synchronization API introduced in CP-1484
> [CP-1483] Add test for sync API

- module-apps/apps-common/ApplicationCommon.cpp
The log is now self-explanatory.
> [MOS-731] Windows switching log clear in meaning

- module-bsp/board/linux/usb_cdc/usb_cdc.cpp
- module-bsp/bsp/usb/usb.hpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- pure_changelog.md
This reverts commit 42ca53a732487f7dabf5e06ee4c03f73c329882b.
> [MOS-686] Revert - Fix the accessibility of user files by MTP

- module-services/service-desktop/endpoints/deviceInfo/DeviceInfoEndpointCommon.cpp
- module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp
- module-services/service-desktop/endpoints/include/endpoints/HttpEnums.hpp
- module-services/service-desktop/endpoints/include/endpoints/filesystem/FS_Helper.hpp
- module-vfs/paths/include/purefs/filesystem_paths.hpp
The user was able to upload more files than there was free space. In addition, the difference between the declared free space through MTP and MC has been corrected.
> [CP-1536] Fix storage memory overflow

- module-apps/apps-common/widgets/DigitsContainer.cpp
- module-apps/tests/widgets/test-DigitsContainer.cpp
Added leading zero when displaying
1-digit number.
> [BH-1542] Stabilize the clock position

- module-apps/apps-common/ApplicationCommonPopupBlueprints.cpp
- pure_changelog.md
The cleanup part (logs, translation) is preserved.
> Revert [MOS-350] partially

- image/user/db/settings_v2_002-devel.sql
- module-apps/application-onboarding/ApplicationOnBoarding.cpp
- module-services/service-desktop/USBSecurityModel.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/endpoints/include/endpoints/Endpoint.hpp
- module-services/service-desktop/endpoints/include/endpoints/HttpEnums.hpp
- module-services/service-desktop/endpoints/security/SecurityEndpointHelper.cpp
- module-services/service-desktop/include/service-desktop/USBSecurityModel.hpp
- pure_changelog.md
Before accepting the EULA,
the user may fully use the Mudita-Center.
> [MOS-713] Fix access to the phone before going onboarding

- image/assets/lang/Deutsch.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
Add missing translations for “Statistics”
from Meditation sub-menu in German,
Spanish and French.
> [BH-1580] Missing translation for Statistics

- tools/generate_update_image.sh
Add audio assets to update package
This cherry-picks commit: 8bc89ac975781ea4cbe22851a76c1e84b69b19c3 added for https://github.com/mudita/MuditaOS/tree/bell_1.6.0-rc.2
> [BH-1449] Add audio to update package

- module-bsp/board/rt1051/bsp/lpm/RT1051LPMCommon.cpp
- module-bsp/board/rt1051/common/reboot_codes.hpp
- module-bsp/bsp/lpm/bsp_lpm.hpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/endpoints/backup/BackupHelper.cpp
- module-services/service-desktop/endpoints/include/endpoints/backup/BackupHelper.hpp
- module-services/service-desktop/endpoints/include/endpoints/restore/RestoreHelper.hpp
- module-services/service-desktop/endpoints/restore/RestoreHelper.cpp
- module-services/service-desktop/endpoints/update/UpdateHelper.cpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- module-sys/SystemManager/PowerManager.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
- module-sys/SystemManager/include/SystemManager/PowerManager.hpp
- module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
- module-sys/common/include/system/Common.hpp
Redesign of backup and restore endpoints in the
service-desktop to delegate responsibility for
execution of the actual backup and restore process onto the Updater.
Documentation:
https://appnroll.atlassian.net/wiki/spaces/CP/pages/1727627287/Backup+Endpoint+API+4
https://appnroll.atlassian.net/wiki/spaces/CP/pages/1733394433/Restore+Endpoint+API+5
> [CP-1424] Refactor backup and restore endpoints

- Target_Linux.cmake
- build_all_dockers.sh
- config/bootstrap_config
- config/build_runner_docker
- config/common_scripts_lib
- config/download_assets
- docker/Dockerfile.runner.in
- docker/jenkins-docker/Dockerfile-jenkins.runner.in
- in_docker.sh
- module-bsp/drivers/i2c/DriverI2C.hpp
- products/PurePhone/test/test-settings/test-service-db-settings-api.cpp
> [MOS-724] codeql setup

- module-audio/Audio/Audio.cpp
- module-audio/Audio/Audio.hpp
- module-audio/Audio/Operation/IdleOperation.cpp
- module-audio/Audio/Operation/IdleOperation.hpp
- module-audio/Audio/Operation/Operation.cpp
- module-audio/Audio/Operation/Operation.hpp
- module-audio/Audio/Operation/PlaybackOperation.cpp
- module-audio/Audio/Operation/PlaybackOperation.hpp
- module-audio/Audio/Operation/RecorderOperation.cpp
- module-audio/Audio/Operation/RecorderOperation.hpp
- module-audio/Audio/Operation/RouterOperation.cpp
- module-audio/Audio/Operation/RouterOperation.hpp
- module-audio/Audio/decoder/Decoder.cpp
- module-audio/Audio/decoder/Decoder.hpp
- module-audio/Audio/decoder/decoderFLAC.cpp
- module-audio/Audio/decoder/decoderFLAC.hpp
- module-audio/Audio/decoder/decoderMP3.cpp
- module-audio/Audio/decoder/decoderMP3.hpp
- module-audio/Audio/decoder/decoderWAV.cpp
- module-audio/Audio/decoder/decoderWAV.hpp
- module-audio/Audio/encoder/Encoder.cpp
- module-audio/Audio/encoder/Encoder.hpp
- module-audio/Audio/encoder/EncoderWAV.cpp
- module-audio/Audio/encoder/EncoderWAV.hpp
- module-audio/Audio/test/unittest_audio.cpp
- module-services/service-audio/ServiceAudio.cpp
- module-services/service-fileindexer/InotifyHandler.cpp
- module-utils/utility/Utils.cpp
- module-utils/utility/Utils.hpp
- pure_changelog.md
Fix of the issue that only files with
extension in lowercase were detected
and listed in the music player's
library.
Additionally code cleanup.
> [MOS-779] Fix music files extensions case sensitivity

- module-bsp/board/linux/os/FreeRTOSConfig.h
- module-bsp/board/rt1051/os/include/FreeRTOSConfig.h
- module-os/CMakeLists.txt
- module-os/trace/DeletedTasks.cpp
- module-os/trace/DeletedTasks.hpp
- module-sys/SystemManager/CMakeLists.txt
- module-sys/SystemManager/CpuStatistics.cpp
- module-sys/SystemManager/PowerManager.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
- module-sys/SystemManager/TaskStatistics.cpp
- module-sys/SystemManager/include/SystemManager/CpuStatistics.hpp
- module-sys/SystemManager/include/SystemManager/PowerManager.hpp
- module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
- module-sys/SystemManager/include/SystemManager/TaskStatistics.hpp
- module-sys/SystemManager/tests/CMakeLists.txt
- module-sys/SystemManager/tests/test-taskStatistics.cpp
- module-utils/utility/Utils.hpp
- module-utils/utility/tests/unittest_utils.cpp
- pure_changelog.md
Every hour, statistics of tasks that put a heavy load on the CPU will be logged
> [MOS-775] Create run-time statistics for tasks

- module-sys/SystemManager/PowerManager.cpp
- pure_changelog.md
After a long time, a counter overflow appeared
> [MOS-788] Fix incorrect total CPU usage in logs

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsPausedWindow.cpp
Add fix: [[BH-1601] Fix back button behavior in Relaxation](https://github.com/mudita/MuditaOS/pull/4133)
[BH-1601]: https://appnroll.atlassian.net/browse/BH-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release bell 1.7.0 rc6

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-background-sounds/windows/BGSoundsPausedWindow.cpp
If the user clicks the back button in the pause
state the user will be switched to the menu with songs.
> [BH-1601] Fix back button behavior in Relaxation

- doc/os_api/endpoints/pure/contacts_endpoint.md
- doc/os_api/endpoints/pure/device_info_endpoint.md
- doc/os_api/protocol_description/common_parameters_explanation.md
- doc/os_api/protocol_description/error_handling_strategy.md
- doc/os_api/protocol_description/methods.md
- doc/os_api/protocol_description/pagination.md
- doc/os_api/protocol_description/protocol_description.md
Publishing Protocol Description section to our community.
Publishing two endpoints: Device Info Endpoint and Contacts Endpoint.
> [CP-1713] Publish OS API as MVP to our community

- products/PurePhone/test/test-settings/test-service-db-settings-api.cpp
- test/pytest/service-desktop/test_user_data_backup_restore.py
Adjust the test script for the new implementation of backup and restore.
Disabling SettingsApi Test
> [CP-1423] Update backup and restore endpoint API test

- harmony_changelog.md
> Update Harmony 1.7.0 changelog

- harmony_changelog.md
> [BH-000] Update changelog for Harmony 1.7.0

- module-apps/CMakeLists.txt
- module-apps/application-settings/ApplicationSettings.cpp
- module-apps/application-settings/include/application-settings/ApplicationSettings.hpp
- module-apps/application-settings/windows/network/NetworkWindow.cpp
- module-cellular/modem/ATCommon.hpp
- module-cellular/modem/mux/DLCChannel.h
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/call/api/ModemCallApi.cpp
- module-services/service-cellular/service-cellular/CellularMessage.hpp
- module-services/service-cellular/src/ModemResetHandler.cpp
- module-services/service-cellular/src/ModemResetHandler.hpp
- module-services/service-cellular/src/ServiceCellularPriv.cpp
- module-services/service-cellular/src/ServiceCellularPriv.hpp
- module-services/service-cellular/src/SimCard.cpp
- module-services/service-cellular/src/SimCard.hpp
- module-services/service-cellular/src/VolteHandler.hpp
- pure_changelog.md
> [MOS-793] Tie GUI and modem VoLTE steering together

- module-services/service-cellular/CellularServiceAPI.cpp
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/service-cellular/CellularMessage.hpp
- module-services/service-cellular/service-cellular/CellularServiceAPI.hpp
- module-services/service-cellular/service-cellular/ServiceCellular.hpp
> [MOS-809] Remove dead code around celular channels

- scripts/lua/migration/doc/index.html
- scripts/lua/migration/doc/ldoc.css
- scripts/lua/migration/migration.lua
- scripts/lua/migration/test/install_dependencies.sh
- scripts/lua/migration/test/test.lua
Added database migration script(LUA).
> [MOS-802] Create DB migration script

- image/assets/lang/English.json
- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingShortcutsWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingShortcutsWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingShortcutsWindow.cpp
- products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingShortcutsWindow.hpp
Fix inactivity information of shortcuts.
Fix text for one of the shortcuts.
> [BH-1594] Fix information displayed during onboarding

- module-services/service-cellular/src/VolteHandler.hpp
- module-services/service-cellular/tests/unittest_volteHandler.cpp
Unit tests and documentation update will be done later - a distinct ticket for that: MOS-822.
> [MOS-811] Make SMS modem domain in line with voice

- image/assets/lang/Deutsch.json
- image/assets/lang/English.json
- image/assets/lang/Espanol.json
- image/assets/lang/Francais.json
- image/assets/lang/Polski.json
- module-apps/application-onboarding/windows/OnBoardingSimSelectWindow.cpp
- module-apps/application-settings/windows/network/SimCardsWindow.cpp
- module-apps/apps-common/locks/data/SimLockMessages.hpp
- module-apps/apps-common/locks/handlers/SimLockHandler.cpp
- module-apps/apps-common/locks/handlers/SimLockHandler.hpp
- module-apps/apps-common/locks/handlers/SimLockSubject.cpp
- module-apps/apps-common/locks/handlers/SimLockSubject.hpp
- module-apps/apps-common/popups/CMakeLists.txt
- module-apps/apps-common/popups/Popups.cpp
- module-apps/apps-common/popups/Popups.hpp
- module-apps/apps-common/popups/lock-popups/SimSwitchingWindow.cpp
- module-apps/apps-common/popups/lock-popups/SimSwitchingWindow.hpp
- products/PurePhone/apps/Application.cpp
- products/PurePhone/services/appmgr/ApplicationManager.cpp
- pure_changelog.md
Sometimes the process of changing the SIM card
takes a few seconds and the user needs to be informed that something is going on in the background.
> [MOS-800] Add a popup for changing the SIM card

- products/BellHybrid/BinaryAssetsVersions.cmake
Change Ecoboot asset version to the newest one,
supporting A/B booting.
> [MOS-798] Bump Ecoboot version for Harmony

- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationEndedPresenter.cpp
Go back to app menu instead of home screen.
> [BH-1603] Fix end transition in relaxation

- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/Sync.cpp
- module-services/service-desktop/endpoints/backup/BackupHelper.cpp
- module-services/service-desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpointCommon.hpp
- module-services/service-desktop/include/service-desktop/Constants.hpp
- module-services/service-desktop/include/service-desktop/Sync.hpp
- module-vfs/paths/filesystem_paths.cpp
- products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- scripts/lua/entry.lua
Fixed paths for sync process
Added timeout for windows in recovery processes
> [MOS-803] Further fixes for sync

- tools/eepromgen.sh
- tools/generate_default_eeprom_bin.sh
Create script that can be used to create
an EEPROM image in a convenient way.
> [MOS-834] Create script to generate EEPROM image

- module-apps/apps-common/popups/presenter/AlarmPresenter.cpp
- module-apps/apps-common/popups/presenter/AlarmPresenter.hpp
> [MOS-829] The active alarm timeout has been added.

- test/pytest/service-desktop/test_device_info.py
- test/pytest/service-desktop/test_user_data_backup_restore.py
Fix of the aforementioned tests after changes
implemented in PureOS.
> [CP-1421] Fix backup, restore and device info tests

- module-services/service-cellular/CellularUrcHandler.cpp
USSD body is printen in log, it will help to solve some customer issues.
> [MOS-655] USSD body in log

- module-apps/application-alarm-clock/ApplicationAlarmClock.cpp
- module-apps/application-antenna/ApplicationAntenna.cpp
- module-apps/application-calculator/ApplicationCalculator.cpp
- module-apps/application-calendar/ApplicationCalendar.cpp
- module-apps/application-call/ApplicationCall.cpp
- module-apps/application-calllog/ApplicationCallLog.cpp
- module-apps/application-meditation/ApplicationMeditation.cpp
- module-apps/application-messages/ApplicationMessages.cpp
- module-apps/application-music-player/ApplicationMusicPlayer.cpp
- module-apps/application-notes/ApplicationNotes.cpp
- module-apps/application-phonebook/ApplicationPhonebook.cpp
- pure_changelog.md
Previously, this information only appears on the desktop, settings application and onboarding.
> [MOS-717] Add pop-up about SIM removed/inserted in all apps

- scripts/lua/entry.lua
- scripts/lua/products/BellHybrid/update_product.lua
- scripts/lua/products/PurePhone/update_product.lua
- scripts/lua/share/helpers.lua
- scripts/lua/share/ltar.lua
- scripts/lua/test/test.lua
- scripts/lua/update.lua
- scripts/lua/update_udm.lua
Added minor tweaks and fixed bugs.
> [MOS-807] Update scripts

- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsModel.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpSettingsModel.cpp
If there is no value in the database use the default one.
> [BH-1615] Crash after entering alarm settings

- products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
- products/BellHybrid/alarms/src/actions/FrontlightAction.hpp
Turn off the front light if pre-wake up is off
in settings.
> [BH-1617] Fix front light in pre-wake up

- harmony_changelog.md
> [BH-000] Update changelog for 1.8.0

- doc/os_api/endpoints/pure/device_info_endpoint.md
Updated docs for DeviceInfo endpoint
> [MOS-856] Update DeviceInfo documentation

- module-gui/gui/core/RawFont.cpp
This facilitates text issues debugging
> [MOS-859] Add missing font glyphs logging

- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/endpoints/deviceInfo/DeviceInfoEndpointCommon.cpp
- module-services/service-desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpointCommon.hpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- module-vfs/paths/filesystem_paths.cpp
- module-vfs/paths/include/purefs/filesystem_paths.hpp
- products/BellHybrid/BellHybridMain.cpp
- products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- products/PurePhone/PurePhoneMain.cpp
- products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
This time it's device-agnostic from purefs paths
> [MOS-856] Another approach to MTP path in DeviceInfo

- tools/print_characters.py
> [BH-1599] Add characters to the py tool

- module-cellular/CMakeLists.txt
- module-cellular/at/UrcCusd.hpp
- module-cellular/at/src/UrcCusd.cpp
- module-cellular/test/unittest_URC.cpp
- module-services/service-cellular/CellularUrcHandler.cpp
- module-services/service-cellular/call/tests/CMakeLists.txt
- pure_changelog.md
* Added handling for shorter +CUSD formats, thus got rid of a crash.
* Added handling for the "push session"+"action required" state of a USSD interaction with the network.
> [MOS-812] Improved CUSD message handling

- pure_changelog.md
Added changelog entry missing in last PR
> [MOS-390] Missing changelog entry

- module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp
- module-services/service-desktop/endpoints/include/endpoints/filesystem/FS_Helper.hpp
Added support for listing directories with nested ones
> [MOS-872] Add support for directories in filesystem endpoint's listdir

- module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp
- third-party/json/CMakeLists.txt
- third-party/json/json11.cpp
- third-party/json/json11.hpp
- third-party/json/test/CMakeLists.txt
- third-party/json/test/json11-test.cpp
Moved statvfs to stack from heap
> [MOS-872] Extended json11 supported types

- module-apps/apps-common/models/SongsRepository.cpp
- module-apps/apps-common/models/SongsRepository.hpp
- pure_changelog.md
Fixed issues when selecting track index higher than 31.
> [MOS-496] Music player broken UI

- module-db/Tables/SMSTable.cpp
After thread was deleted, messages were still in DB and so on
coworked with @Lefucjusz 
> [MOS-855] Fix weird behavior of messages

- module-bsp/board/linux/eink/LinuxEinkDisplay.cpp
- module-bsp/board/linux/eink/LinuxEinkDisplay.hpp
- module-bsp/board/rt1051/bsp/eink/EinkDisplay.cpp
- module-bsp/board/rt1051/bsp/eink/EinkDisplay.hpp
- module-bsp/hal/include/hal/eink/AbstractEinkDisplay.hpp
- module-services/service-eink/ServiceEink.cpp
- module-services/service-eink/ServiceEink.hpp
Fix of the issue that after powering off
the phone with dark mode enabled the
screen remained black instead of being
cleared to white.
> [MOS-887] Fix black screen left after power off

- module-apps/apps-common/notifications/NotificationListItem.cpp
- module-apps/apps-common/notifications/NotificationListItem.hpp
- module-apps/apps-common/notifications/NotificationsListPresenter.cpp
- pure_changelog.md
Fix of the issue that events counter
was displayed incorrectly for more
than 99 events.
> [MOS-174] Fix broken events counter for 99+ events

- module-apps/application-phonebook/windows/PhonebookSearch.cpp
- module-apps/apps-common/widgets/InputBox.cpp
- module-apps/apps-common/windows/AppWindow.cpp
- module-gui/gui/widgets/BoxLayout.cpp
- module-gui/gui/widgets/Item.cpp
- pure_changelog.md
Fix of the issue that clicking right arrow
in search field caused the focus to be moved
to image on the right, what made inputting
text impossible.
Additionally minor code cleanup.
> [MOS-592] Fix right arrow behavior in search field

- module-apps/application-messages/windows/SMSTemplatesWindow.cpp
- pure_changelog.md
Fix of the issue that templates list was
not looped.
> [MOS-279] Add templates list looping

- module-apps/application-calllog/widgets/CalllogItem.hpp
- module-apps/application-messages/data/MessagesStyle.hpp
- module-utils/time/test/unittest_time.cpp
- module-utils/time/time/time_conversion.cpp
- module-utils/time/time/time_conversion.hpp
- pure_changelog.md
If an event (e.g. receiving a call or SMS) happened in the current week, we display the days of the week instead of the date on the list.
> [MOS-196] Add days of the week to the list of SMS, calls and notes

- module-apps/application-call/ApplicationCall.cpp
- module-apps/application-call/include/application-call/ApplicationCall.hpp
- module-apps/application-call/windows/CallWindow.cpp
- module-apps/application-call/windows/CallWindow.hpp
- module-services/service-audio/AudioServiceAPI.cpp
- module-services/service-audio/ServiceAudio.cpp
- module-services/service-audio/include/service-audio/AudioServiceAPI.hpp
- module-services/service-audio/include/service-audio/ServiceAudio.hpp
- pure_changelog.md
> [MOS-871] Loudspeaker icon not updated when audio routing has changed

- doc/os_api/endpoints/pure/contacts_endpoint.md
- doc/os_api/endpoints/pure/messages_endpoint.md
- module-db/Interface/ContactRecord.cpp
- module-db/Interface/ContactRecord.hpp
- products/PurePhone/services/desktop/endpoints/contacts/ContactHelper.cpp
- products/PurePhone/services/desktop/endpoints/include/endpoints/contacts/ContactHelper.hpp
- products/PurePhone/services/desktop/endpoints/messages/MessageHelper.cpp
- pure_changelog.md
Changing the way Center is recognizing the threads in the message window by introducing the numberID.
> [CP-1624] Adding numberID as a field to contact and message response

- module-apps/application-calculator/data/CalculatorInputProcessor.cpp
- module-apps/application-calculator/data/CalculatorInputProcessorText.cpp
- module-apps/application-calculator/data/CalculatorInputProcessorText.hpp
- module-apps/application-calculator/data/CalculatorUtility.cpp
- module-apps/application-calculator/readme.md
- module-apps/application-calculator/tests/CalculatorInput_tests.cpp
- module-utils/rotator/include/rotator/Rotator.hpp
- pure_changelog.md
* Fixed issue with subtract operation triggering unusal behavior.
* Unified handling of the add,sub,mul,div operations.
* Updated and verified existing unit tests and added new ones covering unhandled cases.
* Added basic requirements/readme.
> [MOS-530] Various calculator app fixes

- module-sys/SystemManager/SystemManagerCommon.cpp
- products/PurePhone/PurePhoneMain.cpp
Removed workaround for rebooting into recovery (update)
> [MOS-237] Removed unnecessary workaround for system reboot

- module-services/service-desktop/endpoints/deviceInfo/DeviceInfoEndpointCommon.cpp
Unify the space values returned by DeviceInfo
endpoint by taking into account space taken
by second system partition, which was previously
omitted.
> [CP-1822] Fix space returned by DeviceInfo endpoint

- doc/development_workflow.md
- tools/check_commit_messages.py
Increased max line length to 100 chars, allowed
auto revert commits to pass CI checks
> [MOS-000] Update commit checks

- module-apps/application-messages/ApplicationMessages.cpp
- module-apps/application-messages/models/SMSThreadModel.cpp
- module-db/Database/Database.cpp
- module-db/Interface/NotificationsRecord.cpp
- module-db/Interface/NotificationsRecord.hpp
- module-db/queries/notifications/QueryNotificationsDecrement.cpp
- module-db/queries/notifications/QueryNotificationsDecrement.hpp
- module-db/tests/CMakeLists.txt
- module-db/tests/NotificationsRecord_tests.cpp
- pure_changelog.md
This reverts commit de99e12e000c89088a6d9e79cac3cf2d2e73a90c.
> Revert "[MOS-578] Fix incorrect logic with SMS notifications"

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/popups/TetheringOffPopup.cpp
- module-gui/gui/widgets/StatusBar.cpp
- module-gui/gui/widgets/status-bar/Style.hpp
- module-gui/gui/widgets/status-bar/Tethering.cpp
- module-gui/gui/widgets/status-bar/Tethering.hpp
- products/PurePhone/CMakeLists.txt
- products/PurePhone/assets/assets_common.json
- pure_changelog.md
Fixed phone mode indicators on popups
> [MOS-59] Fix weird behaviour of indicators on popups

- cmake/modules/Utils.cmake
- module-bluetooth/CMakeLists.txt
- third-party/libical/CMakeLists.txt
- third-party/lwext4/CMakeLists.txt
> [MOS-297] Fixed release build for the simulator

- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
- module-services/service-appmgr/include/service-appmgr/messages/SwitchBackRequest.hpp
- module-services/service-appmgr/messages/SwitchBackRequest.cpp
- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
- pure_changelog.md
> [MOS-357] Fixed regression described in MOS-916

- module-apps/application-phonebook/windows/PhonebookSearchResults.cpp
- pure_changelog.md
> [MOS-6] Fix lack of contact data update on returning to search list

- pure_changelog.md
> [MOS-000] Update changelog for latest releases

- module-apps/application-desktop/windows/MmiPullWindow.cpp
- module-services/service-cellular/CMakeLists.txt
- module-services/service-cellular/CellularRequestHandler.cpp
- module-services/service-cellular/CellularUrcHandler.cpp
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/service-cellular/ServiceCellular.hpp
- module-services/service-cellular/src/ServiceCellularPriv.cpp
- module-services/service-cellular/src/ServiceCellularPriv.hpp
- module-services/service-cellular/src/ussd/USSDHandler.cpp
- module-services/service-cellular/src/ussd/USSDHandler.hpp
- module-services/service-cellular/tests/CMakeLists.txt
- module-services/service-cellular/tests/unittest_ussdHandler.cpp
- pure_changelog.md
USSD pull session was not closed when USSD popup
was closed by back button. Also USSD code was slightly refactored.
> [MOS-47] Fixed non closed USSD session

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- module-services/service-audio/AudioServiceAPI.cpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/application-bell-relaxation/ApplicationBellRelaxation.cpp
- products/BellHybrid/apps/application-bell-relaxation/CMakeLists.txt
- products/BellHybrid/apps/application-bell-relaxation/data/RelaxationStyle.hpp
- products/BellHybrid/apps/application-bell-relaxation/include/application-bell-relaxation/ApplicationBellRelaxation.hpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationErrorPresenter.cpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationErrorPresenter.hpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningLoopPresenter.cpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningLoopPresenter.hpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningProgressPresenter.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationErrorWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationErrorWindow.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.hpp
- products/BellHybrid/assets/assets_common.json
Added error handling for incorrect audio formats and corrupted files inside Relaxation app
> CP-1836 Lack of error handling for audio playback

- doc/os_api/endpoints/harmony/device_info_endpoint.md
- harmony_changelog.md
- module-services/service-appmgr/model/ApplicationManagerCommon.cpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/USBSecurityModel.cpp
- module-services/service-desktop/endpoints/include/endpoints/Endpoint.hpp
- module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
- module-services/service-desktop/endpoints/security/SecurityEndpointHelper.cpp
- module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
- module-services/service-desktop/include/service-desktop/USBSecurityModel.hpp
- products/BellHybrid/services/appmgr/ApplicationManager.cpp
- products/BellHybrid/services/db/databases/migration/settings_bell/0/up.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/34a5f438_Move_gs_onboarding_done_to_global_scope/.meta
- products/BellHybrid/services/db/databases/migration/settings_bell/current/34a5f438_Move_gs_onboarding_done_to_global_scope/down.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/34a5f438_Move_gs_onboarding_done_to_global_scope/up.sql
- products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- products/BellHybrid/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
- products/PurePhone/services/db/databases/migration/settings_v2/current/06e96a01_Move_gs_onboarding_done_to_global_scope/.meta
- products/PurePhone/services/db/databases/migration/settings_v2/current/06e96a01_Move_gs_onboarding_done_to_global_scope/down.sql
- products/PurePhone/services/db/databases/migration/settings_v2/current/06e96a01_Move_gs_onboarding_done_to_global_scope/up.sql
- products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- products/PurePhone/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
- pure_changelog.md
- test/pytest/service-desktop/test_device_info.py
Add a parameter to device info about the onboarding status
> [CP-1825] update while on onboarding screen

- module-apps/application-phonebook/ApplicationPhonebook.cpp
- module-apps/application-phonebook/data/PhonebookItemData.hpp
- module-apps/application-phonebook/include/application-phonebook/ApplicationPhonebook.hpp
- module-apps/application-phonebook/models/PhonebookModel.cpp
- module-apps/application-phonebook/models/PhonebookModel.hpp
- module-apps/application-phonebook/windows/PhonebookIceContacts.cpp
- module-apps/application-phonebook/windows/PhonebookMainWindow.cpp
- module-apps/application-phonebook/windows/PhonebookMainWindow.hpp
- module-apps/application-phonebook/windows/PhonebookSearchResults.cpp
- module-apps/application-phonebook/windows/PhonebookSearchResults.hpp
- pure_changelog.md
Removed incorrect CALL/OPEN labels when editing contact obtained by using search engine.
> [MOS-927] Fixed search engine labels

- harmony_changelog.md
This is an update related to several changes for convenience gathered in one commit.
Related:
https://github.com/mudita/MuditaOS/pull/4375
https://github.com/mudita/MuditaOS/pull/4376
https://github.com/mudita/MuditaOS/pull/4377
https://github.com/mudita/MuditaOS/pull/4378
https://github.com/mudita/MuditaOS/pull/4379
https://github.com/mudita/MuditaOS/pull/4382
> [BH-000] Update changelog for 1.8.1

- config/clang/clang-common.sh
- config/style_check_hook.sh
> [MOS-000] Add clang-format support on macos

- module-services/service-db/ServiceDBCommon.cpp
- module-services/service-db/include/service-db/ServiceDBCommon.hpp
- products/PurePhone/services/db/ServiceDB.cpp
Removed old factory reset mechanism that is
no longer needed after UDM.
Fixed accessing previously moved variable.
Minor cleanups.
> [MOS-943] Remove old factory reset mechanism

- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
- module-apps/application-phonebook/windows/PhonebookNewContact.hpp
- module-apps/apps-common/options/type/OptionContact.cpp
- pure_changelog.md
> [MOS-357] Fix backing from new contact window

- products/BellHybrid/assets/assets_proprietary.json
With generated % character that was missing
> [BH-1656] Use fixed gt pressura 46 light

- harmony_changelog.md
- image/system_a/data/lang/Polski.json
> [BH-1654] Change polish meditation summary text

- harmony_changelog.md
- module-services/service-appmgr/include/service-appmgr/model/ApplicationManagerCommon.hpp
- module-services/service-appmgr/model/ActionsRegistry.cpp
- module-services/service-desktop/DesktopMessages.cpp
- module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp
- module-services/service-desktop/endpoints/filesystem/FileContext.cpp
- module-services/service-desktop/endpoints/filesystem/FileOperations.cpp
- module-services/service-desktop/endpoints/include/endpoints/Context.hpp
- module-services/service-desktop/endpoints/include/endpoints/filesystem/FileContext.hpp
- module-services/service-desktop/endpoints/include/endpoints/filesystem/FileOperations.hpp
- module-services/service-desktop/include/service-desktop/DesktopMessages.hpp
- module-services/service-desktop/parser/MessageHandler.cpp
- module-utils/log/CMakeLists.txt
- module-utils/log/LoggerBufferContainer.hpp
- products/BellHybrid/apps/application-bell-main/windows/BellMainMenuWindow.cpp
- products/BellHybrid/serial-number-reader/SerialNumberReader.cpp
- products/BellHybrid/serial-number-reader/include/serial-number-reader/SerialNumberReader.hpp
- products/BellHybrid/services/appmgr/IdleHandler.cpp
- products/BellHybrid/services/appmgr/include/appmgr/ApplicationManager.hpp
- products/BellHybrid/services/appmgr/include/appmgr/IdleHandler.hpp
- products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
- products/BellHybrid/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
General improvements to prevent running out of memory
> [CP-1837] Random crashes while copying files

- module-apps/application-desktop/windows/MmiPullWindow.cpp
- module-apps/application-messages/widgets/SMSInputWidget.cpp
- module-apps/application-messages/windows/NewMessage.cpp
- module-apps/application-messages/windows/SearchStart.cpp
- module-apps/application-notes/windows/NoteEditWindow.cpp
- module-apps/application-notes/windows/SearchEngineWindow.cpp
- module-apps/application-phonebook/models/NewContactModel.cpp
- module-apps/application-phonebook/models/NewContactModel.hpp
- module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.cpp
- module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.hpp
- module-apps/application-phonebook/windows/PhonebookMainWindow.cpp
- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
- module-apps/application-phonebook/windows/PhonebookSearch.cpp
- module-apps/application-settings/models/network/NewApnModel.cpp
- module-apps/application-settings/widgets/network/ApnInputWidget.cpp
- module-apps/application-settings/widgets/network/ApnInputWidget.hpp
- module-apps/application-settings/windows/advanced/UITestWindow.cpp
- module-apps/application-settings/windows/bluetooth/PhoneNameWindow.cpp
- module-apps/application-settings/windows/display-keypad/QuotesAddWindow.cpp
- module-apps/apps-common/windows/AppWindow.cpp
- module-apps/apps-common/windows/AppWindow.hpp
- module-apps/apps-common/windows/AppWindowConstants.hpp
- module-gui/gui/widgets/text/modes/InputMode.cpp
- module-gui/gui/widgets/text/modes/InputMode.hpp
- pure_changelog.md
Added timeout for displaying selected input
mode - now it automatically disappears
after 3 seconds since last change was made.
> [MOS-178] Add input mode displaying timeout

- doc/os_api/endpoints/pure/security_endpoint.md
- module-services/service-desktop/USBSecurityModel.cpp
- module-services/service-desktop/endpoints/include/endpoints/Endpoint.hpp
- module-services/service-desktop/endpoints/security/SecurityEndpointHelper.cpp
- module-services/service-desktop/include/service-desktop/USBSecurityModel.hpp
- products/PurePhone/services/evtmgr/include/evtmgr/battery/Thresholds.hpp
- pure_changelog.md
Decrease critical battery level from 10% to 5%
Add a new entry to the security endpoint in order to block MC when the phone battery level is critical
> [CP-1797] Low battery connection with mc is possible

- tools/verify_translations.py
Added script for verifying if the translation json:
- has duplicates
- has empty entries
- has missing entries
> [MOS-000] Added tool for translations verification

- products/BellHybrid/services/db/databases/databases.json
- products/BellHybrid/services/db/databases/migration/settings_bell/1/down.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/1/up.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/34a5f438_Move_gs_onboarding_done_to_global_scope/.meta
> [CP-1825][BH-1660] Update while on onboarding screen

- harmony_changelog.md
> [BH-000] Update changelog for 1.8.2 and 1.9.0

- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- image/system_a/data/lang/Svenska.json
- module-apps/application-desktop/ApplicationDesktop.cpp
- module-apps/application-desktop/CMakeLists.txt
- module-apps/application-desktop/include/application-desktop/ApplicationDesktop.hpp
- module-apps/application-desktop/include/application-desktop/Names.hpp
- module-apps/application-desktop/windows/MmiConfirmationWindow.cpp
- module-apps/application-desktop/windows/MmiConfirmationWindow.hpp
- module-apps/application-desktop/windows/MmiPullWindow.cpp
- module-services/service-appmgr/include/service-appmgr/Actions.hpp
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/requests/PinChangeRequest.cpp
- module-services/service-cellular/requests/Request.cpp
- module-services/service-cellular/requests/SupplementaryServicesRequest.cpp
- module-services/service-cellular/service-cellular/CellularMessage.hpp
- module-services/service-cellular/service-cellular/requests/PasswordRegistrationRequest.hpp
- module-services/service-cellular/service-cellular/requests/PinChangeRequest.hpp
- module-services/service-cellular/service-cellular/requests/Request.hpp
- module-services/service-cellular/service-cellular/requests/SupplementaryServicesRequest.hpp
- module-services/service-cellular/service-cellular/requests/UssdRequest.hpp
- module-services/service-cellular/src/ServiceCellularPriv.cpp
- products/PurePhone/services/appmgr/ApplicationManager.cpp
- pure_changelog.md
USSD/MMI codes are now confirmed after they are sended.
> [MOS-636] Added MMI/USSD confirmation

- tools/verify_translations.py
Added removal of unused keys in files
Refactored code
> [MOS-000] Reworked translation verification tool

- harmony_changelog.md
- module-gui/gui/core/RawFont.cpp
Fixed problem with badly calculating characters to show which cause a problem with displaying text on UI.
> [CP-1938] UI issues when uploading multiple copies of a specific file

- harmony_changelog.md
- module-bsp/board/rt1051/bsp/eMMC/fsl_mmc.c
Reinit eMMC driver if write/read transmission
failed.
> [BH-1671] Reinit eMMC driver

- module-cellular/at/src/UrcQind.cpp
- module-gui/gui/widgets/status-bar/NetworkAccessTechnology.cpp
- module-utils/EventStore/EventStore.hpp
- pure_changelog.md
> [MOS-982] Recognizing WCDMA network access method for 3G in GUI

- module-apps/apps-common/popups/VolumeWindow.cpp
- pure_changelog.md
> [MOS-980] Match volume popup timeout with phone modes popup

- evkbimxrt1050_sdram_init_T6.jlinkscript
- module-bsp/board/rt1051/bellpx/bsp/rtc/rtc_configuration.cpp
- module-bsp/board/rt1051/bsp/rtc/rtc.cpp
- module-bsp/board/rt1051/common/board.cpp
- module-bsp/bsp/rtc/rtc.hpp
* Fix of the issue that manifested after running MuditaOS on Harmony via JLink,
which resulted in OS freezing when
trying to set time in normally booted
(via the bootloader) device.
* Minor RTC code cleanup.
* Partial T6 JLink script cleanup.
> [BH-1583] Fix SNVS LP lockup after debugging

- module-apps/application-messages/ApplicationMessages.cpp
- module-apps/application-messages/include/application-messages/ApplicationMessages.hpp
- module-apps/application-messages/windows/SMSThreadViewWindow.cpp
- pure_changelog.md
> Mos 975 missing new message notification

- evkbimxrt1050_sdram_init_T6.jlinkscript
- products/BellHybrid/BinaryAssetsVersions.cmake
* Corrected SDRAM timings in T6 JLink script.
* Cleaned-up and commented JLink script.
* Bumped bootloader version.
> [BH-1693] Correct SDRAM timing settings according to chip RM

- module-apps/application-messages/models/SMSTemplateModel.cpp
- module-apps/application-messages/windows/SMSTemplatesWindow.cpp
Additional fix, previous one was not working correctly in all scenarios.
> [CP-1974] Deleting all templates leaves some text on pure screen

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- products/BellHybrid/apps/application-bell-relaxation/data/RelaxationErrorData.hpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningLoopPresenter.cpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningLoopPresenter.hpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningProgressPresenter.hpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationPlayer.cpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationPlayer.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationErrorWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationErrorWindow.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.hpp
Fixed the timer issue when file was deleted during playback.
> [CP-1966] Deleted file which is played does not stop the playback timer

- module-bsp/board/linux/usb_cdc/usb_cdc.cpp
- module-services/service-desktop/DesktopMessages.cpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/include/service-desktop/DesktopMessages.hpp
* Fixed incorrect reset procedure
* Minor refactor
> [BH-1595] USB reset procedure

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- module-apps/apps-common/widgets/BellBaseLayout.cpp
- module-apps/apps-common/widgets/BellBaseLayout.hpp
- module-services/service-desktop/WorkerDesktop.cpp
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-main/include/application-bell-main/presenters/HomeScreenPresenter.hpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellHomeScreenWindow.hpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/layouts/BaseHomeScreenLayoutProvider.hpp
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassic.hpp
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVertical.hpp
- products/BellHybrid/apps/common/include/common/widgets/BellConnectionStatus.hpp
- products/BellHybrid/apps/common/include/common/widgets/LayoutVertical.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithAmPm.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithDate.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
- products/BellHybrid/apps/common/src/widgets/BellConnectionStatus.cpp
- products/BellHybrid/apps/common/src/widgets/ClockVertical.cpp
- products/BellHybrid/apps/common/src/widgets/LayoutVertical.cpp
- products/BellHybrid/apps/common/src/windows/BellWelcomeWindow.cpp
Added text with information about the connection to the main window when the USB cable is connected to the PC
> [BH-1690] Add information about the connection to the PC

- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithDate.cpp
Fixed battery and date layout for Harmony
> [BH-1691] Fix battery and date layout

- doc/os_api/endpoints/pure/contacts_endpoint.md
- module-db/Interface/ContactRecord.cpp
- module-db/Interface/ContactRecord.hpp
- module-db/queries/phonebook/QueryContactAdd.cpp
- module-db/queries/phonebook/QueryContactAdd.hpp
- module-db/tests/ContactsRecord_tests.cpp
- products/PurePhone/services/desktop/endpoints/contacts/ContactHelper.cpp
- products/PurePhone/services/desktop/endpoints/include/endpoints/contacts/ContactHelper.hpp
- pure_changelog.md
Changed a way of returning information to Center about number duplications
> [CP-889] Add extended information about number duplications

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-settings/CMakeLists.txt
- products/BellHybrid/apps/application-bell-settings/models/AboutYourBellModel.cpp
Added serial number entry to about window
> [BH-1647] Add serial number to about section

- module-bsp/board/linux/os/FreeRTOSConfig.h
- module-bsp/board/rt1051/os/include/FreeRTOSConfig.h
- module-os/memory/usermem.c
Added extended statistics to help track potential memory leaks:
* used user heap size per task
* number of successful allocations
* number of successful frees
> [BH-1701] Add extended user heap statistics for debugging

- module-db/Interface/ContactRecord.cpp
Stopped sending notification when contact add failed
> [CP-2020] Imported contact does not appear in Center

- module-utils/utility/Utils.hpp
- pure_changelog.md
Revert: Fixed adding USSD codes to phonebook.
> [MOS-946] Revert: USSD contacts

- products/BellHybrid/BinaryAssetsVersions.cmake
Update ecoboot and recovery versions for building
the software image.
> [BH-000] Update versions

- module-apps/apps-common/notifications/policies/CallNotificationPolicy.cpp
- module-apps/apps-common/notifications/policies/NotificationsListPolicy.cpp
- module-apps/apps-common/notifications/policies/SMSNotificationPolicy.cpp
- module-bsp/board/linux/magnetometer/magnetometer.cpp
- module-bsp/bsp/magnetometer/magnetometer.hpp
- module-gui/gui/widgets/status-bar/PhoneMode.cpp
Fix of the issue that on simulator phone mode
was in 'undefined' state, what resulted in
no phone mode selected in settings.
> [MOS-599] Fix undefined phone mode in simulator

- products/PurePhone/services/db/databases/migration/predefined_quotes/current/618dbb3c_Removed_unsupported_char_from_quotes/.meta
- products/PurePhone/services/db/databases/migration/predefined_quotes/current/618dbb3c_Removed_unsupported_char_from_quotes/down.sql
- products/PurePhone/services/db/databases/migration/predefined_quotes/current/618dbb3c_Removed_unsupported_char_from_quotes/up.sql
- pure_changelog.md
Removed unsupported character from several
quotes used in Pure.
> [MOS-1000] Remove unsupported character from quotes

- products/PurePhone/services/db/databases/databases.json
- products/PurePhone/services/db/databases/migration/settings_v2/1/down.sql
- products/PurePhone/services/db/databases/migration/settings_v2/1/up.sql
- products/PurePhone/services/db/databases/migration/settings_v2/current/06e96a01_Move_gs_onboarding_done_to_global_scope/.meta
- products/PurePhone/services/db/databases/migration/sms/1/down.sql
- products/PurePhone/services/db/databases/migration/sms/1/up.sql
- products/PurePhone/services/db/databases/migration/sms/current/111a2d1b_Adding_new_column_to_templates_table_to_manage_templates_order/.meta
> [MOS-986] Update database version

- products/BellHybrid/services/appmgr/ApplicationManager.cpp
fix for missing pop-up with information
about deactivating the alarm
> [BH-1722] Fix unswitchable alarm audio

- harmony_changelog.md
Create a section for 2.0.0 version in the changelog
> [BH-000] Update changelog

- pure_changelog.md
Added changelog entry accidentally omitted
in previous PR.
> [MOS-1003] Add missing changelog entry

- pure_changelog.md
> [MOS-000] Update changelog for 1.7.1

- harmony_changelog.md
- module-bsp/board/linux/eink/LinuxEinkDisplay.cpp
- module-bsp/board/linux/eink/LinuxEinkDisplay.hpp
- module-bsp/board/rt1051/bsp/eink/ED028TC1.cpp
- module-bsp/board/rt1051/bsp/eink/ED028TC1.h
- module-bsp/board/rt1051/bsp/eink/EinkDisplay.cpp
- module-bsp/board/rt1051/bsp/eink/EinkDisplay.hpp
- module-bsp/board/rt1051/bsp/eink/bsp_eink.cpp
- module-bsp/board/rt1051/bsp/eink/bsp_eink.h
- module-bsp/drivers/pll/DriverPLL.cpp
- module-bsp/drivers/pll/DriverPLL.hpp
- module-bsp/hal/include/hal/eink/AbstractEinkDisplay.hpp
- module-services/service-eink/ServiceEink.cpp
- module-services/service-eink/ServiceEink.hpp
- module-services/service-gui/ServiceGUI.cpp
- pure_changelog.md
Cleanup and refactor for eink code.
Changed turning on/off procedure.
Add error handling.
> [BH-1714] Eink refactor and error handling

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- module-services/service-db/test/lang/English.json
- products/BellHybrid/apps/application-bell-settings/models/AboutYourBellModel.cpp
- products/BellHybrid/serial-number-parser/CMakeLists.txt
- products/BellHybrid/serial-number-parser/DeviceMetadata.cpp
- products/BellHybrid/serial-number-parser/SerialNumberParser.cpp
- products/BellHybrid/serial-number-parser/include/serial-number-parser/Common.hpp
- products/BellHybrid/serial-number-parser/include/serial-number-parser/DeviceMetadata.hpp
- products/BellHybrid/serial-number-parser/tests/CMakeLists.txt
- products/BellHybrid/serial-number-parser/tests/test-BellSerialNumberParser.cpp
- products/BellHybrid/services/db/BellFactorySettings.cpp
- products/BellHybrid/services/db/include/db/BellFactorySettings.hpp
In the Settings->About section, we will have information about which version of Harmony the user has.
co-author @Lefucjusz 
> [BH-1733] Add Harmony version information

- run.sh
In this version of the run.sh script, the arm-none-eabi-gdb version will be chosen based on its python support and the user will be notified if their version supports python 3 or not.
> [BH-1720] choose GDB binary based on python version

- module-apps/application-calllog/ApplicationCallLog.cpp
- module-apps/application-phonebook/models/PhonebookModel.cpp
- module-apps/application-phonebook/widgets/PhonebookListView.cpp
- module-apps/application-phonebook/widgets/PhonebookListView.hpp
- module-apps/apps-common/DatabaseModel.hpp
- module-gui/gui/widgets/ListViewEngine.hpp
- pure_changelog.md
Fix of the issue that in some cases contact entry
would not be displayed on any page in case it
was on the boundary of two pages.
> [MOS-972] Fixed missing contact entries when scrolling phonebook

- module-bsp/board/rt1051/bsp/eink/ED028TC1.cpp
- module-bsp/board/rt1051/bsp/eink/EinkDisplay.cpp
- module-bsp/board/rt1051/bsp/eink/EinkDisplay.hpp
- module-bsp/board/rt1051/bsp/eink/bsp_eink.cpp
- module-bsp/board/rt1051/bsp/eink/bsp_eink.h
- module-bsp/board/rt1051/common/fsl_drivers/fsl_lpspi.c
- module-services/service-eink/ServiceEink.cpp
Added error detection while eink initialization.
Added mechanism to reinitialize the eink in case of error.
> [BH-1714] Handling eink initialization errors

- harmony_changelog.md
- products/BellHybrid/services/evtmgr/screen-light-control/ScreenLightControl.cpp
- products/BellHybrid/services/time/AlarmOperations.cpp
- products/BellHybrid/services/time/include/time/AlarmOperations.hpp
Disable the frontlight and chime when the
pre-wake up is off using a deep press.
> [BH-1241] Fix the frontlight in pre-wake up

- pure_changelog.md
Update changelog for MuditaOS 1.7.2.
> [MOS-1009] Update changelog

- module-bsp/CMakeLists.txt
- module-bsp/board/linux/usb_cdc/usb_cdc.cpp
- module-bsp/bsp/usb/usb.hpp
- pure_changelog.md
Fix of the unhandled error issue that resulted
in occasional device crash when disconnecting
from PC with MC app running.
> [MOS-1012] Fix occasional crash when unplugging Pure from PC

- module-bsp/board/rt1051/bsp/eink/EinkDisplay.cpp
- module-sys/SystemManager/SystemManagerCommon.cpp
- module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
- products/BellHybrid/sys/SystemManager.cpp
- products/BellHybrid/sys/include/sys/SystemManager.hpp
- products/PurePhone/sys/CMakeLists.txt
- products/PurePhone/sys/SystemManager.cpp
- products/PurePhone/sys/include/sys/SystemManager.hpp
Whitelist removed for Harmony
Changed the way whitelist is obtained
Added missing logs for Eink Dispaly
> [BH-1412] whitelist update

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/application-bell-onboarding/include/application-bell-onboarding/ApplicationBellOnBoarding.hpp
- products/BellHybrid/apps/application-bell-settings/models/DateTimeUnitsModel.cpp
- default year update
- added system shutdown if there is no user activity for 180 seconds on the language selection screen
- fixing the logic in onboarding screens
> [BH-1746] Minor fixes for onboarding

- harmony_changelog.md
- module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp
- module-services/service-desktop/endpoints/include/endpoints/filesystem/FS_Helper.hpp
- pure_changelog.md
Corrected check to see if a device has enough free space to upload a file.
> [CP-2130] Never ending files upload

- module-services/service-gui/ServiceGUI.cpp
- module-services/service-gui/service-gui/ServiceGUI.hpp
Revert changes in Service GUI.
> [MOS-1016] Long files list loading time

- harmony_changelog.md
- pure_changelog.md
- third-party/CrashDebug/CrashCatcher/CrashCatcher.c
- third-party/CrashDebug/CrashCatcher/CrashCatcher_armv7m.S
Added a critical section when handling Hard Faults 
co-author @Lefucjusz 
> [BH-1757] Fix Hard Fault handling

- products/PurePhone/BinaryAssetsVersions.cmake
- pure_changelog.md
Bumped Ecoboot version from 2.0.0 to 2.0.2.
> [MOS-1011][MOS-1025] Bump Ecoboot version for Pure

- module-apps/apps-common/windows/AppWindow.cpp
- module-apps/apps-common/windows/AppWindow.hpp
- module-bsp/WorkerQueue.hpp
- module-bsp/board/rt1051/puretx/bsp/battery_charger/MAX77818.hpp
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.hpp
- module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger_utils.hpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryChargerIRQ.hpp
- module-bsp/board/rt1051/puretx/hal/battery_charger/CurrentMeasurementScope.cpp
- module-bsp/board/rt1051/puretx/irq_gpio.cpp
- module-gui/gui/widgets/StatusBar.cpp
- module-services/service-desktop/ServiceDesktop.cpp
- module-services/service-evtmgr/WorkerEventCommon.cpp
- module-services/service-evtmgr/battery/BatteryController.cpp
- module-services/service-evtmgr/service-evtmgr/WorkerEventCommon.hpp
* Added extended logging to Pure's charger driver.
* Removed redundant handling of INOKB pin interrupt - charger is configured to provide
the same interrupt via INTB pin.
* Minor code cleanup.
> [MOS-1026] Add extended logging to Pure's charger driver

- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- image/system_a/data/lang/Svenska.json
- module-apps/application-notes/ApplicationNotes.cpp
- module-apps/application-notes/include/application-notes/ApplicationNotes.hpp
- module-apps/application-notes/windows/NoteEditWindow.cpp
- module-apps/application-notes/windows/NoteEditWindow.hpp
- module-apps/application-phonebook/models/NewContactModel.cpp
- module-apps/application-phonebook/models/NewContactModel.hpp
- module-apps/application-phonebook/widgets/InputBoxWithLabelAndIconWidget.cpp
- module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.cpp
- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
- module-apps/application-phonebook/windows/PhonebookNewContact.hpp
- module-gui/gui/widgets/ListItem.hpp
- pure_changelog.md
Fix for losing data when the user click the BACK button while creating or editing note/contact.
> [MOS-1020] Fix for losing savings data

- module-services/service-gui/CMakeLists.txt
- module-services/service-gui/ServiceGUI.cpp
- module-services/service-gui/ServiceGUIStateManager.cpp
- module-services/service-gui/service-gui/ServiceGUI.hpp
- module-services/service-gui/service-gui/ServiceGUIStateManager.hpp
Introducing states to ServiceGUI instead of using bool variables as flagss.
> [BH-1767] Fix the pre-revert issue inside ServiceGUI

- harmony_changelog.md
- module-gui/gui/widgets/BoxLayout.cpp
- products/BellHybrid/apps/common/include/common/widgets/SnoozeTimer.hpp
- products/BellHybrid/apps/common/src/AlarmModel.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
- products/BellHybrid/apps/common/src/widgets/SnoozeTimer.cpp
Fixed not disappearing snooze icon when an alarm is deactivated
> [BH-1768] Snooze mode with deep pressed knob

- module-apps/application-alarm-clock/ApplicationAlarmClock.cpp
- module-apps/application-alarm-clock/models/CustomRepeatModel.cpp
- module-apps/application-alarm-clock/models/NewEditAlarmModel.cpp
- module-apps/application-alarm-clock/models/NewEditAlarmModel.hpp
- module-apps/application-alarm-clock/presenter/AlarmClockEditWindowPresenter.cpp
- module-apps/application-alarm-clock/widgets/AlarmMusicOptionsItem.cpp
- module-apps/application-alarm-clock/widgets/AlarmMusicOptionsItem.hpp
- module-apps/application-alarm-clock/widgets/AlarmRRuleOptionsItem.cpp
- module-apps/application-alarm-clock/widgets/AlarmRRuleOptionsItem.hpp
- module-apps/application-alarm-clock/windows/CustomRepeatWindow.cpp
- module-apps/application-alarm-clock/windows/CustomRepeatWindow.hpp
- module-apps/application-alarm-clock/windows/NewEditAlarmWindow.cpp
- pure_changelog.md
* Fixed disappearing left functional button label
when popup appeared while focused on sound 
selection field or AM/PM field
* Fixed erasing selections on custom alarm 
edit window when popup appeared.
* Added preview playback stopping after manually 
blocking the phone.
> [MOS-1035] Fixes in new alarm window UI flow

- pure_changelog.md
> [MOS-000] Update Pure 1.8.0 changelog

- harmony_changelog.md
> [BH-000] Update Harmony changelog

- module-db/Tables/NotesTable.cpp
- pure_changelog.md
Changing the search engine in the notes application so that it is not case sensitive.
> [MOS-471] Fix case sensitive in the note search

- products/BellHybrid/BinaryAssetsVersions.cmake
Update ecoboot version for Harmony to 2.0.5
> [BH-1766] Update ecoboot version

- module-apps/application-messages/windows/NewMessage.cpp
- module-apps/application-messages/windows/NewMessage.hpp
- module-apps/application-phonebook/models/NewContactModel.cpp
- module-apps/application-phonebook/models/NewContactModel.hpp
- module-apps/application-phonebook/widgets/InputBoxWithLabelAndIconWidget.cpp
- module-apps/application-phonebook/widgets/InputBoxWithLabelAndIconWidget.hpp
- module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.cpp
- module-apps/application-phonebook/widgets/InputLinesWithLabelWidget.hpp
- module-apps/application-phonebook/windows/PhonebookNewContact.cpp
- module-gui/gui/widgets/text/Text.cpp
- module-gui/gui/widgets/text/Text.hpp
- pure_changelog.md
This reverts commit 1c18ac422b0f5f21de408a66610c1ac6bb15258e.
> Revert "[MOS-195] Phone number input style unification"

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-main/windows/BellBatteryShutdownWindow.cpp
Add more information to discharged screen
> [BH-1784] Replace discharged device screen

- pure_changelog.md
Update Pure's changelog after releasing
MuditaOS 1.9.0.
> [MOS-000] Update Pure 1.9.0 changelog

- module-services/service-cellular/src/volte/ImsiParser_Germany.hpp
Updated list of operators' HNI codes
in Germany, added missing ones.
> [MOS-1050] Add missing Germany HNI codes

- cmake/modules/ProjectConfig.cmake
- harmony_changelog.md
- pure_changelog.md
Disable MTP file transfer protocol.
> [MOS-996] Disable MTP protocol

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- module-apps/apps-common/popups/Popups.cpp
- module-apps/apps-common/popups/Popups.hpp
- module-services/service-evtmgr/battery/BatteryController.cpp
- module-services/service-evtmgr/battery/BatteryController.hpp
- module-services/service-evtmgr/service-evtmgr/BatteryMessages.hpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/alarms/CMakeLists.txt
- products/BellHybrid/alarms/include/popups/ChargingDoneNotificationPopupRequestParams.hpp
- products/BellHybrid/alarms/include/popups/ChargingNotificationPopupRequestParams.hpp
- products/BellHybrid/apps/Application.cpp
- products/BellHybrid/apps/application-bell-alarm/ApplicationBellAlarm.cpp
- products/BellHybrid/apps/application-bell-bedtime/ApplicationBellBedtime.cpp
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
- products/BellHybrid/apps/application-bell-powernap/ApplicationBellPowerNap.cpp
- products/BellHybrid/apps/application-bell-relaxation/ApplicationBellRelaxation.cpp
- products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/popups/ChargingNotificationWindow.hpp
- products/BellHybrid/apps/common/src/popups/ChargingNotificationWindow.cpp
- products/BellHybrid/assets/assets_common.json
- products/BellHybrid/services/appmgr/ApplicationManager.cpp
Adding notifications when charger is connected
> [BH-1696] Notification when connect the device to the charger

- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- image/system_a/data/lang/Svenska.json
- module-apps/application-desktop/ApplicationDesktop.cpp
- module-apps/application-desktop/CMakeLists.txt
- module-apps/application-desktop/data/DeadBatteryInfoWindowData.hpp
- module-apps/application-desktop/include/application-desktop/Names.hpp
- module-apps/application-desktop/windows/ChargingBatteryWindow.cpp
- module-apps/application-desktop/windows/ChargingBatteryWindow.hpp
- module-apps/application-desktop/windows/DeadBatteryInfoWindow.cpp
- module-apps/application-desktop/windows/DeadBatteryInfoWindow.hpp
- module-apps/application-desktop/windows/DeadBatteryWindow.cpp
- module-apps/application-desktop/windows/DeadBatteryWindow.hpp
- module-gui/gui/widgets/StatusBar.cpp
- module-gui/gui/widgets/StatusBar.hpp
- pure_changelog.md
Updated low battery screen view by adding
info windows appearing when trying to
interact with phone that has critical
charge level.
> [MOS-896] Update low battery screen view

- products/BellHybrid/apps/Application.cpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationTimerSelectPresenter.cpp
- products/BellHybrid/apps/common/include/common/popups/ChargingNotificationWindow.hpp
- products/BellHybrid/apps/common/src/popups/ChargingNotificationWindow.cpp
Fixes and improvements for charging notifications
> [BH-1696] Charging notifications improvements

- harmony_changelog.md
- products/BellHybrid/BinaryAssetsVersions.cmake
Ecoboot version changed from 2.0.5 to 2.0.6.
> [BH-1787][BH-1802] Bump Harmony Ecoboot version

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/windows/AppWindow.cpp
- module-apps/apps-common/windows/AppWindow.hpp
- module-gui/gui/widgets/StatusBar.cpp
- module-gui/gui/widgets/StatusBar.hpp
- module-gui/gui/widgets/status-bar/SignalStrengthBar.cpp
- module-gui/gui/widgets/status-bar/SignalStrengthBar.hpp
- module-gui/gui/widgets/status-bar/SignalStrengthBase.cpp
- module-gui/gui/widgets/status-bar/SignalStrengthBase.hpp
- module-gui/gui/widgets/status-bar/SignalStrengthText.cpp
- module-gui/gui/widgets/status-bar/SignalStrengthText.hpp
- module-services/service-cellular/ServiceCellular.cpp
- module-services/service-cellular/src/CSQHandler.cpp
- module-services/service-cellular/src/CSQHandler.hpp
- module-utils/utility/Utils.hpp
- pure_changelog.md
Modified signal strength update mechanism
to avoid unnecessary screen refreshes in
case new signal strength value is equal
to the previous one.
Minor cleanups.
> [MOS-220] Changed signal strength refresh mechanism

- harmony_changelog.md
Update of the changelog after Harmony 2.2.2
has been released.
> [BH-000] Update Harmony 2.2.2 changelog

- harmony_changelog.md
- module-db/Interface/MultimediaFilesRecord.cpp
- module-db/Interface/MultimediaFilesRecord.hpp
- module-db/queries/multimedia_files/QueryMultimediaFilesCount.cpp
- module-db/queries/multimedia_files/QueryMultimediaFilesCount.hpp
- products/BellHybrid/apps/application-bell-relaxation/ApplicationBellRelaxation.cpp
- products/BellHybrid/apps/application-bell-relaxation/CMakeLists.txt
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsModel.cpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsModel.hpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsRepository.cpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsRepository.hpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationMainWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationMainWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
- products/BellHybrid/apps/common/src/options/BellOptionWindow.cpp
- products/BellHybrid/paths/Paths.cpp
- products/BellHybrid/paths/Paths.hpp
Relaxation is loading smooth with any number of files.
> [BH-1815] Optimalize loading music files in relaxation

- pure_changelog.md
Update Pure changelog after MuditaOS
1.10.0 release.
> [MOS-000] Update Pure changelog

- products/BellHybrid/assets/assets_proprietary.json
Add new font for Harmony labels
> [BH-1829] New font gt pressura bold 38 added

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- module-gui/gui/widgets/ListViewEngine.cpp
- module-gui/gui/widgets/ListViewEngine.hpp
- module-gui/gui/widgets/ListViewWithArrows.cpp
- products/BellHybrid/apps/application-bell-relaxation/CMakeLists.txt
- products/BellHybrid/apps/application-bell-relaxation/data/RelaxationCommon.hpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsModel.cpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsRepository.cpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsRepository.hpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationItem.cpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationItem.hpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationListView.cpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationListView.hpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationOption.cpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationOption.hpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.hpp
- products/BellHybrid/apps/common/include/common/options/OptionBellMenu.hpp
- products/BellHybrid/apps/common/src/options/OptionBellMenu.cpp
> [BH-1828] Add labels to relaxation sound list

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- module-apps/apps-common/widgets/DateSetSpinner.cpp
- module-apps/apps-common/widgets/DateSetSpinner.hpp
- module-apps/apps-common/widgets/TimeSetFmtSpinner.hpp
- module-utils/time/time/dateCommon.hpp
- products/BellHybrid/apps/application-bell-settings/CMakeLists.txt
- products/BellHybrid/apps/application-bell-settings/data/BellSettingsStyle.hpp
- products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/models/DateTimeUnitsModel.hpp
- products/BellHybrid/apps/application-bell-settings/models/DateTimeUnitsModel.cpp
- products/BellHybrid/apps/application-bell-settings/widgets/DateFormatSetListItem.cpp
- products/BellHybrid/apps/application-bell-settings/widgets/DateFormatSetListItem.hpp
- products/BellHybrid/apps/application-bell-settings/widgets/DateSetListItem.cpp
- products/BellHybrid/apps/application-bell-settings/widgets/DateSetListItem.hpp
- products/BellHybrid/apps/application-bell-settings/widgets/TimeSetListItem.cpp
- products/BellHybrid/apps/application-bell-settings/widgets/TimeSetListItem.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithDate.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVerticalWithDate.cpp
Added date format selection between YYYY/DD/MM and YYYY/MM/DD. The time setting has been updated.
> [BH-1809][BH-1835] Add date format setting

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/application-bell-relaxation/ApplicationBellRelaxation.cpp
- products/BellHybrid/apps/application-bell-relaxation/data/RelaxationCommon.hpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsModel.cpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsModel.hpp
- products/BellHybrid/apps/application-bell-relaxation/model/RelaxationSongsRepository.cpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationItem.hpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationListView.cpp
- products/BellHybrid/assets/assets_common.json
- products/BellHybrid/paths/Paths.cpp
- products/BellHybrid/paths/Paths.hpp
Adding color of noises to Relaxation
> [BH-1795] Add noises to relaxation

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationRunningProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationErrorWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
Fixed problem with occasional background playback after song has finished
> [BH-1838] Relaxation plays in the background for certain song lengths

- harmony_changelog.md
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.cpp
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.hpp
- module-apps/apps-common/widgets/TimeFixedWidget.hpp
- module-gui/gui/widgets/ProgressBar.cpp
- module-gui/gui/widgets/ProgressBar.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationStyle.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/include/application-bell-meditation-timer/MeditationTimer.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationTimerPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationCountdownWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationMainWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationTimerWindow.cpp
- products/BellHybrid/apps/application-bell-powernap/data/PowerNapStyle.hpp
- products/BellHybrid/apps/application-bell-powernap/windows/PowerNapProgressWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningLoopWindow.cpp
- products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationRunningProgressWindow.cpp
Implemented new countdown progress bar design,
used in Relaxation, Meditation and Power Nap
apps. New implementation shows progress
bar as decrementing as the time passes instead
of incrementing.
Cleanups.
> [BH-1826] Implement new countdown progress bar design

- harmony_changelog.md
- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- module-audio/Audio/Audio.cpp
- module-audio/Audio/Audio.hpp
- module-audio/Audio/AudioCommon.hpp
- products/BellHybrid/alarms/src/actions/PlayAudioActions.cpp
- products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsModel.cpp
- products/BellHybrid/apps/common/include/common/models/AbstractAlarmSettingsModel.hpp
- products/BellHybrid/apps/common/include/common/models/AbstractAudioModel.hpp
- products/BellHybrid/apps/common/include/common/models/AlarmSettingsModel.hpp
- products/BellHybrid/apps/common/include/common/models/AudioModel.hpp
- products/BellHybrid/apps/common/src/AudioModel.cpp
- products/BellHybrid/services/audio/CMakeLists.txt
- products/BellHybrid/services/audio/ServiceAudio.cpp
- products/BellHybrid/services/audio/VolumeFadeIn.cpp
- products/BellHybrid/services/audio/include/audio/AudioMessage.hpp
- products/BellHybrid/services/audio/include/audio/ServiceAudio.hpp
- products/BellHybrid/services/audio/include/audio/VolumeFadeIn.hpp
- products/BellHybrid/services/db/include/db/SystemSettings.hpp
Adding a fade in for the alarm sound (main and power nap) according to the pattern (V): dt = 30[s] * V/10.
> [BH-1264] Add alarm sound fade in

- harmony_changelog.md
- module-audio/Audio/Audio.cpp
- module-audio/Audio/AudioCommon.hpp
- module-audio/Audio/AudioDevice.hpp
- module-audio/board/rt1051/SAIAudioDevice.cpp
- module-audio/board/rt1051/SAIAudioDevice.hpp
- module-audio/board/rt1051/bellpx/BellPxAudioCodec.cpp
- module-audio/board/rt1051/bellpx/BellPxAudioCodec.hpp
- module-audio/board/rt1051/bellpx/CMakeLists.txt
- module-bsp/board/rt1051/bellpx/bsp/audio/CodecAW8898.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/BedtimeSettingsListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
- products/BellHybrid/apps/common/include/common/models/AbstractAudioModel.hpp
- products/BellHybrid/services/audio/ServiceAudio.cpp
Extended volume scale from 10 to 15 point scale
Modified volume approximation function for better user experience
> [BH-1836] Increase range of volume adjustment

- harmony_changelog.md
- module-apps/apps-common/widgets/TimeSetSpinner.hpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/data/StyleCommon.hpp
- products/BellHybrid/assets/assets_common.json
Increase clock font in Relaxation, Meditation, Power nap mode
> [BH-1807] Increase clock font

- pure_changelog.md
Update changelog after Pure 1.11.0
has been released.
> [MOS-000] Update Pure 1.11.0 changelog

- image/system_a/data/lang/English.json
- image/system_a/data/lang/Polski.json
Updated existing translations to the
up-to-date ones received from a
translation company.
> [BH-1731] Replaced outdated translations

- harmony_changelog.md
- module-apps/apps-common/widgets/TimeSetSpinner.hpp
- module-gui/gui/widgets/Style.hpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/assets/assets_common.json
- products/BellHybrid/assets/assets_proprietary.json
- Removed unused 190 px font
- Added new 32px bold and light & 170px regular fonts
- Added a new colon for the 170px font
> [BH-1839] Improved fonts

- harmony_changelog.md
- module-apps/apps-common/widgets/TimeSetSpinner.cpp
- module-apps/apps-common/widgets/TimeSetSpinner.hpp
- module-gui/gui/widgets/ImageBox.cpp
- module-gui/gui/widgets/ImageBox.hpp
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/data/BellMainStyle.hpp
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassic.hpp
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithQuotes.hpp
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutNames.hpp
- products/BellHybrid/apps/common/include/common/widgets/BellConnectionStatus.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithDate.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithQuotes.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayouts.cpp
- products/BellHybrid/apps/common/src/widgets/BellConnectionStatus.cpp
- products/BellHybrid/assets/assets_common.json
- products/BellHybrid/assets/assets_proprietary.json
In the settings, the user can choose a clock face with quotes. A dedicated clock face includes information about the time, alarm settings, quote and author of the quote.
> [BH-1860] Add new clock face with quotes

- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithQuotes.hpp
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithQuotesAmPm.hpp
- products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutNames.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithQuotes.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithQuotesAmPm.cpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayouts.cpp
> add AmPm clock face

- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
- module-utils/EventStore/EventStore.cpp
- module-utils/EventStore/EventStore.hpp
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-main/models/UsbStatusModel.cpp
- products/BellHybrid/apps/application-bell-main/models/UsbStatusModel.hpp
The "connected" label did not appear on the home screen if the USB was connected during onboarding.
> [BH-1882] Fix display of "Connected" label on home screen

- harmony_changelog.md
- module-apps/apps-common/ApplicationCommon.cpp
- module-apps/apps-common/ApplicationCommon.hpp
- module-platform/rt1051/src/disk_emmc.cpp
- module-services/service-desktop/WorkerDesktop.cpp
- module-services/service-desktop/WorkerDesktop.hpp
- module-utils/EventStore/EventStore.cpp
- module-utils/EventStore/EventStore.hpp
- products/BellHybrid/BinaryAssetsVersions.cmake
- products/BellHybrid/apps/application-bell-main/ApplicationBellMain.cpp
- products/BellHybrid/apps/application-bell-main/models/UsbStatusModel.cpp
- products/BellHybrid/apps/application-bell-main/models/UsbStatusModel.hpp
> Commits for release 2.5.1-rc.2

- pure_changelog.md
Update changelog after releasing Pure 1.12.0.
> [MOS-000] Update Pure 1.12.0 changelog

- harmony_changelog.md
Update changelog after releasing Harmony 2.6.0.
> [BH-000] Update Harmony 2.6.0 changelog

- module-db/CMakeLists.txt
- module-db/Interface/MultimediaFilesRecord.cpp
- module-db/Interface/MultimediaFilesRecord.hpp
- module-db/Tables/MultimediaFilesTable.cpp
- module-db/Tables/MultimediaFilesTable.hpp
- module-db/queries/multimedia_files/QueryMultimediaFilesGetOffset.cpp
- module-db/queries/multimedia_files/QueryMultimediaFilesGetOffset.hpp
- module-db/tests/MultimediaFilesTable_tests.cpp
- products/BellHybrid/apps/application-bell-settings/widgets/SongsListViewItem.cpp
- products/BellHybrid/apps/common/include/common/SoundsRepository.hpp
- products/BellHybrid/apps/common/include/common/models/SongsModel.hpp
- products/BellHybrid/apps/common/src/SoundsRepository.cpp
- products/BellHybrid/apps/common/src/models/SongsModel.cpp
After starting applications that use vertical lists of music, a list will open on the appropriate page with the previously selected song.
> [BH-1896] Add opening the vertical lists on the currently set sound

- module-utils/unicode/utf8/utf8/UTF8.hpp
- products/BellHybrid/apps/application-bell-bedtime/models/BedtimeListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsListItemProvider.hpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/BedtimeSettingsListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/BedtimeSettingsListItemProvider.hpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SnoozeListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/PrewakeUpPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/widgets/SongsListViewItem.cpp
- products/BellHybrid/apps/application-bell-settings/widgets/SongsListViewItem.hpp
- products/BellHybrid/apps/common/include/common/SoundsRepository.hpp
- products/BellHybrid/apps/common/include/common/models/SongsModel.hpp
- products/BellHybrid/apps/common/src/SoundsRepository.cpp
- products/BellHybrid/apps/common/src/models/SongsModel.cpp
* Fix of the issue that quick returning from 
window next to the list window to the one 
before list window result in playback not 
being stopped.
* Fix of the issue that list context wouldn't 
be restored after returning from popup.
* Minor cleanup of the logic after adding 
opening on selected sound on list 
entering - removed redundant call to
setValue, rename of some methods
and variables.
> [BH-1897] Integration fixes and cleanups

- harmony_changelog.md
Update the changelog after releasing Harmony 2.6.1.
> [BH-000] Update Harmony 2.6.1 changelog

- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- products/BellHybrid/BellHybridMain.cpp
- products/BellHybrid/apps/application-bell-main/windows/BellMainMenuWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/include/application-bell-meditation-timer/MeditationTimer.hpp
- products/BellHybrid/apps/application-bell-relaxation/include/application-bell-relaxation/ApplicationBellRelaxation.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsWindow.hpp
* Added 'Menu' top label to the list of Harmony apps.
* Minor cleanup.
> [BH-1919] Add 'Menu' label to apps list

- module-db/Tables/MultimediaFilesTable.cpp
- module-gui/gui/widgets/ListViewEngine.cpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/SoundsRepository.hpp
- products/BellHybrid/apps/common/include/common/models/SongsModel.hpp
- products/BellHybrid/apps/common/include/common/widgets/LabelMarkerItem.hpp
- products/BellHybrid/apps/common/include/common/widgets/LabelOptionWithTick.hpp
- products/BellHybrid/apps/common/include/common/widgets/ListViewWithLabels.hpp
- products/BellHybrid/apps/common/src/SoundsRepository.cpp
- products/BellHybrid/apps/common/src/models/SongsModel.cpp
- products/BellHybrid/apps/common/src/widgets/LabelMarkerItem.cpp
- products/BellHybrid/apps/common/src/widgets/LabelOptionWithTick.cpp
- products/BellHybrid/apps/common/src/widgets/ListViewWithLabels.cpp
This is a reimplementation of ListViewWithLabels
which can set the correct page with focused item.
> [BH-1920] Labels with correct page and song

- harmony_changelog.md
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/apps/application-bell-meditation-timer/MeditationTimer.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/data/MeditationCommon.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.hpp
- products/BellHybrid/apps/application-bell-meditation-timer/presenter/SettingsPresenter.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.cpp
- products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationRunningWindow.hpp
- products/BellHybrid/assets/assets_common.json
Added different sound for the end of
meditation session than the one played
at the beginning and at fixed intervals.
> [BH-1934] Add different sound for the end of meditation

- module-apps/apps-common/CMakeLists.txt
- module-apps/apps-common/widgets/AbstractProgressTime.hpp
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.cpp
- module-apps/apps-common/widgets/ProgressTimerWithBarGraphAndCounter.hpp
- module-apps/apps-common/widgets/TimeFixedWidget.cpp
- module-apps/apps-common/widgets/TimeFixedWidget.hpp
- module-apps/apps-common/widgets/TimeMinuteSecondWidget.cpp
- module-apps/apps-common/widgets/TimeMinuteSecondWidget.hpp
- products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.cpp
- products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.hpp
This widget allows to display of minutes and also, seconds when 1 minute is left to the end of the timer.
> [BH-1940] New progress time widget

- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- products/BellHybrid/apps/application-bell-focus-timer/ApplicationFocusTimer.cpp
- products/BellHybrid/apps/application-bell-focus-timer/data/FocusCommon.hpp
- products/BellHybrid/apps/application-bell-focus-timer/include/application-bell-focus-timer/ApplicationFocusTimer.hpp
- products/BellHybrid/apps/application-bell-focus-timer/presenter/FocusSettingsPresenter.cpp
- products/BellHybrid/apps/application-bell-focus-timer/presenter/FocusSettingsPresenter.hpp
- products/BellHybrid/apps/application-bell-focus-timer/presenter/FocusTimerPresenter.cpp
- products/BellHybrid/apps/application-bell-focus-timer/presenter/FocusTimerPresenter.hpp
- products/BellHybrid/apps/application-bell-focus-timer/windows/FocusSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-focus-timer/windows/FocusSettingsWindow.hpp
- products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.cpp
- products/BellHybrid/apps/application-bell-focus-timer/windows/FocusTimerWindow.hpp
The user can set the duration and frequency of the long break in the settings.
> [BH-1901] Add long breaks to focus timer application

- products/BellHybrid/BinaryAssetsVersions.cmake
Bump Ecoboot version for Harmony
to 2.0.11.
> [BH-1952] Bump Ecoboot version

- products/BellHybrid/apps/application-bell-focus-timer/presenter/FocusTimerPresenter.cpp
Fixed incorrect English form of
"minute" word in copy shown on
focus session summary screen.
> [BH-1954] Fix incorrect English form in Focus Timer

- module-apps/apps-common/widgets/TimeMinuteSecondWidget.cpp
- module-apps/apps-common/widgets/TimeMinuteSecondWidget.hpp
Fix for rounding minutes in Focus Timer application
> [BH-1944] Changing the rounding method for minutes in progress bar

- harmony_changelog.md
- module-services/service-desktop/parser/MessageHandler.hpp
Update changelog after Harmony 2.7.0
release.
> [BH-000] Update Harmony 2.7.0 changelog

- harmony_changelog.md
Fixes and improvements implemented by external
company Grinn, expanding the set of supported
chargers.
> [BH-1776] Grinn USB fixes

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
- products/BellHybrid/apps/application-bell-settings/CMakeLists.txt
- products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/ApplicationBellSettings.hpp
- products/BellHybrid/apps/application-bell-settings/presenter/UpdateInstructionWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/UpdateInstructionWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsWindow.cpp
User will see instructions on how to update Harmony operating system at any time in settings.
> [BH-1946] Add update instructions in settings

- module-audio/board/rt1051/bellpx/BellPxAudioCodec.cpp
- module-bsp/board/rt1051/bellpx/audio.cpp
- module-bsp/board/rt1051/common/fsl_drivers/fsl_snvs_hp.c
- module-services/service-desktop/WorkerDesktop.cpp
- module-sys/Service/Worker.cpp
- module-sys/Service/include/Service/Worker.hpp
* Fixed of some issues that have been 
caught by asserts in debug build.
* Minor cleanup.
> [BH-2001] Fix debug build with new FSL

- CMakeLists.txt
Updated sign server IP address after
recent Jenkins migration to new machine.
> [BH-2004] Update sign server IP address

- products/BellHybrid/BinaryAssetsVersions.cmake
Bump ecoboot version to the one
containing fix for MSC mode freeze.
> [BH-1786] Bump ecoboot version

- module-bsp/CMakeLists.txt
- module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp
- module-bsp/devices/power/CW2015.cpp
- module-bsp/devices/power/CW2015.hpp
- module-bsp/devices/power/MP2615GQ.cpp
- module-bsp/devices/power/MP2615GQ.hpp
- module-bsp/hal/include/hal/battery_charger/AbstractBatteryCharger.hpp
Renamed some legacy name of battery charger
chip to the one that is used in the device.
Minor cleanups.
> [BH-2009] Change charger chip name to proper one

- products/BellHybrid/services/db/databases/databases.json
- products/BellHybrid/services/db/databases/migration/settings_bell/2/down.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/2/up.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/1b034c28_Change_tone_names_to_tone_paths/.meta
- products/BellHybrid/services/db/databases/migration/settings_bell/current/1b034c28_Change_tone_names_to_tone_paths/devel.sql
Commit changes that have been introduced
to settings database to change alarm
sounds filenames to absolute paths
to those files.
> [BH-1909] Commit settings database migration

- products/BellHybrid/apps/application-bell-whats-new/ApplicationWhatsNew.cpp
- products/BellHybrid/apps/application-bell-whats-new/data/WhatsNewCommon.hpp
- products/BellHybrid/apps/application-bell-whats-new/include/application-bell-whats-new/ApplicationWhatsNew.hpp
- products/BellHybrid/apps/application-bell-whats-new/presenter/WhatsNewMainPresenter.cpp
- products/BellHybrid/apps/application-bell-whats-new/presenter/WhatsNewMainPresenter.hpp
- products/BellHybrid/apps/application-bell-whats-new/windows/WhatsNewMainWindow.cpp
If the battery level drops below 10%, a low battery notification will be displayed
> [BH-2021] Add low battery notifications for What`s new application

- image/system_a/data/lang/Deutsch.json
- image/system_a/data/lang/English.json
- image/system_a/data/lang/Espanol.json
- image/system_a/data/lang/Francais.json
- image/system_a/data/lang/Polski.json
- products/BellHybrid/apps/application-bell-relaxation/ApplicationBellRelaxation.cpp
- products/BellHybrid/apps/application-bell-relaxation/include/application-bell-relaxation/ApplicationBellRelaxation.hpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationPlayer.cpp
- products/BellHybrid/apps/application-bell-relaxation/widgets/RelaxationPlayer.hpp
- products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
- products/BellHybrid/apps/application-bell-settings/CMakeLists.txt
- products/BellHybrid/apps/application-bell-settings/data/BellSettingsStyle.hpp
- products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/ApplicationBellSettings.hpp
- products/BellHybrid/apps/application-bell-settings/models/RelaxationListItemProvider.cpp
- products/BellHybrid/apps/application-bell-settings/models/RelaxationListItemProvider.hpp
- products/BellHybrid/apps/application-bell-settings/presenter/RelaxationWindowPresenter.cpp
- products/BellHybrid/apps/application-bell-settings/presenter/RelaxationWindowPresenter.hpp
- products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/SnoozePresenter.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsRelaxationWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsRelaxationWindow.hpp
- products/BellHybrid/apps/application-bell-settings/windows/BellSettingsWindow.cpp
- products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsSnoozeWindow.hpp
- products/BellHybrid/apps/common/CMakeLists.txt
- products/BellHybrid/apps/common/include/common/models/AbstractRelaxationFadeModel.hpp
- products/BellHybrid/apps/common/include/common/models/RelaxationFadeModel.hpp
- products/BellHybrid/apps/common/src/models/RelaxationFadeModel.cpp
- products/BellHybrid/services/db/include/db/SystemSettings.hpp
It adds a new option in the settings menu that
configures the fade effect in the relaxation app.
TODO: Add the rest of the translations
> [BH-2031] Add relaxation fade option in settings

- harmony_changelog.md
Updated changelog after releasing Harmony 2.8.0.
> [BH-000] Update Harmony 2.8.0 changelog

- products/BellHybrid/services/audio/VolumeFade.cpp
The newly set duration for the timer will never be zero.
> [BH-2033] Fix timer settings for fade in and fade out

- cmake/modules/DownloadAsset.cmake
- harmony_changelog.md
- products/BellHybrid/CMakeLists.txt
- products/BellHybrid/assets/assets_proprietary.json
Private assets will be versioned from now on. By modifying the repository content we release a new version of the assets.
> [BH-1716] Add versioning for private assets

- products/BellHybrid/CMakeLists.txt
These assets include changed built-in songs in the relaxation application.
> [BH-2030] Bump public assets

- cmake/modules/Assets.cmake
This reverts commit b468e90fe34a4a665a05f0412dddf645ac754243.
> Revert "[BH-000] Workaround for CI/CD issue"

- products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/.meta
- products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/devel.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/down.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/up.sql
Now the fade effect is enabled by default in relaxation.
> [BH-2066] Enable fade effect in the relaxation app

- module-utils/language/tests/unittest_languageutils.cpp
Added missing unit tests for all language
utilities.
> [BH-2074] Add missing unit tests for language utils

- module-services/service-desktop/endpoints/BaseHelper.cpp
- module-services/service-desktop/endpoints/backup/BackupEndpoint.cpp
- module-services/service-desktop/endpoints/backup/BackupHelper.cpp
- module-services/service-desktop/endpoints/developerMode/DeveloperModeEndpoint.cpp
- module-services/service-desktop/endpoints/developerMode/DeveloperModeHelper.cpp
- module-services/service-desktop/endpoints/developerMode/Mode/UI_Helper.cpp
- module-services/service-desktop/endpoints/filesystem/FS_Helper.cpp
- module-services/service-desktop/endpoints/filesystem/FilesystemEndpoint.cpp
- module-services/service-desktop/endpoints/include/endpoints/BaseHelper.hpp
- module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
- module-services/service-desktop/endpoints/include/endpoints/developerMode/DeveloperModeHelper.hpp
- module-services/service-desktop/endpoints/include/endpoints/timeSync/TimeSyncHelper.hpp
- module-services/service-desktop/endpoints/include/endpoints/update/UpdateHelper.hpp
- module-services/service-desktop/endpoints/reboot/RebootEndpoint.cpp
- module-services/service-desktop/endpoints/reboot/RebootHelper.cpp
- module-services/service-desktop/endpoints/restore/RestoreEndpoint.cpp
- module-services/service-desktop/endpoints/restore/RestoreHelper.cpp
- module-services/service-desktop/endpoints/security/SecurityEndpoint.cpp
- module-services/service-desktop/endpoints/security/SecurityEndpointHelper.cpp
- module-services/service-desktop/endpoints/timeSync/TimeSyncEndpoint.cpp
- module-services/service-desktop/endpoints/timeSync/TimeSyncHelper.cpp
- module-services/service-desktop/endpoints/update/UpdateEndpoint.cpp
- module-services/service-desktop/endpoints/update/UpdateHelper.cpp
Added GET method returning current Harmony
time as a timestamp. This is needed by MC
to implement time synchronization
functionality.
> [BH-2075] Add GET method to time sync endpoint

- harmony_changelog.md
Update changelog after Harmony 2.9.0
release.
> [BH-000] Update Harmony 2.9.0 changelog

- harmony_changelog.md
- products/BellHybrid/apps/application-bell-focus-timer/data/FocusCommon.hpp
Changed maximum focus time length from
60 to 120 minutes.
> [BH-2091] Change maximum focus time to 120 minutes

- products/BellHybrid/services/db/databases/databases.json
- products/BellHybrid/services/db/databases/migration/settings_bell/4/devel.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/4/down.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/4/up.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/287a0959_Change_store_brightness_from_percent_to_level/.meta
Committed settings database migration
required for Harmony 2 Pro.
> [BH-2085] Commit Harmony database migration

- harmony_changelog.md
Update changelog after releasing Harmony 2.9.1.
> [BH-000] Update Harmony 2.9.1 changelog

- products/BellHybrid/services/db/databases/migration/quotes/current/87d133bf_Add_a_new_table_for_custom_quotes/.meta
- products/BellHybrid/services/db/databases/migration/quotes/current/87d133bf_Add_a_new_table_for_custom_quotes/down.sql
- products/BellHybrid/services/db/databases/migration/quotes/current/87d133bf_Add_a_new_table_for_custom_quotes/up.sql
A new table has been added to the quotes database for user-added quotes.
> [BH-2098] Add new table with custom quotes to the database

- module-services/service-db/DBServiceAPI.cpp
- module-services/service-db/agents/settings/SystemSettings.hpp
- module-services/service-db/include/service-db/DBServiceAPI.hpp
- module-services/service-db/include/service-db/QuotesMessages.hpp
- module-services/service-desktop/endpoints/include/endpoints/EndpointType.hpp
- module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
- products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithQuotes.cpp
- products/BellHybrid/services/db/agents/QuotesAgent.cpp
- products/BellHybrid/services/db/agents/QuotesAgent.hpp
- products/BellHybrid/services/db/agents/QuotesQueries.hpp
- products/BellHybrid/services/db/agents/ShuffleQuoteModel.cpp
- products/BellHybrid/services/db/agents/ShuffleQuoteModel.hpp
- products/BellHybrid/services/db/databases/migration/settings_bell/current/91a948e7_Add_quote_group_setting/.meta
- products/BellHybrid/services/db/databases/migration/settings_bell/current/91a948e7_Add_quote_group_setting/down.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/91a948e7_Add_quote_group_setting/up.sql
- products/BellHybrid/services/desktop/endpoints/CMakeLists.txt
- products/BellHybrid/services/desktop/endpoints/EndpointFactoryBell.cpp
- products/BellHybrid/services/desktop/endpoints/include/endpoints/quotes/QuotesEndpoint.hpp
- products/BellHybrid/services/desktop/endpoints/include/endpoints/quotes/QuotesHelper.hpp
- products/BellHybrid/services/desktop/endpoints/quotes/QuotesEndpoint.cpp
- products/BellHybrid/services/desktop/endpoints/quotes/QuotesHelper.cpp
Adding a new endpoint for communication with Center; 
Modification of randomization algorithm from a selected group of quotes.
> [BH-2096] Add quote group setting

- harmony_changelog.md
Update changelog after Harmony 2.9.2
release.
> [BH-000] Update Harmony 2.9.2 changelog

- module-services/service-db/DBServiceAPI.cpp
- module-services/service-db/include/service-db/DBServiceAPI.hpp
- module-services/service-db/include/service-db/QuotesMessages.hpp
- module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
- products/BellHybrid/apps/application-bell-main/presenters/HomeScreenPresenter.cpp
- products/BellHybrid/services/db/agents/QuotesAgent.cpp
- products/BellHybrid/services/db/agents/QuotesAgent.hpp
- products/BellHybrid/services/db/agents/QuotesQueries.hpp
- products/BellHybrid/services/desktop/endpoints/quotes/QuotesHelper.cpp
- test/custom_quotes.py
Adding and removing custom quotes in the database sent by Center
> [BH-2097] Adding and deleting a single custom quote

- module-services/service-db/DBServiceAPI.cpp
- module-services/service-db/agents/settings/SystemSettings.hpp
- module-services/service-db/include/service-db/DBServiceAPI.hpp
- module-services/service-db/include/service-db/QuotesMessages.hpp
- module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
- products/BellHybrid/services/db/agents/QuotesAgent.cpp
- products/BellHybrid/services/db/agents/QuotesAgent.hpp
- products/BellHybrid/services/db/agents/ShuffleQuoteModel.cpp
- products/BellHybrid/services/db/agents/ShuffleQuoteModel.hpp
- products/BellHybrid/services/db/databases/migration/settings_bell/current/b6dd0dff_Add_quote_interval_setting/.meta
- products/BellHybrid/services/db/databases/migration/settings_bell/current/b6dd0dff_Add_quote_interval_setting/down.sql
- products/BellHybrid/services/db/databases/migration/settings_bell/current/b6dd0dff_Add_quote_interval_setting/up.sql
- products/BellHybrid/services/desktop/endpoints/quotes/QuotesHelper.cpp
- test/custom_quotes.py
Modifying the time after which new quotes are displayed on the Harmony screen.
> [BH-2095] Add quote interval setting

- module-services/service-db/DBServiceAPI.cpp
- module-services/service-db/include/service-db/DBServiceAPI.hpp
- module-services/service-db/include/service-db/QuotesMessages.hpp
- module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
- products/BellHybrid/services/db/ServiceDB.cpp
- products/BellHybrid/services/db/agents/QuotesAgent.cpp
- products/BellHybrid/services/db/agents/QuotesAgent.hpp
- products/BellHybrid/services/db/include/db/ServiceDB.hpp
- products/BellHybrid/services/desktop/endpoints/quotes/QuotesHelper.cpp
- test/custom_quotes.py
Added support for sending a quotes database file and sending feedback about custom quotes settings.
> [BH-2099] Add synchronization of custom quotes with Center

- harmony_changelog.md
Updated changelog after Harmony 2.10.0
release.
> [BH-000] Update Harmony 2.10.0 changelog
